### ISSUE TITLE
Add tests for all scipy solvers

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1001]
As mentioned in PR #978, the super LU solver cannot handle int64 indices.  Also, we recently found that cg returns a tuple rather than an array.  These discoveries clearly mean that we don't test the algorithms with all reasonable solvers, so this should be remedied.

**Comment by jgostick** [comment]
Also, we might want to include scikit-umfpack as a dependency in our package, so that users always have a better solver

**Comment by jgostick** [comment]
The pyamg solver is also pretty sweet.  I was reading in the sckimage docs of all places, about how they use it to  generate a preconditioner, which they then pass to cg.  I've used pyamg for doing full solving and it's quite quick but I think limited to a few million pores.  I've never tried it for getting just the preconditioner though.  Could be worth considering.  If the speed is really decent we should consider making this the default path in openpnm, instead of making this a user choice.

**Comment by ma-sadeghi** [comment]
Is generating the preconditioner really worth it? In my _limited_ experience, the time it takes to generate the preconditioner + solution time is almost always greater than the solution time with an iterative solver without supplying the preconditioner. In transient simulations or generally when only the right-hand side is changing, computing the preconditioner might be worth it.

Another potential downside for making `pyamg` the default solver: I think it requires a `C++` compiler in Windows (maybe I'm confusing it with something else). In case it does, most users don't have that installed by default and while installing it is quite simple, it's a frustrating experience for users.

**Comment by magnaou** [comment]
So, another good reason to use petsc :-) 
I have added a test with scipy cg solver on PR #992.
