### ISSUE TITLE
Improve the way dirichlet conditions are added

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1002]
I was poking around the scipy.sparse.linalg docs, and saw a function called `spsolve_triangular`.  If the matrix is symmetric, then you can use this and is speeds up the solver by about 7x!  HOWEVER, there is a problem.  The way we add dirichlet BCs is quite naive, and results in a non-symetric matrix.  I did a little google searching and came across [this SO article](https://scicomp.stackexchange.com/questions/20515/how-to-efficiently-implement-dirichlet-boundary-conditions-in-global-sparse-fini) that explains the problem well, and has an answer from the author of Deal.II, the leading FE solver.  

Iimplementing dirichlet BCs to keep the matrix symmetric seems like pretty important win for speed.

**Comment by magnaou** [comment]
Our A matrices are generally not symmetric. So, imposing Dirichlet BCs the way we are doing it now doesn't break any symmetry.
However, I think it's worth testing new approaches (such as the 1st approach on your link) to see if the performance of the solver is better.

**Comment by jgostick** [comment]
What do you mean, they're not symmetric?  They definitely are, until we add dirichlet conditions.

**Comment by jgostick** [comment]
It's relatively easy to 'zero' the column, using the same approach we use to 'zero' the row.  Then we just need to add some extra stuff to the b matrix, and voila, 10x speed up using `spsolve_triangular`.  Can you also investigate if there is any such option in Petsc, or the other sparse solvers in scipy?

**Comment by magnaou** [comment]
@jgostick My bad, you are right. A matrices are symmetric before applying BCs and/or source terms.
I take care of this and let you know.

**Comment by ma-sadeghi** [comment]
@magnaou What sort of treatment? You mean permutating the rows/columns?

**Comment by magnaou** [comment]
@ma-sadeghi Use some sort of symmetrization technique [https://ac.els-cdn.com/0307904X85900599/1-s2.0-0307904X85900599-main.pdf?_tid=d9cb76ab-d76e-4e08-927c-392ef6c42e58&acdnat=1532014879_1c3677140c3b2c24c38fbcd75ec8c8ca](url)

**Comment by magnaou** [comment]
Not sure whether the cost of symmetrization is negligible compared to the potential speed up (it depends on the problem apparently).

**Comment by magnaou** [comment]
Done on PR BCs #1076. I think you can close it @jgostick
