### ISSUE TITLE
add scikit-umfpack to deps

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1004]
I just checked and `pip install scikit-umfpack` works just fine (no compilation required).  For comparison `pip install pyamg` fails.  `conda install pyamg` would work, but we have no way (that I know of) of enforcing conda packages via pip install.

**Comment by ma-sadeghi** [comment]
`pip install pyamg` doesn't fail, at least on my Windows 10 machine.

**Comment by ma-sadeghi** [comment]
After chatting with @jgostick , it turns out it might be that `pyamg` requires a working `C++` compiler on your machine.

**Comment by jgostick** [comment]
done in PR #970
