### ISSUE TITLE
Coplanar domain issue

### ISSUE THREAD

**Issue by SeongyeopJung** [PMEAL/OpenPNM#1019]
When using 'calc_eff_diffusivity()' method in Bravais(FCC) network, exception raised. 
: _Exception: Detected inlet pores are not coplanar_ 
Because of this issue, domain area and domain length need to be defined manually.  But it is coplanar, so it should work. Inlet/outlet was 'top' and 'bottom'.

**Comment by jgostick** [comment]
First off, I guess this should throw an 'ERROR' log message rather than an Exception right?  Secondly, it should work just fine for Bravais.

**Comment by jgostick** [comment]
This is now fixed...turns out there was a problem with `label_faces` in the topotools module.  Will open a separate bug for that.
