### ISSUE TITLE
Improve throat 'straight' model

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1034]
The straight model should include the overlap with the pores, as the 'spherical_pore' models does.

**Comment by TomTranter** [comment]
Then it would only apply to spherical pores. Might be worth having both and renaming them as pore_ends and sphere_intersection or something like that. It kinda begs the question, should we even have geometry models separate from geometry classes?

**Comment by jgostick** [comment]
fixed in PR #1062
