### ISSUE TITLE
Hydraulic conductance still broken for Voronoi boundary pores

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1036]
I'll look into this asap

**Comment by TomTranter** [comment]
Hydraulic conductance uses the pore.diameter which is zero for boundary pores. 
In the old models boundary pores were effectively fudged by setting the conductance to inf if the conductance was less than zero or nan. I guess this worked fine for the old solvers but not sure if this will mess up any of the new ones.

**Comment by jgostick** [comment]
fixed in PR #1062
