### ISSUE TITLE
How to denote the "shape" of a pore or throat?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1037]
Many pore scale models require knowing whether a pore is being treated as a sphere or cube or something else.  We managed this in the past by having models for each (e.g. pore_volume.sphere and pore_volume.cube), but now we need to know this for other models.  Any suggestions on how to track this efficiently and effectively are welcome!

**Comment by jgostick** [comment]
we could use labels?  Perhaps offer a default set of labels on each geometry object, like:
`'pore.spherical'`, `'throat.cuboid'`.  If these labels are always there, then the models could check the pore/throat type by querying the various label arrays?

**Comment by TomTranter** [comment]
I don't like that idea. I assume you are talking about conductance models when referring to "other" models. Probably the easiest way to handle this is to have a shape factor. I would be in favor of making the transport algorithms as simple as possible and handling geometrical irregularities inside the geometry classes entirely. I think we're making things overly complex. What would you do if you had cylindrical throat and cuboid pore. How do you handle extracted nets? Impose some sort of nearest shape?

**Comment by jgostick** [comment]
@ma-sadeghi has essentially solved this issue in his recent conductance model over hauls.  There is basical a set of models for spherical pore and another for square, and all other cases are dealth with using shape factors.
