### ISSUE TITLE
What to do about Boundary Pores

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1038]
I think we need to think about a proper treatment of boundary pores for both linear transport and percolation. And whether we need them and whether taking them out causes more problems than keeping them. Currently they are causing a lot of issues for the conductance models.

- They are useful for percolation when you want to start the simulation with zero saturation

- They are useful for transport for when you need a coplanar face for effective properties

- They are annoying as part of the model framework where they may not contain the data needed for some models to work and end up having unphysical values or fudged data

- They are easy to add to cubic networks but not random or extracted

So is it more useful and consistent to treat them as real pores in a sort of ultra high-porous material that sits directly in contact with the main domain and give them real diameters, volumes, conductances. Then when doing percolation and stuff it's simple enough to look at saturation in a bulk geometry rather than the whole domain. Or is it better to not give them any physical properties, maybe not even a geometry so that all the interleaved data returns nans and then give them special treatment in the conductance models - fudging the nans into real values when needed?

**Comment by ma-sadeghi** [comment]
Here are some thoughts:
1. Would it make a difference to use boundary pores to calculate effective properties?
2. For percolation, would it hurt to start the simulation at some small-enough value, rather than 0?

**Comment by TomTranter** [comment]
So for effective properties which is really treating the whole network as one large resistor or black box the effect of adding boundary pores is to say the edges of this box go through the centers of the boundary pores which affects the length and area in the calculation. So even though they shouldn't offer any extra resistance the calculation is going to return a different result compared to using the first set of real pores by virtue of having a slightly bigger box. The user can now specify the length and area in calc_eff_property so I guess they can decide where they want their box to be drawn. Another advantage to adding boundary pores is to make the box shape around an irregular internal structure (e.g. Voronoi). 

I would say starting percolation from zero is important but as I suggested above it can be handled using geometry labels. 

With the Voronoi, it's actually the throats at the surfaces of the shape that have real dimensions and the boundary pores connecting outside are purely fictitious. However, this is not always the case. I guess sometimes both could be real, like connecting to an external reservoir and sometimes both could be fictitious.

So for the purposes of transport maybe we should allow for real values in the boundary pores but also handle when they are fictitious. If they are real then they are assigned a regular geometry with all the necessary models, if they are fictitious they are not assigned a geometry or they are assigned a boundary geometry that purely exists for labelling them as boundary pores and preventing geometry_health_checks. Then we need to make sure that if a model tries to access the data inside the boundary pore or throat it can handle the nans and come up with some sensible value.

At the moment we're in the middle where the boundary class has real values for some data and zero or missing values for other data and the other models further down the line don't know what to do with it

**Comment by magnaou** [comment]
@ma-sadeghi
1- The choice of boundary pores affects the effective properties (Zohaib had issues regarding this point).
2- I'm not sure about your point (2). How do you want to start from a small value? is it by only using few pores as inlet boundary?

**Comment by ma-sadeghi** [comment]
> Other solution is to not allow the concept of a fictitious pore but then how do you calculate effective properties on irregular networks?

If we can somehow figure out the pores sitting on each face (which probably we can/should, otherwise nor we can add boundary pores on that face), then it would be similar to that in cubic networks.

**Comment by ma-sadeghi** [comment]
> The choice of boundary pores affects the effective properties (Zohaib had issues regarding this point).

Maybe a few percent.

**Comment by ma-sadeghi** [comment]
> I'm not sure about your point (2). How do you want to start from a small value? is it by only using few pores as inlet boundary?

I meant starting with all of the pores on the inlet face filled. Anyways, Tom says it's important to start with 0 saturation, so nevermind this.

**Comment by TomTranter** [comment]
We came to the conclusion that boundary pores could (but don't have to be fictitious) and have zero volumes etc but the connecting throat should be real and have non-zero length and volume. We need to investigate the effect of having infinite conductance in the boundary pore.

**Comment by TomTranter** [comment]
@jgostick do we also need to update DelaunayVoronoi to label boundary pores consistently with the other networks? What gets labelled surface should be boundary by the look of it. There is also an add_boundary_pores method which I don't use for VoronoiFibers that would presumably add another layer. This isn't really right as the surface ones on the Delaunay already have zero volume.... Not sure what it would do for the Voronoi. What is you experience with boundary pores on the dual network @Zohaib-Atiq ?

**Comment by TomTranter** [comment]
It seems the add_boundary_pores method doesn't actually work for DelVorDual. I make it it work but do wee need it considering the above point

**Comment by TomTranter** [comment]
So I've modified quite a few files in the associated PR. The most important changes are to DelaunayVoronoiDual so it would be good if @Zohaib-Atiq could test any scripts he has. There is a potentially script breaking change as surface pores are now the first layer of real pores connected to the edges and pores on the edge are labelled boundary. There is also a method which is pretty redundant which adds another layer of boundary pores outside the original domain. It could be useful for something I guess but as we already have boundary pores maybe we should name this something else

**Comment by TomTranter** [comment]
```python

import openpnm as op
import openpnm.topotools as tt
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

plt.close('all')

dv = op.network.DelaunayVoronoiDual(num_points=50)
dv['pore.coords'] = np.around(dv['pore.coords'], 12)

dv.add_boundary_pores(offset=0.1)

fig = tt.plot_coordinates(network=dv, pores=dv.pores(['delaunay', 'boundary'], mode='intersection'), c='r')
fig = tt.plot_connections(network=dv, throats=dv.throats(['delaunay', 'boundary'], mode='intersection'), fig=fig,c='r')
fig = tt.plot_coordinates(network=dv, pores=dv.pores(['delaunay', 'surface'], mode='intersection'), fig=fig, c='b')
fig = tt.plot_connections(network=dv, throats=dv.throats(['delaunay', 'surface'], mode='intersection'), fig=fig, c='b')
fig = tt.plot_coordinates(network=dv, pores=dv.pores(['delaunay', 'internal'], mode='intersection'), fig=fig, c='g')
fig = tt.plot_connections(network=dv, throats=dv.throats(['delaunay', 'internal'], mode='intersection'), fig=fig, c='g')
#fig = tt.plot_connections(network=dv, throats=dv.throats(['voronoi']), fig=fig, c='k')

cu = op.network.Cubic(shape=[5, 5, 5])
cu.add_boundary_pores()
fig2 = tt.plot_coordinates(network=cu, pores=cu.pores('*boundary'), c='r')
fig2 = tt.plot_connections(network=cu, throats=cu.throats('*boundary'), fig=fig2, c='r')
fig2 = tt.plot_coordinates(network=cu, pores=cu.pores('surface'), fig=fig2, c='b')
fig2 = tt.plot_connections(network=cu, throats=cu.throats('surface'), fig=fig2, c='b')


fig3 = tt.plot_coordinates(network=dv, pores=dv.pores(['voronoi', 'boundary'], mode='intersection'), c='r')
fig3 = tt.plot_connections(network=dv, throats=dv.throats(['voronoi', 'boundary'], mode='intersection'),fig=fig3, c='r')
fig3 = tt.plot_coordinates(network=dv, pores=dv.pores(['voronoi', 'surface'], mode='intersection'), fig=fig3, c='b')
fig3 = tt.plot_connections(network=dv, throats=dv.throats(['voronoi', 'surface'], mode='intersection'), fig=fig3, c='b')
fig3 = tt.plot_coordinates(network=dv, pores=dv.pores(['voronoi', 'internal'], mode='intersection'), fig=fig3, c='g')
fig3 = tt.plot_connections(network=dv, throats=dv.throats(['voronoi', 'internal'], mode='intersection'), fig=fig3, c='g')

gn = op.network.Gabriel(shape=[1, 1, 1], num_points=50)


fig4 = tt.plot_coordinates(network=gn, pores=gn.pores(['boundary'], mode='intersection'), c='r')
fig4 = tt.plot_connections(network=gn, throats=gn.throats(['boundary'], mode='intersection'),fig=fig4, c='r')
fig4 = tt.plot_coordinates(network=gn, pores=gn.pores(['surface'], mode='intersection'), fig=fig4, c='b')
fig4 = tt.plot_connections(network=gn, throats=gn.throats(['surface'], mode='intersection'), fig=fig4, c='b')
fig4 = tt.plot_coordinates(network=gn, pores=gn.pores(['internal'], mode='intersection'), fig=fig4, c='g')
fig4 = tt.plot_connections(network=gn, throats=gn.throats(['internal'], mode='intersection'), fig=fig4, c='g')

fig5 = tt.plot_coordinates(network=dv, pores=dv.pores(['back_boundary','front_boundary'], mode='union'), c='r')
fig5 = tt.plot_connections(network=dv, throats=dv.throats(['back_boundary','front_boundary'], mode='union'), fig=fig5, c='r')
fig5 = tt.plot_coordinates(network=dv, pores=dv.pores(['left_boundary','right_boundary'], mode='union'), fig=fig5, c='b')
fig5 = tt.plot_connections(network=dv, throats=dv.throats(['left_boundary','right_boundary'], mode='union'), fig=fig5, c='b')
fig5 = tt.plot_coordinates(network=dv, pores=dv.pores(['top_boundary','bottom_boundary'], mode='union'), fig=fig5, c='g')
fig5 = tt.plot_connections(network=dv, throats=dv.throats(['top_boundary','bottom_boundary'], mode='union'), fig=fig5, c='g')
fig5 = tt.plot_coordinates(network=dv, pores=dv.pores('boundary'), fig=fig5, c='k')
```

**Comment by TomTranter** [comment]
The above code will help you visualize the changes

**Comment by Zohaib-Atiq** [comment]
-The add boundary nodes function in porespy is working fine for me in dual network. Currently its in dual network extraction PR. 
-As far as its applicability in VoronoiDelaunayDual I think it is not a good idea to use it for such kind of generated network as it produces another voxel layer at the boundary of image. 
-I will try to check your new boundary pore function Let see what I can find.

**Comment by xu-kai-xu** [comment]
@TomTranter @jgostick  when i use the method 'calc_effective_permeability', i found  two parameters'domain_area=None, domain_length=None', which i did not understand, and tne documentation seems not clear enough for me.  wish for you to give some specific explaination, thanks.
the 3D models seem could guess the domain themselves. and i made a '[3,4,1]' model, it need to specific the value of the 'domain_area, domain_length'.

**Comment by jgostick** [comment]
Hi @xu-kai-xu.  We have found that calculating domain area and length is actually quite difficult!  The problem is that we only know pore centers, but the domain is actually a bit bigger than this. So we *suggest* that users specify it when calling ``calc_effective_permeability``, but if not given, we do attempt to guess it, but throw a warning that it might not be accurate.  If the domain is large, then the error would only be a few %, so not a big deal.

**Comment by xu-kai-xu** [comment]
@jgostick  i read the user guide and pdf format guidings, just did not find the documentation of `calc_effective_permeability`, which i wish would give some specific explanation fo what the domain area, of some graphs to illustrate the domain area visually. May i ask you to give a visually explanation to that 'calc_effective_permeability'? Thanks.

**Comment by jgostick** [comment]
Good point.  we have some of this info in the tutorials, but these have been moved recently.  We are in the process of improve the documentation.   For the time being, this tutorial might help you:

https://github.com/PMEAL/OpenPNM-Examples/blob/fixes/Tutorials/intermediate_usage.ipynb

basically, the domain area and domain length are needed to invert darcy's law and solve for K
