### ISSUE TITLE
Calling trim after extend puts -1 in throat conns

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1039]
The issue is that after extend there is no clearance of network._am and ._im like at the end of trim
@jgostick was this done for a reason (maybe to call it in a loop or something?) or should these matrices always be cleared after topology changes

**Comment by jgostick** [comment]
I actually caught this bug as well, and it's fixed in my ongoing branch on labeling boundary pores.  I will put into a new PR and merge asap
