### ISSUE TITLE
Relative permeability calculations

### ISSUE THREAD

**Issue by sukrumerey** [PMEAL/OpenPNM#1047]
I have imported my pore network model to OpenPNM.

I plan to calculate relative permeabilities.

https://github.com/PMEAL/OpenPNM-Examples/blob/master/Simulations/relative_diffusivity.md was helpful to understand it.

But I have got  errors when I import pore network instead of using PN of OpenPNM.

**Comment by jgostick** [comment]
Hmm, I got the error message in my email alert from Github, but it's now showing here.  Anyway, it seems that your network does not have a 'pore.diameter' assigned.  How did you get your network?  You say you import it?  Maybe you only have radii, like 'pore.radius', so you need to do something like: `pn['pore.diameter'] = 2*pn['pore.radius']`?

**Comment by sukrumerey** [comment]
I had some PN data extracted from micro CTs. I have revised for the format of "Statoil.load(path=path, prefix='Berea')". It worked.

Yes you were right. pn['pore.diameter'] = 2*pn['pore.radius'] and did it for throats as well. But this time I got mistake as KeyError: 'throat.occupancy'. Couldnt find it inside the codes to understant it

**Comment by jgostick** [comment]
The KeyError warning means that the data you are requesting is not present, so in this case it means that you have not calculated the occupancy yet.  This is done by either the ordinary or invasion percolation algorithms.  Algorithms generally do not write data back to their associated phase objects unless you explicitly call the ``return_results`` function, so make sure your' doing that.  You then need to regenerate the physics objects which will use the occupancy values it finds to update the hydraulic conductances.
