### ISSUE TITLE
Add I/O support for PerGeos format

### ISSUE THREAD

**Issue by neumannrf** [PMEAL/OpenPNM#1050]
PerGeos has a network extraction algorithm for microCT geometries. The output can be exported into an ASCII format that could be read by OpenPNM for performing flow simulations.

**Comment by neumannrf** [comment]
@jgostick I am willing to help @mbandreeta contribute with her script to the OpenPNM code base. This could lower the entry barrier for new OpenPNM users who are already accustomed to PERGEOS. Is this feature welcome?

**Comment by jgostick** [comment]
Any IO class is welcome for sure!  Especially from such high profile commercial code.  

(BTW: we are *very* close to finalizing V2, after which we'll finally be ready to merge your PR.  I'm sorry this is taking so long, but I appreciate your patience).
