### ISSUE TITLE
IO doesn't like exporting nets with pore.prop and pore.prop.subprop

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1052]
IO doesn't like exporting nets as xmf with pore.prop and pore.prop.subprop
must be pore.prop.subprop_a, pore.prop.subprop_b

I found this by accident when running a script exporting a net with throat.conduit_lengths and throat.conduit_lengths.pore1 etc

I have only tried this with xmf and the problem is with the NestedDict.

Probably not hard to fix if it's the type of situation we want to support. Or alternatively could add a data health check to spot these scenarios

**Comment by jgostick** [comment]
Which IO is the problem?  It exports are VTK just fine for me.  HDF5 would not like it, but it already changes all '.' to '_' I think

**Comment by jgostick** [comment]
I'm not havng any problem with this.... :-(

**Comment by jgostick** [comment]
OK, so there are actually two problems here:
1.  Exporting does not like a network with no throats, so a 1x1x1 is cause one problem
2.  Having pore.foo and pore.foo.bar is another

**Comment by jgostick** [comment]
This breaks:
```
import openpnm as op
net = op.network.Cubic(shape=[1,1,1])
prj = net.project
net['pore.foo.bar']=1
prj.export_data(network=net, filename='foobar', filetype='xmf')
```

**Comment by jgostick** [comment]
and this breaks:
```
import openpnm as op
net = op.network.Cubic(shape=[2,1,1])
prj = net.project
net['pore.foo']=1
net['pore.foo.bar']=1
prj.export_data(network=net, filename='foobar', filetype='xmf')
```

**Comment by jgostick** [comment]
but this does not:
```
import openpnm as op
net = op.network.Cubic(shape=[2,1,1])
prj = net.project
net['pore.foo.bar']=1
prj.export_data(network=net, filename='foobar', filetype='xmf')
```

**Comment by jgostick** [comment]
So this is really two issues.  One is the networks with 1 pore and 0 throats break things, and the other is that property names like 'pore.boo' and 'pore.foo.bar' should not be allowed simultaneously.  I'm going to close this issue and open two new ones.
