### ISSUE TITLE
How should we handle cases where throat diam > pore diam?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1057]
I agree that this is unphysical, but maybe we should throw a warning or something, but still have a default way to handle it. Here are two suggestion:

![image](https://user-images.githubusercontent.com/14086031/44149212-2eb9a5c4-a069-11e8-8bba-fd7b93d17de3.png)

**Comment by ma-sadeghi** [comment]
Another option is to set `conduit_lengths.pore_head` to 0 and increase the throat length to compensate.

**Comment by ma-sadeghi** [comment]
I think adding a check in `check_geometry_health` is a good idea.

As for implementation, the truncated trapezoid/pyramid should work just fine, but the spherical model probably needs an explicit check.

**Comment by jgostick** [comment]
Fixed in PR #1062
