### ISSUE TITLE
What does 'internal' keyword supposed to do when called upon pores/throats?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1059]

**Comment by jgostick** [comment]
Can you give a code snippet?  Is this a mode?  If so, then it's been removed and replaced with `xnor`.

**Comment by ma-sadeghi** [comment]
```
net.add_boundary_pores()
Ps_int = net.pores('internal')
```
I exptected Ps_int to contain all interal pores, but it doesn't.

**Comment by jgostick** [comment]
We changed the meaning of internal, it now means exactly that.  There are now 'surface' pores and 'internal' pores, and they do not overlap.  You'll also have 'boundary' pores if you add them.

**Comment by ma-sadeghi** [comment]
I see. Wouldn't having both `boundary` and `surface` be a bit confusing?

**Comment by TomTranter** [comment]
Apparently there has been some confusion on this issue. Jeff and I both agree that internal should be all the pores that are not boundary and surface should be the outer layer of internal pores. I will make this change across all the networks ASAP

**Comment by TomTranter** [comment]
@jgostick just so we are super clear. This is the commit you made the change to cubic in to take make the internal label False for pores at the surfaces. https://github.com/PMEAL/OpenPNM/commit/0f214217866c557c7e283a5684b8e2b4947a1b2b#diff-4a66d49b7d0425346b680a17cab0d7bc I then followed suit for DelaunayVoronoi. We are now saying that when we create a cubic network all the pores should be internal and then the user has to add_boundaries and these get the label boundary and connect to the surface pores

**Comment by TomTranter** [comment]
Addressed in PR #1074

**Comment by jgostick** [comment]
We've reverted this back to the old way in PR #1074
