### ISSUE TITLE
Result array names in transient algs should include actual time

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1078]
Instead of outputting the 'loop' number it would be nice if the array names had the actual time in their name, like 'pore.concentration_300' would be for the 300th second.  

As it is now, it only says 0, 1, 2, 3, so the user needs to multiply this number (+1) by  the total time divided by the t_output to find which time the array is actually for...this is suboptimal.

**Comment by jgostick** [comment]
Also, the 0 values should always be written like `'pore.concentration_0'` so that users can find the initial conditions array programatically (i.e. in a for loop)

**Comment by ma-sadeghi** [comment]
What if the time span is only 1 seconds? (so the intervals are fraction of a second)

**Comment by jgostick** [comment]
fair point...maybe could include units: `'pore.concentration_45us'`...assuming all times entered are in seconds.
