### ISSUE TITLE
Allowing pore-scale models to be attached to any objects terribly hurts the performance

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1084]
Following issue #1083, I realized that we're using `map_pores` and `map_throats` pretty much everywhere. Despite the 3X improvement in `_map` in PR #1082, it's still the bottleneck in pretty much any pore-scale model that uses either of the two. I tried without, and pore-scale models will become 3-5X faster. I know that we've already decided that we allow adding pore-scale models to any object, but might be worth discussing.

**Comment by jgostick** [comment]
I've just run my performance notebook with the new dev branch (including your speed-up of _map) and StickAndBall takes them same time.  I'm thinking the delay is entirely from the maximum_sphere method...I will check. But my point is the calls the faster _map function didn't help noticable (though every little bit helps!).

**Comment by jgostick** [comment]
StickAndBall takes 46 seconds to generate, but if I do regenerate with `exclude=['pore.max_size']` it only takes 2.6 seconds.  I will add 'fix max sphere' as an issue and close this...I don't think this _map is a problem really...especially with your recent fixes.
