### ISSUE TITLE
Direction Dependent Quantities: Add touch pressure to meniscus models and handle in MixedIP

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1086]
Version 1 had some capillary pressure models that accounted for the meniscus bulging into the connecting pores and interacting with the pore walls. This was accomplished by comparing a protrusion distance from the throat center with the inscribed diameter of the pore. i.e if the tip of the meniscus extended a distance greater than the indiameter it would touch a solid feature and invasion would occur. This can happen at lower pressures than standard breakthrough which is the maximum pressure required to transition through a throat. Especially when the connecting pores have a high aspect ratio such as those in a Voronoi which has been stretched in one direction (fiber alignment) or extracted fibrous networks.
@jgostick 
It is simple enough to include this analysis in the current framework. However, as each throat is connected to two pores and generally each will have a different size, the touch pressure is dependent on the direction of travel. This was handled in the old Mixed Invasion Percolation algorithm as a special case. The question is do we want to think about direction-dependent properties in a more general way?

**Comment by TomTranter** [comment]
It appears that the convention for positive and negative meniscus movement relative to the throat axis as pressure increases is different for the toroidal and sinusoidal meniscus models. This is problematic for cooperative pore filling which requires a meniscus center that moves towards the center of the pore as pressure increases. Previously it was found that the sign of the radii was inconsistent and efforts were made to correct this but in doing so this new problem has arisen.

**Comment by TomTranter** [comment]
I have re-written the toroidal meniscus model. In the process of calculation it now mirrors the method I developed for the sinusoidal one and both give consistent results for sign or radius and movement of center as pressure increases.

**Comment by jgostick** [comment]
This vaguely applied to some transport algorithm, like compressible flow though a converging vs. diverging throat.
