### ISSUE TITLE
Maybe surface pores in 2d should account for those on the boundary

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1099]
Since in 2d, all the pores are technically on the surface, `net['pores.surface']` is the same as `net.Ps`.

**Comment by jgostick** [comment]
Or...add edges...which would have meaning in 2D and 3D?

**Comment by jgostick** [comment]
I have changed the find_surface_pores method to work properly on 2D networks...so now in 2D only the edges are labeled as surface.  I think we'll skip the 'edges' label for now.
