### ISSUE TITLE
Improve merge_pores by letting it accept a list of lists (instead of a single list)

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1101]
Currently, `merge_pores` accepts a list of pores and merges them together. If you want to do consecutive merging, the current workflow is slow since `trim` is called at the end of each call to `merge_pores`, which essentially rebuilds the adjacency matrix (since it gets destroyed during `extend`). Jeff and I propose `merge_pores` to accept a list of lists, so there's only a single call to `trim`. I've tested the new approach and it makes it at least 10 times faster.

**Comment by jgostick** [comment]
this is done in PR #1105 but is not quite merged yet...but I will close this anyway
