### ISSUE TITLE
Pluralization of dict names

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1108]
We usually use singular dict names, like 'pore.area', but we now have 'throat.conduit_lengths' as plural.  This is a bit inconsistent, causes errors and is hard to diagnose.  

I know this is trivial, but I just wasted too much time on this...so it's worth discussing.

**Comment by ma-sadeghi** [comment]
Each element in `pore.area` is for a single entity, whereas that for `throat.conns` and `throat.conduit_lengths` are for multiple entities. So, it seems that we're consistent with the naming.
