### ISSUE TITLE
Residual is inappropriately being calculated in ReactiveTransport

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1110]
Basically, residual is being calculated as the sum of errors in each pore. This is inappropriate since even a small error in large networks is treated as diverged (say if the network has 1e6 pores, then 1e-6 error in concentration for each pore translates to residual = 1). 

Either we need to redefine tolerance such that it accommodates network size, or redefine residual for instance, as the average error per pore.

**Comment by magnaou** [comment]
I made changes on my "transient" branch to fix this.
The way the residual is calculated:
1) allows to identify whether a source term is linear or not (if yes, the alg will solve 1 time only)
2) makes the tolerance being used independent of the problem being solved (to a certain extent)

I think these were the 2 points Amin raised during last teleconference regarding the "ReactiveTransport".

**Comment by jgostick** [comment]
fixed in PR #1122
