### ISSUE TITLE
Problem with OpenPNM installation

### ISSUE THREAD

**Issue by borahdj2010** [PMEAL/OpenPNM#1118]
I tried installing OpenPNM V2 on my computer. I have anaconda and I tried installing it using the following methods
1) pip install openpnm
2) pip install -e "repository"
When I use conda prompt it gives some error with respect to scikit-umfpack package. The last line of the log file is here 
"Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\deep1\\AppData\\Local\\Temp\\pip-install-jr2g5h8x\\scikit-umfpack\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\deep1\AppData\Local\Temp\pip-record-c3c0sjwo\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\deep1\AppData\Local\Temp\pip-install-jr2g5h8x\scikit-umfpack\"

However, if I try this from windows command prompt it works. Any suggestions on solving this issue?

**Comment by jgostick** [comment]
Interesting, you're the 2nd person to contact me in the past few days about this...I wonder if scikit-umfpack has changed their package somehow?  I am investigating.

**Comment by jgostick** [comment]
See issue #1119
