### ISSUE TITLE
Add AppVeyor to build / test process

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1123]
The recent problem with scikit-umfpack not install in numpy 1.15 was a windows only problem, but travis doesn't accept windows as an optional environment (although it does allow linus and osx).  Apparently AppVeyor allows windows so I've started the process of setting this up.

**Comment by Zohaib-Atiq** [comment]
Travis has started support for windows. Check below link if that helps.

[https://blog.travis-ci.com/2018-10-11-windows-early-release?utm_source=twitter&utm_medium=web&utm_campaign=windows_early_release]

**Comment by Zohaib-Atiq** [comment]
[https://blog.travis-ci.com/2018-10-11-windows-early-release?utm_source=twitter&utm_medium=web&utm_campaign=windows_early_release](url)

**Comment by jgostick** [comment]
Un-be-lievable!!  On the exact day I started looking into appveyor, travis announces this!  Thanks for the heads up @Zohaib-Atiq !
