### ISSUE TITLE
New version note

### ISSUE THREAD

**Issue by Saeid-Sli** [PMEAL/OpenPNM#1128]
As a new version of OpenPNM has been released, it is really worth to have a document showing enhanced features and the main code changes from the version of 1.7 to 2.0. Running previous written codes into the current version breaks easily. So a document showing how to modify them to be run in version 2.0 is necessary.

**Comment by jgostick** [comment]
This is technically an issue for the examples repo, but we'll leave it here since it is so important to the usage.

**Comment by jgostick** [comment]
I have added a new page to the docs that highlights all the changes that I could think of, but I probably missed some
