### ISSUE TITLE
Solve method to simulation transport phenomena in fuel cells

### ISSUE THREAD

**Issue by angelswat** [PMEAL/OpenPNM#1144]
Hi,

I want to know how solve OpenPNM the simulation of electrical, thermal and mass conductivity? I know the above laws have their universal equations and they are diffential partial equations. OpenPNM use numeric methods or use another method? Please, explain me. I need to report it in my research.

**Comment by jgostick** [comment]
I am not quite sure how to answer your question.  The title suggests you want to know how to solve a fuel cell simulation, but the question itself seems like you want the theory behind the numerical methods.  Could you explain your question in a bit more detail?

**Comment by angelswat** [comment]
Sorry if I was not clear.

My question is, what method use OpenPNM to solve for example, Ohm´s Law, Fick´s Law, Stoke´s Law, Fourier´s Law. All those are partial and differential equations and solve them is so complex. So, I want to know how OpenPNM do it.

**Comment by jgostick** [comment]
All the simulations you mention are actually analogous, so we only implement one solver (GenericTransport) and subclass it to the various specialized versions.  These subclasses add the specific details like identifiable names (OhmsLaw) and set sensible defaults (like 'throat.electrical_conductance').  The way we solve these systems is the normal PNM discretization which can be found in the recent review article by Jivkov. Also, we have a bit of info on our [website](https://openpnm.readthedocs.io/en/master/userguide/algorithms/transport.html).  Hope this helps!
