### ISSUE TITLE
problem with boundary pores (2d circle)

### ISSUE THREAD

**Issue by masoodmoghaddam** [PMEAL/OpenPNM#1145]
It seems that find surface pores method breaks when the network is 2d!
I want to work with a 2D circular geometry.  I have:

_import openpnm as op
import scipy as sp
import matplotlib.pyplot as plt
x = op.topotools.template_cylinder_annulus(height=1,outer_radius=20)
pn=op.network.CubicTemplate(template=x,spacing=2e-7)
fig = op.topotools.plot_connections(network=pn)_

but I can not find the boundry pore !!!

_op.topotools.find_surface_pores(network=pn, label='bond')
pn.num_pores('bond')_

I recive this error:
QhullError: QH6239 Qhull precision error: Initial simplex is cocircular or cospherical.  Use option 'Qz' for the Delaunay triangulation or Voronoi diagram of cocircular/cospherical points.  Option 'Qz' adds a point "at infinity".  Use option 'Qs' to search all points for the initial simplex.

While executing:  | qhull d Qt Qc Q11
Options selected for Qhull 2015.2.r 2016/01/18:
  run-id 2043532228  delaunay  Qtriangulate  Qcoplanar-keep
  Q11-trinormals Qtriangulate  _pre-merge  _zero-centrum  Qinterior-keep  Pgood
  _max-width 2.2e+03  Error-roundoff 2.6e-12  _one-merge 2.3e-11
  Visible-distance 1.6e-11  U-coplanar-distance 1.6e-11  Width-outside 3.1e-11
  _wide-facet 9.3e-11

**Comment by jgostick** [comment]
Indeed, you've found a bug.  It's not too tricky to fix though.

**Comment by TomTranter** [comment]
Change one of the coordinates to be slightly out of the plane maybe as a temporary fix, then change back afterwards.

**Comment by jgostick** [comment]
Fixed in PR #1156
