### ISSUE TITLE
bug exists in CubicTemplate

### ISSUE THREAD

**Issue by masoodmoghaddam** [PMEAL/OpenPNM#1147]
want to creat 2d circular geometry but it seems that there is a bug in CubicTemplate!
It dos not show any change with respect to spacing!!!
------------------------------------------------------------------------------------------------------
import openpnm as op
im = op.topotools.template_cylinder_annulus(15, 10, 5)
pn = op.network.CubicTemplate(template=im,spacing=[10e-2,10e-2,10e-2]) :
image.png

pn = op.network.CubicTemplate(template=im,spacing=[10e-2,10e-2,10e-2]) :
image.png

while cubic works well:
pn = op.network.Cubic(shape=[10, 15, 5], spacing=[10e-2,10e-2,10e-8],connectivity=6):
image.png
pn = op.network.Cubic(shape=[10, 15, 5], spacing=[10e-2,10e-2,10e-2],connectivity=6)
image.png

Is it true?

**Comment by jgostick** [comment]
Thanks @masoodmoghaddam, I will investigate asap.

**Comment by jgostick** [comment]
Fixed in #1155
