### ISSUE TITLE
Re-add basic throat length model

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1149]
I know we wanted to be 'rigorous' but the lack of a simple throat length model is a problem.  It caught me off guard today...took me ages to figure out why the scipt wasn't working.

**Comment by ma-sadeghi** [comment]
Don't we have `piecewise` for that?

**Comment by jgostick** [comment]
Piecewise requires end points....which are easy to do, but no if you don't know you're supposed to!

**Comment by jgostick** [comment]
I'm proposing to add an IF to the conductance models, that if 'throat.conduit_lengths' is not found, then 'throat.lengths' is used instead.
