### ISSUE TITLE
Loading projects after class changes

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1151]
Save a project, change a definition in a model or class, try loading it and it will fail. Can we catch these and just load the data?

**Comment by jgostick** [comment]
There is nothing we can do about this.  The only option is for users to either use consistent versions of openpnm between saving and load, or for them to save the data to something like CSV.

This does suggest that maybe there is a better way to save data, but I don't see how we could save all the model info and arguments and such without doing an actual pickle.
