### ISSUE TITLE
Should 2D networks have a top and bottom label?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1160]
In PR #1156 I have fixed the find_surface_pores method to work on 1 and 2D networks.  This means that we can, if we want, avoid labeling 'top' and 'bottom' on networks that are [X, Y, 1].  In fact, this is already happening automatically on this PR, but it means tests are failing because they are expecting to find these labels.  Should I change the tests or change the labeling back to the old way?

**Comment by jgostick** [comment]
@TomTranter and @ma-sadeghi can you guy weigh in on this?

**Comment by TomTranter** [comment]
I think change the tests

**Comment by ma-sadeghi** [comment]
I agree with Tom

**Comment by jgostick** [comment]
fixed on PR #1156
