### ISSUE TITLE
quick plotting in openpnm 

### ISSUE THREAD

**Issue by xu-kai-xu** [PMEAL/OpenPNM#1171]
@jgostick @TomTranter , i did the tutorial in the  OpenPNM-Examples/IO_and_Visualization/quick_plotting_in_openpnm.ipynb section, and i found that the code gave some different plot with what you show. i repeat the work in spyder and jupyter and try on two computers.  the former results are the same. the only difference is the last one and i think the code related is the last two line.
what i got is showed below, which means `find_neighbor_throats` did not really work. 
and i use window system, could that be the problem?

![x e wu49 hy n0w e ln c](https://user-images.githubusercontent.com/44153643/50390638-7e6a3080-0774-11e9-8d4b-0b1a96987107.png)

and the link is [https://github.com/PMEAL/OpenPNM-Examples/blob/master/IO_and_Visualization/quick_plotting_in_openpnm.ipynb](url)

**Comment by jgostick** [comment]
The behavior of find_neighbor_throats changed between version 1 and 2...specifically the `mode='intersection'` argument.  Maybe ensure that spyder and jupyter are using the same version of openpnm?

**Comment by jgostick** [comment]
Yes, the problem is the changed meaning of the intersection keyword.  

Instead of:
```Ts = net.find_neighbor_throats(pores=net.pores('internal'), mode='intersection')```

It should be:
```Ts = net.find_neighbor_throats(pores=net.pores('internal'), mode='shared')```

**Comment by xu-kai-xu** [comment]
@jgostick  yes, thank you. the final result is correct. i can export the photos as yours.

![default](https://user-images.githubusercontent.com/44153643/50573416-75c9c800-0e0e-11e9-9950-c5ec4354be5f.png)

**Comment by xu-kai-xu** [comment]
i saw on the offical page of OpenPNM, a picture showed a sandstone network extracted using the maximal ball algorithm, but i did not find the revelant article. May you tell me which article this picture belongs? and i am trying to transfor the X-ray computed tomography data to a pore network, seems that  i can not directly do it using openpnm, right?    thanks for your time to read and reply it.

**Comment by jgostick** [comment]
That network is extracted using porespy, our other open source package.  We  have a network extraction algorithm called SNOW, that we think does a pretty good job.  BTW, if you have general questions for me, feel free to email, so we can keep the github issues just for issues.  jgostick at uwaterloo dot ca
