### ISSUE TITLE
label_surfaces is slow

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1181]
Here's some benchmarks:

| Size        | w/o           | w  |
| ------------- |:-------------:| -----:|
| 10^3      | 2 ms | 40 ms |
| 20^3      | 10 ms      | 500 ms  |
| 30^3 | 40 ms      |    1600 ms |
| 40^3 | 0.1 s      |    4.4 s |
| 50^3 | 0.2 s      |    10 s |

For relatively large networks (100^3, 200^3, ...), it takes minutes to generate a Cubic network.

**Comment by jgostick** [comment]
damn, I think I did this same thing about a year ago!  I'll fix asap

**Comment by jgostick** [comment]
I just pushed a fix in a PR (#1182).  I reduced the times by 10x based on your chart above, but not the 50x that your seeing....can you check the PR on your PC and see what you get?

**Comment by jgostick** [comment]
OK, I can get the 50x speedup if I remove the find_neighbor_throats call from the init, but this is necessary if we want to label throats on the surface.

**Comment by jgostick** [comment]
This is fixed in the PR, which now passes.
