### ISSUE TITLE
Some questions about codes in example 

### ISSUE THREAD

**Issue by wangyihang12** [PMEAL/OpenPNM#1205]
There are some questions in these codes copied from your website about fluid flow and thermal conduction. In my view, it can be the problem caused by different version in Python or the different version in Openpnm or the system in Linux and Windows. I try to use different version of Openpnm but I did not solve them so I list my questions here and want to learn more things from your reply.

Firstly, the thermal conduction. I use different version of Openpnm from 2.0.0 to 2.0.3 and question is the same as below. 
![thermal conduction bug 2 0 0](https://user-images.githubusercontent.com/45484427/51437585-3985db00-1cdb-11e9-9e8c-90bbd2ee99fa.png)

Secondly, the relative diffusivity. I use different version of Openpnm from 2.0.0 to 2.0.3 and question is different. First one is using Openpnm==2.0.0 and second is using Openpnm==2.0.0b. 
![relative diffusivity bug2 0 0](https://user-images.githubusercontent.com/45484427/51437601-591d0380-1cdb-11e9-80d1-ccf876145efe.png)
I try to solve this problem using the method in the issue part on your website, but I failed.

For Openpnm==2.0.0b
 ![relative diffusivity bug2 0 0b](https://user-images.githubusercontent.com/45484427/51437600-54f0e600-1cdb-11e9-8d87-273b54411e1e.png)

Thirdly, the 2007 model. I use different version of Openpnm from 2.0.0 to 2.0.3 and question is different. First one is using Openpnm==2.0.0b2 and second is using Openpnm==2.0.3 and others.
![2007 bug 2 0 0b2](https://user-images.githubusercontent.com/45484427/51437607-676b1f80-1cdb-11e9-92ef-f659b633dffb.png)

For Openpnm==2.0.3
 ![2007 bug 2 0 3-2 0 0b3](https://user-images.githubusercontent.com/45484427/51437611-6e922d80-1cdb-11e9-845c-6c560bf08387.png)

In the bugs above, they all need more parameters and I do not know how to solve them.

**Comment by TomTranter** [comment]
Hi,
It looks like a whole bunch of different problems. Please post the full scripts you are running for each one. The last error is definitely wrong syntax but I'm not sure where you would have got the idea to put shape='cubes' we have never supported this...

**Comment by jgostick** [comment]
Since we haven't heard back about this in 5 months, I guess it's been solved?
