### ISSUE TITLE
Telecon for Jan 22, 2019

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1206]
Mostly, we need to clear up the open PR.  Too many open for too long makes things very difficult to merge.

1.  #1200 - Using bounding box for area and length: Overview and discussion
2.  #1204 - Allowing retrieval of nested dicts: A good idea or not?  Discuss current limitations.
3.  #1167 - Assigning Geometries to all pores and throats by default: keep or delete?
4. #1140  - Adding preset algorithm for MIP: Works pretty well, any additions?
5. #1199 - Updating Statoil import: Current status and discussion?
6. #1179 - Change results on percolation: should apply_trapping change invasion_sequence?

**Comment by TomTranter** [comment]
7. Brief update on Dragonfly plugin
8. What happened to pip_requirements?
