### ISSUE TITLE
Should apply_trapping adjust invasion sequence arrays?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1207]
When ip is run it creates and invasion_sequence array for both pores and throats.  This is being returned via the ``results`` method (if we accept PR #1179 ).  However, after we have run ``apply_trapping`` the sequence changes but the initial invasion sequences are not changed.  At present trapped pores are just set to -1.  

In the #1179 PR, I have 
(1) set the invasion sequence of trapped pores to a very high number (instead of -1) so boolean thresholding works
(2) changed the invasion sequence of non-trapped pores so that they are contiguous, thus the pore invaded 10th, will become 9th if the pore invaded on step 9 was found to be trapped.

**Comment by TomTranter** [comment]
What's wrong with -1?
