### ISSUE TITLE
regenerate_models is slow

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1215]
It takes about 2 seconds, when solving the network takes 2 ms.  I guess this is from the graph construction-lookup for property dependence.  As a first fix, we should make sure this is only called when really needed.

**Comment by ma-sadeghi** [comment]
I just checked and for 100^3 network, regenerate models takes about 4 sec for `StandardPhysics`, 8 sec for `StickAndBall`, and about 1 sec for `Air`. Also, the overhead is mostly coming from calling the pore-scale models themselves.
