### ISSUE TITLE
Dual networks for simulating heat and mass transfer

### ISSUE THREAD

**Issue by samanjalilian** [PMEAL/OpenPNM#1218]
Hello all
I have some questions in openpnm and I'd really appreciate if you could help me.
I'm using openpnm 2.0.3 and i have faced some problems in Dual networks.
i want to simultaneously simulate a reaction-diffusion mechanism in Voids and heat transfer in solid, so i  used Dual networks for my work. i used secondary network for simulating reaction-diffusion, and the primary network for Heat transfer mechanism. my question is how should i deal with interconnected throats?
i have set "throat.diffusive_conductance" equal to 1e-1000 because i don't want to happen any species transfer  between the two networks (primary and secondary), but how should i set "throat.thermal_conductance"?? because we know that the interconnected throats are just artificial and  have no external existence and they are just the interface between solid and void .(i have set some heat source terms in voids (secondary network) and i want this heat be transferred to solids(primary network) by interconnecting throats.)
I'd be very grateful if you help me

**Comment by jgostick** [comment]
This is a tricky thing to do, but we are in the process of making it easier.  We will have a big coding marathon here next week, and this will be one of the things we address.  I'll get back to you after than.

**Comment by samanjalilian** [comment]
Thanks for your help Mr. @jgostick ,  I'll follow up future conversations in this page

**Comment by jgostick** [comment]
I am sorry to report that after spending several weeks thinking and tinkering with this it is even harder than I expected.  The problem is this:  void-solid heat is exchanged between solid and void pores, but the heat transfer coefficient is known for the throats where the fluid velocity is known.  I cannot seem to figure out how to translate the throat heat transfer to the respective pores for the heat transfer calculation.  I will keep thinking about this, but it will not be ready any time soon.

**Comment by samanjalilian** [comment]
Thank you Mr.gostick for your answer, but it seems that I've found a way to solve this problem in the past weeks. we know that in void phase there is a gas which has a conductivity of K1 and in solid phase we have a material which has a conductivity of K2. so i considered the conductivity in the throats connecting these two phase ( interconnecting throats) as the average of K1 and K2. and then used the series resistors model to calculate the throat thermal conductance in interconnecting throats. but i don't know if this is a right thing to do. or should i set the throat conductivity as the solid conductivity K2 ?
