### ISSUE TITLE
Tortuosity in openpnm 

### ISSUE THREAD

**Issue by samanjalilian** [PMEAL/OpenPNM#1219]
hello all
i have a question in openpnm
how can i calculate the tortuosity of a pore network generated in openpnm? ( i mean like a cube or cylinder generated by openpnm.networks.Cubic ) , i have looked at another python packages( Pytrax and Porespy ) and these packages are dealing very good with any kind of complex porous medias (like sphere packs) , but i didn't find any options related to calculating tortuosity in pore networks generated in openpnm.

**Comment by jgostick** [comment]
Hi @samanjalilian 
So sorry for the late response.  You probably don't need this answer anymore, but I'll post it anyway.  Basically, you have to find the 'effective diffusion coefficient' (Deff) of the network, then find tortuosity from:

Deff/DAb = porosity/tortuosity

This of course also requires finding porosity, which is relatively simple....just add the pore and throat volumes, then divide by the domain volume.  

We are thinking of adding a 'pre-written' algorithm to OpenPNM for doing things like this, but for now it's by hand.

**Comment by xu-kai-xu** [comment]
@jgostick @samanjalilian For the tortuosity, can we just calculate it by finding the actual flowing path or the main actual flowing path and divided it by the length of the network?

**Comment by jgostick** [comment]
Hi @xu-kai-xu Tortuosity is a continuum parameter, so it's really only defined as the ratio of open air to effective diffusivity (times porosity).  Besides, what is the length of the actual flowing path?  This only has a meaning in terms of the observed/simulated effective diffusivity.

**Comment by xu-kai-xu** [comment]
@jgostick , I don't really understand the relation between tortuosity and diffusion. In my previous understanding, tortuosity comes from the Bundle of Capillary Tubes Model. I ref to equation 14 in the article "Yu B. Analysis of Flow in Fractal Porous Media[J]. Applied Mechanics Reviews, 2008, 61(5): 050801. " for the defination of tortuosity. May you recommend an article about the relation between tortuosity and diffusion for me? Thanks!

**Comment by ma-sadeghi** [comment]
@xu-kai-xu Sorry to jump in your discussion. Here's the definition of tortuosity for diffusion:

tau = eps * D(measured) / D(void)

D(void) is the diffusion coefficient in open-space, and D(measured) is the actually-measured diffusion coefficient by fitting the experimental (or direct modeling) to Fick's law, and eps is the porosity of the material.

Here's the [reference](https://link.springer.com/content/pdf/10.1007/s11242-011-9734-9.pdf).

**Comment by jgostick** [comment]
Thanks @ma-sadeghi.  Tortuosity is a fitting parameter that accounts for the difference between diffusion flux though open space and diffusion flux through a porous medium.  The porosity accounts for some of the reduction, but not all.  The extra reduction is attributed to the added path length of the paths through the medium, so is has a physical basis, but it is ultimately just an extra fitting factor.
