### ISSUE TITLE
Import of network generated by porespy

### ISSUE THREAD

**Issue by lanetszb** [PMEAL/OpenPNM#1223]
Dear Team,

We have extracted the network using porespy and now are trying to import this network into openPNM. 

We use methods Dict.load and Dict.from_dict. While the first one works, the second method gives an error saying:

line 76, in from_dict
    objs['base'][path[-2]][path[-1]] = d[item]
IndexError: list index out of range

We have tried to pass two different 'delimiter' arguments:
 1) from_dict(dct, project=None, delim='.')
2) from_dict(dct, project=None, delim=' | ')

P.S. I also attach the extracted pore network model and the exact code we use
[openPNM_test.py.zip](https://github.com/PMEAL/OpenPNM/files/3026433/openPNM_test.py.zip)

[Berea_openPNM.net.zip](https://github.com/PMEAL/OpenPNM/files/3026417/Berea_openPNM.net.zip)

I would be grateful if you help me to resolve this issue.

Thank you in advance, Zak

**Comment by jgostick** [comment]
Hi Zak, I will investigate this, but the easiest way to get into openpnm is:

```
pn = op.network.GenericNetwork()
pn.update(net)
```

where ``net`` is the dicitonary returned from the ``snow`` extraction algorithm.  This illustrated in [this example](https://github.com/PMEAL/porespy/blob/master/examples/networks/snow_basic.ipynb).

**Comment by jgostick** [comment]
I see that the ``from_dict`` method does not work on the dict produced by PoreSpy, which is obviously a problem.  I will remedy this asap.  I also notice, embarrassingly, that ``ps.io.to_openpnm`` also does not work!  We changed openpnm's file format to accept a list of dicts, and failed to update this method.  Oy.  The unit tests should've caught that, but I see we didn't write a proper test.  I will fix today, and push to dev.  It should find it's way into master and PyPI asap.

**Comment by jgostick** [comment]
Ok, the changes are not yet merged into dev or master, but both porespy and openpnm have been tweaked to improve interoperability.  You can now do any of the following to get data from porespy to openpnm:

Assuming the extracted network is in a dictionary called ``net``:

* Open dict directly in OpenPNM
```
proj = op.io.OpenpnmIO.load_object_from_dict(dict=net, objtype='net', objname='pn_01')
```

* Create empty network and update with dict by hand:
```
pn = op.network.GenericNetwork()
pn.update(net)
```

* Save to an OpenPNM project from within PoreSpy, then open in OpenPNM:
```
ps.io.to_openpnm(network=net, filename='snow.net')
project = op.io.OpenpnmIO.load_project(filename='snow.net')
```

**Comment by anooppandey276** [comment]
@jgostick respected sir, I was trying this syntax: pn = op.network.GenericNetwork() ,  and it shows that module 'openpnm.network' has no attribute 'GenericNetwork'


![image](https://user-images.githubusercontent.com/129926811/229987091-e8efb916-5683-489c-82d2-72457b6e8be8.png)

**Comment by anooppandey276** [comment]
can you please help me out

**Comment by likeduck** [comment]
It was 4 year ago! Now openpnm have been updated to 3.0, you can use `op.io.network_from_porespy` to import.
