### ISSUE TITLE
Add regen_mode as argument when instantiating geometries, etc.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1244]
When experimenting on large networks, it would be nice if `regen_mode` could be passed during instantiation of objects such as `StickAndBall`, `Standard`, etc. such that it would affect all containing pore-scale models. This is advantageous because sometimes you need the base object (ex. `Standard`), but would like to change one specific pore-scale model, and without passing `regen_mode=deferred`, you need to regenerate models multiple times, which takes a long time on large networks.

**Comment by jgostick** [comment]
This is a fine idea.  We can add 'regen_mode' to the setting dict, and the ``add_model`` method can check there for the default value.  At the moment it defaults to 'normal' via a keyword argument.  This is an easy and helpful fix.  Start a new PR!

**Comment by jgostick** [comment]
This is done in PR #1307.  It took only 4 lines of code and a test!  Very easy.

**Comment by jgostick** [comment]
I should add that you now do:

```
pn = op.network.Cubic(shape=[5, 5, 5])
geo = op.geometry.StickAndBall(network=pn, pores=pn.Ps, throats=pn.Ts, 
                               settings={'regen_mode': 'deferred'})
```
