### ISSUE TITLE
Add Dispersion to metrics folder as a wrapper for AdvectionDiffusion

### ISSUE THREAD

**Issue by magnaou** [PMEAL/OpenPNM#1253]
We now have on "dev" 2 algorithms doing the same thing; the "AdvectionDiffusion" and "Dispersion". Should we keep both?
I like having an "AdvectionDiffusion" algorithm as it can be applied to both heat and mass transfer problems, etc. On the other hand, dispersion is a popular transport phenomenon and having a "Dispersion" algorithm makes sense on OpenPNM.
Also, if we decided to keep both, the "_build_A" should be moved outside of the "AdvectionDiffusion" algorithm and the conductance should be renamed to be consistent with the rest of the code.

**Comment by jgostick** [comment]
I think the idea was to go with **AdvectionDiffusion** as the base algorithm, and add a **Dispersion** class to the ``metrics`` sub-folder, with the latter just being a wrapper around the former, including a method for getting the dispersion coefficient of the network.

**Comment by magnaou** [comment]
Ok, it is fixed on PR #1255. Didn't put the dispersion alg in a metrics sub-folder though. Should we do that for Interpore?

**Comment by ma-sadeghi** [comment]
@jgostick @maghighi What's the status of this issue?

**Comment by ma-sadeghi** [comment]
We basically need to convert the existing [example](https://github.com/PMEAL/OpenPNM/blob/dev/examples/notebooks/algorithms/transient/transient_advection_diffusion.ipynb) into a proper metric.

**Comment by jgostick** [comment]
We no longer have a metrics folder, only examples of how to use the existing algorithms to find the desired metrics by hand.
