### ISSUE TITLE
Should Cubic allow 2D shape in the form of [nx,ny]?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1256]
Currently, `Cubic` throws an error if the shape argument is in the form of `[nx,ny]`, instead of say `[nx,ny,1]`.

**Comment by jgostick** [comment]
For sure!  I think I actually snuck that into a branch I have somewhere, but haven't merged yet.  Go ahead and do it and I'll remove my version.  Just check if len(shape) == 2, then append a 1 to the end.

**Comment by ma-sadeghi** [comment]
Addressed in #1258
