### ISSUE TITLE
Implement adaptive time stepping

### ISSUE THREAD

**Issue by magnaou** [PMEAL/OpenPNM#1269]
The transport's time scale strongly varies from one problem to another. I think it makes sense to implement adaptive time stepping. We can do something to force the deltaT to not allow a fluid particle to cross more than one throat within one time step (the famous CFL condition).

**Comment by jgostick** [comment]
This is built into the scipy.integrate.ivp_solver, which we will start to use.  We have also implemented it in the solverlib sandbox so can add this as an option if needed.  I'm going to remove this from project.
