### ISSUE TITLE
About Vapour Phase Compressibility in Percolation

### ISSUE THREAD

**Issue by HongyangWangUniversityofRegina** [PMEAL/OpenPNM#1277]
Hi, Dear Prof.Gostick,

I am wondering if openpnm can fulfill a process of gas cluster expansion under pressure depletion with/without mass transfer, such that it considers gas compressibility corresponding to pressure field? I am assuming the InvasionPercoaltion module in openpnm is for incompressible flow? Just wondering if you have done such a case before?

Thank you for answering.

Sincerely,
Hongyang

**Comment by jgostick** [comment]
Hi @Hongyang  I thought I'd replied to you already, sorry for the delay.  Our percolation algorithms are for incompressible gases and we've not done anything like you propose.  Sorry.
