### ISSUE TITLE
Add examples of transport phenomena. Improve user experience.

### ISSUE THREAD

**Issue by angelswat** [PMEAL/OpenPNM#1298]
Hi @jgostick and @TomTranter 

In the past versions of openpnm we had examples about transport phenomena and that were so good. Now, with the updates Im not so clear with the new implementations and how to use it.

Please, could you recommend me any example, if it exists, or could you coordinate the implementation of any example about this topic (thermal conductivity, electrical conductivity, mass difussion, etc). 

Thanks for your help!

**Comment by jgostick** [comment]
We've moved the examples to the main repo, to ensure that they are always up to date.  You can find them here:

https://github.com/PMEAL/OpenPNM/tree/master/examples
