### ISSUE TITLE
InvasionPercolation should have plot intrusion curve method

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1304]

**Comment by TomTranter** [comment]
@jgostick I can do this if you agree it's needed. Was it something @Ni2M was working on a while back too?

**Comment by jgostick** [comment]
I don't think she has the time/knowledge about the IP algorithm to do this.  My thought was to make a curve that shows the 'fuzzy' spikes in capillary pressure where the envelope of peak pressures corresponds to the OP curve...do you know what I mean?  I think you've done a graph like this before, so hopefully you can dust off this code?  It would be handy if the IP alg had a method for plotting this curve automatically, making it analogous to OP, so ``plot_intrusion_curve``.

**Comment by jgostick** [comment]
This is already present.  Not sure when it was added, but it's there now! :-)
