### ISSUE TITLE
Porespy network not connected

### ISSUE THREAD

**Issue by mbandreeta** [PMEAL/OpenPNM#1310]
The extracted network from porespy is not fully connected for some samples that I'm trying to find the permeability . It would be helpful having a method to remove isolated pores, or to find the largest connected subgraph in openpnm.

**Comment by jgostick** [comment]
There are several ways to solve your problem.  
1.  You can pre-proccess the image, by removing isolate pores using ps.filters.trim_isolated_pores
2.  You can post-process your network in openpnm as follows:

This health check will find all isoalated pores that are causing you trouble.  It returns a dictionary that has several keys pertaining to different topological aspects.  You can print it to see if any problems were found ([ ] mean no problem).  
```
h = pn.check_network_health()
```

It sounds like in your case you have some isolated pores or disconnected clusters of pores.  The check will attempt to predict which pores should be removed from the network to solve your issue, and this is given as 'trim_pores'.  So you can then do:

```
op.topotools.trim(network=pn, pores=h['trim_pores'])
```

Running the health check again should indicate all empty square brackets, meaning all is good.

**Comment by mbandreeta** [comment]
thank you for your prompt reply!
I opted for trimming the pores post-process and it solved the issue.
