### ISSUE TITLE
Warning: Some inlet pores have non-zero volume, will result in non-zero initial saturation 

### ISSUE THREAD

**Issue by fjkr5** [PMEAL/OpenPNM#1313]
Dear all,

I tried the example from the following page but I got a warning.
https://github.com/PMEAL/OpenPNM

Code attached.

`import openpnm as op

pn = op.network.Cubic(shape=[10, 10, 10], spacing=0.0001)
geo = op.geometry.StickAndBall(network=pn, pores=pn.Ps, throats=pn.Ts)
Hg = op.phases.Mercury(network=pn)
phys = op.physics.Standard(network=pn, phase=Hg, geometry=geo)
mip = op.algorithms.Porosimetry(network=pn)
mip.setup(phase=Hg)
mip.set_inlets(pores=pn.pores(['left', 'right', 'top', 'bottom']))
mip.run()`

The warning is:
Some inlet pores have non-zero volume, will result in non-zero initial saturation 
    SOURCE: openpnm.algorithms.OrdinaryPercolation.set_inlets 

Can you please tell me what's wrong with it? Thank you!

**Comment by jgostick** [comment]
Nothing is wrong.  The warning is as it says.  Pc curves start by setting the inlet pores to saturated then proceeding by invading the connected throats, and so on.  Ideally, you should start this simulation in 'boundary pores', which have 0 volume, and you wouldn't get this error.  If you start in 'real internal pores', then they will have a volume, hence the error.  

It just so happens that this error and the invasion approach that causes it have been annoying us as well and we''ve changed the algorithm in the current dev version.  Now the inlet pores are NOT set to invaded until at least one of their throats is invaded.  This is not quite as physical, but solves several problems, including this 'non-zero' starting saturation business. 

For the time being, you can manually set your inlet pores to have volume of zero to make nicer capillary curves, and avoid this error.

**Comment by fjkr5** [comment]
Hi Dr @jgostick <https://github.com/jgostick>,

Thanks for your answering. But how to set the volume of inlet pores to
zero? I changed the code
'mip.set_inlets(pores=pn.pores(['left', 'right', 'top', 'bottom']))'
to
'mip.set_inlets(pores=[0])',
but it returns to the same warning.

In this page https://github.com/PMEAL/OpenPNM , it also says '
MIP.plot_intrusion_curve()'
gives the drainage curve, but no figures comes out. Can you please explain
why? Thanks a lot!

**Comment by jgostick** [comment]
You should literally set their geometry to zero like:

geom['pore.volume'][pn.pores(['left', 'right', 'top', 'bottom']] = 0.0

**Comment by fjkr5** [comment]
Thank you so much! I can run it now, but it still doesn't have the drainage
curve. I tried 'plt.show()' and 'mip.plot_intrusion_curve()'. Both don't
work. Do you have any suggestions on it? Thanks again.

**Comment by jgostick** [comment]
Hmm.  Are you doing this in Spyder or a Jupyter notebook?  If a notebook put %matplotlib inline at the top of the file.

You should also be able to get the data using ``mip.get_intrusion_data()``.  This returns a tuple containing the pressure and non-wetting phase saturation.

**Comment by fjkr5** [comment]
Hi Dr @jgostick <https://github.com/jgostick>,

Thanks so much for your patient! I am using terminal to run .py file now. I
added %matplotlib inline at the top and it returns:

File "test.py", line 2
    %matplotlib inline
    ^
SyntaxError: invalid syntax


Then I copy paste the code in Terminal. I got the following result. It says
"Figure size 640x480 with 1 Axes".


>>> import openpnm as op
>>> import matplotlib.pyplot as plt
>>> pn = op.network.Cubic(shape=[10, 10, 10], spacing=0.0001)
>>> geo = op.geometry.StickAndBall(network=pn, pores=pn.Ps, throats=pn.Ts)
>>> geo['pore.volume'][pn.pores(['left', 'right', 'top', 'bottom'])] = 0.0
>>>
>>> Hg = op.phases.Mercury(network=pn)
>>>
>>> phys = op.physics.Standard(network=pn, phase=Hg, geometry=geo)
>>> mip = op.algorithms.Porosimetry(network=pn)
>>> mip.setup(phase=Hg)
>>> mip.set_inlets(pores=pn.pores(['left', 'right', 'top', 'bottom']))
>>> mip.run()
>>> mip.get_intrusion_data()
pc_curve(Pcap=array([ 21356.30059424,  23817.68082303,  26562.74279735,
 29624.18172284,
        33038.46102954,  36846.24667148,  41092.89148067,  45828.97534444,
        51110.90763982,  57001.59910039,  63571.21111797,  70897.9914035 ,
        79069.20596059,  88182.17847184,  98345.4494777 , 109680.06915433,
       122321.03908811, 136418.92021914, 152141.6261053 , 169676.42286556,
       189232.15962295, 211041.75601307, 235364.97638576, 262491.52374204,
       292744.49025708]), Snwp=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
0.044652902554029074, 0.17646514814576056, 0.3784377423022627,
0.5518712364394008, 0.696333900155297, 0.7837403186424815,
0.846989093852444, 0.8958162383114775, 0.9325199175352639,
0.9652577342592725, 0.9887927291642227, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
>>> mip.plot_intrusion_curve()
<Figure size 640x480 with 1 Axes>


Thank you!

**Comment by fjkr5** [comment]
Hi Dr @jgostick <https://github.com/jgostick>,

Please just ignore my last email. This problem is solved. I am just
wondering what is the unit of the capillary pressure. Thank you!

**Comment by jgostick** [comment]
The units are 'user defined'.  We don't have a way to track units in openpnm unfortunately.  All the unit packages have down sides and/or performance issues.  So, basically, just always use SI units all the way through, then the pc curve will also be in SI (Pc = Pa, snwp = dimensionless)

**Comment by fjkr5** [comment]
OK. Thank you so much for your help!!
