### ISSUE TITLE
Delaunay network generation

### ISSUE THREAD

**Issue by Abolfazlmsl** [PMEAL/OpenPNM#1316]
Hello,
I started to generate delaunay networks with various number of pores. it works for networks with few pores but for generating a network with large number of pores (182185185) i got this error.
![1564405803887blob](https://user-images.githubusercontent.com/41609766/62158191-25730400-b324-11e9-841b-bd134b7b84db.jpg)
![1564405785885blob](https://user-images.githubusercontent.com/41609766/62158192-25730400-b324-11e9-8114-a5884eff7c31.jpg)

Thanks for your help
best regards,
Abolfazl

**Comment by jgostick** [comment]
Hi Abolfazl, from your script is seems you're trying to generate a network with 182 billion pores.  This is too many.  Our current dream is to model 1 billion pores on a super computer, and we're not there yet. I suggest you try less then 100,000 pores.

**Comment by Abolfazlmsl** [comment]
Thank you for your response🙏
