### ISSUE TITLE
Local variable "R" referenced before assignment

### ISSUE THREAD

**Issue by angelswat** [PMEAL/OpenPNM#1321]
Hi @jgostick and @TomTranter !

Please help me. I was running a code to generate a porous media based on voronoi fibers model. But I got this error, and I have tried to fix it but I haven't obtained a good result.

`---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-48-1611f678e0c6> in <module>
     59 flow.run()
     60 phase.update(flow.results())
---> 61 peef = round(flow.calc_effective_permeability(domain_area=side**2,inlets=net.pores('front'),outlets=net.pores('back'),domain_length=side)[0], 20)
     62 print('Hydraulic permeability: ' + str(peef) + ' m^2')

C:\ProgramData\Anaconda3\lib\site-packages\openpnm\algorithms\StokesFlow.py in calc_effective_permeability(self, inlets, outlets, domain_area, domain_length)
    109         d_normal = self._calc_eff_prop(inlets=inlets, outlets=outlets,
    110                                        domain_area=domain_area,
--> 111                                        domain_length=domain_length,mode='single')
    112         K = d_normal * sp.mean(phase['pore.viscosity'])
    113         return K

C:\ProgramData\Anaconda3\lib\site-packages\openpnm\algorithms\GenericTransport.py in _calc_eff_prop(self, inlets, outlets, domain_area, domain_length)
    601 
    602         Ps = np.isfinite(self['pore.bc_value'])
--> 603         BCs = np.unique(self['pore.bc_value'][Ps])
    604         Dx = np.abs(np.diff(BCs))
    605         if inlets is None:

C:\ProgramData\Anaconda3\lib\site-packages\openpnm\algorithms\GenericTransport.py in rate(self, pores, throats, mode)
    570             Qp = np.zeros((self.Np, ))
    571             np.add.at(Qp, P12[:, 0], -Qt)
--> 572             np.add.at(Qp, P12[:, 1], Qt)
    573             R = Qp[pores]
    574             if mode == 'group':

UnboundLocalError: local variable 'R' referenced before assignment`

**Comment by TomTranter** [comment]
Can you post the whole script you used to get this error. From looking at the GenericTransport it could be because the pores you used as boundaries don't exist but I can't tell without more info
