### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atsamaei** [PMEAL/OpenPNM#1332]
Hi  @jgostick and @TomTranter ,

Is it possible to transfer a geometry made by OpenPNM to a FEM software such as ABAQUS or ANSYS? If so, is there any filter in OpenPNM in this regard?

Thank you.

**Comment by jgostick** [comment]
Hi @atsamaei.  We have been working on this, but at the moment its not ready or complete.  What were you hoping to export exactly?  A domain of sticks and balls that can be meshed?

**Comment by atsamaei** [comment]
I was thinking of getting the geometry that you show on the Highlight section (the olive colored matrix and pores/holes). No sticks and balls. There are very few open source codes that can generate pores in the solid matrix. I see that DREAM3D can do the job but creating a secondary phase as pores instead of real holes/pores. It has a filter that writes ABAQUS input so that the geometry made by DREAM3D can be transferred to ABAQUS. But, OpenPNM can in fact create the real pores/holes. If it had a filter for generating the geometry (matrix and pores) for ABAQUS, it would be the only code package doing the job for those researching on porous media/materials.

**Comment by jgostick** [comment]
Hmmm, I'm still not clear.  I don't know what you mean by "pores instead of real holes/pores".  Anyway, we don't have this capability anyway, sorry.

**Comment by atsamaei** [comment]
I meant that the secondary phase (that you consider as pore) is solid on ABAQUS and, there, you need to convert it to holes. It is not like holes when you read it on ABAQUS. Thanks for the replies. You did a great job. Thanks.

**Comment by TomTranter** [comment]
If you have a tomography image you can use simpleware scan IP to turn it into a mesh. Not open source though I'm afraid but I've seen the results and they are very good. If you don't yet have the image look at our porespy package under generators. Cheers

**Comment by atsamaei** [comment]
Thank you so much, Tom. It helped me a lot.
