### ISSUE TITLE
Problem with zero value BC and rate BC

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1337]
```
import openpnm as op
import openpnm.topotools as tt
import matplotlib.pyplot as plt
import numpy as np

plt.close('all')
I_app = 1.0
sigma = 1e-3
spacing = 1e-5
net = op.network.Cubic(shape=[10, 2, 1], spacing=spacing)
print(net.labels())
net['pore.cc'] = net['pore.left']
net['pore.sep'] = net['pore.right']
net['pore.terminal'] = net['pore.front']

del net['pore.left']
del net['pore.right']
del net['pore.front']
del net['pore.back']
del net['pore.internal']
del net['pore.surface']
del net['throat.internal']
del net['throat.surface']
print(net.labels())

Ts = net.find_neighbor_throats(net['pore.sep'], mode='xnor')
tt.trim(net, throats=Ts)
Ts = net.find_neighbor_throats(net['pore.cc'], mode='xnor')
net['throat.cc'] = False
net['throat.cc'][Ts] = True

trim = np.logical_and(~net['pore.cc'], net['pore.terminal'])
tt.trim(net, pores=trim)
terminal = np.logical_and(net['pore.cc'], net['pore.terminal'])
Ps = net.Ps
Ts = net.Ts
geo = op.geometry.GenericGeometry(network=net, pores=Ps, throats=Ts)
geo['pore.volume'] = (spacing)**3
phase = op.phases.GenericPhase(network=net)
phase['throat.electrical_conductance'] = sigma*spacing
q = I_app*geo['pore.volume']
for bc_val in [-0.1, 0.0, 0.1]:
    alg = op.algorithms.OhmicConduction(network=net)
    alg.setup(phase=phase,
              quantity="pore.potential",
              conductance="throat.electrical_conductance",
              )
    alg.set_rate_BC(net['pore.sep'], values=-q[net['pore.sep']])
    alg.set_value_BC(terminal, values=bc_val)
    alg.run()
    print(bc_val, alg['pore.potential'][0]-alg['pore.potential'][-1])
```

**Comment by ma-sadeghi** [comment]
Hi @TomTranter, can you elaborate?

**Comment by TomTranter** [comment]
What do you see when you run the code? For the zero BC the potential everywhere is zero and shouldn't be.

**Comment by jgostick** [comment]
This problem goes away when you set I_app to 10,000 or higher. Is it a solver tolerance issue?

**Comment by TomTranter** [comment]
Probably, I played with some of the tolerances and made them small but didn't always get the same result as the other two cases.

**Comment by jgostick** [comment]
But the default solver is scipy is lapack, or umfpack if installed, and both are direct, so tolerance shouldn't be an issue.  Other culprits could be use of an ``int`` array somewhere that is causing truncation, or a float 'underflow', meaning the low g values times the low delta V values are conspiring to make the values too small for the float representation.  Is that even a thing?

**Comment by ma-sadeghi** [comment]
@TomTranter 
You're right, I get zero potential everywhere when potential BC is zero. So, I changed the applied current `I_app` from `1` to `10000`, and here are the average potentials:
```
bc: -0.1
mean potential: -0.1304736842105252
bc: 0.0
mean potential: -0.03047368421052603
bc: 0.1
mean potential: 0.06952631578947312
```
So, I think for `I_app = 1`, for this specific problem, the source term is too small to affect the potential distribution in the network.

**Comment by jgostick** [comment]
ya, but it goes from to 0's when you put 1000, which seems a bit to abrupt to me.

**Comment by ma-sadeghi** [comment]
@TomTranter , @jgostick 
You're right, this is indeed a bug, which was recently fixed on our private repo, although not yet merged onto `dev` (you can try `fix_partitioning_BC` branch on our private repo). Basically, the way we calculated the residual/stopping criteria was not quite right. I ran the code w/ 0 voltage BC and here's what I get
```
bc: 0.0
mean potential: -2.171608077235968e-06
```
I guess we'll be merging this change along with some other changes in the coming week.
