### ISSUE TITLE
Modify plt.imshow in documentation to accomodate a 90-degree rotation to align w/ output of plot_connections/coordinates

### ISSUE THREAD

**Issue by Saeid-Sli** [PMEAL/OpenPNM#1353]
The two sister tools for plotting 2-D pore networks (1-plot_connections and 2-imshow)  are not functioning well. For example, the output of imshow should be rotated -90 degree to lie on top of the output of plot_connections (See attached figures). These two functions worked very well in the first version of OpenPNM

![Figure_1](https://user-images.githubusercontent.com/29663268/70504994-2589d880-1b3c-11ea-802e-df8ab1637c2f.png)
![Figure_2](https://user-images.githubusercontent.com/29663268/70505013-2de21380-1b3c-11ea-8814-0fc2c956b6c4.png)

.

**Comment by ma-sadeghi** [comment]
@Saeid-Sli, `plot_connections` uses xy-coordinates, i.e. Cartesian coordinate system, whereas `imshow` uses rc-coordinates, i.e. row-column coordinate system, and since row = column = 0 for a matrix is the top-left most element, hence the -pi/2 rotation is needed to align the two.

**Comment by Saeid-Sli** [comment]
Thank you Amin. That's right.I think we should apply this  -90 rotation to the imshow matrix by transposing its matrix before plotting. 
Saeid

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 10, 2019 at 15:54, Amin Sadeghi<notifications@github.com> wrote:   
@Saeid-Sli, plot_connections uses xy-coordinates, i.e. Cartesian coordinate system, whereas imshow uses rc-coordinates, i.e. row-column coordinate system, and since row = column = 0 for a matrix is the top-left most element, hence the -pi/2 rotation is needed to align the two.

**Comment by ma-sadeghi** [comment]
Hi @Saeid-Sli. I think the way `plot_connections` works at the moment is how most people expect, i.e. x-axis to stretch from left to right, and y-axis from bottom to top. So, I guess we can close this issue? or am I missing something?

**Comment by Saeid-Sli** [comment]
Hi @ma-sadeghi . The problem has not been resolved yet. The problem is that the two outputs are plotted in different orientations (with -pi/2 degree rotation). As you indicated, **plot_connections**  works well but the problem is with **im.show**. Compare the following two images which are plotted from the same image by both methods but at two different orientations.

![image](https://user-images.githubusercontent.com/29663268/73589184-2b6ebb00-44e8-11ea-9630-d5d4719ce2e3.png)

![image](https://user-images.githubusercontent.com/29663268/73589186-31649c00-44e8-11ea-8c84-ed8838652d72.png)

**Comment by ma-sadeghi** [comment]
@Saeid-Sli I know, but `plt.imshow` is part of `matplotlib`.

**Comment by Saeid-Sli** [comment]
@ma-sadeghi One of these plots are not being shown correctly!  You are right that **plt.imshow** is a part of **matliplot**. So, please check the output of **plot_connections**. Maybe it is not being shown correctly. I had the same problem when the output was exported to **paraview** (the same -pi/2 rotation was necessary). I found this issue when I  was ploting 2D networks by these tools simultaneously.  I think the problem should be related to the **origin** of OpenPNM and its axes are not based on the right-hand rule.

**Comment by ma-sadeghi** [comment]
Tho following code
```
import openpnm as op

net = op.network.Cubic(shape=[5, 5, 1])
# Trimming two pores along the y-axis
op.topotools.trim(net, pores=[0, 1])
op.topotools.plot_connections(net)
```
produces
![image](https://user-images.githubusercontent.com/14086031/73610077-be1f6080-45a1-11ea-836a-8b5fa27be3ab.png)
which is what I expected. 

And this is what paraview rendered

![image](https://user-images.githubusercontent.com/14086031/73610113-0b033700-45a2-11ea-9804-a60d5c44581e.png)

**Comment by Saeid-Sli** [comment]
@ma-sadeghi Hi Amin. 

I checked the code again. I run the code in both 1st and 2nd versions of OpenPNM. The rotation problem was raised just in the first version of OpenPNM. 

In Ver2, both `topotools.plot_connections` and Paraview outputs are identical. However, the `imshow` output needs +90 rotation in order to be aligned with `Paraview `and `topotools.plot_connections`. As `imshow` is a part of `matplotlib`, we should modify the examples on the OpenPNM documentation site by the following code:

`plt.imshow(sp.ndimage.rotate(pn.img,90))`

I checked our documentation, in two times we used `imshow`, both in percolation algorithms (see below),

![image](https://user-images.githubusercontent.com/29663268/73819937-d98aa580-4805-11ea-81f8-0573fdcb3c2d.png)

**Comment by ma-sadeghi** [comment]
Right, so it's a documentation issue. I'll tag this issue for the next release to be fixed.

**Comment by jgostick** [comment]
We use imshow once in the actual code:  `plt.imshow(slice_image.T, cmap='Greys', origin='lower')`.  In this instance the orientation is correct.  I supposed to be thorough we should add the .T and the origin='lower' to the examples too.

**Comment by jgostick** [comment]
I have fixed the only use of imshow in the docs to transpose and use origin='lower' in PR #1404
