### ISSUE TITLE
Stopping criteria for nonlinear algorithms

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1355]
~~Suppose we're trying to solve Fickian diffusion with a nonlinear source term, say r = kc^2. For the algorithm to stop iterating, it must produce a solution vector c* such that the residual is less than a reference tolerance. Naturally, we defined residual as `r = A*c* - b`. But, there's something fundamentally wrong with that: `A` and `b` are not the true manifestations of the physics behind the problem, rather they are only linear approximations of it close to the exact solution. Because of that, `r` computed this way does not truly show how far we are from the exact soluton.~~

Another issue worth discussing is how we calculate reference tolerance. Currently, it is defined as `ref_tol = norm(A*x + b)`, which is fine for the most part, except when the solution starts to diverge, `ref_tol` becomes unstable as `x` (and possibly entries in `A` and `b` due to `_apply_sources`) starts to rapidly grow. One quick fix would be to catch when `ref_tol` becomes infinite, and throw an exception accordingly. But, there might be a better solution that involves redefining `ref_tol` in a way that's invariant throughout the iterations.

Finally, this is not a pressing issue, but might be worth discussing.

---
PS. We took the formula for `ref_tol` from a highly-cited textbook (Bai, Zhaojun, et al., eds. Templates for the solution of algebraic eigenvalue problems: a practical guide. Society for Industrial and Applied Mathematics, 2000.)

**Comment by jgostick** [comment]
Is this one done now that (a) scipy has changed it's definition of atol, and (b) we've updated a few things?

**Comment by ma-sadeghi** [comment]
I'm pushing some changes as a new PR soon, will reference this issue then

**Comment by jgostick** [comment]
Fixed in PR #1378
