### ISSUE TITLE
Update docstring in find_nearby_pores to describe what include_input means more clearly

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1358]
Amin:
> The following code snippet
> ```
> ps = find_nearby_pores(pores=10, r=5, include_input=True)
> ```
> is expected (or is it?) to include pore 5 in ps, but it doesn't do so.
> 
Jeff:

> This is the intended behavior, but perhaps the arg name is not good. We can update the docstring to be more clear.

**Comment by jgostick** [comment]
Fixed in PR #1404
