### ISSUE TITLE
Ensure iterative solver's tolerance is less than the non-linear reaction's tolerance #29

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1360]
When using an iterative linear solver with the new _run_reactive on reactiveTransport, the tolerance of the linear solver should be smaller than the one set for the _run_reactive method. Otherwise, the solver keeps iterating giving back the same solution after each iteration until reaching the max_iter.

**Comment by jgostick** [comment]
Fixed in PR #1378
