### ISSUE TITLE
[Proposal] pores and throats methods on objects should look up in network and return mapped indices for that object

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1361]
Right now, if we have multiple domains, to get the right indices of pores/throats, we need to explicitly use `map_pores` or `map_throats`. Here's what that I'm proposing should look like:
```
>>> phys1.map_pores(net.pores("blah"), origin=net)
[1, 2, 3, 9, 15]
>>> phys1.pores("blah")
[1, 2, 3, 9, 15]
```
Currently, the following snippet expectably throws an error.
```
>>> phys.pores("blah")
KeyError: 'pore.blah'
```
Is there a reason why we don't do this? @jgostick What do you think?

**Comment by jgostick** [comment]
I recently added a ``target`` argument to pores and throats, so you can do:

```python
>>> phys1.set_label(pores=[1, 2, 3], label='blah')
>>> phys1.pores('blah')
[1, 2, 3]
>>> phys1.pores('blah', target=net)
[a, b, c]
```
where a, b and c are the indices of pores 1, 2, 3 in terms of network indices.

Not sure if this is the same as what you're suggesting?

**Comment by jgostick** [comment]
Are you suggesting that 'blah' is a network label?  So:

```python
>>> net.set_label(pores=[1, 2, 3], label='blah')
>>> net.pores('blah')
[1, 2, 3]
>>> phys.pores('blah')
raise KeyError 'blah' not found
>>> phys.pores('blah', origin=net)
[a, b, c]
```

Where a, b and c are the pore indices relative to the `phys` indices?

**Comment by ma-sadeghi** [comment]
> Are you suggesting that 'blah' is a network label? So:
> 
> ```python
> >>> net.set_label(pores=[1, 2, 3], label='blah')
> >>> net.pores('blah')
> [1, 2, 3]
> >>> phys.pores('blah')
> raise KeyError 'blah' not found
> >>> phys.pores('blah', origin=net)
> [a, b, c]
> ```
> 
> Where a, b and c are the pore indices relative to the `phys` indices?

Yes, exactly. I think it's really convenient for multi-domain geometries.

**Comment by jgostick** [comment]
Hmmm, now that I"ve looked at it a bit, the functionality is **exactly** what ``map_pores`` is for.  I am thinking if is just too much feature creep to add this feature to ``pores``.  It would literally call ``map_pores`` behind the scenes.
