### ISSUE TITLE
Allow pore-scale models to optionally accept numeric values in addition to strings

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1364]
The idea is to allow pore-scale models to (optionally) directly accept numeric values in addition to strings as dictionary keys. This has some non-trivial benefits; for instance, some pore-scale models have arguments that are constant, in the sense that they don't change from pore to pore. This could be the

- the number of electrons transferred in redox reactions (z)
- exchange current density of redox reactions (j0)
- transfer coefficient of redox reactions (alpha)
- reference concentration in rate equations
- stochiometric coefficients in rate equations
- coefficients of almost every correlation for physical properties
- etc.

From what I understand, we already sort of allow this pattern and use it ourselves, for instance in the pore-scale model for calculating vapor pressure (Antoine's equation) and in a few other places. What I'm proposing, however, is that to do this in a unified way such that the user no longer has to worry about whether or not a string should be passed as an argument, plus it's more convenient for rapid prototyping.

**Comment by ma-sadeghi** [comment]
@jgostick what do you think?

**Comment by jgostick** [comment]
There is nothing stopping the use of numerical values, and it's fine when you're talking about scalar values like Antoines.  We just want to avoid send numpy arrays of Np and Nt length.

I mean, who ever writes the model gets to choose which data to accept.  Generally, pore and throat data (which can vary by location) should be a dict, and everything else should be a scalar or numerical value. I' not sure I see the problem.

**Comment by ma-sadeghi** [comment]
Issue #1363 is relevant

**Comment by jgostick** [comment]
I'm going to close this because we basically already support this.  The user can create their own function that accepts arrays.  We don't do it since we don't want to store numpy arrays in the saved files, and it prevents regeneration of models.
