### ISSUE TITLE
Problems at the moment to import OPENPNM

### ISSUE THREAD

**Issue by angelswat** [PMEAL/OpenPNM#1365]
Hi!
Please @TomTranter @jgostick I need your help today with this problem. I want to import openpnm but I get this error with the variable name that it isnt declared. 

`NameError: name 'μSymbol' is not defined

During handling of the above exception, another exception occurred:

UnitParseError                            Traceback (most recent call last)
<ipython-input-16-68a79d9b7e68> in <module>
      1 from PIL import Image
      2 import numpy as np
----> 3 import porespy as ps
      4 
      5 im = Image.open('image.tif')

C:\ProgramData\Anaconda3\lib\site-packages\porespy\__init__.py in <module>
     85 from . import filters
     86 from . import metrics
---> 87 from . import networks
     88 from . import generators
     89 from . import visualization

C:\ProgramData\Anaconda3\lib\site-packages\porespy\networks\__init__.py in <module>
     32 """
     33 
---> 34 from .__funcs__ import add_boundary_regions
     35 from .__funcs__ import map_to_regions
     36 from .__funcs__ import generate_voxel_image

C:\ProgramData\Anaconda3\lib\site-packages\porespy\networks\__funcs__.py in <module>
      1 import scipy as sp
      2 import numpy as np
----> 3 import openpnm as op
      4 from porespy.tools import make_contiguous
      5 from skimage.segmentation import find_boundaries

C:\ProgramData\Anaconda3\lib\site-packages\openpnm\__init__.py in <module>
     57 from . import utils
     58 from .utils import Workspace, Project
---> 59 from . import core
     60 from . import models
     61 from . import network

C:\ProgramData\Anaconda3\lib\site-packages\openpnm\core\__init__.py in <module>
    104 
    105 from .ModelsMixin import ModelsMixin, ModelsDict
--> 106 from .Base import Base
    107 from .Subdomain import Subdomain

C:\ProgramData\Anaconda3\lib\site-packages\openpnm\core\Base.py in <module>
----> 1 import unyt
      2 from flatdict import FlatDict
      3 from collections import namedtuple
      4 import matplotlib.pyplot as plt
      5 from openpnm.utils import Workspace, logging

C:\ProgramData\Anaconda3\lib\site-packages\unyt\__init__.py in <module>
     69 from ._version import get_versions
     70 
---> 71 from unyt import unit_symbols
     72 from unyt import physical_constants
     73 

C:\ProgramData\Anaconda3\lib\site-packages\unyt\unit_symbols.py in <module>
     31 for _canonical_name, _alt_names in _name_alternatives.items():
     32     for _alt_name in _alt_names:
---> 33         _namespace[_alt_name] = _Unit(_canonical_name, registry=_registry)

C:\ProgramData\Anaconda3\lib\site-packages\unyt\unit_object.py in __new__(cls, unit_expr, base_value, base_offset, dimensions, registry, latex_repr)
    171                 return registry._unit_object_cache[unit_expr]
    172             unit_cache_key = unit_expr
--> 173             unit_expr = parse_unyt_expr(unit_expr)
    174         # Simplest case. If user passes a Unit object, just use the expr.
    175         elif isinstance(unit_expr, Unit):

C:\ProgramData\Anaconda3\lib\site-packages\unyt\_parsing.py in parse_unyt_expr(unit_expr)
     94             repr(e),
     95         )
---> 96         raise UnitParseError(msg)
     97     return unit_expr

UnitParseError: Unit expression 'µm' raised an error during parsing:
NameError("name 'μSymbol' is not defined",)`

**Comment by jgostick** [comment]
try ``pip install --upgrade unyt``

**Comment by jgostick** [comment]
Hi @angelswat, Did this work for you?

**Comment by jgostick** [comment]
This usually happens if you upgrade some packages in your environment, but not all of them.  It's happened to me a few times too.  It's not easy to prevent though, because we don't want to 'force' package versions since this creates dependency conflicts.  Anyway, I'll close this now.
