### ISSUE TITLE
Errors/typos in tutorials?

### ISSUE THREAD

**Issue by fablion** [PMEAL/OpenPNM#1368]
Hi,

I think there are several errors in [tutorials](https://github.com/PMEAL/OpenPNM/blob/master/examples/tutorials/02 - Intro to OpenPNM - Intermediate.ipynb):

> The remaining arguments are those required by the chosen model. In the above cases, these are the parameters that define the statistical distribution. Note that the mean pore size for geom1 will be **20** um (set by **scale**) while for geom2 it will be **50** um, thus creating the smaller surface pores as intended. The pore-scale models are well documented regarding what arguments are required and their meaning; as usual these can be viewed with Object Inspector in Spyder.

- Is mean pore size [controlled ](https://openpnm.readthedocs.io/en/master/modules/models/geometry.html#module-openpnm.models.geometry.pore_size) by loc and not scale?

> scale (float) – The standard deviation of the Normal distribution
loc (float) – The mean of the Normal distribution

- in the code, 50 µm is written for both:

```
geom1.add_model(propname='pore.diameter',
                model=op.models.geometry.pore_size.normal,
                scale=0.00001, loc=0.00005,
                seeds='pore.seed')
geom2.add_model(propname='pore.diameter',
                model=op.models.geometry.pore_size.weibull,
                shape=1.2, scale=0.00001, loc=0.00005,
                seeds='pore.seed')`
```

There is also a error in the [docs](https://openpnm.readthedocs.io/en/master/modules/models/geometry.html#module-openpnm.models.geometry.pore_size) :
> openpnm.models.geometry.pore_size.**normal**(target, scale, loc, seeds='pore.seed')[source]
> Produces values from a **Weibull** distribution given a set of random numbers.

I will use this topic again, if I found other errors (or what seems to be errors for me as a new user of openPNM)

**Comment by fablion** [comment]
in this [tutorial ](https://github.com/PMEAL/OpenPNM/blob/master/examples/tutorials/01 - Intro to OpenPNM - Basics.ipynb), the last Paraview image show pore_air_pressure. But this tutorial present only 1 phase ("water"). So is it an error or did I miss something?

**Comment by jgostick** [comment]
@fablion , thanks for point these out. They do indeed seem like typos.  It's been quite a while since we wrote those tutorials, and we 'translated' them from V1 to V2, so I guess somethings got messed up.  

Please keep posting typos/errors that you find in this thread, thanks!

**Comment by fablion** [comment]
In basic tutorial, there is 4 x 3 x 1 pore network.
The following code is proposed :
```
Q = alg.rate(pores=pn.pores('front'))
A = 0.0001*3*1  # Cross-sectional area for flow
L = 0.0001*4  # Length of flow path
del_P = 101325  # Specified pressure gradient
K = Q*mu_w*L/(A*del_P)
print(K)
```

As the front has 3 pores connected by 2 throats,, if I understand well, A should be 0.0001*3*1.
And L should be 0.0001*3 (3 throats) isn't it?

**Comment by jgostick** [comment]
The tutorials have been massively revamped and all turned into notebooks, so I think this is safe to close.
