### ISSUE TITLE
A matrix doesn't get rebuilt even when some properties are set as iterative_prop

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1392]
The issue is that even if you set some of the properties such as viscosity, etc. as `iterative_prop`, although these properties get updated during the call to `alg.run`, but if `self._pure_A` is not `None`, which happens, for instance, when you want to rerun the algorithm in a parametric study, `self._build_A` gets bypassed and `self._pure_A` which has been cached will be returned. Long story short, if properties that are input to the conductance pore-scale model are iterative, `A` will not be recalculated although it should.

Here's what I propose:

Store conductance values **also**  on the algorithm object, then during the call to `_build_A`, force a rebuild if a change in g-values is found.
```
    def _build_A(self):
        r"""
        Builds the coefficient matrix based on conductances between pores.
        The conductance to use is specified in the algorithm's ``settings``
        under ``conductance``.  In subclasses (e.g. ``FickianDiffusion``)
        this is set by default, though it can be overwritten.
        """
        cache_A = self.settings['cache_A']
        if not cache_A:
            self._pure_A = None
        g = phase[self.settings['conductance']]
        if self._g:
            if not sp.allclose(self._g, g, rtol=1e-10, atol=0):
                self._pure_A = None
                self._g = g.copy()
        if self._pure_A is None:
            network = self.project.network
            phase = self.project.phases()[self.settings['phase']]
            am = network.create_adjacency_matrix(weights=g, fmt='coo')
            self._pure_A = spgr.laplacian(am).astype(float)
        self.A = self._pure_A.copy()
```
In fact, if we do so, there's no need to have `cache_A` flag, and `_build_A` will then become:
```
    def _build_A(self):
        r"""
        Builds the coefficient matrix based on conductances between pores.
        The conductance to use is specified in the algorithm's ``settings``
        under ``conductance``.  In subclasses (e.g. ``FickianDiffusion``)
        this is set by default, though it can be overwritten.
        """
        g = phase[self.settings['conductance']]
        if self._g:
            if not sp.allclose(self._g, g, rtol=1e-10, atol=0):
                self._pure_A = None
                self._g = g.copy()
        if self._pure_A is None:
            network = self.project.network
            phase = self.project.phases()[self.settings['phase']]
            am = network.create_adjacency_matrix(weights=g, fmt='coo')
            self._pure_A = spgr.laplacian(am).astype(float)
        self.A = self._pure_A.copy()
```

**Comment by jgostick** [comment]
based on the above code snippet, I cannot see where the conductance values are stored on the alg object.

**Comment by ma-sadeghi** [comment]
> based on the above code snippet, I cannot see where the conductance values are stored on the alg object.

Updated.

**Comment by ma-sadeghi** [comment]
This could be related to issue #1393, if we go w/ automatic dependency handling, then there's no need to even store conductance values on algorithms for comparison. If conductance is inferred as an iterative property by the algorithm, then it always recreates `_pure_A`.

**Comment by jgostick** [comment]
Ok, let's can this then, and focus on proper treatment of iterative properties.
