### ISSUE TITLE
Should we add conduit_*** models?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1418]
We currently only have pore_** and throat_** categories, but I'm thinking it might make sense to include a conduit category, like conduit_area, length, etc.  These would return an Nt-by-3 array with pore-throat-pore info.  We have some conduit model distributed through the models library, so we could consider relocating them.

**Comment by ma-sadeghi** [comment]
I strongly agree. This would make dictionaries more predictable, plus it solves some of the problems we currently have, for instance, the multiphase diffusion model requires individual pore conductance values (i.e. g1, gt, and g2). Currently, we recalculate those properties inside the model, whereas if we adopt this approach, those properties will be stored under `"conduit.diffusive_conductance"`.

**Comment by jgostick** [comment]
Actually, I was thinking of adding conduit models as a categorization in models library, but I also agree that allowing conduit.property in the dicts would be handy.  I have actually added that idea to the openpnm V3 project, where I'm collecting a list of breaking changes.

**Comment by jgostick** [comment]
I just came across another use case for allowing conduit as a keyword.  Consider a throat viscosity model for a powerlaw fluid.  It returns a viscosity for each element of the conduit, pore1-throat-pore2.  Now consider using viscosity in a standard conductance model.  The models needs to know whether a standard viscosity or a 'conduit' viscosity is provided.  'conduit.viscosity' would indicate that values are provides in a different format than 'pore.viscosity'.

**Comment by jgostick** [comment]
In PR #1604 we have add size_factor models.  These return an Nt-by-3 array so effectively return conduit models, but did not include the name conduit in the file for conciseness.
