### ISSUE TITLE
Flow and poisson shape factors should be geometry models

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1420]
It would be better if we could attach these to a geometry object and their values used by the physics objects just like other geometry properties.  This way they could be added to the 'imported' geometry class.

**Comment by jgostick** [comment]
Also, flow shape factor should be 'stokes' shape factor maybe?  This would be analogous to poisson shape factor.  Alternatively poisson could be called diffusion_shape_factor (with a convenience wrapper called conduction_shape_factor).

**Comment by jgostick** [comment]
We should also have 'capillary_shape_factors' as a file.  At the moment the 'throat_shape_factors' file only has capillary shape factors in it.

**Comment by jgostick** [comment]
This would also help with network extraction, since it could calculate shape factors directly for each type of transport and return as geometrical properties.

**Comment by xu-kai-xu** [comment]
@jgostick  hi, jeff. I have made a discussion in issue #1421 about **flow shape factor**. I really want to know how to calculate flow shape factor and the mechanism why you calculate it this way. Only by the docstrings I can not figure it out. May you supply me with some refs about the definition of **flow_shape_factor**?? Thanks.

**Comment by xu-kai-xu** [comment]
@jgostick  hi, jeff. I have made a discussion in issue #1421 about **flow shape factor**. I really want to know how to calculate flow shape factor and the mechanism why you calculate it this way. Only by the docstrings I can not figure it out. May you supply me with some refs about the definition of **flow_shape_factor**?? Thanks.

**Comment by ma-sadeghi** [comment]
@xu-kai-xu You can find the reference at the bottom of the docstrings under `openpnm.models.physics.flow_shape_factors` under `Notes` section:
```
    References
    ----------
    Akbari, M., Sinton, D., & Bahrami, M. (2011). Viscous flow in variable
    cross-section microchannels of arbitrary shapes. International Journal of
    Heat and Mass Transfer, 54(17-18), 3970-3978.
```

**Comment by jgostick** [comment]
After a LOT of thought and discussion we decided to forge ahead with this in PR #1604.  It looks to be a major improvement in the way openpnm delegates tasks between objects.
