### ISSUE TITLE
flow_shape_factor models yield nans when L / D > 0.5

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1421]
[The problem is on this line](https://github.com/PMEAL/OpenPNM/blob/b3873d35270b0acaad019264368d0055c677d159/openpnm/models/physics/flow_shape_factors.py#L99)

The arctan term goes to inf when the argument == 1 and nan when arg > 1, so when L / D > 0.5 it's then multiplied by 2, and creates an undefined result.  This is putting nans in the hydraulic conductance array.

**Comment by ma-sadeghi** [comment]
@jgostick I understand that you're referring to ball_and_stick flow shape factor model. In that case, L/D must always fall below 0.5, right? (assuming that pores are spherical)

**Comment by ma-sadeghi** [comment]
But still, I think we should have a more generic shape factor. In fact, the paper from which I implemented the flow shape factor models doesn't assume a particular cross-section shape. So, I think it might be worth it to go back and see if we can make the shape factor model generic. If I remember correctly, the key term in the paper was some special area integral. This can be linked to issue #1418, ideally, if we have conduit properties, then we can add that special integral as a conduit model, which can later be used by shape factor models.

**Comment by xu-kai-xu** [comment]
@ma-sadeghi , hi, I am reading the source code about **shape factors**. And I found three types of shape factor:

> * throat_shape_factor, which belongs to openpnm\models\geometry;
> * flow_shape_factor, which belongs to openpnm\models\physics;
> *  poisson_shape_factor, which belongs to openpnm\models\physics;

You mentioned the paper from which you implemented the flow shape factor, so I wish you could share the paper information (if also for poission shape factor, it will be better). Then I can figure out the mechanism of this concept. 

According to the categories, I guess that **throat shape factor** is a variable related to throat geometry, which I can figure out with the references you supplied. But the other two are related to specific physical processes (flow and heat transfer).
Thanks!

**Comment by ma-sadeghi** [comment]
@xu-kai-xu Honestly, I don't even know what `throat_shape_factor` is. You can find the reference to the article in the docstrings of the shape factor models.

**Comment by xu-kai-xu** [comment]
I read the articles about **throat_shape_factors**, and figured out how it is calculated.
But I can't understand how the **flow shape factor** is calculated. May you offer some references for me? Thanks.

**Comment by ma-sadeghi** [comment]
@xu-kai-xu Can you send a link to the article that you're referring to?

**Comment by xu-kai-xu** [comment]
@ma-sadeghi I referred to the article mentioned in the docstrings of **throat_shape_factors.py** file.
The links are:
1. [Reexamination of Hagen-Poiseuille
    flow: Shape dependence of the hydraulic resistance in microchannels](https://pubmed.ncbi.nlm.nih.gov/16089701/)

2. [Capillary behavior of a perfectly wetting
    liquid in irregular triangular tubes](https://www.sciencedirect.com/science/article/abs/pii/002197979190321X)

3. [The effect of elliptical pores on
    mercury porosimetry results](https://www.sciencedirect.com/science/article/abs/pii/0032591084800479)

Again, I really want to know which paper you referred to for the implementation of **flow shape factor**. You mentioned a paper from which you implemented the flow shape factor models.  May you send me links to this paper? Thanks.

> But still, I think we should have a more generic shape factor. In fact, the paper from which I implemented the flow shape factor models doesn't assume a particular cross-section shape. So, I think it might be worth it to go back and see if we can make the shape factor model generic. If I remember correctly, the key term in the paper was some special area integral. This can be linked to issue #1418, ideally, if we have conduit properties, then we can add that special integral as a conduit model, which can later be used by shape factor models.

**Comment by ma-sadeghi** [comment]
@xu-kai-xu The reference I was referring to is listed under `openpnm.models.physics.flow_shape_factors`:
```
    References
    ----------
    Akbari, M., Sinton, D., & Bahrami, M. (2011). Viscous flow in variable
    cross-section microchannels of arbitrary shapes. International Journal of
    Heat and Mass Transfer, 54(17-18), 3970-3978.
```

**Comment by Ni2M** [comment]
In general in cases where L/D>0.5 the pore shapes can be categorized as an ellipse instead of sphere. But we are assuming sphere and the equations for resistance (conductance) are developed assuming a spherical shape for pore (that's where tan(alpha)=(d/2)/L  appears because of the spherical assumption). Basically, we used the relation of diameter and length in calculation of the integral part for the frictional resistance based on spherical pore shapes. If we change the assumption of sphere and use the ellipse equation to find the resistance, it interferes with the geometry assumptions of pore.diameter in the extracted pore network or the assigned geometry. If we change the geometry to an ellipse to be consistent with resistance assumption, we need more information such as minor and major axis of ellipse.

I read the reference paper. The paper covers both frictional and inertial resistance in the overall resistance of a conduit with varying cross section. In our code we assumed inertial term can be negligible, which I think it's still valid (low Reynolds number, periodic profile). So to change the model for (L/D)>0.5 I'm thinking of using the general formulation of resistance for varying cross section conduit (for the pore parts). I'm working with the formulation for this flow shape factor. The resulting resistance would be for cases where the geometry shape is assumed to be sphere (stick and ball geometry), but the resistance is not based on spherical assumption

**Comment by Ni2M** [comment]
The geometry "throat_endpoints" formulations which are used for pore and throat length in the conduit suggests that having a pore length>0.5*pore diameter is not valid for spherical pores. e.g. Their corresponding throat diameter will be zero if L1=D1/2 and it will not have a physical value (interferes with basic assumptions to find endpoints and length of conduit elements) if L1>D1/2.

**Comment by Ni2M** [comment]
This is a schematic of the problem and geometrical assumptions that can lead to this problem. With the information of the existing geometry (pore.diameter and throat.diameter) the third model in this schematic can be used instead of stick and ball:
![image](https://user-images.githubusercontent.com/43128873/86625501-24fed680-bf93-11ea-8676-8974d0d76ec4.png)

**Comment by xu-kai-xu** [comment]
@Ni2M  Thanks for your answers!

**Comment by Ni2M** [comment]
@xu-kai-xu No problem. I am currently working on implementing the general formulations and other possible solutions described above. I will give more updates later about this issue.

**Comment by Ni2M** [comment]
![image](https://user-images.githubusercontent.com/43128873/87793036-b2072280-c812-11ea-9feb-b5156d6e561a.png)

**Comment by Ni2M** [comment]
We will use the proposed method in #1570

**Comment by xu-kai-xu** [comment]
@Ni2M, thanks. I see the derivation process. I have two questions. The first is that the equation: $$  g\*SF = g*L / (A\*F) $$

It seems not the same as the code, which is $$ g\*SF = g*L / (A^2 \*F) $$.

The second is that the concept **flow shape factor** has no dimension. But it seems different to the definition of $$SF = A / P^2$$, in which A is the area of the cross-section, P is the perimeter of the cross-section. What confuses me is that What is the physical meaning of flow shape factor for the first definition. For the second definition, I can understand it easily.

**Comment by Ni2M** [comment]
@xu-kai-xu Thank you for your comment. You are right. I apologize the right equation is  $$ g*SF = g*L / (A^2 *F) $$. It was my bad in writing the equations. Just to give you a side update we are not using this new derived F factor, as it still provides problems. We are working on other ideas that are mentioned in related issues.

The idea we defined shape factor here is adopted from the reference paper. It is basically a correction to the conductance of pores/throats/conduits. The paper provides resistance correction on resistance of slowly-varying cross sections in conduits. In OpenPNM we have the conductance (equivalent to inverse of resistance). Comparing the resulting resistance with the resistance of a cylindrical tube provides the correction factor (shape factor). That is basically the deviation in resistance from resistance of a perfect ideal condition of flow in a simple cylinder with constant cross section. It accounts for the shapes and varying cross sections of the conduit in the integral form that is included in the formulation. 
A/P^2 has the assumption of a constant cross sectional shape for the pore/throat (which is not the case for a slowly varying cross section. In a slowly varying cross section in a pore/throat the reference paper provides a solution to account for the deviation of the resistance value (account for the shape factor correction).
