### ISSUE TITLE
It is not obvious that flow vs poisson shape factors are analogous

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1423]
Maybe ``flow_shape_factor`` should be ``stokes_shape_factor``? This would be analogous to ``poisson_shape_factor``. 

Alternatively poisson could be called ``diffusion_shape_factor`` (with a convenience wrapper called ``conduction_shape_factor``).

**Comment by ma-sadeghi** [comment]
Maybe we should go with both changes that you suggested! After all, our `flow_shape_factor` only works for Stokes flow. Also, having wrappers such as `diffusion_shape_factor` make things more clear.

**Comment by jgostick** [comment]
In PR #1604 we have reworked the whole conduit conductance thing, and this issue is gone.  We use the terms diffusive and hydraulic size_factors.  They analogy is obvious and the use of poisson is gone, which was not super clear.
