### ISSUE TITLE
CubicTemplate immensely slow because of find_surface_pores

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1427]
Create a trimmed network using CubicTemplate class is ~100X slower than creating it by trimming a Cubic network, and it's almost entirely coming from the call to `find_surface_pores`.

I think we either need to massively optimize `find_surface_pores` method, or should get rid of it in `CubicTemplate` class as calling it on a relatively large template makes it virtually unresponsive.

PS. `CubicTemplate` on 50^3 image is ~4 seconds vs. ~0.03 seconds using `Cubic`

**Comment by jgostick** [comment]
I think it uses the delauny tessellation class in scipy. We could probably drop it...or cull many points from the interior before running it.

**Comment by jgostick** [comment]
Let's break this class and remove lines 80+, let's keep labels from cubic, and let's add 'internal_surface' label for pores that have < 6 neighbors and are not a 'real' surface pore.

**Comment by ma-sadeghi** [comment]
This is fixed in PR #1447.
