### ISSUE TITLE
Maybe a more convenient way of getting global indices of subdomain objects

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1437]
Maybe we've talked about it in the past. I think getting global indices of subdomain objects should be more convenient than doing:
```
network.map_pores(geom_A.Ps, origin=geom_A)
```

**Comment by jgostick** [comment]
suggestions?   BTW, you can also do:

```
pn.pores('left', target=geom_A)
```
Which will fetch all 'left' pore from ``pn``, then return their corresponding index on ``geom_A``

**Comment by jgostick** [comment]
FYI, you can also do this:

``` python
geo.set_label('test', pores=[0, 1, 2])
geo.pores('test', target=pn)
```

Which is more verbose than the map_pores function.

**Comment by ma-sadeghi** [comment]
> suggestions? BTW, you can also do:
> 
> ```
> pn.pores('left', target=geom_A)
> ```
> 
> Which will fetch all 'left' pore from `pn`, then return their corresponding index on `geom_A`

Actually, I wasn't aware of this. This makes a lot more sense to me. So, basically, for getting the global indices, we simply need to do:
```python
obj.pores(label, target=network)
```
Then I guess all is good.

**Comment by jgostick** [comment]
Yes, but the only problem is that you must have labelled the pores on ``obj``.  We could enhance the ``pores`` method to accept an array as well as string.  If string -> look up pores, if array -> just use them directly.  Would be about 3 lines to add.  

The only down side is that accepting such a wide variety of arguments starts to make the methods unpredictable and complex.  For instance, we used to accept objects handles AND names in many functions, but decided to go with handles everywhere for consistency.  

I'd be willing to make an exception this time though.

**Comment by jgostick** [comment]
BTW, the ``target`` argument was added to ``pores`` and ``throats`` very recently, like in fall 2019ish.

**Comment by ma-sadeghi** [comment]
I see, it's just that `obj.pores([1,3], target=network)` to me seems more readable and self-descriptive than `network.map_pores([1, 3], origin=obj)`, though it might as well just be my preference. 

But, I see your point about consistency.
