### ISSUE TITLE
find pores and throats in heterogeous stitched network 

### ISSUE THREAD

**Issue by siz23** [PMEAL/OpenPNM#1440]
Hi @jgostick ,

I would appreciate if you could help on issue on stitched network. My network is form by 2 cubic networks stitched together, one having large spacing and the other small spacing (these two parts also need to have different geometry settings). I would like to a column pores of small spacing network to have different geometry properties, so need to find the pores and neighbor throats. This step, however, gives me trouble because there is always either '"overlap" or "missing" of pores/throats in different region.

For example, I want to choose left and top pores and their connecting throats of the small-spacing part as the channel region, so define it as below:

Ps1=cathode_net.pores(['small','left','top'],mode='intersection')
Ts1=cathode_net.find_neighbor_throats(pores=Ps1,mode='xnor')
geom_channel=op.geometry.GenericGeometry(network=cathode_net, pores=Ps1, throats=Ts1)

After this, I have trouble for the rest part of the whole network, because either some pores/throats will not be included or be counted twice, which is not allowed. For example,

Ps = cathode_net.pores(['large','top'],mode='not')
Ts = cathode_net.find_neighbor_throats(pores=Ps,mode='union')
geom_sm_cathode = op.geometry.GenericGeometry(network=cathode_net, pores=Ps, throats=Ts)
Ps = cathode_net.pores('large')
#Ts = cathode_net.throats('small', mode='not')
Ts = cathode_net.throats('large')
geom_lg_cathode_1 = op.geometry.GenericGeometry(network=cathode_net, pores=Ps, throats=Ts)

If I use "Ts = cathode_net.throats('small', mode='not')", the stitching throats will be counted twice; if I use "Ts = cathode_net.throats('large')", the stitching throats between large part and small+top part will be missed.

I have tried so many ways to figure this out but not yet make it. Would you please offer some help on this? For your information, I have attached my script here.

Thanks so much for your consideration and help!

Best,

[channel_part.txt](https://github.com/PMEAL/OpenPNM/files/4331249/channel_part.txt)

**Comment by jgostick** [comment]
I have run parts of your code and found that the stitching seems to be working as it should.  I'm not quite what your exact issues is.  Could you reply with more specific information, and perhaps a small test case that illustrates the issue?

**Comment by siz23** [comment]
Hi @jgostick ,

Thanks so much for replying. The issue is that to use the network to simulate what I am interested in, such as diffusion problem, I need to define specific geometries for all pores and throats, and each pore/throat can be only assigned once. My problem is that there are always some pores and/or throats missed or assigned twice. If some pores/throats are missing, the simulation will have singularity problem (this shows in my computer as an warning "/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:193: MatrixRankWarning: Matrix is exactly singular warn"Matrix is exactly singular", MatrixRankWarning" and give me nonsense result). If some pores/throats are assigned twice, it will tell me that "Given indices are already assigned to geo_02" or something like it. Thus, I need a way to assign geometry to every pore/throat without any missing or overlapping.

The example I have uploaded is an example of missing. In that part, I defined the "channel" part as the top pores and throats in small network. In current setting, some stitching throats are missing (the stitching throats connecting large top back pores and small top front pores). When this setting is submitted to my diffusion part, singularity problem happened. If line 65 is used instead of line 66, i.e.  use "Ts = cathode_net.throats('small', mode='not')", most of the stitching throats are assigned twice so it shows "Given indices are already assigned to geo_02". I attached this file again here.
[channel_part.txt](https://github.com/PMEAL/OpenPNM/files/4344277/channel_part.txt)

Thanks so much for your help and effort on this!

Best

**Comment by jgostick** [comment]
I totally forgot about this.  Did you find an answer?

**Comment by siz23** [comment]
Hi @jgostick ,

Sorry for not updating. I did find an alternative way, which is just to enumerate IDs of all pores and throats then find the pore IDs and throat IDs for "channel". Fortunately there were only 10 pores and 9 throats in this case so it is doable. 

I have no idea if there can be a more "smart" way to do it, since it would be very hard if the number of IDs of pores and throats is much larger. I have been still trying but nothing come up yet.

Please let me know if you could find something. Many thanks!

Best

**Comment by jgostick** [comment]
I have a lot on my plate at the moment (teaching online this winter and this summer) so I will close this issues and deal with it if it pops up again.  I'm sorry to leave you hanging.
