### ISSUE TITLE
Add example for effective permeability/diffusivity using extracted networks as integration testing

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1466]

**Comment by jgostick** [comment]
@ma-sadeghi and @Zohaib-Atiq can you work together to get this added to the examples asap?  I will merge the hotfix and push since the examples are not part of the pypi package, but I don't want this to happen again, so let's get the example pushed before we make anymore changes to the code.

**Comment by ma-sadeghi** [comment]
@jgostick : @Zohaib-Atiq already sent me some `pnm` files from extracted networks, which I'll push to dev soon.

**Comment by jgostick** [comment]
I merged the hotfix and pushed to pypi already. The "test" is only needed to ensure we don't break this again in the future, so we'll just merge it into dev and it'll be part of the next release.

**Comment by jgostick** [comment]
@ma-sadeghi if this is done, can you close it?

**Comment by ma-sadeghi** [comment]
This is addressed in PR #1511
