### ISSUE TITLE
Run check_network_health as part of _sanity_check

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1469]
While creating an example for permeability benchmark, I just realized that extracted networks could have disconnected pores, which leads to solver divergence, leaving the user clueless of the cause. I think it's essential that we check for network health prior to running the algorithm. This could be part of the recently added `_sanity_check` method.

**Comment by jgostick** [comment]
network health is a bit of an expensive check to do if the network is large.  It calls the clustering method in scipy.sparse.csgraph.  Maybe this is the time to re-visit @magnaou's quick-union algorithm again?

**Comment by jgostick** [comment]
I wonder if there is an easier way to see if the A matrix is complete?  the clustering algorithm is slow because it actually clusters the nodes.  If you just want to ensure the equations are coupled there might be a simple and fast solution?

**Comment by ma-sadeghi** [comment]
@jgostick I did some profiling and it turned out that the clustering algorithm is actually pretty quick. It's the call to `num_neighbors` which is the bottle neck. 

So, I propose  adding a private helper method to `GenericTransport` called `_is_connected` which basically calls the clustering algorithm and see if more than 1 cluster is found. What do you think?

**Comment by jgostick** [comment]
Ok, so just add the clustering check to the ``sanity_check`` method, and if there is an problem, raise and Exception telling the user to run check_network_health and fix things up.
