### ISSUE TITLE
GenericTransport solver at least gets called twice even for direct methods

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1473]
This is a known issue. The problem is that `_is_converged` method does more than what it's supposed to do, which is to tell if the solution has converged, rather it throws an `Exception` if the residual is `inf` or `nan`. Because of this, we had to enforce at least 2 iterations before `_is_converged` is called:
```python
            # Check solution convergence
            res = self._get_residual()
            if itr >= 1 and self._is_converged():
                logger.info(f'Solution converged: {res:.4e}')
                return x
```
This was to keep the main for loop as concise as possible. In hindsight, it was a bad idea, as for large matrices, the saved time is huge. The solution is refactor `_is_converged` from:
```python
    def _is_converged(self):
        r"""
        Check if solution has converged based on the following criterion:
            res <= max(norm(b) * tol, atol)
        """
        res = self._get_residual()
        # Verify that residual is finite (i.e. not inf/nan)
        if not np.isfinite(res):
            logger.error(f'Solution diverged: {res:.4e}')
            raise Exception(f"Solution diverged, undefined residual: {res:.4e}")
        # Check convergence
        tol = self.settings["solver_tol"]
        res_tol = norm(self.b) * tol
        flag_converged = True if res <= res_tol else False
        return flag_converged
```
to:
```python
    def _is_converged(self):
        r"""
        Check if solution has converged based on the following criterion:
            res <= max(norm(b) * tol, atol)
        """
        res = self._get_residual()
        # Check convergence
        tol = self.settings["solver_tol"]
        res_tol = norm(self.b) * tol
        flag_converged = True if res <= res_tol else False
        return flag_converged
```
and put back this part:
```python
        # Verify that residual is finite (i.e. not inf/nan)
        if not np.isfinite(res):
            logger.error(f'Solution diverged: {res:.4e}')
            raise Exception(f"Solution diverged, undefined residual: {res:.4e}")
```
back to the main for loop inside `_run_transient` and `_run_reactive` (and wherever needed).

**Comment by jgostick** [comment]
seems like a no-brainer to me, go for it

**Comment by ma-sadeghi** [comment]
It seems that this issue has already been addressed in previous PRs, although using a different solution.

Currently, we "manually" call `_update_A_and_b` before the main loop, so that `_is_converged` can be safely called (safely as in: if x0 is undefined for some reason, residual will be undefined as well). Consequently, we safely got rid of the `if itr >= 1` check.
