### ISSUE TITLE
End points does not change with contact angle

### ISSUE THREAD

**Issue by saeidabd** [PMEAL/OpenPNM#1474]
OpenPNM Team,
I use MixedInvasionPercolation and apply_trapping() to find the irreducible water saturation in network. I repeat this process with some different contact angles to see how end points varies, but end points keep unchanged. Is this correct? in real cases we know end points changed. Am I wrong in any part of coding?
I attach algorithm part of code and figure I explain it. (in this case end point for both contact angle (60 and 30 degree) are 0.27)
```
#%% drainage: oil invade water
IP_withdrawal = op.algorithms.MixedInvasionPercolation(network=pn)
IP_withdrawal.setup(phase=oil30)
IP_withdrawal.set_inlets(pores=pn.pores('left'))
IP_withdrawal.run()
IP_withdrawal.set_outlets(pores=pn.pores(['right']))
IP_withdrawal.apply_trapping()
injection_data = IP_withdrawal.get_intrusion_data()
```
![Figure_2](https://user-images.githubusercontent.com/49044459/80370839-24b4d180-88a6-11ea-9470-aeaad41ff10c.png)

**Comment by jgostick** [comment]
I'm not totally sure that it should change.  The main effect of changing the contact angle is to shift the capillary pressure curve, but it's not a given that the order of filling will change.  If you vary the contact angle randomly, then I would expect a change, but if you just change it uniformly from 130 to 110 then not much would happen.  That being said, it depends on the capillary model you're using.  We have been working on a paper where the bulging/inflating of menisci causes early invasion into pores via touching the backs of pores and touching other menisci.

**Comment by saeidabd** [comment]
I did it and this is result and is interesting for me but I really don't know it is useful for my case or not.
![randomly](https://user-images.githubusercontent.com/49044459/80412324-f43f5880-88e2-11ea-8cd3-dc8ad6079df8.png)

**Comment by jgostick** [comment]
What am I looking at here?  Is this the result of putting 30 and 60 everywhere?  Have you tried put a random contact angle in different locations to see if that changes the invasion order?

**Comment by saeidabd** [comment]
> What am I looking at here? Is this the result of putting 30 and 60 everywhere? Have you tried put a random contact angle in different locations to see if that changes the invasion order?

yes, there is random contact angle distribution for 30 (I mean between 25 to 35) and 60 (55 to 65) for pores.

**Comment by jgostick** [comment]
Maybe try a varying the randomness a bit wider.  And can you also confirm that that invasion pattern is changing or not?  Like actually look into the 'pore.invasion_sequence' for Pore X in the two scenarios and see if it changes.

**Comment by saeidabd** [comment]
I checked it and found out the invasion pattern changed in these two scenarios (and cluster in pore and throats).
