### ISSUE TITLE
Default data type of integer arrays: int32 vs int64

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1476]
Currently, we're forcing `int64` as the default `dtype` of `int` arrays. Apart from `umfpack` not liking `int32` for large-enough matrices, is there a reason we do this? 

PS. the `umfpack` issue is contained in `GenericTransport._solve`.

**Comment by jgostick** [comment]
At one point Ubuntu and windows were using different dtypes, so the test were failing on one platform or the other.  We decided to explicitly force int64 because bigger is better!  Other than that, I don't think there is a reason.

**Comment by ma-sadeghi** [comment]
I think I remember the testing issue.

However, from the standpoint of data storage, I doubt that we'll hit the 2^32 anytime soon (~4.3e9). That being said, most our models store `float64` and very few use `int`, so I guess using `int64` doesn't really affect us memory-wise. So, I'm closing this issue.
