### ISSUE TITLE
Is something wrong in set_residual function?

### ISSUE THREAD

**Issue by saeidabd** [PMEAL/OpenPNM#1477]
Hello,
I have question about MixedInvasionPercolation. I am trying to simulate imbibition following by drainage. There is a question for me in starting point of imbibition. 
when I use set_residual function with those pores in last Pc of drainage invasion for inputting, some pores and throats seem miss in imbibition (I check it in network library and in ParaView visually too), So the starting point in imbibition shifts to left. Is something wrong here or any comment?
![Figure_1](https://user-images.githubusercontent.com/49044459/80412602-5a2be000-88e3-11ea-9e7a-625951ee4ba0.png)

here are the algorithm parts:
```
IP_withdrawal = op.algorithms.MixedInvasionPercolation(network=pn)
IP_withdrawal.setup(phase=oil)
IP_withdrawal.set_inlets(pores=pn.pores(['left']))
IP_withdrawal.run()
IP_withdrawal.set_outlets(pores=pn.pores(['right']))
IP_withdrawal.apply_trapping()
injection_data = IP_withdrawal.get_intrusion_data()
# imbibition: water invade oil
IPw = op.algorithms.MixedInvasionPercolation(network=pn)
IPw.setup(phase=water)
IPw.set_inlets(pores=pn.pores(['left']))
IPw.set_residual(pores=IP_withdrawal['pore.invasion_sequence'] == -1)
IPw.run()
IPw.set_outlets(pores=pn.pores(['right']))
IPw.apply_trapping()
injw = IPw.get_intrusion_data()
```
and this is confirmed process I am trying to simulate:
![Capture](https://user-images.githubusercontent.com/49044459/80418491-bcd5a980-88ec-11ea-8112-a2a12d982f12.PNG)

**Comment by jgostick** [comment]
I'm sooo sorry!  I forgot to reply to this.  I'm guess the reason is that your boundary pores have non-zero volumes.  The algorithms begin by filling them so the curves will be shifted to non-zero startng saturations if you don't use boundary pores.

**Comment by ma-sadeghi** [comment]
@saeidabd Does this answer your question? I'm closing this issue for now, but feel free to reopen if you still need help.

**Comment by Mohammadrezapilehkouhi2000** [comment]
hello
Is it possible to send the complete form of this code?
thanks

**Comment by saeidabd** [comment]
> hello Is it possible to send the complete form of this code? thanks

Dear M.Reza, I really don't access them right now, I am in your touch if this is force for you.  saeid.abdollahi1996@gmail.com
