### ISSUE TITLE
Store initial guess, x0, in algorithm: alg["pore.initial_guess"]

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1478]

**Comment by jgostick** [comment]
I'd rather not store it in the settings, which we would like to be able to print nicely.  How about as an attribute like _x0?  hidden or not.

**Comment by ma-sadeghi** [comment]
I agree, `alg._x0` seems where it belongs.

**Comment by jgostick** [comment]
Why not just store it in the dict, along with all the other arrays?  ``'pore.x0'``, or ``'pore.initial_guess'``

**Comment by jgostick** [comment]
this is now forbidden...only json serializable objects can be stored in settings as of PR #1641

**Comment by jgostick** [comment]
I think we're doing this right?

**Comment by jgostick** [comment]
This is being done, and it's use case is to see after the solution what initial guess was used.  It's not being used in solver though.
