### ISSUE TITLE
docrep only renders in Spyder IPython console

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1497]
Unfortunately, `docrep` doesn't render in Spyder editor, which is where most of the development occurs. I already reported this to Spyder dev team, but there's little they can do now (see [here](https://github.com/spyder-ide/spyder/issues/12492)). In addition, it doesn't work in other IDEs either, at least those I tried, the most popular of which is Microsoft's VS Code. @Zohaib-Atiq, can you please report back for PyCharm here?

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi For me docrep is rendering in Pycharm. I have used spyder as well but its not working there.

**Comment by jgostick** [comment]
Hmmm, maybe we should let the docrep guy know? He's pretty active over there. I guess I find that the help console does not launch from the editor but does from the commandline.  I have had this problem with spyder periodically for a long time, so I am used to it.  BTW, is it only docrepped functions?

**Comment by jgostick** [comment]
so, given the following:

``` python
fd = op.algorithms.FickianDiffusion(network=pn)
```

When I do ``fd.settings`` + ctrl-i in the editor I get nothing (actually a message saying there are no docs) and at the command line I get the full glory of all the inherited docstrings.  It's odd to me that spyder could do it from one location but not the other.  Like a I say, calling the help from spyder has always been glitchy to me.

**Comment by Zohaib-Atiq** [comment]
![pycharm](https://user-images.githubusercontent.com/30351879/83558803-93a6cb00-a4e1-11ea-9e99-b79329f5b578.png)

Works in Pycharm in text editor and console

**Comment by jgostick** [comment]
check the ``settings`` attribute.  That is loaded with fancy docrep stuff.

**Comment by Zohaib-Atiq** [comment]
cannot see `settings` from text editor or console using pycharm

**Comment by jgostick** [comment]
I can see this in Spyder, so the system is not totally broken.  I'll mention it on docrep.

**Comment by jgostick** [comment]
I was browsing the scipy source code the other day, and the use something similar to inherit docs.  I'm making a note here to check what they use.  Here is an [example](https://github.com/scipy/scipy/blob/6bd8975294ec0d66d159195d3ffb50d336eb6410/scipy/ndimage/filters.py#L54).

**Comment by jgostick** [comment]
Docrep works in Spyder, Jupyter Notebook, Jupyter Lab, and Sphinx.  I think trying to support all possible IDEs is not feasible, so I'm willing to close this and forget it.
