### ISSUE TITLE
Solvers don't check for convergence when maximum iterations is reached

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1501]
This is a corner-case that @mkaguer has recently found. Basically, when `max_iter` is reached, the solver gets tricked that the solution has converged. This is because unless `update_iterative_props` is called, the solution `x`, not surprisingly, satisfies `Ax-b~0`. It's only when we update the `A` matrix with the new solution (due to a nonlinear source term for instance), that `Ax-b~0` no longer necessarily holds. When `max_iter` is reached, the `for` loop is ended, and `update_iterative_props` which happens to be at the top of the loop never gets called again.

**Comment by jgostick** [comment]
The for-else construct might be useful, since it's literally meant to check 'why' the loop ended, either a ``break`` or the end of the loop.  

https://book.pythontips.com/en/latest/for_-_else.html
