### ISSUE TITLE
About the parameter of the function `jenkins_rao`

### ISSUE THREAD

**Issue by xu-kai-xu** [PMEAL/OpenPNM#1502]
dir: OpenPNM/openpnm/models/geometry/throat_shape_factor.py

When I read the file to understand the shape factor, I find the function `jenkins_rao` includes the parameter `throat_diameter` with the default `'throat.indiameter'`. This makes me confused. Usually, the parameter `throat_diameter` uses default `'throat.diameter'`. Do you make this way on purpose?

**Comment by jgostick** [comment]
It might be a typo, but it might mean 'inscribed diameter'.  We haven't used that function in ages, maybe never actually.  You can just do ``throat_diameter='throat.diameter'`` for now.  I will investigate.

**Comment by jgostick** [comment]
I'm sorry, I looked at the paper but could not find the time to dig up a correct answer for you. I have a better suggestion though: have you tried writing your own model? That way you'll know exactly what is going on and what each parameter is doing.

**Comment by xu-kai-xu** [comment]
@jgostick , ok, I will try it. Thanks.
