### ISSUE TITLE
Numba deprecations warnings are being silenced, should probably fix

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1510]
numba is being used in the invasion percolation algorithm [here](https://github.com/PMEAL/OpenPNM/blob/740d834189b918a32b56c228476c00e6673b143b/openpnm/algorithms/InvasionPercolation.py#L472)

Should probably deal with whatever this warning is about before it becomes an error.

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi, @jgostick This is a bug in `numba` (https://github.com/numba/numba/issues/4926). Actually `heapq` method does not accept `numba` builtin `typed.list()`. This is already a pending issue in `numba` that @ma-sadeghi posted last year. For now just ignore the warning as we are doing. May be they will implement this in future. If not then we have to find alternate of `heapq` method or write our own.

**Comment by jgostick** [comment]
This has been fixed upstream, so we can now address this.  This means we should remove the silencing of the warnings since there won't be warnings anymore
