### ISSUE TITLE
Do Jupyter Notebook examples really provide value?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1529]
These things are a pain for several reasons:

1.  They often don't render on github.  There seems to be some sort of limit to the number of notebooks github can/will render per hour, so I'm often left with a 'something went wrong, reload?' message.
2.  Do people actually download them and use them?  Generally our notebooks have a LOT of explanatory text, which a user would not want, so I suspect they'd just delete it.  More likely, the just cut-and-paste the actual code snippets into their own script or notebook.
3.  People are not contributing notebooks, so the 'ease' of creating a notebook example does not seem to be motivating people to push them to the repo.
4.  When all examples are in notebooks, they do not show up on the 'documentation' page, only on the github site.  If we revert to have RST files as examples, then they can show up in both places.  I've also been experimenting with sphinx-gallery, which makes a very nice landing page for examples, but this only works with RST files.  Interestingly, they allow downloading of notebooks if a user wants.

**Comment by ma-sadeghi** [comment]
@jgostick Some thoughts:
1. Maybe we can use `nbconvert` to convert them to RST so we can embed them in the documentation
2. I think at the moment, the biggest advantage of having them in notebook format is that they serve serve nicely as integration tests
3. A minor benefit is that they're always up to date, meaning that what you see as output is what you get had you run the example yourself
4. I don't know how powerful `nbconvert` is in converting notebooks to RST. If it does a decent job, we can have both, with RST files being generated on the fly.

**Comment by jgostick** [comment]
Counter points:  
* pytest can test rst files, and actually adding notebook testing was more recent
* rst files also contain hardcoded output which is compared to the actual output during test, just like the notebooks.  We've added @NBVAL_IGNORE_OUTPUT to many notebooks since output doesn't always match the result of a cell
* the sphinx-gallery plugin is AWESOME.  It looks like it can generate notebooks from rst files, instead of the other way around.

**Comment by ma-sadeghi** [comment]
I agree with your points. I was suggesting that we could have them both, especially that writing an example from scratch as a notebook is easier than writing it from scratch in RST form. If `nbconvert` can do a good job in converting notebook to RST then I think it should be fine to support both.

**Comment by jgostick** [comment]
let's go with notebook for now, and we can convert to rst's later using nbconvert if needed
