### ISSUE TITLE
Throat size definition

### ISSUE THREAD

**Issue by aaornsc** [PMEAL/OpenPNM#1537]
Hello to everyone, 

My name is Aarón Sánchez, and I’m currently working on my Geophysics Engineering bachelor thesis, which is advised by PhD Martin Diaz-Viera from Instituto Mexicano del Petróleo (IMP). Actually my work is related to the one explained in the issue #489.
I'm not quite sure if it's something I'm missing or something i don't understand completely.

First I'll explain what I'm working on; I'm using micro-CT X-Ray data of a rock provided by IMP in Mexico City, I extracted the network information with the Pore Network Extraction algorithm from the Imperial College research group (Martin Blunt), and applied the io.Statoil method to use the .dat files as input in OpenPNM. I can create my network model and do the flow simulations to get permeability values. The problem i have now is I'm trying to create new sizes of pores and throats while maintaining my network structure (pn.coords and pn.conns). I found that i can use [pn.clear] to "erase" the sizes and other geometry properties. Then to create new sizes (that i actually want them to be part of the size distribution from the original data) I use a distribution and parameters obtained by a fitting algorithm and run the next lines.

```

geom = op.geometry.GenericGeometry(network=pn, pores=pn.Ps, throats=pn.Ts)
geom['pore.seed'] = np.random.rand(geom.Np)
seeds_p = np.zeros_like(pn.Ps, dtype=float)
seeds_p[pn.pores(geom.name)] = geom['pore.seed']
seeds_p = pn['pore.seed']

stats_obj_p = sp.stats.pearson3(1.1913338059494305,loc=7.802740422503951e-05, scale=4.5905121354537024e-05)
geom.add_model(propname='pore.diameter',model=op.models.geometry.pore_size.generic_distribution, seeds='pore.seed',func=stats_obj_p)

```
And the pore.size list is created without problems, but when i'm defining the throat.size list is where my problem comes up. As i can see in the documentation to define the throat sizes I'll have to use the next line:

`geom.add_model(propname='throat.diameter', model=op.models.misc.from_neighbor_pores, pore_prop='pore.diameter',mode='min')`

And i can change the mod to be 'min', 'max' or 'average' if i remember well.
Unfortunately what i want to do is define my throat.size from a distribution as i did with the pores, so my new throat sizes are related in a way with the original sizes.

Is there any way to define throat.size without implying a dependence on the pore size? I understand the modes and model "from_neighbor_pores" are set to keep the consistency of the network.

What I thought was to create a little function that take the pn.conns and use the sizes of pores as restrictions or limits and return the throat.size list, but I'm not sure if that's a good approach. Any comments and/or suggestions are really appreciated.

**Comment by jgostick** [comment]
Hi @aaornsc.  We are currently working on updating our examples, and have a new branch called ``examples_galore``.  This branch has an example that may help you:  

https://github.com/PMEAL/OpenPNM/blob/examples_galore/examples/notebooks/geometry/adjusting_pore_size_distributions.ipynb

Note that this link will disappear eventually once we merge the branch into dev, but then you can navigate to it by clicking through "examples/notebooks/geometry/adjusting_pore_size_distributions.ipynb"

**Comment by jgostick** [comment]
I'm going to close this question since I think the example I directed you to should get you started.

**Comment by aaornsc** [comment]
Sorry for the late response.

Yes, indeed I was able to create the size distribution as I described before with the example given. 

Thanks a lot!!

Ps. Just as a comment, in both instances [17] and [18] there was a small typo, or at least i had to change the name of the argument `prop='pore.diameter' ` to `pore_prop='pore.diameter'`


In [17]:

f = op.models.misc.from_neighbor_pores
geo.add_model(propname='throat.diameter_1',
              model=f, **prop='pore.diameter'**, mode='min')

In [18]:

f = op.models.misc.from_neighbor_pores
geo.add_model(propname='throat.seed',
              model=f, **prop='pore.seed'**, mode='min')
f = op.models.geometry.throat_size.weibull
geo.add_model(propname='throat.diameter_2',
              model=f, shape=1.5, scale=.2, loc=0)
