### ISSUE TITLE
Computing conductance values using Laplacian operator is convoluted

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1540]
Basically, for calculating conductance values, we use Scipy's `laplacian` operator with default arguments, i.e. `use_out_degree=False`. This is fine for symmetric problems, but explaining it becomes very convoluted when the problem is assymetric, such as mass partitioning or advection-diffusion. I researched the matter quite a bit and I think we should use `laplacian` with `use_out_degree=True`. This transition needs a thorough analysis of the code to make sure we don't break anything, although we have tons of unit tests. Anyways, this ways, explaining why we did what we did in `multiphase_diffusion` pore-scale model becomes almost obvious to someone reading the code. This issue was brought up while I was trying to explain it to @mkaguer.

**Comment by Ni2M** [comment]
I have realized the same problem as well. use_out_degree=True changes the axis for summation of the conductance values of neighboring throats (off-diagonal elements) to find the value of the diagonal element. axis=0 is the default value that sums column-wise (which is no different than row-wise in a symmetric matrix), whereas in an asymmetric matrix sum over the rows and columns are not necessarily the same.

![image](https://user-images.githubusercontent.com/43128873/99808907-8e7d1d00-2b0f-11eb-9e05-fe178429d28f.png)

**Comment by ma-sadeghi** [comment]
Following the discussion with @Ni2M, I don't think this is no longer an issue. Here's a brief summary for future reference:

- The use of `csgraph.laplacian` with the default settings, i.e. column-wise summation is correct.
- What's wrong is the way we used to define throat conductance
- Conductance in its most generic form is defined as `g = [G12, G21].T`, which is an Nt by 2 array.
- Mass transfer in conduit 12 was incorrectly defined as `m12 = G12 * c1 - G21 * c2`, meaning that `G12` is the coefficient of `c1`, and `G21` is the coefficient of `-c2`. This is incorrect.
- The correct definition is that `G12` is the coefficient of `-c2` and `G21` is the coefficient of `c1`.
- Here's an example: consider advection-diffusion in conduit 12, where there's a net positive flow rate from pore 2 to pore 1.
- Assuming upwind (for simplicity), we have `m12 = g (c1 - c2) - Q * c2`
- Based on the correct definition of `G12` and `G21`, we will have: `G12 = g + Q`, and `G21 = g`.
