### ISSUE TITLE
Make conical_frustum_and_stick the default shape factor model

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1570]
The default flow/Poisson shape factor models in `Standard` physics assume spherical pores. This assumption is not a robust one in terms of numerical calculations (see #1421 for instance). If we use `conical_frustum_and_stick` shape factor models instead, we won't have any issues with the values becoming `inf` or `nan` as they're mathematically relatively simple. Also, while the spherical assumption is best for an actual stick and ball geometry, it's not realistic in other cases and in my experience (if I remember correctly), `conical_frustum_and_stick` shape factor models overall give more accurate results.

**Comment by jgostick** [comment]
We have actually side-stepped this one by creating the new size-factor models in PR #1604
