### ISSUE TITLE
[Feature Request]: add "origin" as optional argument to Cubic

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1581]
**Is your feature request related to a problem? Please describe.**
Although it is very minor, this feature is handy when creating multidomain networks. Also, the change would be entirely backwards compatible.

**Describe the solution you'd like**
```python
net1 = op.network.Cubic(shape=[100, 10, 100], origin=[0, 0, 0])
net2 = op.network.Cubic(shape=[100, 25, 100], origin=[0, net1.shape[1], 0])
```

**Describe alternatives you've considered**
Currently, the user needs to manually translate the nodes to a different origin via:
```python
net1 = op.network.Cubic(shape=[100, 10, 100])
net2 = op.network.Cubic(shape=[100, 25, 100])
net2.coords += [0, 10, 0]
```

**Comment by jgostick** [comment]
This is too easy to do manually afterwards, just with ``pn['pore.coords'] += [0, 0, 1]`` for example.  There is no need to clutter the init of the class with this.
