### ISSUE TITLE
Add pores-scale models to networks

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1584]
I just had a bit of a eureka.  This is in addition to the already great idea in #1505 of using them to do health checks on the topology.

We should add pore-scale models to the GenericNetwork class, and here's why:

1.  'throat.bond_length': This would be the site-to-site distance between each pore.  It is useful when finding actual throat lengths in geometry models.
2.  'pore.nearest_neighbor':  Similar to above, but for each pore you could report the distance to the nearest neighbor pore.
3.  'pore.num_neighbors':  This is similar to the num_neighbors method, but is just a straight-up count of coordination number

**Comment by xu-kai-xu** [comment]
About the coordination number,  what about to add a function for showing the statistical information of a PNM, including, pore diameter distribution, throat, diameter distribution, and pore coordination distribution. You can also plot it directly. For now, I just think the three, do you think throat length is also important for the statistical information? Or, it is too easy to make it a function?

**Comment by jgostick** [comment]
There is a function already, called ``show_hist``, and you can pass in a list of props, like ['pore.diameter', 'throat.length', etc].  This isn't super well formatted, but people should make their own graphs if they want something publishable.
