### ISSUE TITLE
[Bug]: plot_connections and plot_networkx produce out-of-scale plots

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1592]
**Describe the bug**
plot_connections and plot_networkx produce out-of-scale plots

**To Reproduce**
Steps to reproduce the behavior, ideally a code snippet that only reproduces the bug:
```python
import openpnm as op
net = op.network.Cubic(shape=[3, 3, 1])
op.topotools.plot_networkx(net)
op.topotools.plot_connections(net)
```

**Expected behavior**
Similar plot but with better margins.

**Screenshots**
Here's what you get:
![image](https://user-images.githubusercontent.com/14086031/88293178-a8753300-ccc8-11ea-83cf-dcc08ec0242c.png)

**Comment by Ni2M** [comment]
investigation on https://github.com/PMEAL/OpenPNM/blob/98e055cf3e680b023e47904efcf8b9936ec9d0cb/openpnm/topotools/plottools.py#L333 and https://github.com/PMEAL/OpenPNM/blob/98e055cf3e680b023e47904efcf8b9936ec9d0cb/openpnm/topotools/plottools.py#L350

**Comment by jgostick** [comment]
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.autoscale.html
