### ISSUE TITLE
[Question]: <Warning thrown when adding new pores to a network, does this indicate issue when geometry is assigned?>

### ISSUE THREAD

**Issue by taylrcawte** [PMEAL/OpenPNM#1600]
When adding boundary pores to network a warning issues the following statement (pictured below) : "WARNING: Network has active geometries, new pores must be assigned a Geometry". This warning is thrown even if the pores are assigned a geometry after being added. Is the warning just highlighting the need to assign a geometry to the new pores or is it saying that these new pores do not have a geometry assigned to them (even after the geometry has been assigned) 

![image](https://user-images.githubusercontent.com/65000690/88702943-127f4500-d0da-11ea-8877-faed242ce4a5.png)

```python
<
import porespy as ps
import openpnm as op

im = ps.generators.cylinders(shape=[100, 100, 100], radius=4, ncylinders=100, phi_max=90, theta_max=90)
im = ps.filters.fill_blind_pores(im)
im = ps.filters.trim_floating_solid(im)

net = ps.networks.snow(im=im, voxel_size=1e-6)

pn = op.network.GenericNetwork()
pn.update(net)

geom = op.geometry.Imported(network=pn, name='geom1')

op.topotools.add_boundary_pores(pn, pores=pn.pores('top'), offset=[0, 0, max(net['pore.diameter'])],
                                apply_label='top_inlet')

PsB = pn.pores('*inlet')
TsB = pn.find_neighbor_throats(pores=PsB, mode='xor', flatten=True)
geom_b = op.geometry.GenericGeometry(network=pn, pores=PsB, throats=TsB, name='boun1')
>
```

**Comment by jgostick** [comment]
Yes, it's just a warning...you're covered because you create ``geom_b`` below, so you heeded the warning ;-)

**Comment by taylrcawte** [comment]
Great Thanks for the clarification !
