### ISSUE TITLE
Which flow_shape_factor should be defined for Standard physics?

### ISSUE THREAD

**Issue by Ni2M** [PMEAL/OpenPNM#1607]
The ball_and_stick flow shape factor is the default for Standard physics. For cases with problematic pore size, they can not use Standard physics neither. 
please refer to https://github.com/PMEAL/OpenPNM/pull/1605#issuecomment-673038767
I think we might need to assign an alternative shape factor model for Standard physics.

**Comment by ma-sadeghi** [comment]
Good point @Ni2M. This was proposed in #1570, so I'm closing this issue.
