### ISSUE TITLE
Stop adding the internal label during network instantiation

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1608]
I expected that "internal" refers to all pores except those labeled "surface", but apparently that's not the case.

**Comment by jgostick** [comment]
for clarity, 'internal' pores should be removed.  This was added pre-emptively for when uses add boundary pores, so there was a way to get 'not boundary pores', so maybe this internal label should be applied when boundary pores are added?  Or, the user should just know to do a quick ``pn['pore.surface'] = True`` first.
