### ISSUE TITLE
Why does A need to be symmetric in LinearTransport? 

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#1620]
https://github.com/PMEAL/OpenPNM/blob/289558826270ab8e1558aa5c8e0194177d9a34e0/openpnm/algorithms/GenericTransport.py#L479

A way to set value BC's is to set all the coefficients in the A matrix to zero except the BC pore and set this coefficient to 1 then set b to the value. The current implementation is more complicated and affects the connected pores and I think was done to keep the A matrix symmetric. Why was this done? The reason I ask is that I am looking at making a coupled solver where the A matrix is z*Np x z*Np where z is number of coupled variables and I'm getting some issues following this boundary logic

**Comment by ma-sadeghi** [comment]
Hey @TomTranter. For symmetric matrices, direct solvers such as `spsolve` are faster. Also, iterative solvers like `cg` only work on symmetric matrices. The alternative is to use more general iterative solvers such as `bicgstab` or `gmres` which is considerably slower than `cg`.

RE: connected pores, what exactly is the issue?

**Comment by TomTranter** [comment]
It's just I'm not getting the solution I expect and thought it was this boundary logic but could be something else. Thanks for the explanation. I'm using pyamg and seems to handle the solving fine
