### ISSUE TITLE
Partial assignment of geometric properties on network should throw a warning

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1622]
When `"pore.diameter"` is already available on `geometry`, **partial** assignment of `"pore.diameter"` silently fails. I think it should throw a visible warning under such circumstances.

**Comment by jgostick** [comment]
I'm going to need you to elaborate.  When I try to write 'pore.diameter' to a network when it's already defined on a geometry, I get an error.  I'm not sure what you mean by partial.

**Comment by ma-sadeghi** [comment]
> I'm going to need you to elaborate. When I try to write 'pore.diameter' to a network when it's already defined on a geometry, I get an error. I'm not sure what you mean by partial.

I meant assignment of properties on "network" as opposed to geometry, for instance:
```python
net["pore.diameter"][Ps] = 1.5
```
has no effect if `pore.diameter` is avaiable on geometry.

**Comment by ma-sadeghi** [comment]
**Update**: if we have `throat.foo` on `phys1` but not on `phys2`, running `phys2["throat.foo"][subset] = 1.0` silently fails to do anything (i.e. `phys2["throat.foo"]` still evaluates to `nans`)

**Comment by jgostick** [comment]
This is the 'expected' behavior, or more to the point, this is unavoidable.  The array returned by the call above is an 'interleaved' array and it does not exist on any object, so when you write to it, that doesn't get stored anywhere.  The only way to have this work is to subclass the numpy array and overload their __setitem__ method, but this is more trouble that we want to deal with.
