### ISSUE TITLE
"import openpnm" leads to "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by j-d-edwards** [PMEAL/OpenPNM#1636]
This is a problem that has cropped up only recently, after I changed machines and upgraded openpnm. If I try to import the OpenPNM package into a Python script, I get the following error:

```
import openpnm

Traceback (most recent call last):

  File "<ipython-input-2-3160d0f88a7a>", line 1, in <module>
    import openpnm

  File "/home/jdedwards/anaconda3/lib/python3.8/site-packages/openpnm/__init__.py", line 64, in <module>
    from . import algorithms

  File "/home/jdedwards/anaconda3/lib/python3.8/site-packages/openpnm/algorithms/__init__.py", line 13, in <module>
    from .GenericTransport import GenericTransport

  File "/home/jdedwards/anaconda3/lib/python3.8/site-packages/openpnm/algorithms/GenericTransport.py", line 102, in <module>
    class GenericTransport(GenericAlgorithm):

  File "/home/jdedwards/anaconda3/lib/python3.8/site-packages/openpnm/algorithms/GenericTransport.py", line 217, in GenericTransport
    @docstr.get_full_descriptionf(base='GenericTransport.reset')

  File "/home/jdedwards/anaconda3/lib/python3.8/site-packages/docrep/decorators.py", line 110, in deprecated
    return func(self, *args, **kwargs)

  File "/home/jdedwards/anaconda3/lib/python3.8/site-packages/docrep/__init__.py", line 974, in get_full_descriptionf
    return self.get_full_description(base=args[0], *args[1:], **kwargs)

IndexError: tuple index out of range
```

I am running an Ubuntu 18.04.5 machine, Linux Kernel 5.4.0-45. I have Anaconda version 2020.07. The OpenPNM release I am running now is 2.4.2.

I have tried uninstalling OpenPNM, running it with an older release version (2.3.1) that is still functioning on another machine. I have also tried using an older release version of Docrep (0.2.7) instead of the most current (0.3.0). I have completely uninstalled Anaconda and OpenPNM and done a fresh install of all related packages. None of these attempts have fixed the issue. I really have no idea what is going wrong, is this an issue that has shown up before?

**Comment by ma-sadeghi** [comment]
You need to update `OpenPNM` to 2.5.1. Run
```
pip install openpnm --upgrade
```

**Comment by j-d-edwards** [comment]
Thank you, that worked! I was using the `conda install -c conda-forge openpnm` installation instructions, which seems to be downloading the older version of the package. Unfortunately, I'm now running into an issue with `No module named 'pypardiso'`, but I should be able to work that out.

**Comment by ma-sadeghi** [comment]
@j-d-edwards That's right, we're moving towards making `conda` the default installation, but at the moment I'm trying to add `pypardiso` to `conda-forge`. Should be done in a week or so.

Anyways, you can install `pypardiso` by:
```
conda install -c haasad pypardiso
```

**Comment by ma-sadeghi** [comment]
@j-d-edwards We just fixed the conda-forge builds. So you can install `openpnm` via conda as well. Also, we've packaged `pypardiso` ourselves (as the package author is no longer active on github) and shipped it to conda-forge under `pardiso4py`. It's now listed as a dependency, so if you install `openpnm` via `conda`, you shouldn't get any error regarding `pypardiso`.
