### ISSUE TITLE
Enforcing matching of surface labeling between OpenPNM and SNOW networks

### ISSUE THREAD

**Issue by DMaxJ** [PMEAL/OpenPNM#1639]
[openpnm2.docx](https://github.com/PMEAL/OpenPNM/files/5180215/openpnm2.docx)

**Problem description**
There seems to be a mismatch depending on how networks are generated/imported in OpenPNM. This issue could also go to the porespy thread, but I am a bit confused.
1) When one generates a network using the cubic template like this 
```
import openpnm as op  
pn=op.network.Cubic(shape=[20, 10, 5], spacing=1)  
```
the generated surfaces will be labeled like this: (here the directions refers to network directions)
front and back along x-direction at xmin=.5 and xmax=19.5 respectively
left and right along y-direction at ymin=0.5 and ymax=9.5 respectively
bottom and top along z-direction at zmin=0.5 and zmax=4.5 respectively

2) For extracting networks using SNOW a tif file is created from image stack. The images of X width and Y height are put in a stack of Z slices in ImageJ which is then exported as a tif or RAW file. Now the following code is used:
```
path = 'X:\\.................\\TEST_SNOW'  
os.chdir(path)  
file_format = '.tif'  
file_name = 'SNOW_850x680x490'  
file = file_name + file_format  
fetch_file = os.path.join(path, file)  
im = imageio.mimread(fetch_file, memtest=False)  
resolution = 1 
net = ps.networks.snow(im=im, voxel_size=resolution)  
pn = op.network.GenericNetwork(name='TEST', project=proj)  
pn.update(net)  
````
Here, the surfaces are labeled like this
front and back along y-direction at ymin=1 and ymax=684 respectively
left and right along x-direction at xmin=3.5 and xmax=492 respectively
bottom and top along z-direction at zmin=1 and zmax=854 respectively
3) If the same stack from the above point is used to extract network using the maxball algorithm, then the inlets and outlets will be along x-direction. If one uses the topotools.label_surface() function then it will front and back will be along x-direction with xspan=850, left and right will be along y-axis with yspan=680, and top and bottom will be along z-axis with zspan=490.

Thus, it is a bit problematic while running multiple simulations using Maxball or SNOW for the same image stack as the difference in their labeling creates confusion while carrying out calculations.

**SUGGESTION**
Please ensure that porespy generates networks such that this problem does not arise
                                                OR
Some function inside openpnm that takes care of this issue while updating the network

**NOTE**
Re-slicing the image array in the beginning itself could be a solution as well. Please let me know if there is any better solution or if I have missed anything.

**Comment by jgostick** [comment]
Hi @borahdj2010 thanks for the suggestion.  We are in the process of moving PoreSpy to V2, at which point we can make the backwards incompatible changes you suggest.  This process is just taking ages but there is reason to believe things will go faster this fall.
