### ISSUE TITLE
Add model to subdomain objects that returns the indices into the full domain

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1642]
This would allow something like ``Ps = geo['pore.net_01']`` and would in many cases remove the need to use the ``map_pores/throats`` function which is a bit confusing to use.

**Comment by ma-sadeghi** [comment]
@jgostick, so in your snippet, `Ps` is the same as `Ps = net.map_pores(geo.Ps, origin=geo)`?

I think we also have `geo.pores(target=net)` for this purpose, is that right?

I admit that using `map_pores/throats` is confusing, but I think `obj.pores(target)` is maybe intuitive enough. What do you think?

**Comment by jgostick** [comment]
Yes, so the following would be equivalent;

``` python
Ps = net['pore.geo_01']  # Assuming geo.name = geo_01...note this already works
Ps = geo.pores('all', origin=net)
Ps = geo['pore.net_01']  # Assuming net.name = net_01

```

So the first line already works, and I'm just proposing to add the reverse option as shown in line 3, but to do it via a pore-scale model.

**Comment by jgostick** [comment]
This will not be needed in the new Base since there is the new `relative` flag in the `pores/throats` methods.

**Comment by jgostick** [comment]
I was overexcited when I closed this.  The new Base classes will not be happening.  However, I will be adding the relative argument to the pores/throats methods in a new PR.
