### ISSUE TITLE
VTK output failed to visualized in ParaView

### ISSUE THREAD

**Issue by megavolts** [PMEAL/OpenPNM#1648]
**Describe the bug**
Pore network was extracted with porespy 1.3, then imported in openpnm via pn.update(net), and finally exported in VTK or XDMF format for visualization in Paraview. 

When loading the file in Paraview, Paraview consume all available memory and freeze the computer. The not working VTK output is attached in the tarball archive (FAIL.vtk)

I am expecting the but to be either in openpnm or porespy.

**Step to reproduce**
The only change in the code was to use the true voxel_size=4e-5, rather than the default voxel_size=1
```
net = porespy.networks.snow(im_sub, marching_cubes_area=True, voxel_size=4e-5)
pn = openpnm.network.GenericNetwork()
openpnm.update(net)
op.io.VTK.save(network=pn, filename=VTK_fn)
```

**Expected behavior**
I expect to be able to visualize the VTK/XDMF file in paraview

**Additional context**
Earlier this year, the same operation was performed with successful visualization.  The working VTK output is attached in the tarball archive (SUCCESS.vtk). At that point I was using porespy v.1.2 which still had the find_percolating_paths filters, and voxel_size=1 for the SNOW algorithm

[VTP_files.tar.gz](https://github.com/PMEAL/OpenPNM/files/5241577/VTP_files.tar.gz)

**Comment by jgostick** [comment]
Based on your above code, the offending line is ``openpnm.update(net)``.  It should be ``pn.update(net)``.  This transfers all the data from the 'net' dict produced by porespy onto the empty network created by openpnm.

**Comment by jgostick** [comment]
We are working to improve the import process, and I recommend doing the following:
```
proj = op.io.PoreSpy(net)
pn = proj.network
```

This will create both a network and a geometry, storing them both in the project.  It divides the data between two accordingly.

**Comment by megavolts** [comment]
My bad, I used `pn.update(net)`

I used the following code:
```
proj = op.io.PoreSpy()
proj = proj.load(net)
pn = proj.network
```
As the use of  `op.io.PoreSpy(net)` led to:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: PoreSpy() takes no arguments
```

However the problem still exists, and it seems to depends on the voxel_size parameters:
- voxel_size = 1 succesfully visualize
- voxel_size = 4e-5 failed to visualize

**Comment by jgostick** [comment]
Also, my bad, should have been ``op.io.PoreSpy.load``.

**Comment by jgostick** [comment]
I just ran the following and it worked like a charm:

```
import porespy as ps
import openpnm as op
im = ps.generators.blobs(shape=[300, 300, 300])
net = ps.networks.snow(im, voxel_size=1e-4, marching_cubes_area=True)
proj = op.io.PoreSpy.load(net)
op.io.VTK.save(proj.network)
```

ps.__version__ = '1.3.0'
op.__verison__ = '2.5.1'
Paraview version = 5.7.0

**Comment by jgostick** [comment]
Also, your FAILED file opens in my Paraview no probs.

**Comment by megavolts** [comment]
Thanks for testing.
I will investigate more on my side.
