### ISSUE TITLE
Is it possible for the boundary pores to allow flux?

### ISSUE THREAD

**Issue by p-thomson** [PMEAL/OpenPNM#1653]
I am running the transient advection diffusion simulation and I want to obtain the pore concentration in the outlet pores. At present I am applying Dirichlet boundary conditions like those in the Transient Fickian Diffusion example (ad.set_value_BC(pores=outlet, values=0.0) so all boundary pores at the outlet have a value of 0 at the end of the simulation. 

Is there a way to get the pore concentration in the outlet pores assuming flux out of the domain?

**Comment by ma-sadeghi** [comment]
We have `set_rate_BC` which does that, except that it's rate not flux. Does that answer your question?

**Comment by jgostick** [comment]
Ya, we don't have a flux because we don't know the 'area' of the cells, meaning we only know the area of the pores/throats, but not the solid area that surrounds them.

**Comment by p-thomson** [comment]
Thank you both. In the end I used **set_outflow_BC** on the outlet pores and this gives me the pore concentration at each time step.

**Comment by ma-sadeghi** [comment]
> Thank you both. In the end I used **set_outflow_BC** on the outlet pores and this gives me the pore concentration at each time step.

Just to state the obvious: `set_outflow_bc` sets the diffusive gradient at the given pores to zero, whereas `set_rate_bc(pores, values=0)` sets the entire rate to zero.
