### ISSUE TITLE
Problem adding boundary pores to extracted networks 

### ISSUE THREAD

**Issue by DMaxJ** [PMEAL/OpenPNM#1654]
I am trying to add boundary pores to an extracted (SNOW) network. I first use the Imported class to get the network data to the geometry object. Then I add boundary pores. But using the Boundary class to create the boundary object fails. The code is shown below (I have mentioned only the relevant portion)

```
ws = op.Workspace()
ws.load_project(fname)
proj=ws[fname]
pn=proj.network
Ps=pn.pores()
Ts=pn.throats()
geo = op.geometry.Imported(network=pn, pores=Ps, throats=Ts, name='geo')
op.topotools.add_boundary_pores(pn, pores=pn.pores('left'), 
                                move_to=[x0, None, None], 
                                apply_label='left_boun')
Ps_boun=pn.pores('*boun')
Ts_boun=pn.throats('*boun')

boun=op.geometry.Boundary(network=pn, pores=Ps_boun, throats=Ts_boun, name='boun')
```

The error occurs with throat_endpoints.spherical_pores. The error message looks like this

```
  File "l:\openpnm\openpnm\geometry\Boundary.py", line 82, in __init__
    model=gm.throat_endpoints.spherical_pores)

  File "l:\openpnm\openpnm\core\ModelsMixin.py", line 257, in add_model
    self._regen(propname)

  File "l:\openpnm\openpnm\core\ModelsMixin.py", line 340, in _regen
    self[prop] = model(target=self, **kwargs)

  File "l:\openpnm\openpnm\models\geometry\throat_endpoints.py", line 143, in spherical_pores
    LP1T = _sp.linalg.norm(TC - xyz[cn[:, 0]], axis=1) + 1e-15

  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\linalg\misc.py", line 142, in norm
    a = np.asarray_chkfinite(a)

  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")

ValueError: array must not contain infs or NaNs
```

Any suggestions as to how to solve this problem? I have no issues when I try with Cubic network. 

Upon creation the pores and throats have NaN values for both Cubic and Imported networks. But somehow while creating the boundary object it throws the error.

**Comment by ma-sadeghi** [comment]
@DMaxJ Thanks for reporting this. Boundary pores in OpenPNM are finicky and not robust at the moment. We're trying to address this issue soon.

> I have no issues when I try with Cubic network.

You mean when adding boundary pores to a Cubic network and assigning `Boundary` class to those pores, you don't get the same error?

**Comment by DMaxJ** [comment]
Hi! I have a solution to the problem as well. 
`You mean when adding boundary pores to a Cubic network and assigning Boundary class to those pores, you don't get the same error?
`
You are right, I do not get any error while adding boundary pores whether 1) I assign existing pores and throats to geometry or 2) I do not

**THE SOLUTION**

I tried changing 
```
import scipy as _sp
```
 to 
```
import numpy as _np
```

and changed the respective lines in the respective source file. I guess the scipy and numpy interchange needs immediate attention.

**Comment by DMaxJ** [comment]
Actually I had some simulations from some earlier version of openpnm. Now, things have changed and I lost track of what I did before. But this error was solved by pure chance only (after trying many things).

**Comment by DMaxJ** [comment]
By source file I mean the `throat_endpoints.py` file

**Comment by ma-sadeghi** [comment]
@DMaxJ I'll look into it.

**Comment by ma-sadeghi** [comment]
@DMaxJ which version of OpenPNM do you use? You can try:
```python
import openpnm
print(openpnm.__version__)
```

**Comment by DMaxJ** [comment]
The version is 
2.2.0

**Comment by ma-sadeghi** [comment]
@DMaxJ Oh! that explains it. We're now at 2.5.1. You should update it too. We've fixed a bunch of bugs. You can see the changelog [here](https://github.com/PMEAL/OpenPNM/releases). 

Also, make sure you install OpenPNM using `conda`. Although we still support `pip`, since we've changed our default solver to `pypardiso` (now known as `pardiso4py`), which is not available on `pip`, you need to manually install `pardiso4py`.

Anyways, long story short, install using `conda install -c conda-forge openpnm`. Probably you need to uninstall your previous installation first (`pip uninstall openpnm`). 

I'm closing this issue, but feel free to re-open it if your problem isn't solved even after updating OpenPNM.

**Comment by DMaxJ** [comment]
Thanks for the suggestion. But what would be the best way to install from a local repository similar to pip install -e "path/". I have some custom codes which I would like to use inside of openpnm.

**Comment by ma-sadeghi** [comment]
@DMaxJ In that case, pull the latest changes from github via `git pull`, or just do a fresh `git clone https://github.com/PMEAL/OpenPNM`. Then do `pip install -e "path/"`, but make sure to install `pardiso4py` using `conda install -c conda-forge pardiso4py`.

**Comment by jgostick** [comment]
Is it possible to do `conda install -e .` ?  I've never tried.

**Comment by ma-sadeghi** [comment]
> Is it possible to do `conda install -e .` ? I've never tried.

They don't have `-e`, but they do support `conda develop path/`, though I haven't tested.
