### ISSUE TITLE
Assigning geometry to merged pores

### ISSUE THREAD

**Issue by Eravalord** [PMEAL/OpenPNM#1656]
Hello everyone,

I am writing a code that splits and merges certain pores based on different conditions. I am not quite sure if this question was asked before: How can I add a previously existing geometry to a newly merged pore? 

I have an existing geometry:
`geo=op.geometry.GenericGeometry(network=net, pores=net.Ps, throats=net.Ts)`

Indeed I create a pore with:
`op.topotools.merge_pores(network=net, pores=[to_be_merged], labels=['merged'])`

so I thought adding it to the desired geometry could be a good way with a True/False statement:

`geo['pore.all'][net['pore.merged'][-1]] = True`

However, it does not add it to 'geo'. Maybe I missed a part in the documentation/among the forum threads, but any idea how to overcome this tiny hurdle? 

Thanks in advance! :)

**Comment by jgostick** [comment]
Your question is a good one.  It is related to #1407 actually, which is pretty high on our 'to do/fix' list.  There is a work around, but it's hidden:  

``` python
import openpnm as op
ws = op.Workspace()
proj = ws.new_project()
pn = op.network.Cubic(shape=[10, 10, 10], spacing=1e-4, project=proj)
geo = op.geometry.StickAndBall(network=pn, pores=pn.Ps[:-2], throats=pn.Ts)
print(geo.Np)
998
geo._set_locations(element='pores', indices=999, mode='add')
print(geo.Np)
999
```

We used to have a ``add_locations`` and ``drop_locations`` methods on the geometry class, but removed it for reasons I can't recall.  The issue I mentioned above will basically result in us re-implementing those functions.

**Comment by Eravalord** [comment]
@jgostick thank you very much for your answer! 

An additional question to this topic would be the visualization. As I create new pores for example by splitting (the program selects a point, creates a random amount of new pores between 2-5, and allocates them around the original cube randomly by taking 0,5*spacing to each direction), then I search for neighboring pores with op.topotools.find_neary_pores within a given radius for each newly created pore, eventually I connect every pore with the ones found in the previous step. However, when I try to gain image by Paraview, I repeatedly get the following error:

![image](https://user-images.githubusercontent.com/71832974/94416035-9b6c3880-017e-11eb-9069-026f4973b85e.png)

It is important to mention that while I am running the script, I get the following messages:

![image](https://user-images.githubusercontent.com/71832974/94416158-c6568c80-017e-11eb-8080-dca7754bcbf9.png)

Could you please help me, how to solve visualization?

**Comment by jgostick** [comment]
Can you run a network health check on your network, using:

```
h = pn.check_network_health()
print(h)
```

I'm guess that your network is not fully connected. That warning is probably not important, it's just telling you that it received [b, a] as a throat conn, but is switching it to [a, b] to keep the adjacency matrix upper triangular.

**Comment by Eravalord** [comment]
@jgostick Since your last comment, I managed to proceed with my work, and extended it to multiple networks. I am facing a little problem when several networks are present: I have a network dictionary containing all the networks, to each one of them I assign a single geometry (all together x number of geometries are present), and I would like to do this pore assignment in the similar way as you have showed it before, however this
` geo[num]._set_locations(element='pores', indices=len(net[num]['pore.coords'])-1, mode='add')`
gives this error message:
![image](https://user-images.githubusercontent.com/71832974/95742288-0a25b780-0c90-11eb-8e83-da00e0824c08.png)
How can I add an item to a geometry if multiple geometries are present within a dictionary?

**Comment by jgostick** [comment]
Can you post a minimum code snippet so I can see what's going on?

**Comment by Eravalord** [comment]
Sure!
So basically I have a dictionary filled with networks (net dictionary), I loop through each of them like this:
`for num in range(len(net)): `
Each network has one corresponding geometry, so I have a geo dictionary with the same length. What I am trying to do is creating new pores in each network based on some conditions, and adding them to the geometry with the matching index (net[0] is matched with geo[0]). All together num of geometries (or networks) are available.
```
# Merge the pores and store them under a label
                   op.topotools.merge_pores(network=net[num], pores=[to_be_merged], labels=['merged']) 
                   # Add the merged pore to the geometry
                   geo[num]._set_locations(element='pores', indices=len(net[num]['pore.coords'])-1, mode='add')
```
However calling set locations like this does not work if geo is a nested dictionary (containing num number of geometries), since it drops the following message that I have introduced previously:
![image](https://user-images.githubusercontent.com/71832974/95836618-f5086180-0d3f-11eb-8a92-3d5115da35c2.png)

Is there a way to overcome the "nestedness" of the geometry dictionary?

Thank you very much once again!

**Comment by Eravalord** [comment]
In the meantime I solved this issue, thank you for the help!

**Comment by jgostick** [comment]
great!  I guess you were just doing something too fancy with the geometry dict.
