### ISSUE TITLE
Add set outflow BC to Nernst Planck algorithm

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#1659]
@magnaou I noticed that set_outflow_BC is not available in nernst planck simulations only in advection diffusion simulations. But since nernst planck has flow we should also make this set_outflow_BC feature available for nernst planck simulations, right? Is there any reason why nernst planck currently does not have this feature? Right now set_outflow_BC method is found in the AdvectionDiffusion class. Perhaps we should move it to ReactiveTrasnport class. Problem there is that nonflow algorithms may have access to set_outflow_BC method. Would that be a problem? Or, what I have currently done to resolve the issue is added the set_outflow_BC method to the TransientNernstPlanck class. So it appears in two places: AdvectioDiffusion and TransientNernstPlanck. Anyway, I am just looking for your input into how to resolve this or if there is a good reason why set_outlfow_BC was overlooked.

**Comment by magnaou** [comment]
Good catch, this is being fixed on issue ##1657.
