### ISSUE TITLE
OpenPNM version number and journal output

### ISSUE THREAD

**Issue by DMaxJ** [PMEAL/OpenPNM#1661]
I have a request for few things to be incorporated within OpenPNM. I am not completely sure as to how it can be done, but it would be helpful if the following can be done.

1) While importing OpenPNM, it should show which version it is.
2) Is it possible for the OpenPNM output files to have the OpenPNM version number mentioned somewhere for later reference?
3) Is it possible to have some kind of a journal output similar to Ansys fluent or other software? One can still have an output from the ipython console, but can this be incorporated within OpenPNM such that when a script is run on Spyder, a journal output is available for future reference? Jupyter notebooks have kind of similar functionality, but not exactly the way I want (or maybe I do not know)

Could you please consider these points? Please let me know if I have missed anything already there. I have some simulations from around 2016 or earlier, but right now I cannot exactly tell which version it was. I tried to replicate some simple tests using cubic networks in the present version of OpenPNM (I changed the respective lines to be compatible with the new version) and saw that the permeability value diminished by a factor of 4. Right now I cannot determine what has changed there. I probably need to dig deeper. This is the reason behind asking for the features above.

**Comment by jgostick** [comment]
Hi @DMaxJ 
1.  You can type ``op.__version__`` at the command line to get the version.  This is standard practice in python, even though the __version__ thing is a bit hidden...once you know it's there, pretty much all packages have it.
2.  We are working on a new file format, which is more robust to saving/loading in different versions, unlike the pickle approach we currently use.  This file will have the version number in it, and I think it's a good idea for the version to print out when this file is reloaded.
3.  I'm not sure what you mean by 'journal'...can you paste in an example of what you'd like to see?

**Comment by DMaxJ** [comment]
Hello @jgostick 
Thank you for your reply. 
Sorry for using the word 'journal', it is actually the .out file typically created when one runs a simulation in Ansys fluent (or some job in a computer cluster). It is like writing the console output to a file. I am not completely sure as to how exactly it should be. Below is a part of such an output.
```
/appl/ansys_inc/v145/fluent/fluent14.5.0/bin/fluent -r14.5.0 3ddp -g -i sub.jou -t8 -mpi=intel -ssh -cnf=hostlist
Loading "/appl/ansys_inc/v145/fluent/fluent14.5.0/lib/fluent.dmp.114-64"
Done.
/appl/ansys_inc/v145/fluent/fluent14.5.0/bin/fluent -r14.5.0 3ddp -pmpi-auto-selected -host -alnamd64 -t8 -mpi=intel -cnf=hostlist -path/appl/ansys_inc/v145/fluent -ssh -cx cn01.cluster:56080:50394

     Welcome to ANSYS Fluent 14.5.0

     Copyright 2012 ANSYS, Inc.. All Rights Reserved.
     Unauthorized use, distribution or duplication is prohibited.
     This product is subject to U.S. laws governing export and re-export.

..........................................
.........................................
skipping some details here
...........................................
..........................................
hybrid initialization is done.
> /solve/iterate 2000
  iter  continuity  x-velocity  y-velocity  z-velocity   vf-oxygen     time/iter
     1  1.0000e+00  0.0000e+00  2.5255e-04  0.0000e+00  2.5825e-06  8:14:43 1999
     2  3.2064e-01  2.2225e-06  1.7813e-01  1.9553e-05  1.9999e+00  8:51:36 1998
     3  6.7179e-01  3.7068e-04  3.5454e-01  1.4653e-03  9.9989e-01  9:11:22 1997
     4  1.0000e+00  8.1579e-04  5.2902e-01  4.0122e-03  6.6656e-01  9:27:12 1996
     5  1.0000e+00  9.8730e-04  6.9995e-01  7.3308e-03  4.9989e-01  9:40:00 1995
     6  1.3968e+00  9.6002e-04  8.3278e-01  1.0773e-02  3.9990e-01  9:41:20 1994
     7  1.8348e+00  9.9870e-04  8.1771e-01  1.2243e-02  3.3323e-01  9:42:18 1993
     8  2.2436e+00  6.6835e-04  7.1561e-01  1.1960e-02  2.8562e-01  9:43:02 1992
     9  2.5744e+00  5.4344e-04  6.2785e-01  1.1421e-02  2.4990e-01  9:44:18 1991
    10  2.9921e+00  3.5752e-04  5.5521e-01  1.0813e-02  2.2213e-01  9:35:59 1990
    11  3.5380e+00  3.2523e-04  4.9257e-01  1.0138e-02  1.9991e-01  9:29:02 1989

-------------------------------------------------------
-------------------------------------------------------

 reversed flow in 2251 faces on pressure-outlet 18. 
  1955  1.0277e+04  6.6822e-05  3.4846e-03  1.8972e-03  4.6770e-03  0:10:09   45

 reversed flow in 2250 faces on pressure-outlet 18. 
  1956  1.0304e+04  6.6972e-05  3.4831e-03  1.8970e-03  4.6734e-03  0:09:57   44

Fatal error has happended to some of the processes!
Exiting ... 


```

It could be something like this. How exactly it would affect the performance of OpenPNM I do not know. But sometimes it is helpful to find out where things went wrong.

**Comment by jgostick** [comment]
We have rolled out a new file format, called PNM (``op.io.PNM``) that is much more robust than the previous OpenpnmIO approach, which was based on pickles and therefore broke if you updated your openpnm version.  The new format can handle this.  As part of the new format, we do store the version that was used to save the file, and prints out a few key lines when the file is reloaded.

**Comment by ma-sadeghi** [comment]
@DMaxJ Just to make sure, by journal output do you want OpenPNM to output iteration/residual info while solving and stuff like that?
