### ISSUE TITLE
The ability to freeze models not to regenerate

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1669]
**Is your feature request related to a problem? Please describe.**
Sometimes, it's convenient to be able to manually change some entries of a property, instead of properly adding a separate model to handle them.

**Comment by jgostick** [comment]
You can set regen_mode to 'constant' and the model will stop regenerating.  If you want to have some locations set by hand, while having other regenerate, then you should create two physics's, one with the model and one for the constant values. If you're thinking about a phase, then I'm not sure we have a way to do this, though there is nothing stopping you from putting phase properties on a physics object, so you could use the above mentioned approaches.

**Comment by ma-sadeghi** [comment]
> You can set regen_mode to 'constant' and the model will stop regenerating. If you want to have some locations set by hand, while having other regenerate, then you should create two physics's, one with the model and one for the constant values. If you're thinking about a phase, then I'm not sure we have a way to do this, though there is nothing stopping you from putting phase properties on a physics object, so you could use the above mentioned approaches.

I was thinking to maybe avoid the two-physics solution, for convenience. For example, maybe you want to temporarily "deactivate" some pores by setting the corresponding conductance values to a small number, without properly creating two geometries/physics.

**Comment by jgostick** [comment]
This issue of partially addressed by the new @domain syntax.  You could assign hand calculated values to some locations and have a model generating values to the others.  I think we can safely close this issue now, since the ability to do this is now present.
