### ISSUE TITLE
Bug in charge_conservation in generic_source_term model file

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#1686]
A charge conservation source term is applied to potential algorithm. For the electroneutrality case there is a problem with the source term always being zero. Check line number 81 in file [here](https://github.com/PMEAL/OpenPNM/blob/dev/openpnm/models/physics/generic_source_term.py)

The problem comes from how phase['pore.valence.'+e.settings['ion']] is multiplied. Element-wise multiplication will fix this issue. I have done my own hand calculation to validate this approach to myself and think it is right.

**Comment by mkaguer** [comment]
Here is my script where I was getting the error. print(phys['pore.charge_conservation.S2']) and you will notice that you always get zeros but if you do a hand calculation for the charge conservation source term you see it should not be zero!

`# -*- coding: utf-8 -*-
"""

Small three pore network for testing hand calaculations

Date: October 7, 2020
Created by: Mike McKague

"""

import openpnm as op
from openpnm.phases import mixtures
import cdi_models as cdi
import numpy as np
ws = op.Workspace()
proj = ws.new_project()

np.random.seed(0)

[Npx, Npy, Npz] = [3, 1, 1]
spacing = 1e-4
net = op.network.Cubic(shape=[Npx, Npy, Npz], spacing=spacing)

Ps = net.pores(labels='all')
Ts = net.throats(labels='all')

geo = op.geometry.StickAndBall(network=net, pores=Ps, throats=Ts)

sw = mixtures.SalineWater(network=net)
# Retrieve handles to each species for use below
Na = sw.components['Na_' + sw.name]
Cl = sw.components['Cl_' + sw.name]
H2O = sw.components['H2O_' + sw.name]

# physics
phys = op.physics.GenericPhysics(network=net, phase=sw, geometry=geo)

# stokes flow
flow = op.models.physics.hydraulic_conductance.hagen_poiseuille
phys.add_model(propname='throat.hydraulic_conductance',
               pore_viscosity='pore.viscosity',
               throat_viscosity='throat.viscosity',
               model=flow, regen_mode='normal')

current = op.models.physics.ionic_conductance.electroneutrality
phys.add_model(propname='throat.ionic_conductance', ions=[Na.name, Cl.name],
               model=current, regen_mode='normal')

dif_Na = op.models.physics.diffusive_conductance.ordinary_diffusion
phys.add_model(propname='throat.diffusive_conductance.' + Na.name,
               pore_diffusivity='pore.diffusivity.' + Na.name,
               throat_diffusivity='throat.diffusivity.' + Na.name,
               model=dif_Na, regen_mode='normal')

dif_Cl = op.models.physics.diffusive_conductance.ordinary_diffusion
phys.add_model(propname='throat.diffusive_conductance.' + Cl.name,
               pore_diffusivity='pore.diffusivity.' + Cl.name,
               throat_diffusivity='throat.diffusivity.' + Cl.name,
               model=dif_Cl, regen_mode='normal')

scheme = 'powerlaw'
ad_dif_mig_Na = op.models.physics.ad_dif_mig_conductance.ad_dif_mig
phys.add_model(propname='throat.ad_dif_mig_conductance.' + Na.name,
               pore_pressure='pore.pressure', model=ad_dif_mig_Na,
               ion=Na.name, s_scheme=scheme)

ad_dif_mig_Cl = op.models.physics.ad_dif_mig_conductance.ad_dif_mig
phys.add_model(propname='throat.ad_dif_mig_conductance.' + Cl.name,
               pore_pressure='pore.pressure', model=ad_dif_mig_Cl,
               ion=Cl.name, s_scheme=scheme)

# settings for algorithms
setts1 = {'solver_max_iter': 5, 'solver_tol': 1e-08, 'solver_rtol': 1e-08,
          'nlin_max_iter': 10, 'cache_A': False, 'cache_b': False, 'ion': Na.name}
setts2 = {'g_tol': 1e-4, 'g_max_iter': 4, 't_output': 5000, 't_step': 500,
          't_final': 20000, 't_scheme': 'implicit'}

# algorithms
sf = op.algorithms.StokesFlow(network=net, phase=sw, settings=setts1)
sf.set_value_BC(pores=net.pores('left'), values=10)
sf.set_value_BC(pores=net.pores('right'), values=0)
sf.run()
sw.update(sf.results())

p = op.algorithms.TransientIonicConduction(network=net, phase=sw,
                                           settings=setts1)
p.set_value_BC(pores=net.pores('left'), values=1.0)
p.set_value_BC(pores=net.pores('right'), values=0.0)
p.settings['charge_conservation'] = 'electroneutrality'

eA = op.algorithms.TransientNernstPlanck(network=net, phase=sw, ion=Na.name,
                                         settings=setts1)
eA.set_value_BC(pores=net.pores('left'), values=20)
eA.set_value_BC(pores=net.pores('right'), values=10)

eB = op.algorithms.TransientNernstPlanck(network=net, phase=sw, ion=Cl.name,
                                         settings=setts1)
eB.set_value_BC(pores=net.pores('left'), values=20)
eB.set_value_BC(pores=net.pores('right'), values=10)

pnp = op.algorithms.TransientNernstPlanckMultiphysicsSolver(network=net,
                                                            phase=sw)
pnp.setup(potential_field=p.name, ions=[eA.name, eB.name])

pnp.settings['t_initial'] = 0
pnp.settings['t_final'] = 1
pnp.settings['t_step'] = 0.1

eA.set_IC(values=0)
eB.set_IC(values=0)
p.set_IC(values=0)

pnp.run()

sw.update(sf.results())
sw.update(p.results())
sw.update(eA.results())
sw.update(eB.results())
`

**Comment by ma-sadeghi** [comment]
@magnaou Can you please take a look?

**Comment by jgostick** [comment]
closed by #1803
