### ISSUE TITLE
Object names must be unique within a project

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1687]
Currently, this is not enforced.

**Comment by jgostick** [comment]
If this is not enforced, then I must've screwed something up, because it's definitely supposed to be.

**Comment by ma-sadeghi** [comment]
> If this is not enforced, then I must've screwed something up, because it's definitely supposed to be.

@jgostick Then better double check, since I think this is my first time touching `Base.py`, it's very likely that I might have missed something. I also made a PR #1689
