### ISSUE TITLE
Why is there a conduit_lengths model in the misc.py file?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1696]
According to codecov, this does not get called, so can be deleted probably?

**Comment by ma-sadeghi** [comment]
Could it be for for `Voronoi` maybe?

**Comment by jgostick** [comment]
we should delete it and see what breaks.

**Comment by Ni2M** [comment]
I didn't find any conduit_length in misc.py file. Perhaps this issue has been addressed?

**Comment by jgostick** [comment]
It seems this has been removed, so let's close it
