### ISSUE TITLE
Unexpected results in multiphase air diffusvity/permeability calculations when using "strict" conduit conductance. 

### ISSUE THREAD

**Issue by taylrcawte** [PMEAL/OpenPNM#1698]
**Background**
I am running ordinary percolation on an extracted network and calculating the relative diffusivity and permeability. The script can be found at the below gist:

https://gist.github.com/taylrcawte/1c61d80e640a649d19f5422a7b92da9c

**Question**
When using mode='strict' for the air physics multiphase conduit conductance (both hydraulic and diffusive) the relative transport drops essentially to 0 (for both diffusivity and permeability) even though the network is only about 20% saturated with water. This is unexpected as i would only think that the permeability/diffusivity would go to 0 near saturation. Choosing mode='medium' for the the air physics multiphase conduit conductances avoids the issue, but i'm confused why 'strict' cannot be used, i would prefer to use "strict" as this method is more conservative. 

The unexpected behaviour is illustrated in the "Code Snippets" section below, the first set of images illustrate what i believe is unexpected behaviour while the second set show behaviour that i believe is more physical. 

**Some additional information to note:**
1. This behaviour does not arise when boundary pores are stored on the same geometry object as the internal pores. This issue arose when i was trying to deal with boundary pores, by using the boundary pores generated by the SNOW algorithm (refer to Gist above) strict can be used as the multiphase conductance, however, during my investigation i found that SNOW was adding too many boundary pores and opted for a more defined method of adding boundary pores, see issue #1425 and #1668. So it seems that having separate physics models may be contributing to the issue... 

2.  This issue seems only to be impacting the air transport properties, when running permeability/diffusivity of water using either strict or medium the results are essentially the same. 

3. A cursory investigation suggests that pore occupancy is not really impacted by the mode. For example at the 15th step in the ordinary percolation both strict and and medium yield the same number of occupied pores (occupied by air), and this remains true for mostly all steps in percolation, with the exception of a small difference of 1 or 2 pores here or there. 

**Code Snippets**

Using strict yields the below multiphase dif/perm. 
```
phys_air.add_model(model=pm.multiphase.conduit_conductance,
                           propname='throat.conduit_hydraulic_conductance',
                           throat_conductance='throat.hydraulic_conductance',
                           mode='strict')
phys_water.add_model(model=pm.multiphase.conduit_conductance,
                             propname='throat.conduit_hydraulic_conductance',
                             throat_conductance='throat.hydraulic_conductance',
                             mode='strict)
phys_air.add_model(model=pm.multiphase.conduit_conductance,
                           propname='throat.conduit_diffusive_conductance',
                           throat_conductance='throat.diffusive_conductance',
                           mode='strict')
 phys_water.add_model(model=pm.multiphase.conduit_conductance,
                             propname='throat.conduit_diffusive_conductance',
                             throat_conductance='throat.diffusive_conductance',
                             mode='strict')

# boundary physics
phys_air_b.add_model(model=pm.multiphase.conduit_conductance,
                             propname='throat.conduit_hydraulic_conductance',
                             throat_conductance='throat.hydraulic_conductance',
                             mode='strict')
phys_water_b.add_model(model=pm.multiphase.conduit_conductance,
                               propname='throat.conduit_hydraulic_conductance',
                               throat_conductance='throat.hydraulic_conductance',
                               mode='strict')
phys_air_b.add_model(model=pm.multiphase.conduit_conductance,
                             propname='throat.conduit_diffusive_conductance',
                             throat_conductance='throat.diffusive_conductance',
                             mode='strict')
phys_water_b.add_model(model=pm.multiphase.conduit_conductance,
                               propname='throat.conduit_diffusive_conductance',
                               throat_conductance='throat.diffusive_conductance',
                               mode='strict')
```
![image](https://user-images.githubusercontent.com/65000690/96000659-21d27c80-0e05-11eb-94e7-3e61093f02aa.png)
![image](https://user-images.githubusercontent.com/65000690/96000684-2a2ab780-0e05-11eb-9fe1-938824a5478f.png)

Using medium for air yields the below dif/perm. 

```
phys_air.add_model(model=pm.multiphase.conduit_conductance,
                           propname='throat.conduit_hydraulic_conductance',
                           throat_conductance='throat.hydraulic_conductance',
                           mode='medium')
phys_water.add_model(model=pm.multiphase.conduit_conductance,
                             propname='throat.conduit_hydraulic_conductance',
                             throat_conductance='throat.hydraulic_conductance',
                             mode='strict)
phys_air.add_model(model=pm.multiphase.conduit_conductance,
                           propname='throat.conduit_diffusive_conductance',
                           throat_conductance='throat.diffusive_conductance',
                           mode='medium')
 phys_water.add_model(model=pm.multiphase.conduit_conductance,
                             propname='throat.conduit_diffusive_conductance',
                             throat_conductance='throat.diffusive_conductance',
                             mode='strict')

# boundary physics
phys_air_b.add_model(model=pm.multiphase.conduit_conductance,
                             propname='throat.conduit_hydraulic_conductance',
                             throat_conductance='throat.hydraulic_conductance',
                             mode='medium')
phys_water_b.add_model(model=pm.multiphase.conduit_conductance,
                               propname='throat.conduit_hydraulic_conductance',
                               throat_conductance='throat.hydraulic_conductance',
                               mode='strict')
phys_air_b.add_model(model=pm.multiphase.conduit_conductance,
                             propname='throat.conduit_diffusive_conductance',
                             throat_conductance='throat.diffusive_conductance',
                             mode='medium')
phys_water_b.add_model(model=pm.multiphase.conduit_conductance,
                               propname='throat.conduit_diffusive_conductance',
                               throat_conductance='throat.diffusive_conductance',
                               mode='strict')
```

![image](https://user-images.githubusercontent.com/65000690/96002911-ab834980-0e07-11eb-9ae1-6db2ef8cc9d4.png)
![image](https://user-images.githubusercontent.com/65000690/96002945-b76f0b80-0e07-11eb-9472-89f5d33ca29a.png)

**Comment by jgostick** [comment]
Thanks for the detailed issue...though it's a lot to digest.  I 'think' your problem is that 'strict' mode means that a conduit (1/2 pore + throat + 1/2 pore) is considered blocked to air transport when any of the elements are invaded by water, while 'moderate' means that two elements must be invaded (a pore and a throat, or two pores...I think).  'loose' means that all three must be water filled before the air transport is blocked.  Does that help? I think moderate is a fine mode and that strict is too strict.

**Comment by taylrcawte** [comment]
Yes! This clears up a lot. We were just concerned that the difference between strict and moderate would greatly impact the calculated relative transport. Thanks for the quick response, I'll close the issue now!

**Comment by jgostick** [comment]
I will also add that strict plays havoc when transport and percolation occur from the same face, since the percolation fills all the boundary pores by default, the all transport ceases immediately.

**Comment by taylrcawte** [comment]
This is the exact problem i think we were having, looking at transport in z direction while percolating from top to bottom face!

**Comment by jgostick** [comment]
Another option is the use the boundary pores for the percolation simulation, but then use the first layer of internal pores for the transport simulation.

**Comment by DMaxJ** [comment]
Here is a comment after looking at the github gist @taylrcawte : 
`line 68 boun['throat.diameter'] = max(pn['throat.diameter'])`
would lead to very different calculation of relative permeability if one uses 'strict' mode for conduit conductance. Using a throat diameter model to estimated the diameter from the nearest pore would produce more realistic results when one uses boundary pores for percolation and first layer for transport as mentioned by @jgostick  . I had similar issues with boundary pores before.
