### ISSUE TITLE
Should I be using set_outflow_BC for TransientFickianDiffusion simulation?

### ISSUE THREAD

**Issue by p-thomson** [PMEAL/OpenPNM#1699]
I would like to run the Transient Fickian Diffusion simulation through my PNM imposing 100% concentration at the inlet pores and zero gradient at the outlet pores. I think I should be using the set_outflow_BC condition to achieve this?  

Thanks for your help,

Paul

**Comment by jgostick** [comment]
When you say 0 gradient, you presumably mean no flux?  This happens automatically in openpnm if you don't assign any BCs, so you just want to set the ICs everywhere, and the value BCs on the inlet pores, and you'll be good to do.  

FYI, we have a ``set_rate_BC``, which is analogous to flux BCs, but the 'rate' out of pores on the surface of a domain is automatically 0 from the mass balances, so there is no need to specify this explicitly.

**Comment by p-thomson** [comment]
Ah yes, thank you. As you have described - assigning value BCs on the inlet pores and leaving the outlet pores without BCs works for me. In fact I realised after that the simulation results I obtained were as expected - there was an error in my own work when extracting the data from the results. Anyway, thank you for the information, it is good to know.
Cheers, Paul
