### ISSUE TITLE
How to export the invasion sequence to a vtk file

### ISSUE THREAD

**Issue by DMaxJ** [PMEAL/OpenPNM#1704]
I need to visualize the invasion sequence of a percolation algorithm. Somehow, I am not able to get it in the VTK output using the `proj.export_data()` function. Maybe I have missed some detail there. Could you please help?

**Comment by DMaxJ** [comment]
I must have been stupid. Please ignore

**Comment by jgostick** [comment]
So, all good?  We should probably have more tutorials/examples on using paraview, but we're kinda having enough trouble making tutorials for openpnm, don't want to make too much work for ourselves.  Basically, you need to use the threshold on the 'pore.invasion_sequence'.

**Comment by DMaxJ** [comment]
I did it before. Actually I found that the sequence data was exported by the function. I was looking at the wrong file and wondering why the data was not exported. Sorry for the trouble.
