### ISSUE TITLE
Can't load a saved project using workspace with imported geometry and boundary geometry  

### ISSUE THREAD

**Issue by taylrcawte** [PMEAL/OpenPNM#1707]
**Bug Description**
Cannot load a saved pnm file that uses imported geometry class and generic geometry (for boundary pores) class, throws KeyError: 'pore.all'. The same error is not thrown if using a cubic geometry (instead of imported) with boundary geometry, or just imported geometry (see **additional context**). 

**To Reproduce Error**
```
im = psp.generators.cylinders(shape=[100, 100, 100], radius=2, ncylinders=100)
ws = op.Workspace()
ws.clear()
proj = ws.new_project(name='proj1')

net = psp.networks.snow(im, boundary_faces=[None])
pn = op.network.GenericNetwork(project=proj, name='network')
pn.update(net)

geom = op.geometry.Imported(network=pn, name='geometry_1')

x, y, z = pn['pore.coords'].T

for pore in pn.pores('all'):
    if pn['pore.diameter'][pore] / 2 >= (max(z) - z[pore]):
        pn.set_label(label='top_face', pores=[pore])
    elif pn['pore.diameter'][pore] / 2 >= (z[pore] - min(z)):
        pn.set_label(label='bottom_face', pores=[pore])
    else:
        pass

Ps_top = pn.pores('top_face')
op.topotools.add_boundary_pores(network=pn, pores=Ps_top, offset=[0, 0, 2], apply_label='top_boundary')

# assign boundary geometry and add properties
boun = op.geometry.GenericGeometry(project=proj, pores=pn.pores('*boundary'), throats=pn.find_neighbor_throats(pores=pn.pores('*boundary')), name='boundary_1')

ws.save_project(proj, filename='test10.pnm')
ws.clear()
ws.load_project('test10.pnm')
```

**Expected behavior**
Expected to be able to load pnm file in last line of code but throws below error

**Screenshots**
The below error is thrown 
![image](https://user-images.githubusercontent.com/65000690/96370790-09c46b00-112d-11eb-8cea-d28ac366241d.png)

**Additional context**
By using cubic network and generic geometry instead of imported geometry no error is thrown. 
```
ws = op.Workspace()
ws.clear()
proj = ws.new_project(name='proj1')

pn = op.network.Cubic(shape=[10, 10, 10])
geom = op.geometry.GenericGeometry(network=pn, name='geom1')

Ps_top = pn.pores('top')
op.topotools.add_boundary_pores(network=pn, pores=Ps_top, offset=[0, 0, 2],
                                apply_label='top_boundary')
# assign boundary geometry and add properties
boun = op.geometry.GenericGeometry(project=proj, pores=pn.pores('*boundary'),
                                   throats=pn.find_neighbor_throats(pores=pn.pores('*boundary')),
                                   name='boundary_1')
ws.save_project(proj, filename='test10.pnm')
ws.clear()
ws.load_project('test10.pnm')
```
By only using imported geometry the error is not observed. 
``` 
im = psp.generators.cylinders(shape=[100, 100, 100], radius=2, ncylinders=100)
#
ws = op.Workspace()
ws.clear()
proj = ws.new_project(name='proj1')
#
net = psp.networks.snow(im, boundary_faces=[None])
#
pn = op.network.GenericNetwork(project=proj, name='network')
pn.update(net)

geom = op.geometry.Imported(network=pn, name='geometry_1')

# identify bottom and top faces
x, y, z = pn['pore.coords'].T
for pore in pn.pores('all'):
    if pn['pore.diameter'][pore] / 2 >= (max(z) - z[pore]):
        pn.set_label(label='top_face', pores=[pore])
    elif pn['pore.diameter'][pore] / 2 >= (z[pore] - min(z)):
        pn.set_label(label='bottom_face', pores=[pore])
    else:
        pass

ws.save_project(proj, filename='test10.pnm')
ws.clear()
ws.load_project('test10.pnm')
```

**Comment by ma-sadeghi** [comment]
@taylrcawte Can you also post the exact OpenPNM version you're using?

**Comment by taylrcawte** [comment]
@ma-sadeghi OpenPNM v. 2.4.2

**Comment by ma-sadeghi** [comment]
@taylrcawte Can you upgrade to 2.5.1 (the most recent version on conda/pip) and try again?

Btw, it'd be best to use conda to install OpenPNM, since we recently added a dependency (PARDISO solver) that's not available on pip. Although you could still install OpenPNM using pip but you need to manually install the dependency via `conda install -c conda-forge pardiso4py`.

**Comment by jgostick** [comment]
In our latest dev version (not yet released to main) we have an entirely new file format for openpnm, called PNM.  This format does not use the pickle module.  The pickle module is problematic since it requires that you open your saved files with exactly the same version of openpnm as you saved them with.  The new format does not have this limitation.  We will be releasing new version with this new feature, in the next few weeks.

**Comment by taylrcawte** [comment]
@ma-sadeghi installing openpnm from the command line with conda did not work so i used pip and installed the dependency with the provided command. It did not solve the issue detailed above; openpnm.__version__ = '2.5.1'. 

@jgostick that is good to know; will the file formats be backwards compatible? i.e. will networks saved on versions < 2.5.1 be able to be opened using the methods presented in the newest openpnm version?

**Comment by taylrcawte** [comment]
I realize this isn't the biggest issue, but wanted to bring it to your attention none the less. I've found 2 solutions that work for me: 

1. remove all pores associated with boundary geometry prior to exporting the network, these can be added back in the event that i need to review the network/re-run simulations. 

2. pickle the generated porespy image (3D "im" object) so that it can be re-extracted using the same method at a later date

While not exactly solving the issue it does for my purposes. Feel free to close the issue.

**Comment by ma-sadeghi** [comment]
> @ma-sadeghi installing openpnm from the command line with conda did not work so i used pip and installed the dependency with the provided command. It did not solve the issue detailed above; openpnm.**version** = '2.5.1'.

Could you please provide the error message? (I mean the `conda` error)

**Comment by taylrcawte** [comment]
It couldn't find the package, although trying it again i just had to specify the channel; i.e. 
```conda install openpnm``` did not work but ```conda install -c conda-forge openpnm``` did

![image](https://user-images.githubusercontent.com/65000690/96386317-04384680-1168-11eb-84e1-2224a9c4ca58.png)

**Comment by ma-sadeghi** [comment]
That's right, `openpnm` is only on `conda-forge`. The default channels are maintained by Anaconda, so there's no control over which package gets through. I think every package on the default channels could also be found on `conda-forge`.

**Comment by taylrcawte** [comment]
makes sense, okay since you guys are dealing with this issue in an upcoming release i will close the issue.
