### ISSUE TITLE
Assume all pores and throats if no pores/throats arg is passed to geometry

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1708]
I know we removed this feature because of the issue we had with our new file format. But, since that's resolved, I think we can put it back, right? @jgostick

**Comment by jgostick** [comment]
Hmmm, worth looking into...I 'think' it is still a requirement though.  I prefer the explicit approach to be honest.

**Comment by jgostick** [comment]
I have actively prevented this behavior in a recent PR (#1705).  It think it's overall much safer to make things explicit...python style: explicit is better than implicit.
