### ISSUE TITLE
Change default solver to scipy's spsolve if pypardiso is not found

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1710]
Currently, the default solver is `pypardiso`, which relies on MKL, and installing MKL using `pip` seems to be not so straightforward.

**Comment by TomTranter** [comment]
where are you getting pypardiso from? it doesn't seem well supported

**Comment by ma-sadeghi** [comment]
@TomTranter It's originally from this repo: https://github.com/haasad/PyPardisoProject. The package was not on `conda-forge`, and the author has been inactive on GitHub for almost 2 years, so I had to fork it and push the fork to `conda-forge` under a different name, `pardiso4py`.

**Comment by aaornsc** [comment]
> @TomTranter It's originally from this repo: https://github.com/haasad/PyPardisoProject. The package was not on `conda-forge`, and the author has been inactive on GitHub for almost 2 years, so I had to fork it and push the fork to `conda-forge` under a different name, `pardiso4py`.

Hello @ma-sadeghi, i hope you are doing great,  i'm currently having the next error message that is related to this issue :

> Traceback (most recent call last):
  File "perm_OPNM.py", line 103, in <module>
    flow.run()
  File "/home/aaron/anaconda3/lib/python3.7/site-packages/openpnm/algorithms/ReactiveTransport.py", line 158, in run
    x = self._run_reactive(x0)
  File "/home/aaron/anaconda3/lib/python3.7/site-packages/openpnm/algorithms/ReactiveTransport.py", line 352, in _run_reactive
    self[quantity] = x = self._solve(x0=x) * w + x * (1 - w)
  File "/home/aaron/anaconda3/lib/python3.7/site-packages/openpnm/algorithms/GenericTransport.py", line 591, in _solve
    x = solver(A, b, atol=atol, rtol=rtol, max_it=max_it, x0=x0)
  File "/home/aaron/anaconda3/lib/python3.7/site-packages/openpnm/algorithms/GenericTransport.py", line 649, in solver
    import pypardiso
ModuleNotFoundError: No module named 'pypardiso'

I don't understand right away what the problem with the package is, do i have to run my scripts from github repository? or how can i solve the error?
I'm using version 2.5.1 of openpnm on my laptop.

**Comment by TomTranter** [comment]
You need to install pypardiso from conda-forge https://anaconda.org/conda-forge/pardiso4py
