### ISSUE TITLE
size_by argument in plot_coordinates doesn't do anything

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1714]

**Comment by jgostick** [comment]
I think you have to also specify 'markersize=50' or something large like that just to see the effect.  We should probably set the marker size to something very large by default, but I don't know if this is universal across platforms.

**Comment by ma-sadeghi** [comment]
## `net["pore diameter"] = 1`
```python
import openpnm as op
import matplotlib.pyplot as plt


net = op.network.Cubic(shape=[5, 1, 1])
net["pore.diameter"] = 1.0

fig, ax = plt.subplots()
op.topotools.plot_coordinates(net, fig=fig, markersize=50, size_by=net["pore.diameter"])
op.topotools.plot_connections(net, fig=fig)
```
![image](https://user-images.githubusercontent.com/14086031/96756368-01c13100-13a2-11eb-949d-e8b182ec0ebf.png)
## `net["pore diameter"] = 1000`
```python
import openpnm as op
import matplotlib.pyplot as plt


net = op.network.Cubic(shape=[5, 1, 1])
net["pore.diameter"] = 1000.0

fig, ax = plt.subplots()
op.topotools.plot_coordinates(net, fig=fig, markersize=50, size_by=net["pore.diameter"])
op.topotools.plot_connections(net, fig=fig)
```
![image](https://user-images.githubusercontent.com/14086031/96756358-fc63e680-13a1-11eb-84ad-6ede14ae75d5.png)

**Comment by jgostick** [comment]
this actually works just fine, but you need to use much larger marker size, like 1000

**Comment by ma-sadeghi** [comment]
You're right. Shouldn't we change the default marker size then?
