### ISSUE TITLE
Unify Mixtures and Multiphases

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1719]

**Comment by jgostick** [comment]
At the moment, Multiphase assumes on 1 component is dissolving into the liquid.  If we have a "mixture" for the gas, then there would be N things dissolving, each with their own Henry's law coefficients.  Can we update the multiphase to check each species in the gas phase?

**Comment by ma-sadeghi** [comment]
@jgostick Did we do anything about this?
