### ISSUE TITLE
start with open pnm

### ISSUE THREAD

**Issue by kooti1992** [PMEAL/OpenPNM#1722]
hi , how are you
I'm so happy to Learn about this application
I'm working about a Project that related to pore network modeling , that is simulation  a membrane its can separate  between multiple gases such as N2 from air , the membrane is hollow fiber .
1) How I can start with open pnm & simulate a cylindrical  shape ?
I have low information about working with this apps, Matlab also has this ability for pnm , but I want to Learn about this application.
2) where I can Run require codes ?  Spider of Python can do pnm for this project ?
Thank you , Good luck

```

**Comment by jgostick** [comment]
Hi @kooti1992 
* Install the 'anaconda' distribution to get python and the "scipy-stack" pre installed.
* Assuming you're on windows, open the windows menu/anaconda/anaconda prompt
* Install openpnm with ``conda install -c conda-forge openpnm``
* Open spyder (from  windows menu/anaconda/spyder)
* Download this example script we have [here](https://github.com/PMEAL/OpenPNM/blob/dev/example.py) and run it
* To learn more, check out the tutorials and examples [here](https://github.com/PMEAL/OpenPNM/tree/dev/examples)
