### ISSUE TITLE
Extracted networks - Modification of geometrical properties

### ISSUE THREAD

**Issue by Eravalord** [PMEAL/OpenPNM#1733]
Hello everyone,
I am facing a problem right now, as I have an extracted pore network, and I would like to do simple pore diameter modifications on it, however if I change pore diameters, the throat conduit length, throat diameter, etc. should change as well based on certain requirements. Probably, if these values are linked together by the assignment of corresponding geometry models, my anticipation is that my problem could be solved. Unfortunately, I am not able to add geometry models as properties are already defined in extracted networks. Is there a tool for extracted networks that provides dynamical changability of (for instance) throats lengths/diameters as pore diameters are modified?

Thank you for the help in advance! :)

**Comment by jgostick** [comment]
You can add "models" that have different names.  So you can take the 'throat.length' from the extracted network, and rename it to 'throat.length_extracted', (i.e. ``pn['throat.diameter_extracted'] = pn.pop('throat.diameter')``), THEN you can add your model.  So if you create a new geometry that applies to all pores, you can do:

``` python
pn['throat.diameter_extracted'] = pn.pop('throat.diameter')
geo = op.geometry.GenericGeometry(network=pn, pores=pn.Np, throats=pn.Nt)
geo.add_model(propname='throat.diameter',
              model=op.models.misc.from_neighbor_pores, mode='min')
```

**Comment by Eravalord** [comment]
It works now, thank you very much! :)
