### ISSUE TITLE
Add Initial guess argument to run method in TransientNernstPlanck similar to run in ReactiveTransport

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#1737]
Here is a link to [line 145](https://github.com/PMEAL/OpenPNM/blob/ceeace0c753a492dc61f6a4749cd81d3d4a7089e/openpnm/algorithms/ReactiveTransport.py#L145) of ReactiveTransport where the run method contains argument for initial guess. I am wondering if we could add this feature to TransientNernstPlanck or any other algorithms.

**Comment by jgostick** [comment]
I'm thinking that 'initial guess' will be something that is handled by the new Solver class, so this is not relevant any more.
