### ISSUE TITLE
Pass initial condition to phase where it is used to update physics models prior to alg.run()

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#1738]
It would help if alg.set_IC() passes initial conditions to phase object as 'pore.quantity'. Then physics models can be rerun so that upon running algorithm all physics models start at correct initial condition. 

This problem came up for me when running a nernst planck simulation where ionic_conductance depends on pore.concentration but setting initial condition did not change starting value for ionic_conductance. The work around was setting phase['pore.concentration'] = initial_condition prior to adding ionic conductance model.

This issue is related to issue #1478 in how initial guess could be written to phase object. Should initial guess be initial condition?

**Comment by jgostick** [comment]
In my latest version I got the ICs and value BCs to both fill the 'pore.ic' array as well as the 'pore.quantity' array.  There is one problem though...the crank-nicolson scheme has different values.  There are hard coded values in the test, and now they've changed, so I'm guess that the previous version was not including BCs in the initial time step, and they didn't get added until the second time step.  This would corroborate some results I've seen lately.
