### ISSUE TITLE
Caching fails if "conductance" dictionary key is changed, same for discretization scheme in AdvectionDiffusion

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1741]
```python
ad = op.algorithms.AdvectionDiffusion(network=net, phase=phase)
# Do some stuff
ad.settings["conductance"] = "throat.foo"
ad.run()  # this returns the old results since A was cached
# Now let's change the discretization scheme
ad.settings["s_scheme"] = "upwind"
ad.run()  # this also returns the old results
```

**Comment by ma-sadeghi** [comment]
The first fix that comes to mind is to set `cache_A` to `False` if conductance keyword is changed, same goes for the discretization scheme in `AdvectionDiffusion`, but maybe there's a more general approach.

**Comment by jgostick** [comment]
This can be universally solved by deleting ``self._pure_A`` and ``self._b``, etc everytime someone updates ANY setting.  Then the algorithm will automatically update itself.  This would be done by adding some checks to the __setitem__ method.  

Alternatively, we can be more selective an only delete them if certain settings are changed.

**Comment by jgostick** [comment]
Firstly , this is no longer relevant since s_scheme is gone...but there is a bigger issue which will be discussed in its own issue thread: #2077
