### ISSUE TITLE
pip install openpnm in new environment throws no module named numpy error.

### ISSUE THREAD

**Issue by Zohaib-Atiq** [PMEAL/OpenPNM#1748]
When we create new environment which don't have `numpy` in it `pip install openpnm` throws an error although `numpy` is in `requirements.txt` 

![error](https://user-images.githubusercontent.com/30351879/98615338-57fe0180-22c8-11eb-9316-e263e88b894f.PNG)

**Comment by jgostick** [comment]
It is not recommended under any circumstances to pip install numpy, so if you're doing this it will almost certainly end in tears.  Maybe our setup.py could throw a warning if this is found to be the case somehow.  We recommend using conda install, of just use an env with numpy/scipy/etc already installed

**Comment by ma-sadeghi** [comment]
It's interesting though, based on the screenshot, it's not even trying to install `numpy`, which is strange.

**Comment by jgostick** [comment]
There is a package somewhere upstream that specifies numpy < 3.9.  I tried adding 3.9 to the test suite and got this error.  Zohaib got things working when he put numpy 3.8 in the env.  I don't think this is our bug and I'm sure will be fixed soon.
