### ISSUE TITLE
Adding miscellaneous model drops error if prop_name defined in dev version

### ISSUE THREAD

**Issue by Eravalord** [PMEAL/OpenPNM#1749]
Hello everyone, 
I have encountered with the above-mentioned problem in the dev version, as I downloaded the latest update. 

I receive this message:
![image](https://user-images.githubusercontent.com/71832974/98671514-ac4ec300-2354-11eb-8c0b-bd82820d2958.png)
in case of calling the following geometry model:
`geo[i].add_model(propname='throat.max_size',
                         model=op.models.misc.from_neighbor_pores,
                         mode='min',
                         pore_prop='pore.diameter')`
I am wondering how the pore_prop is expressed in the newest version. 
Thank you for your help in advance!

**Comment by ma-sadeghi** [comment]
I think it's been changed to just `prop` or `propname` maybe?

**Comment by jgostick** [comment]
Yes, just change `pore_prop` to `prop`.  We have been a bit aggressive with pushing 'breaking' changes lately.  It's too difficult to support so many backwards compatibility related features.
