### ISSUE TITLE
Unreasonably high estimate of permeability from an extracted network

### ISSUE THREAD

**Issue by muntahi398** [PMEAL/OpenPNM#1757]
Dear good people,
I was trying to estimate permeability of a porous structure shown below. Images are from micro CT volumes and voxel resolution of 25micron. But following the steps in Barea in [Link](https://github.com/PMEAL/OpenPNM/blob/dev/examples/notebooks/networks/extraction/predicting_effective_permeability_of_berea.ipynb) I could not get a desirable result. With water column permeability measurement, I get a value around 0.3-0.6 Dercy. But above approach calculates it  more than 300 dercy. 

Am I making some mistakes or my structure is not suitable for this approach? Would you suggest any other modification for getting the results right?

Thank you in advance for your suggestion.

>resolution = 25.00e-6
net = ps.networks.snow(im=im, voxel_size=resolution)
proj = op.Project()
pn = op.network.GenericNetwork(name="baustein", project=proj)
pn.update(net) 
mod = op.models.geometry.throat_endpoints.spherical_pores
pn.add_model(propname='throat.endpoints', model=mod)
mod = op.models.geometry.throat_length.conduit_lengths
pn.add_model(propname='throat.conduit_lengths', model=mod)
mod = op.models.geometry.pore_area.sphere
pn.add_model(propname='pore.area', model=mod)
mod = op.models.geometry.throat_volume.cylinder ##added
pn.add_model(propname='throat.volume', model=mod)  ### added
geo = op.geometry.GenericGeometry(network=pn, pores=pn.Ps, throats=pn.Ts)
air = op.phases.Air(network=pn)
phys_air = op.physics.Standard(network=pn, phase=air, geometry=geo)
perm = op.algorithms.StokesFlow(network=pn, project=proj)
perm.setup(phase=air)
perm.set_value_BC(pores=pn.pores('top'), values=0)
perm.set_value_BC(pores=pn.pores('bottom'), values=5001325)
perm.run()
air.update(perm.results())
Q = perm.rate(pores=pn.pores('bottom'), mode='group')
A = (im.shape[0] * im.shape[1]) * resolution**2
L = im.shape[2] * resolution
mu = air['pore.viscosity'].max()
delta_P = 5001325 - 0
K = Q * L * mu / (A * delta_P)
print('The value of K is:', K/0.98e-12*1000, 'mD')`

[share_struc.zip](https://github.com/PMEAL/OpenPNM/files/5531393/share_struc.zip)
![image](https://user-images.githubusercontent.com/28182093/98957545-96323580-2501-11eb-8b06-db06ae541b0b.png)

In attached zip (share_struc.zip) file small volume of porous structure added for checking.

**Comment by jgostick** [comment]
Hi @muntahi398 ... I think there is a problem with your experimental value.  Based on the stated voxel resolution (25 um per voxel) and the images you have provided, I find the particles in your image are about 1 mm diameter...is this correct?  Because they are perfectly spherical, you can directly apply the [Carman-Kozeny equation](https://en.wikipedia.org/wiki/Kozeny%E2%80%93Carman_equation).  I found a value of 604 D (using a porosity of 0.356 from the image).  When I run the snow extraction from porespy and the openpnm permeability calculation I get a prediction of 788 D.  This is not as close as I would like, but considering it's done on such as small sample, and the Carmen-Kozeny equation is just a correlation, I think that 20% difference is probably reasonable.

**Comment by jgostick** [comment]
Since you have not checked back, I'm going to close this.  Reopen it if my answer above is not correct.

**Comment by muntahi398** [comment]
@jgostick Sorry for not checking this earlier. Thank you very much for testing my attached CT images and relying on them. You are right about the spherical pores having 1-2mm diameter. But usually, they have low interconnections in between. When I have tested one of the samples, I found water passing through them very slowly. 8mL water passing through a sample of 7mm  diameter and 10.4mm thickness takes around 11 minutes for 1.18m water column. That makes permeability measurement less than 1 Dercy. I am still a bit puzzled about where I made a mistake here. 



--

**Comment by jgostick** [comment]
Hi @muntahi398, I honestly think your experiment is off. The Carman-Kozeny model is bang-on for sphere packs.  Perhaps there are lots of air bubbles in your experiment?  This would block water flow significantly.  Are you able to flow air through a dry column?  This way it's for sure single phase flow.  You could also fill the column with water first, THEN drop the beads in (assuming you're not already doing this?).

**Comment by muntahi398** [comment]
@jgostick Thank you very much for the nice explanation. I will recheck the experiment setup.
