### ISSUE TITLE
Easy to fix bug in electroneutrality conductance model

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#1761]
[Line 568](https://github.com/PMEAL/OpenPNM/blob/6f58dc235a079cfe4cd5101a2234b8eb8f984c14/openpnm/models/physics/ionic_conductance.py#L568) and [line 569](https://github.com/PMEAL/OpenPNM/blob/6f58dc235a079cfe4cd5101a2234b8eb8f984c14/openpnm/models/physics/ionic_conductance.py#L569) of electroneutrality model should read `network.Np` instead of `network.Nt`. This is because it is being indexed by `throat.conns` which contains pore indices not throat indices. Therefore, it may try to index a pore that is outside the range of throat indices and an error is thrown. This bug is simple to fix.

**Comment by jgostick** [comment]
Yes, it looks like you are correct

**Comment by mkaguer** [comment]
Alright, I will fix it then.

**Comment by ma-sadeghi** [comment]
@mkaguer Is this fixed?

**Comment by mkaguer** [comment]
Yes @ma-sadeghi... well I made the change on the dev branch and pushed it to git hub as [commit 031894a](https://github.com/PMEAL/OpenPNM/actions/runs/367139011). Not sure if I should have done it exactly like that but it was such an easy fix that I didn't want to do the whole create a branch and merge back into dev thing.

**Comment by ma-sadeghi** [comment]
@mkaguer Good job. Just one thing: it's always desirable to create a new branch and submit the changes via a pull request, maybe with some exceptions: like when editing docstrings (and not the code) such as updating the README file or maybe updating class docstrings, etc. The reason is that when making even slight changes to the code, something might break.

Anyway, nothing broke after your commit, so it's all good.

**Comment by mkaguer** [comment]
Ok @ma-sadeghi I will keep that in mind. I wasn't sure if it still goes through all the same units tests as a normal PR. Does it?

**Comment by ma-sadeghi** [comment]
@mkaguer You mean when pushing directly to dev? If so, yes, the CI will run whenever we "push" any changes to any branch.

**Comment by mkaguer** [comment]
@ma-sadeghi yea that is what I meant. Thanks!
