### ISSUE TITLE
Should we create an OpenPNM-forum repo for user questions?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1763]
It's easy to take an issue and move it to another, so we could consider creating a new repo, called openpnm-forum or openpnm-helpdesk, or something, and move all user question related issues to that repo?  We could first triage the question to see if it's an actual bug, but most are just questions or confusions about using openpnm.  We could leave all the issues open, so they can be easily browsed, and we could point people there as needed. This should really be done on something like stackoverflow but our project is not big enough to warrant our own channel there. I have considered self hosting something, but this a hassle we don't need.  I think hyjacking the github repo might actually work.  Note:  I have been focusing on keeping the number open issues down to just real ones, so we can focus on what matters.

**Comment by ma-sadeghi** [comment]
We can use Discourse. Julia and a whole bunch of other famous projects (like Paraview) use it. We can apply for their free tier, which they provide for eligible open source projects. I read their FAQ and I think we qualify. Their website says if your issue tracker is being crowded with questions and feature requests, you might be eligible. Anyway, it's worth a try. 

https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/

Using Github is fine, but services like Discourse are much more feature-rich to be used as forums, so I think if we qualify for their free tier, it might be the better alternative.

**Comment by jgostick** [comment]
Ya, I like the idea of a dedicated service that does it properly, but that won't stop people from posting their question here because most tech support type issues look like bugs at first.  If we open a new repo there is the option of transferring issues, so very low friction.  We can discuss it tomorrow morning.

**Comment by ma-sadeghi** [comment]
You're right. Actually, Discourse already takes care of that, they have integration with GitHub issues.

**Comment by jgostick** [comment]
solved by the Discussions feature!
