### ISSUE TITLE
Time varying boundary conditions needed in transient algorithms

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1766]

**Comment by jgostick** [comment]
We need to discuss the best way to do this.  The first option I think of is passing a pandas dataframe with each row being a pore and each column being the time step, with the entry in the array being the value to apply:

pore | 0 | 10 | 20
--- | --- | --- | ---
0 | 1 | 0.5 | 0 
3 | 1 | 0 | 0
11 | 1 | 1 | 1  

This is a bit of a pain to program though, especially if there are a lot of pores and changes.  For instance, how would you do sinusoidal BCs with this?

Another option might be to use pore-scale models, and assign them like source terms to certain pores (i.e. the boundary pores).  The models could be things like sinusoids or heavyside functions.

Clearly we should look into other packages for how they do it.  

Incidentally, this is actually possible with openpnm at present by just running the alg until t_final (i.e. 5 seconds), then setting t_initial to t_final, setting an new t_final (i.e 200 seconds), and putting the current solution (i.e. pore.concentration) as the initial conditions.

**Comment by jgostick** [comment]
At present you can do this:

```
alg.set_IC(alg['pore.concentration'])
alg.settings['t_initial'] = alg.settings['t_final']
alg.settings['t_final'] = alg.settings['t_final'] + 20
```

One option is to add a ``continue`` method to alg:

```
alg.run()  # This ran from 0 to 10 seconds
alg.continue(20)  # This runs from 10 to 30
```

The ``continue`` method will need to look up the current time by looking ``t_final``, then doing the specific steps mentioned above for the user (i.e. adjusting the settings and setting ICs).

**Comment by jgostick** [comment]
This may also be possible using the planned ``callback`` functionality

**Comment by jgostick** [comment]
@ma-sadeghi, is this issue still valid? I seem to remember you saying that the new transient solver approach made this feature unnecessary.  Can you comment on this, or close?

**Comment by ma-sadeghi** [comment]
I've created a prototype of the callback mechanism in PR #2254. Time-varying BCs can be applied using callbacks. In the same PR, you can find an example of setting time-dependent Dirichlet BC.

Probably we need some nice wrappers, like `set_pulse_BC`? Needs some thought...
