### ISSUE TITLE
Some hidden methods on GenericTransport should be on ReactiveTransport

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1786]
I am working on a notebook about class inheritance in the algorithms, and when printing out all the methods have noticed some methods that should maybe be on Reactive:  

```
_get_atol
_get_rtol
_get_residual
_is_converged
```

Are these related to the solving of source terms, variable properties, or just iterative solvers?  If the latter then they're ok, but otherwise they should be moved to ReactiveTransport.

**Comment by ma-sadeghi** [comment]
They're used in `GenericTransport` as well as other subclassed algorithms, which is probably why we put them in `GenericTransport`. I don't think they're specifically related to source terms and variable props.

**Comment by jgostick** [comment]
These are all now on the solver class
