### ISSUE TITLE
Problem with how NernstPlanckMultiphysicsSolver passes settings (e.g. time step) to coupled algorithms

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#1788]
Before running the `TransientNernstPlanckMultiphysicsSolver` I set the time step in settings to 0.01 and believed that this change would automatically change the corresponding settings in charge and mass algorithms. However, the change did not take effect until after the first time step. That is, the first time step was calculated using 0.1 (the default) and then after was mysteriously changed to 0.01 which is what I set. To fix this issue I had to set the time step for mass and charge conservation algorithms as well as for the multiphysics solver before running the solver. 

Note: I was using a multiphysics solver that I made some custom changes in. None of my changes I thought would have caused this error. So I am noting this issue here for now.

**Comment by ma-sadeghi** [comment]
Hey @mkaguer, what's the status on this? Did you find a fix for this issue?

**Comment by mkaguer** [comment]
Hi @ma-sadeghi no I did not find a fix for this. I don't even know yet where the issue or bug is exactly. My way around it at the moment is manually setting the time step of each algorithm as opposed to only settings the time step in multiphysics solver.

**Comment by ma-sadeghi** [comment]
We're going to implement the NernstPlanck algorithm using the yet-to-be-implemented multiphysics solver.
