### ISSUE TITLE
Refactor GenericTransport and subclassed algorithms' run method

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1797]
Currently, each algorithm is overloading the `run` method on `GenericTransport`. A better design would be to have only the `run` method only on `GenericTransport`, which calls `_run_special` at the end. `_run_special` is then overloaded by subclassed algorithms. The reason this is a better design is that we're doing a bunch of checks (`_validate_data_health`, `_validate_settings`) that needs to be called for all algorithms, which is currently hardcoded all over the place.

**Comment by jgostick** [comment]
This is fixed on the new PR
