### ISSUE TITLE
dependency_graph doesn't include properties that are not models

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1823]
I looked into this and I don't think it can be done in a straightforward way. `dependency_graph` is a method of `ModelsDict`. To look for properties that are not models, we need to get a handle to the object containing the models, but `dependency_graph` can only access `obj.models`, which is just a plain dictionary.

@jgostick Can you confirm if this is accurate?

**Comment by jgostick** [comment]
Add this to the mixin:

``` python
    def _find_parent(self):
        for proj in ws.values():
            for obj in proj:
                if obj.models is self:
                    return obj
```
