### ISSUE TITLE
Possible bug in rate method when used w/ throats as argument

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1835]
Currently, calling the `alg.rate` method always returns a positive rate when used for throats. Although this might be the expected behavior when we initially coded it, it doesn't seem right. Here's an example that demonstrates why it's confusing:

Consider an internal pore, i.e., one that's not connected to any inlet/outlet, such as below (numbers in brackets are throat indices):
```
          4
          |
         (3)
          |
1 --(1)-- 2 --(2)-- 3
```
if we call the rate method on pore 2, we get 0, i.e. `alg.rate(pores=2) ~ 0`, which is as expected since it's an internal pore and mass balance requires that the net rate be ~ 0. Now, if we call `alg.rate(throats=[1,2,3])`, I would expect that it be ~ 0 as well, since it's essentially the same thing, we're calling for the net in/out of pore 2, but it returns a positive value equal to summation of absolute values of all throat rates.

@jgostick What do you think?

**Comment by jgostick** [comment]
The problem is that the direction is not clear.  Is the positive direction going from pore i to j where i < j, or do we mean positive is the going from C1 to C2, where C2 < C1?  I think we chose the absolute value because neither options were super clear.

**Comment by ma-sadeghi** [comment]
Yeah, right. The issue is I'm trying to calculate the net rate from one set of pores to another, and I couldn't find a convenient way of doing this. One way is to search `net.conns` for possible connections from `pores1` to `pores2`, note the possible direction mismatch (a pore in `pores2` appears first in `net.conns`), call rate and account for these possible mismatches and return a net rate. I think it'd be handy, but I'm not really sure where in `openpnm` this fits.
