### ISSUE TITLE
Find connecting throats between two sets of pores

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1836]
Given two sets of pores in a network, it'd be handy to have a network on `GenericNetwork` to be able to find all the throats between these two sets.
```python
net.find_connecting_throats(pores1, pores2)
```

**Comment by jgostick** [comment]
What is wrong with the existing ``find_connecting_throat`` method?

**Comment by ma-sadeghi** [comment]
Oh, I didn't know we had such a thing! Thanks!

**Comment by jgostick** [comment]
Just make sure it works for you

**Comment by ma-sadeghi** [comment]
@jgostick For consistency, shouldn't be `find_connecting_throats`? similar to `find_neighbor_throats`

**Comment by jgostick** [comment]
I think I called it that since there is only 1 throat between each pair of pores

**Comment by ma-sadeghi** [comment]
Right, but doesn't it accept two sets of pores as well?

**Comment by jgostick** [comment]
yes, but it only finds the single connecting "throat" for each pair.

**Comment by ma-sadeghi** [comment]
Yes, makes sense.

I just noticed that the order of `P1` and `P2` matters in `find_connecting_throat`. So, let's say `P1 = [1, 2, 3]`, and `P2 = [6, 8, 10]`, and `conns = [[1, 8], [3, 6], [2, 10], [1, 10]]`, calling `find_connecting_throat` on theses sets of pores returns `[None, None, None]`. What I was looking for is some method that returns the throat indices of all connections between the two sets of pores, in this case it should return a 4-long list, `[0, 1, 2, 3]`.

**Comment by ma-sadeghi** [comment]
Here's what I was looking for:

```python
def find_interface_throats(network, P1, P2):
    Ts1 = network.find_neighbor_throats(pores=P1, mode="xor")
    Ts2 = network.find_neighbor_throats(pores=P2, mode="xor")
    return np.intersect1d(Ts1, Ts2)
```

Do you think it's worth adding it to `GenericNetwork`? @jgostick

**Comment by jgostick** [comment]
How about the 'xnor' mode in find_neighbor_throats?

pn.find_neighbor_throats(pores=[0, 1, 2, 5, 6, 7], mode='xnor')

**Comment by ma-sadeghi** [comment]
> How about the 'xnor' mode in find_neighbor_throats?
> 
> pn.find_neighbor_throats(pores=[0, 1, 2, 5, 6, 7], mode='xnor')

That'd also include the throats within P1 and within P2.

Network:

<img src="https://user-images.githubusercontent.com/14086031/106795228-d2b88d80-6627-11eb-8b2c-e78745b622ec.png" width=50%>

Using `find_interface_throats` (`P1 = [1, 6]`, `P2 = [2, 5]`):

<img src="https://user-images.githubusercontent.com/14086031/106795202-c7fdf880-6627-11eb-983d-39070cc18926.png" width=50%>

Using `xnor`:

<img src="https://user-images.githubusercontent.com/14086031/106795150-bd436380-6627-11eb-879f-7f039489eef5.png" width=50%>
