### ISSUE TITLE
Convergence checks in Generic/ReactiveTransport are too aggressive

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1843]
Currently, if convergence checks fail, the program breaks. But, I think we shouldn't do that, or at least be less aggressive. I'll elaborate more in the upcoming meeting. Briefly, for multiphysics problems, it's likely that you don't even want each algorithm to fully converge since the intermediate solutions are not accurate anyway.

**Comment by jgostick** [comment]
* It's not really a bug, more like a missing feature. The 'back and forth' solution of algs is occurring outside of OpenPNM's scope, so it can't really do anything about it.
* This pertains to Mike's multiphysics algorithm, which will orchestrate the interaction between algs.  
* Also, algs should not raise an exception anyway, but return an error code or something.  Perhaps an ``is_converged`` method on each alg that returns 0 or 1 (or some other number indicating the situation).  The user should check that before proceeding.

**Comment by jgostick** [comment]
At present an exception is always thrown, but this should instead only throw an exception if the answer is inf/nan, otherwise maybe just output some logger warning, but let the algorithm proceed.
