### ISSUE TITLE
Should we test the output of examples notebooks?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1884]
Every now and then, we're sprinkling the notebooks with `# NBVAL_IGNORE_OUTPUT`. It makes me wonder (as @jgostick once suggested) that maybe we shouldn't really check the output of examples. As long as they don't fail, it should be good. The only downside is that we lose those "few" notebooks that indeed help us catch inconsistencies (like those related to effective properties, etc.). However, we could also add them as integration tests. What do you guys think?

**Comment by jgostick** [comment]
I just updated an example and wrote # NBVAL_IGNORE_OUTPUT in EVERY SINGLE CELL!  It's ridiculous.  We don't need the notebooks to act as unit tests.  We need to make sure they run, but that is all.  If we can JUST catch the case where a notebook outputs an exception, or doesn't execute all the cells, then I say let's do it.

Also, if we REALLY need the notebook to be correct, then we can add an ``assert something is True``.  This would throw an exception that would get caught by the above mentioned approach.

**Comment by ma-sadeghi** [comment]
100% agreed. Another nuisance is that every now and then, we update one of the main classes (add/remove attributes, etc.) that causes a whole bunch of notebooks to break, just because `print(object)` has produced something slightly different (for instance, when we added `iterative_props`, we had to update many examples).

**Comment by jgostick** [comment]
We should do the same thing we're doing in PoreSpy, just run the book and make sure it completes.

**Comment by ma-sadeghi** [comment]
This has been fixed.
