### ISSUE TITLE
Refactor (overhaul?) GenericTransport

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1889]
There are a few issues that come to mind:

# Unnecessary methods
`GenericTransport` currently has `_get_domain_length`, `_get_domain_area`, `_get_inlets`, `_get_outlets`, and `_calc_eff_prop`. In my opinion, the first 4 are not really the algorithm's business and thus should be removed. The last one, `_calc_eff_prop`, is also a post-processing thing, and might not really belong to the algorithm.

# Solvers should be in their own class
Currently, solvers are defined as part of `GenericTransport`. Apart from the fact that they're not really exclusive to `GenericTransport` and so they should be moved one level up (maybe to `GenericAlgorithm` or a new subclass), I don't think solvers are algorithms business. Maybe they should be a mixin or passed during initialization, e.g., `alg.linear_solver = op.Solvers.PETSc()` (I support the latter).

# Runtime validation checks
Currently, all runtime validation checks (`_validate_settings`, `_validate_geometry_health`, `_validate_topology_health`, and `_validate_data_health`) are inside `GenericTransport`. Again, I don't think they belong to algorithms. Maybe they should be a mixin class?

# Boundary condition setters
`_set_bc` generic method which accepts `bctype` is currently in `GenericTransport`, but I think it could be moved out. Setting value and rate BCs is not really exclusive to transport algorithms (for instance, they can be used in their current form for solid deformation too) and thus I think these can also be moved out to a new subclass of `GenericAlgorithm`.

Applying these changes will potentially shave 400-600 loc off the currently bloated ~1100-loc `GenericTransport`.

**Comment by jgostick** [comment]
This all sounds pretty well thought out and correct.
