### ISSUE TITLE
Regenerate models drops error after structure modification

### ISSUE THREAD

**Issue by Eravalord** [PMEAL/OpenPNM#1890]
Dear all,

I encountered a problem while modifying the structure of a cubic network. The modifcations consist of pore merging, network extension with new pores, establishment of new connections (and correspondingly adding them to a geometry). And it seems everything goes quite well until a certain point, where regenerate_models causes this error:

![image](https://user-images.githubusercontent.com/71832974/112135884-8ffa4700-8bce-11eb-9e4a-b14e5800ea4a.png)

Several regenerate_models were called before successfully, and the method of modifications does not change as the algorithm proceeds.

Do you maybe have any idea what the problem can be? 

Thank you for your help in advance!

**Comment by ma-sadeghi** [comment]
@Eravalord Can you share the shortest possible script that reproduces this bug so we can look into it?

**Comment by jgostick** [comment]
I'm going to close this, but you can let us know if this should still be open @Eravalord
