### ISSUE TITLE
Convenient way to find interconnections between labels

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1905]
Suppose we have two labels in the network: `air` and `water`. It would be handy to support the following API (or something similar) to find the interconnections between these two labels:
```
net["throat.air:water"]
```
we could, of course, choose a different delimiter to avoid confusion, ex. `|`, `-`, `^`, `||`, etc.

**Comment by jgostick** [comment]
We currently have ``net.throats(['air', 'water'], mode='or')`` for this.  I see the point of wanting a more concise way to do it, but we need to be careful about being overly cute about it.

**Comment by jgostick** [comment]
BTW, if we do decide to do this, I propose the + sign

**Comment by ma-sadeghi** [comment]
> We currently have `net.throats(['air', 'water'], mode='or')` for this. I see the point of wanting a more concise way to do it, but we need to be careful about being overly cute about it.

Would this work if the throats are not labeled?

**Comment by jgostick** [comment]
Oh, I see, you're trying to find throats connected to *pores* with given labels.  Hmmm.

**Comment by ma-sadeghi** [comment]
> Oh, I see, you're trying to find throats connected to _pores_ with given labels. Hmmm.

Ya, this would be especially handy for multiphase simulations like Li-ion, CL, etc.

**Comment by jgostick** [comment]
We would need to add code to the __getitem__ method of ``Base`` to search for the presence of the magic delimeter, and then call an actual method (which may or may not be hidden), so I propose writing the method first.

```
def throats_by_label(net, labels): 
    Ts = np.ones_like(net.Ts, dtype=bool)
    for label in labels:
        L1 = net['pore.' + label][net.conns[:, 0]]
        L2 = net['pore.' + label][net.conns[:, 1]]
        Ts = Ts * L1 * L2
    return Ts
```

A better name is needed.  Also, it could be incorporated into the 'throats' function somehow?
