### ISSUE TITLE
Issue runtime warning when network is clustered

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1908]
We've already discussed this issue and realized that there are some valid cases where the network is clustered but the solution is valid. However, I think we should still issue a runtime warning. I just came across a clustered extracted network for which `StokesFlow` would diverge, and it took a while before I realized it was clustered.

**Comment by jgostick** [comment]
is probably something that should be in the GenericTransport health/sanity checks

**Comment by jgostick** [comment]
The problem with this is that it depends on the boundary conditions.  If the network is divided in the x-direction, then doing a simulaiton in the x-direction will actually work, but in the y-direction will fail.  We have added this check in the ``isclustered`` function which gets called when an algorithm is run.

**Comment by jgostick** [comment]
We fixed this, but screwed up.  Lines 793 and 794 need to be moved BEFORE the short-circuited nan/inf check
