### ISSUE TITLE
new shape factor models break on networks with subdomains

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1912]
It seems the indexing did not accounting for the possibility that a geometry might not apply to all pores in the network.

**Comment by Ni2M** [comment]
This issue was addressed in PR #2001.

**Comment by Ni2M** [comment]
This issue was addressed in a test in PR #2001 where only some throats were assigned to a geom. I will double check with another test with more subdomains in PR #2032.

**Comment by Ni2M** [comment]
I double checked with another multidomain test in PR #2032 (test_generic_diffusive_multi_domain) that could also pass in the merged PR #2001. Therefore, the current version of dev works fine on subdomains. This issue is now closed.
