### ISSUE TITLE
Profile the Transient solvers to find the bottleneck(s)

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1935]
There seems to be something slowing down the transient solvers, at least for small networks.  When comparing to a "pure" solve, the openpnm process is about 10x slower than it should be.  This may only be on small networks...like maybe the overhead is constant so become insignificant as the network gets larger, or maybe we're doing something dumb like recomputing values on each time step that we don't need to.  Worth looking into.

**Comment by ma-sadeghi** [comment]
I profiled a small transient simulation and here are my observations:

- The health checks are not the bottle neck.
- The slowness comes from `update_iterative_props` and a few other places that are part of `openpnm` machinery.
- The slowness becomes irrelevant once the network is large enough.

@jgostick Could you please run a simulation on a 25^3 network using your `solverlib` and compare it with `openpnm`?

**Comment by jgostick** [comment]
Yep, the problem disappeared.  In fact it flipped because solverlib uses spsolve and openpnm uses pypardiso, so the solverlib took 89 seconds and openpnm took 4 seconds.  And when I tell openpnm to also use spsolve, it also takes 90 seconds, so nearly identical.
