### ISSUE TITLE
Remove the tables of methods/attributes from class docsrings

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1945]
While it's really nice to have those tables, they're hard to maintain and might easily get outdated after a while. Users can use autocomplete or just look through the file to see what's available (or just look at examples).

**Comment by jgostick** [comment]
Yes I was thinking the same thing.  I was inspired to create those by scipy who have a lots of tables like that, but it does add an extra level of stuff to maintain.  We should just make sure the docs are well designed.

**Comment by mkaguer** [comment]
I found a table like this in the [Base](https://github.com/PMEAL/OpenPNM/blob/c45a26e9ffda0447ac2bc8f19ccda399d0a4ed5a/openpnm/core/Base.py) class. Are  they anywhere else?

**Comment by mkaguer** [comment]
https://numpydoc.readthedocs.io/en/latest/format.html#documenting-classes

**Comment by mkaguer** [comment]
The style guides at the link above do not encourage naming methods in class documentation. Also, the list of parameters and attributes can introduce redundancies. I say we don't need both lists. So I decided to just delete the tables all together after consulting the style guides.

**Comment by ma-sadeghi** [comment]
@mkaguer Is there a way to automatically generate a list of methods?

**Comment by jgostick** [comment]
I think ``dir(obj)`` does it, but you get ALL the methods and attributes.  You can use sets to reduce the list like: ``set(dir(op.network.Cubic)).difference(dir(op.core.Base))``.
