### ISSUE TITLE
_calc_eff_prop should return a float, not an ndarray

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1949]
Currently, `_calc_eff_prop` returns an `ndarray` with only 1 element. I think we should just return a `float` so we don't have to index into the results to get `Keff`:

```python
Keff = perm.calc_effective_permeability()[0]
```

**Comment by jgostick** [comment]
I agree it should be a float, but we are removing this from algorithms and putting it on the corresponding metric, so I'm going to close this one.
