### ISSUE TITLE
Base.set_label could use some refactoring

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1950]
`Base.set_label` could use some refactoring, especially to simplify the logic (simplify the complex `if-else` structure, etc.). Also, it seems that the `mode='add'` is not enforced. I mean, if `mode` is not in `['purge', 'remove', 'overwrite']`, it might as well be any other string, it works the same as `mode='add'`. This is not a bug, but like I said it could be a bit cleaner. Obviously, not urgent at all. Just a note for future.

**Comment by jgostick** [comment]
This will be fixed as I refactor Base, but that is a longer term project, so moving to new Milestone
