### ISSUE TITLE
Subclass ndarray when Base.__set__item is called on a masked property

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2033]
Suppose `pore.foo` is defined on the `network` object. If we try to set values using a subdomain, it won't work as `numpy` returns a copy (and not a view) when operating on masked arrays (i.e., b is a copy in b = a[mask]). We could/should subclass `ndarray` to throw a warning when we try to set item on such arrays.

```python
net["pore.foo"] = 1
print(geo1["pore.foo"])    # [1, 1, 1]
geo1["pore.foo"][0] = 2    # has no effect
print(geo1["pore.foo"])    # [1, 1, 1]
```

**Comment by jgostick** [comment]
This is no longer needed as we're abondoning the approach that made it necessary
