### ISSUE TITLE
Remove map_pores/throats and replace with to_global and to_local

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2042]
The mapping functionality is only used very occassionally, but needs to be kept.  I think the terminology is confusing though and propose we add ``to_global`` and ``to_local``.  These would complement the ``to_mask`` and ``to_indices`` functions that we have (also note their names have an underscore added for better readability).  

Additionally, the ``pores`` and ``throats`` methods will have a ``relative=True/False`` argument added.  Although, as I write this I'm seeing a mis-match between the terminology.  I guess the argument should be ``local=True/False`` for consistency.  OR, the methods could be called ``to_relative`` and ``to_absolute``?

**Comment by ma-sadeghi** [comment]
I'd say global and local are more descriptive.

**Comment by jgostick** [comment]
The argument should be ``global=False`` by default, and if you want global indices, then you have to explicitly type ``global=True`` so you know for sure what you're getting.
