### ISSUE TITLE
Rename phases to phase

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2058]

**Comment by jgostick** [comment]
This would make the four main submodules all singular and more consistent.  I actually think we meant to do this for V2 but forgot!

**Comment by jgostick** [comment]
Alternatively we could unpluralize phases to phase.

**Comment by jgostick** [comment]
The main submodules are all 'singular' except phases.

**Comment by jgostick** [comment]
We all agreed this should be done.  It will Break a lot stuff, especially in examples.
