### ISSUE TITLE
Remove __new__ method from our objects

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2061]
I'm not exactly sure why we introduced it in the first place (I guess the PNM file format needed it for some reason). But, I think we no longer need it.

**Comment by jgostick** [comment]
We still need it. The 'settings' attribute gets added during the __new__, then the settings are used within the __init__

**Comment by ma-sadeghi** [comment]
Can't we add `settings` during the \_\_init__ as well?

**Comment by jgostick** [comment]
Is there a problem with having it?  Does it break something for you?  The settings get added by the user during init, then they need to be added to the object before super.__init__ is called because classes up the chain also use the settings, specifically the name.

**Comment by ma-sadeghi** [comment]
No, just for the sake of simplicity and making the code more readable (for those who probably don't know what __new__ means).
