### ISSUE TITLE
Override __repr__ for alg.settings

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2062]
Currently, we override the `__str__` method for algorithms' settings so it prints out nicely formatted. However, this requires `print(alg.settings)`. I propose we also override `__repr__`, so typing `alg.settings` in IPython console prints out the formatted version.

**Comment by jgostick** [comment]
This makes sense.  We could also do it for models too.

**Comment by jgostick** [comment]
Small problem...the __repr__ method does not render the string, like adding new lines etc, it's just an unformatted string dump.  Upon a bit of reading it seems that the repr is not supposed to be human readable...its mean for debugging purposes.  If you want to "see" it, the "print" it.

**Comment by ma-sadeghi** [comment]
I changed `PrintableDict`'s `__repr__` method to:
```python
class PrintableDict(OrderedDict):
    ...
    def __repr__(self):
        return self.__str__()
    ...
```
and it seems to work (I'm using Linux). Could you try it on your Windows machine?
