### ISSUE TITLE
Remove Boundary geometry class

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2070]
This class is no longer needed.  Remove tests as well.

**Comment by Ni2M** [comment]
This issue has been addressed in the [unified PR](https://github.com/PMEAL/OpenPNM/pull/2032).

**Comment by xu-kai-xu** [comment]
@jgostick hi, I want to know does this mean that I do not need to add boundary pores and boundary geometrys to conduct the simulation? Thanks

**Comment by jgostick** [comment]
We have a new approach for computing conductances.  The 'recommended approach for boundary pores will be 'cones_and_cylinders', which solves lots of the problems with boundary pores.  For instance, with extracted network, the boundary pores are wide but only 3 voxels this.  The new approach handles this easily be making a cone that is only 3 pixels tall but has the corrected width.  This was very challenging to get right when using spheres.
