### ISSUE TITLE
Nernst-Planck example scripts are broken (both 2d and 3d)

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2088]
How did this happen? Don't we test the `scripts/` folder?

**Comment by ma-sadeghi** [comment]
@mkaguer Could you please look into this?

**Comment by mkaguer** [comment]
Hi @ma-sadeghi. Yes I see. 

We removed electroneutrality_2d that is why the 2d example is failing. And we removed the setup method. That is why the 3d example is failing. 

I can fix these example scripts so they are working but we must not be testing the scripts folder. How can we check if these scripts are being tested?

**Comment by ma-sadeghi** [comment]
Thanks @mkaguer! I'll fix the workflows to also test the scripts folder. Just one thing: I locally fixed the setup issue for the 3d example, but the script still fails to converge. It diverges after a dozen Gummel iterations IIRC. Can you verify?

**Comment by mkaguer** [comment]
Hi @ma-sadeghi. I think this example has been diverging for a long time. I tested an old branch I had and it did the same thing. In the PR #2102 I made recently, I changed the number of gummel iterations from 100 to 50. That stopped it before it started to diverge.

**Comment by mkaguer** [comment]
@ma-sadeghi How did you fix the setup issue? Do we still use the setup method?

**Comment by ma-sadeghi** [comment]
Write:
```python
pnp.settings["potential_field"] = p.name
pnp.settings["ions"] = [eA.name, eB.name]
```
instead of:
```python
pnp.setup(potential_field=p.name, ions=[eA.name, eB.name])
```

**Comment by mkaguer** [comment]
Ok yes that is what I did.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ma-sadeghi** [comment]
Did you look into why it diverges?

**Comment by mkaguer** [comment]
I don't know exactly why it diverges. But it is just an example so can't we just change settings/parameters to something that converges? This example has been diverging for a long time I think.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ma-sadeghi** [comment]
Hmm, which settings/parameters do you suggest to change for it to converge?
