### ISSUE TITLE
Categorize algorithms?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2089]
Currently, we have 23 built-in algorithms, and possibly with the addition of a proper multiphysics machiner, many more to come. It might be a good idea to categorize them so users can search through them more easily.

**Comment by ma-sadeghi** [comment]
It would particularly be useful for the documentation to look cleaner maybe?

**Comment by jgostick** [comment]
Maybe we can revisit this if the number gets really ridiculous, but for now it's ok.
