### ISSUE TITLE
Create openpnm.models.health_checks submodule for storing the new health check functions

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2109]
So:

```
openpnm
  - models
    - health_checks
      - topopolgy
        - duplicate_pores
        - etc
      - subdomains
        - unassigned_locs
      - data_integrity
        - has_nans
```

Then we can call these from the ``project.check_<...>_health()`` functions.  

The only wierdness is that 'models' are generally meant to be assigned to objs and the results stored on the objs, so this breaks things.  Another option might be to put ``health_checks`` under the ``topotools`` folder or perhaps ``utils``?

**Comment by ma-sadeghi** [comment]
Yeah, maybe `topotools` or `utils` is a better place than models.
