### ISSUE TITLE
Update text bits in documentation/examples

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2111]
We've made some significant changes to the code such as "introduced the idea of size factors", "deleted `Boundary` class", etc. We should comb through the documentation and notebooks to update obsolete info.

# Examples

- [ ] intro to openpnm advanced
- [ ] intro to openpnm intermediate
- [ ] concise overview of openpnm (maybe)

# Docstrings
- [ ] Add text to phases init file
- [ ] Make sure Parameters/Returns sections are populated (add Returns None for those not returning anything)

**Comment by jgostick** [comment]
This is obsolete now that we have new list of what to work on
