### ISSUE TITLE
Remove examples from docstrings

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#2114]
Some classes contain examples in the docstring. I thought this is confusing if we have a dedicated examples folder. Here are some places where we have examples in the docstring:
- GenericGeometry
- GenericNetwork
- GenericPhase

Should we delete? This would help clean up docstrings.

**Comment by ma-sadeghi** [comment]
Hmm, I just checked and `networkx` seems to follow the same pattern (see [here](https://networkx.org/documentation/stable/reference/classes/digraph.html) for instance). Not that we should copy them though, but I'm now undecided whether this is a good/bad idea.

**Comment by jgostick** [comment]
Let's keep these all.
