### ISSUE TITLE
Rounding error in method openpnm.utils.nbr_to_str()

### ISSUE THREAD

**Issue by s-lunowa** [PMEAL/OpenPNM#2120]
The number to string conversion method `openpnm.utils.nbr_to_str(nbr, t_precision)` results in wrong output for some numbers, e.g.:
```.py
import openpnm.utils as u
nbrs = [ u.nbr_to_str(0.2904, 3), u.nbr_to_str(29.9996, 3) ]
print(nbrs)
# result: ['28e-2', '300e-1']
# expected: ['29e-2', '30']
```
This seems to occur due to the some round-off error in the following lines:
https://github.com/PMEAL/OpenPNM/blob/f176ea2cd76f7879edc7eabe13115a6ba9a8b18e/openpnm/utils/misc.py#L571-L573

I would suggest to replace it by the following code, which seems to resolves the issue:
```.py
    number = dc(str(round(nbr, precision)))
    n = int(-number.as_tuple().exponent * (number != int(number)))
    nbr_str = str(int(number * 10**n)) + (f'e-{n}') * (n != 0)
```

**Comment by ma-sadeghi** [comment]
Hi @s-lunowa, thanks for reporting this. We're in the middle of refactoring `openpnm` to release `v3`, hopefully soon (maybe by the end of 2021?). We've significantly changed the internals of algorithms, and the method you mentioned is no longer used.

Please "watch" openpnm so you get notified when we make the release (if you don't want your inbox to get full of openpnm messages, you can go to watch -> custom -> releases, so you only get notified of the releases, which are not that often (maybe a couple of releases a year?).

**Comment by ma-sadeghi** [comment]
Since in a few days, we'll merge #1383, which will entirely get rid of the old algorithms, fixing this bug would only stay in the code base for just a few days, so I'm closing this issue.
