### ISSUE TITLE
Remove effective property calculation business out of GenericTransport

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2125]

**Comment by jgostick** [comment]
Ex: StokesFlow has a ``calc_eff_permeability`` method. The idea was to return K for the network. This required computing the domain area and length which is actually very difficult, so required lots of code. We want to move this code to its own ``metrics`` class, caled Permeability or PermeabilityCoefficient.  This class should run a StokesFlow algorithm behind the scenes then compute K using the area and length provided by the user.  

So....this task requires (a) removing the related code from each Transport alg, and (b) creating a corresponding class in the metric folder.  However, part (b) is complicated, so let's break it up and start by deleting unneeded code from the transport classes.
