### ISSUE TITLE
Refactor runtime validation checks

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2126]
- `_validate_data_health` is very complex and needs to be broken up.
- `_validate_data_health` should also check if `x0` doesn't contain `nan`/`inf`s

**Comment by jgostick** [comment]
I don't think these should be a mixin.  They are quite foundational to transport solvers, so they're in the right place.  Also, the file will be a LOT shorter once the BC mixin is done and the calc effective props is removed.  

However, the validate methods should be refactored and tided up.  This is related to the health check stuff that I've been working on and thinking about in issues #2041 and #2109
