### ISSUE TITLE
Refactor boundary condition business out of GenericTransport (as a mixin?)

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2127]
This helps reusing the boundary condition machinery for solid mechanics algorithms.

**Comment by jgostick** [comment]
This is a good idea.  Each transport class still needs to implement its own ``_apply_BCs`` method, but the user-facing helper methods such as ``set_rate_BC``, etc are not technically needed.  If fact, if the user just creates the correct arrays (i.e. ``pore.rate_bc``) then the ``_apply_BC`` function will work.  Actually, these arrays are created by the init function, so are already present.  The user just needs to update them.  In other words, we can separate these methods into a mixin and the transport classes will still be 'self sufficient'.
