### ISSUE TITLE
On the docs in `models.geometry.hydraulic_size_factors.py` file

### ISSUE THREAD

**Issue by xu-kai-xu** [PMEAL/OpenPNM#2138]
In the docs of `models.geometry.hydraulic_size_factors.py`, I found that the math for the size factor is

![equation](https://user-images.githubusercontent.com/14086031/140257520-5de1aa49-dd58-4d47-ba3a-25822d2da40d.png)

I found there is a problem. I found that the classical equation for stokes flow in circular tube is

![equation(1)](https://user-images.githubusercontent.com/14086031/140257549-be101775-2adb-496b-b7e5-3e9521ea03b2.png)

And after transformation with cross section area, I get the different result. There is a PI in denominator. So I am confused is there anything wrong with my derivation?

**Comment by ma-sadeghi** [comment]
Hi @xu-kai-xu! Thanks for reporting this. That's certainly a typo in our docstring. We'd really appreciate it if you could fix it in a PR? Thanks :)

**Comment by xu-kai-xu** [comment]
OK.
