### ISSUE TITLE
Re-enable the berea integration test and the generate voxel image test when skfmm is sorted out

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2139]

**Comment by ma-sadeghi** [comment]
The issue with `scikit-fmm` seems to have been fixed (see [here](https://github.com/scikit-fmm/scikit-fmm/issues/63))

**Comment by jgostick** [comment]
- [x] re-add porespy to test_requirements
- [x] Uncomment this file: https://github.com/PMEAL/OpenPNM/blob/dev/tests/integration/PoreSpyIO_on_Berea.py
- [x] Uncomment this test: https://github.com/PMEAL/OpenPNM/blob/bc228c59e60376dd59fef4ecd505d13de67241e7/tests/unit/topotools/PlotToolsTest.py#L64
