### ISSUE TITLE
pore_volume in TransientReactiveTransport's settings is vague

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#2147]
For the case of transient heat transfer pore_volume = heat capacity. Maybe we should be using term pore_capacity??

**Comment by jgostick** [comment]
This needs some thought:
* when doing transient diffusion the 'capacity' is just the pore volume, which we can lookup on the network 
* for transient conduction, the capacity is the specific heat capacity of the phase/fluid multiplied by the pore volume, so it's now a "physics" property.  
* The transient code is currently hard-coded to only lookup volume from the network.  We need a way for it to also lookup the fluid/phase capacity...but this has no meaning for diffusion so there is not an obvious general solution.

**Comment by mkaguer** [comment]
From looking at the wikipedia page [here](http://en.wikipedia.org/wiki/Thermal_diffusivity) on thermal diffusivity. I am realizing that the thermal diffusivity is not k but alpha where alpha is k/Cp. Using alpha removes Cp from the transient term altogether and only volume remains analogous to transient fickian diffusion. I think this should be the approach. I kept Cp on the transient term but it should have been divided on both sides. Does this make sense?

**Comment by ma-sadeghi** [comment]
@jgostick Did we fix this issue?
