### ISSUE TITLE
Change Stick and Ball to create nice pore and throat distributions

### ISSUE THREAD

**Issue by jhinebau** [PMEAL/OpenPNM#216]
(also for Cube and Cuboid)
Harold and I will work on this together:

Ideally, we'd do:

    >>> import OpenPNM
    >>> pn = OpenPNM.Network.TestNet()
    >>> geo = OpenPNM.Geometry.Stick_and_Ball(network=pn,porosity=0.85,variability=0.5,distribution='uniform')

porosity would be a float between 0 and 1

variability would range between 0 (uniform pore sizes) to 1 (max pore size range without overlapping pores)

distribution would be either 'uniform' or 'weibull'

Initially, it should work for Cubic networks, but eventually, it would be nice to work on random networks too (tricky)

**Comment by jgostick** [comment]
I can probably knock this out quickly enough.  The other stuff that tom showed with FCC, BCC, etc needs to be highlighted in the code more prominently.  Calling it DelaunayCubic is too obscure. I will open an issue and add a few extra ideas too.

**Comment by jgostick** [comment]
I have added these changes to a PR where I'm improving the pore and throat size  models (#504).  The changes are quite small...I basically just use a Normal distribution to generate pores sizes with the mean at 0.5x the lattice spacing, then put a standard deviation of 0.1x the lattice spacing.  This will produce a decently usable network regardless of the spacing.
