### ISSUE TITLE
Deprecate pore/throat area models

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2182]
As I was combing through the code I found a todo:  We decided to remove the pore_area and throat_area models, since these should be called pore/throat_crosssectional_area to be explicit.

**Comment by Ni2M** [comment]
During my investigations I have noticed that we are still using 'throat.area' in some places such as test files where it does not create any problem, However I propose to change the naming in those files as well to be consistent.
Places where using pore.area is still problematic is in some models such as Valvante Blunt hydraulic conductance [here] (https://github.com/PMEAL/OpenPNM/blob/bb91356bd308d619d425311f553930f692af0376/openpnm/models/physics/hydraulic_conductance.py#L196) and some other .py files. I'll be looking into it.
