### ISSUE TITLE
Tutorial 1 Paraview visualization

### ISSUE THREAD

**Issue by debanik1** [PMEAL/OpenPNM#2185]
How to visualize the Cubic network using Paraview in [Tutorial 1](https://github.com/PMEAL/OpenPNM/blob/dev/examples/tutorials/intro_to_openpnm_basic.ipynb)? The instructions link therein is empty.

**Comment by jgostick** [comment]
Not sure how this got lost, but we have salvaged it and put it in the contrib folder for now (click [here](https://github.com/PMEAL/OpenPNM/blob/dev/examples/contrib/plotting_in_paraview.rst)).
