### ISSUE TITLE
AttributeError: module 'openpnm.geometry' has no attribute 'SpheresAndCylinders'

### ISSUE THREAD

**Issue by thsmit** [PMEAL/OpenPNM#2197]
I am trying to run the basic usage example after installing openPNM. I get following error.

Running:
```python
import openpnm as op
Lc = 1e-4
Nx, Ny, Nz = (10, 10, 10)
pn = op.network.Cubic(shape=[Nx, Ny, Nz], spacing=Lc)
geo = op.geometry.SpheresAndCylinders(network=pn, pores=pn.Ps, throats=pn.Ts)
Hg = op.phases.Mercury(network=pn)
phys = op.physics.Standard(network=pn, phase=Hg, geometry=geo)
mip = op.algorithms.Porosimetry(network=pn, phase=Hg)
mip.set_inlets(pores=pn.pores(['left', 'right', 'top', 'bottom']))
mip.run()
```

Error:

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-82-11dabb12c30d> in <module>
      7 # Generate network, geometry, phase, and physics
      8 pn = op.network.Cubic(shape=[Nx, Ny, Nz], spacing=Lc)
----> 9 geo = op.geometry.SpheresAndCylinders(network=pn, pores=pn.Ps, throats=pn.Ts)
     10 Hg = op.phases.Mercury(network=pn)
     11 phys = op.physics.Standard(network=pn, phase=Hg, geometry=geo)

AttributeError: module 'openpnm.geometry' has no attribute 'SpheresAndCylinders'
```

What am I doing wrong here?

**Comment by ma-sadeghi** [comment]
Can you paste the output of `print(openpnm.__version__)`?

**Comment by jgostick** [comment]
This is almost certainly because you're using an old version of OpenPNM.  You need to be using 2.8+.

**Comment by wwx2277** [comment]
After solve this problem,I have a new problem that "module 'openpnm' has no attribute 'phases'"

**Comment by jgostick** [comment]
can you paste the full traceback so we can see where the error comes from?

**Comment by 46506799** [comment]
Professor,
I used the version 2.8.2.dev111118 to test the pasted sample in windows 10, but it's not work, the error for your reference:                  
 geo = op.geometry.SpheresAndCylinders(network=pn, pores=pn.Ps, throats=pn.Ts)                                                            
 AttributeError: module 'openpnm' has no attribute 'geometry'
could you give me support how to fix it?

**Comment by jgostick** [comment]
Your installation seems to be broken.  You're using 'dev' version, so presumably downloaded the code from github.  Did you do ``pip install -e .`` in the directory containing the setup.py file?

**Comment by 46506799** [comment]
Thanks for your quickly reply.
Could you give me more detail information to fix it ?

**Comment by JahanzebTariq** [comment]
Greetings.. please help me understand where I am going wrong. The code does not seem to be working for me.


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10188\3271317616.py in <module>
----> 1 h = pn.check_network_health()
      2 op.topotools.trim(network=pn, pores=h['trim_pores'])
      3 h = pn.check_network_health()
      4 print(h)

AttributeError: 'Network' object has no attribute 'check_network_health'

**Comment by JahanzebTariq** [comment]
These are some line wise errors that I'm getting again and again. Please help me getting these correct


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10188\2033630369.py in <module>
----> 1 geo = op.geometry.GenericGeometry(network=pn, pores=pn.Ps, throats=pn.Ts)

**AttributeError: module 'openpnm' has no attribute 'geometry'**

**Comment by baelow** [comment]
**when I ran code of example, it shows error (`AttributeError: module 'openpnm' has no attribute 'geometry'`) again and again**. It makes me very confused. Could dear professor help me deal with this problem? Thank you.
The following is details:

```
import openpnm as op
Lc = 1e-4
Nx, Ny, Nz = (10, 10, 10)
pn = op.network.Cubic(shape=[Nx, Ny, Nz], spacing=Lc)
geo = op.geometry.SpheresAndCylinders(network=pn, pores=pn.Ps, throats=pn.Ts)
Hg = op.phases.Mercury(network=pn)
phys = op.physics.Standard(network=pn, phase=Hg, geometry=geo)
mip = op.algorithms.Porosimetry(network=pn, phase=Hg)
mip.set_inlets(pores=pn.pores(['left', 'right', 'top', 'bottom']))
mip.run()
```
```
ipython-input-3-11dabb12c30d in module
      7 # Generate network, geometry, phase, and physics
      8 pn = op.network.Cubic(shape=[Nx, Ny, Nz], spacing=Lc)
----> 9 geo = op.geometry.SpheresAndCylinders(network=pn, pores=pn.Ps, throats=pn.Ts)
     10 Hg = op.phases.Mercury(network=pn)
     11 phys = op.physics.Standard(network=pn, phase=Hg, geometry=geo)

AttributeError: module 'openpnm' has no attribute 'geometry'
```
**WHAT I TRIED:**
* I checked my version-- `'3.1.1'`
*  I reinstall by `conda install -c conda-forge openpnm` serials times, but it still shows this type error.
*  I uninstall by `conda remove openpnm` and then install dev version from github, --[The hard (but correct) way](https://openpnm.org/installation.html), but it shows another error. -- DLL error (I uesed python 3.8). 
*  I have tried another env `conda create -n foropenpnm`, same error as before (module 'openpnm' has no attribute 'geometry')

**Now I donnot konw how to do nexr, hope you can help me. Thank you a lot.**

**Comment by brucelerping** [comment]
Professor,
Greetings！
I used the version 3.1.2 and try to run this code:
geo = op.geometry.StickAndBall(network=net, pores=net.Ps, throats=net.Ts)
but an error occurred:  AttributeError: module 'openpnm' has no attribute 'geometry'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

----> 7 geo = op.geometry.StickAndBall(network=net, pores=net.Ps, throats=net.Ts)

AttributeError: module 'openpnm' has no attribute 'geometry'
---------------------------------------------------------------------------
I tried to reinstall openpnm, but the same error still occurred
Could you know why and how I can solve it？

**Comment by likeduck** [comment]
OpenPNM==3.1.2 has removed the concept of Geometry and Physics objects.

See [here](http://pmeal.com/posts/2022-10-10-notebook-post/)

**Comment by brucelerping** [comment]
> OpenPNM==3.1.2 has removed the concept of Geometry and Physics objects.
> 
> See [here](http://pmeal.com/posts/2022-10-10-notebook-post/)

oops！My bad and thankyou！

**Comment by Amirhosein-Sarchami** [comment]
Dear colleagues,
I'm just getting started with OpenPNM and trying out the basic usage code for the first time when I ran into an error that seems everyone had before (AttributeError: module 'openpnm' has no attribute 'geometry'). I deleted OpenPNM and installed the dev version, but I still got the same error. I read in this link that the concepts of the commands were deleted. If they are deleted, what should be done to start working with OpenPNM without encountering an error? And that the link you posted above does not work. Thanks

**Comment by jgostick** [comment]
Sounds like you're using a new version of openpnm with an old script.

**Comment by Amirhosein-Sarchami** [comment]
Thank you doctor for your response. So, is there any way to learn openpnm using the new version? I can use your website's examples, but as you mentioned the geometry and physics objects have been removed, which makes errors for beginner users. Would it be possible for you to change the scripts on the website based on the recent version of openpnm?

**Comment by jgostick** [comment]
I thought they were all updated already..which pages are referring to?

**Comment by Amirhosein-Sarchami** [comment]
You're right. I thought they were similar to basic usage. So I think only the basic usage should be updated. Thank you for your effort in answering the questions.
