### ISSUE TITLE
Possible bug in "tutorial #2" of examples

### ISSUE THREAD

**Issue by debanik1** [PMEAL/OpenPNM#2208]
I am following Tutorial 2of3 (https://github.com/PMEAL/OpenPNM/blob/dev/examples/tutorials/intro_to_openpnm_intermediate.ipynb) line by line.

I don't get Out[9] after In[9].

**Comment by jgostick** [comment]
We are in the middle of converting from V2 to V3 and will be completley updating all the docs.  We'll ensure that all examples run correctly before releasing V3, but this is a few months away.
