### ISSUE TITLE
Make main arguments mandatory for main objects

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2212]
I think we should make main arguments, namely `network`, `geometry`, `phase`, `physics` (where applicable), mandatory for main objects. Here's what I propose:

- `network`: looks good as is
- `geometry`: `network`
- `phase`: `network`
- `physics`: `network`, `geometry`, `phase` (maybe even just `phase` and `geometry`?)
- `algorithm`: `network`, `phase` (or just `phase`?)

**Comment by jgostick** [comment]
The ability to create objs without args was required for the PNM file format...but now we are reverting to just pickle so it's not needed anymore.   This is a good suggestion.

**Comment by jgostick** [comment]
I think I agree that everything should take a network (except networks themselves), but I prefer allowing physics to have phase/geometry blank. This is very well tested in the code and works great.  It allows for physics objects to be assigned to other subdomains.  This is not really used, but does reinforce how the code is designed.
