### ISSUE TITLE
set_label with mode="remove" could sometimes be confusing

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2220]
I was under the impression that the following snippet removes the label "top" from the network. However, it throws an error.

```python
net = op.network.Cubic([3,4,5])
net.set_label("top", mode="remove")
```

The correct way of calling `set_label` for this purpose is to also pass `pores=net.Ps`.

**Comment by jgostick** [comment]
I think the idea is that you'll "remove" the label from the given pores.  I guess we'd could make it literally remove the whole label if the pores/throats is None.  Or we could a new mode, like 'purge'.

**Comment by ma-sadeghi** [comment]
If we're using `purge` in other places with a similar functionality, then let's reuse it, otherwise, I'd say just wipe the label entirely if no pores/throats is specified.

**Comment by jgostick** [comment]
I am looking into the function and we already have a purge mode.  There is also a comprehensive suite of tests too.  I just reformatted to docstring to list the modes in a nice table, but otherwise the function looks solid to me.
