### ISSUE TITLE
Allow identical "name" for objects of different type

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2221]
Currently, `openpnm` doesn't allow assigning identical "names" to objects if they've already been used in another object or an identical label is found. This is somewhat inconvenient: let's say you have a composite network, one for "air" and one for "water". To make things worse, you also have two geometries, one for air and one for water. Finally, you're performing a multiphase diffusion simulation, which requires you to have two separate phases one for air, and one for water. Currently, you have to name your networks, geometries, phases, and physics something along the lines of:

- `net_air`, `net_water`
- `geom_air`, `geom_water`
- `phase_air`, `phase_water`
- `phys_air`, `phys_water`

I don't know how hard would it be to lift this limitation, but I think that it'd be nice. Theoretically(?), it should be possible to tell them apart as each of these objects have a different type. Apart from less typing, it makes the code more pleasing. Suppose you want to ask `Project` about the water phase, currently, you'd type:

```python
proj.phases("phase_water")
```

whereas without the limitation, we'd simply type:

```python
proj.phases("water")
```

which is both more straightforward and beautiful.

**Comment by jgostick** [comment]
this would be a big change for a minimal payback, so I think it's a no-go for now.
