### ISSUE TITLE
Implement Solution class for steady state simulations

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2222]
Currently, `Solution` object is only implemented for transient simulations.

**Comment by ma-sadeghi** [comment]
What added value does a SteadyStateSolution class provide? Is it just for consistency with transient algs?

**Comment by jgostick** [comment]
Yes, mostly for consistency, but there are perhaps features we'll add to the Solution class in the future which could be useful for both transient and steady-state.  For instance, the solver convergence if interative, run times, etc.

**Comment by jgostick** [comment]
Also, for instance, see #2053.  In fact, we also have the ``rate`` method on algorithms, which perhaps should be on the solution object, instead of the algorithm?  Maybe?

**Comment by jgostick** [comment]
Also, it seems to me like the the conductance should be copied to the solution object, so there is a permanent record of the values in case they are changed on the physics object.  Same for any reactions terms.
