### ISSUE TITLE
Unneeded code in GenericTransport when setting BCs?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2228]
I noticed the following code while I was answering Discussion #2227.

In _apply_BCs, we do the following to keep A symmetric, but I'm not sure it's necessary.  I have confirmed that removing these lines gives exactly the same answer.  It *might* be necessary for the AdvectionDiffusion alg or something.  Anyway, we should look into this since it (a) make the returned ``b`` matrix a bit confusing to users and (b) is probably adding overhead to the building of b.

``` python
# Update b (substract quantities from b to keep A symmetric)
x_BC = np.zeros_like(self.b)
x_BC[ind] = self['pore.bc_value'][ind]
self.b[~ind] -= (self.A * x_BC)[~ind]
```

**Comment by ma-sadeghi** [comment]
We added this so that "special" symmetric solvers could be leveraged (like `cg` that only works on symmetric matrices, and other solvers are likely to be more optimized for such matrices). For instance, in `porespy.dns.tortuosity`, we use `cg`, which would break if we were to remove those lines.

**Comment by jgostick** [comment]
great!  I will add a bit more detail to the comment in the code
