### ISSUE TITLE
Add extra info to __version__ for dev branches

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2233]
At the moment ``openpnm.__version__`` will output 2.8.2 regardless of how many merges we've done onto dev.  It would be great if the \_\_version\_\_ could be updated each time we merge onto dev wtih some sort of -devXYZ tag

**Comment by jgostick** [comment]
@ma-sadeghi what do you think about this?  Is there anyway to make this work with your bump_version workflow?

**Comment by ma-sadeghi** [comment]
I looked into it, there seems to be a way in `bump2version` library to do that. I'm afraid it might break up the release process (maybe not). I can look into it more thoroughly if you think it's worth it.

**Comment by jgostick** [comment]
The current plan is to tell ``bump2version`` to add an additional level of numbering to the semantic version.  Each time we merge on to dev this last number will be incremented.  When we merge onto release this number will be dropped.  So working on a release __version__ will be ``3.0.4``, while working on dev it will be ``3.0.4.123``, indicating that there have been 123 merges onto dev since the last release.  When we merge dev into release, then the version will become ``3.0.5`` or ``3.1.0``, and the dev branch will get ``3.1.0.0``.
