### ISSUE TITLE
Physical forces in IP tutorial

### ISSUE THREAD

**Issue by debanik1** [PMEAL/OpenPNM#2234]
How to identify the physical forces (capillary, viscous or gravity) at play in the [Invasion Percolation ](https://github.com/PMEAL/OpenPNM/blob/release/examples/notebooks/algorithms/percolation/B_invasion_percolation.ipynb) tutorial? I am interested in the capillary regime.

**Comment by jgostick** [comment]
The IP algorithm only considers capillary forces.  A dynamic IP is on the roadmap but we haven't implemented it yet.  Gravity would be possible with the existing IP algorithms with a small amount of work.  Luckily you only want capillary forces!

**Comment by debanik1** [comment]
I see. It's not clear yet how I change the surface tension, velocity or viscosity in the algorithm. Also, I am interested in dynamic behavior in the capillary regime.
