### ISSUE TITLE
dep handler not putting ad_dif_conductance in right order

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2269]
Using the new ``collections`` of models seems to have confused the dep handler.  For some reason it does not generate ad_dif_conductance in the correct order.  

``` python
net = op.network.Cubic(shape=[5, 5, 5])
geom = op.geometry.SpheresAndCylinders(network=net, pores=net.Ps, throats=net.Ts)
air = op.phase.Air(network=net)
phys = op.physics.Standard(network=net, phase=air, geometry=geom)
```

printing ``phys`` will not show ``throat.ad_dif_conductance``, but do ``phys.rengerate_models`` again, and it will appear just fine.

**Comment by ma-sadeghi** [comment]
@jgostick It seems that the new way we add models doesn't assign the parameters in models dict.

Here's what I get for `phys.models["throat.hydraulic_conductance"]`:

```python
{'model': <function generic_hydraulic at 0x7fecb4d683a0>}
```

and here's what I get based on dev:

```python
{'model': <function openpnm.models.physics.hydraulic_conductance.hagen_poiseuille(target, pore_viscosity='pore.viscosity', throat_viscosity='throat.viscosity', size_factors='throat.hydraulic_size_factors')>,
'regen_mode': 'normal',
'pore_viscosity': 'pore.viscosity',
'throat_viscosity': 'throat.viscosity',
'size_factors': 'throat.hydraulic_size_factors'}
```
