### ISSUE TITLE
Fall back to scipy's spsolve on AMD architectures 

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2273]
As per the discussions in #2227, it seems that `pypardiso` doesn't work on AMD architectures. This is odd. We should double check this by testing `openpnm` on another AMD machine, and if it turns out to be the case, we should fall back to another solver (possibly scipy's spsolve).

**Comment by haasad** [comment]
The discussion in #2272 is probably related to https://github.com/haasad/PyPardisoProject/issues/36. There's currently something broken on windows with `mkl` and `intel-openmp` on conda-forge. I doubt that's it's related to AMD, but if you receive any similar reports, I'd be grateful if you could direct those users to open an issue in the pypardiso repo.
