### ISSUE TITLE
Specify settings via dict warning is triggered using set_variable_props

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#2274]
Look into this. This occurs in my unit test of new TransientMultiPhysics. Warning disappears when I delete set_variable_props lines.

**Comment by jgostick** [comment]
We have decided to not deprecate that aftrer all...its a fairly handy way to pass 1 or 2 settings and it doesn't harm anything by allowing it.

**Comment by ma-sadeghi** [comment]
So I guess we need to remove the deprecation warning, right?
