### ISSUE TITLE
Fix docstrings of pore-scale models

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2286]
In the Notes section of almost all conductance models (including 3d ones), it says "this model should only be used for 2D simulations, etc.".

**Comment by jgostick** [comment]
I think we should use the matplotlib ``substitution`` function rather than docrep in the models module.  I have a mix of both at the moment, so we need to go back in there and tidy up anyway.

**Comment by jgostick** [comment]
The phase models are all very sparsely documented.  This is a fairly large chunk of work to fix though.

**Comment by jgostick** [comment]
I have refactored all these models to use the plt.Substitution trick, and populated most of the text snippets.
