### ISSUE TITLE
Unable to run the Ficken diffusion example code

### ISSUE THREAD

**Issue by JiyuanZhang221** [PMEAL/OpenPNM#2287]
Hi there,
I've followed strictly the example code (attached as follows) for modeling single-phase Fickian diffusion. Unfortunately, the following error was raised: `KeyError: 'throat.diffusive_conductance'`. I checked the physics class and did see that the  throat.diffusive_conductance property was missing. 

However, when I use `op.geometry.GenericGeometry` to build the geometry model, the model runs successfully and produces reasonable results.

Really confused and need help.
 
```python
import numpy as np
import openpnm as op
import random
import matplotlib.pyplot as plt

np.random.seed(10)
ws = op.Workspace()
ws.settings["loglevel"] = 40
np.set_printoptions(precision=5)


spacing=1e-7
shape = [1, 10, 10]
pn = op.network.Cubic(shape=shape, spacing=spacing)
# op.topotools.reduce_coordination(network=pn, z=3)

geom = op.geometry.SpheresAndCylinders(network=pn, pores=pn.Ps, throats=pn.Ts)
air = op.phases.Air(network=pn)
phys_air = op.physics.Standard(network=pn, phase=air, geometry=geom)

fd = op.algorithms.FickianDiffusion(network=pn, phase=air)

inlet  = pn.pores('front') 
outlet = pn.pores('back')
C_in = 1.0
C_out = 0.0
fd.set_value_BC(pores=inlet, values=C_in)
fd.set_value_BC(pores=outlet, values=C_out)

fd.run()
```

**Comment by jgostick** [comment]
Hi @JiyuanZhang221...we are aware of the problem but not sure how to fix it.  It's a bit out of our hands we think.  Basically the Pardiso solver is acting badly.  Can tell me which version you are using so I can help you find a solution?

**Comment by ma-sadeghi** [comment]
@jgostick Is this issue related to Pardiso? It seems that he's getting `KeyError: 'throat.diffusive_conductance'`. Might be an old version?
