### ISSUE TITLE
Error using target.name in ad_dif_mig conductance model?

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#2289]
Is this [line 65](https://github.com/PMEAL/OpenPNM/blob/c9514b858d1361b2090b2f9579280cbcd476c9b0/openpnm/models/physics/ad_dif_mig_conductance.py#L65) an error? Can this actually work? Because this line is giving me errors when I use phys.add_model. I get a KeyError back.

**Comment by mkaguer** [comment]
Change to `throats = target.throats('all')`

**Comment by ma-sadeghi** [comment]
It should work. Basically, when you create a physics, a label is created indicating which pores belong to that physics. For example, if your physics is named "phys_01", calling network.pores("phys_01") should give you the pores associated with that physics. At least, that's how I thought it should work.

**Comment by mkaguer** [comment]
Ok I tried that net.pores('phys_01') again and I am getting a KeyError. So I think there might be a bug if that is supposed to work,

**Comment by ma-sadeghi** [comment]
I'm sorry, you should try `phase.pores("phys_01")`, since physics belongs to phase (and geometry to network).

**Comment by mkaguer** [comment]
Yup that works, so do we need to change line 65 then since target is physics. Or Is target supposed to be phase?? Uh, conductance models are kept on phase now is that right?

**Comment by ma-sadeghi** [comment]
No, conductance models are kept on physics. I think it should be something like this:
https://github.com/PMEAL/OpenPNM/blob/c9514b858d1361b2090b2f9579280cbcd476c9b0/openpnm/models/physics/_utils.py#L40-L42
