### ISSUE TITLE
Change solution objects to be nested inside a dict

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2294]
All solutions should be returned inside a dict, so that ``sol = alg.run()`` and ``sol['pore.concentration']`` points to the actual Solution object. This way (a) the solution knows the quantity it contains (pore.concentration) and (b) multiphysics can be combined into one object, like ``sol['pore.concentration]`` and ``sol['pore.temperature']``.  It also allows us to add functionality to the sol object higher up than the subclassed numpy array, so the namespace is not so messy.

**Comment by mkaguer** [comment]
Create SolutionContainer(dict) class. This will give us a dictionary of solutions. For Steady state, transient, and multiphysics.

self.soln = SolutionContainer()
self.soln['pore.quantity'] = self.settings['pore.quantity'] # put results from algorithm to SolutionContainer dict
