### ISSUE TITLE
set_variable_props 'merge' does not remove duplicates

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#2295]
The set_variable_props method does not remove duplicates using mode='merge'. The docstring says it will but it doesn't. I checked the set_source method and that method no longer uses 'merge' as a mode. Instead it uses 'add' but does delete duplicate propnames in self.settings['sources']. Although, the docstring in set_source does not say add means delete duplicates. Should we update docstring here as well?

**Comment by ma-sadeghi** [comment]
Actually, `variable_props` should be a set, so duplicates are not allowed in the first place.

**Comment by mkaguer** [comment]
Yes agreed! But there is nothing enforcing no duplicates.

**Comment by mkaguer** [comment]
Currently not using TypedSet. I will make sure we use that so duplicates are not allowed.
