### ISSUE TITLE
Metrics 'run' methods need to pass args to the algorithms

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2296]
I'm having trouble using pardiso at the moment so need to specify algs to use the scipy solver.  This works fine with the run method on all the main algs, but metrics call run within their own run.  We should pass kwargs through to the internal run method.

**Comment by Ni2M** [comment]
During the dev meeting we have decided to include the default solver in the workspace settings. A PR will be created to address this issue.
