### ISSUE TITLE
Legend with pore network plot?

### ISSUE THREAD

**Issue by thsmit** [PMEAL/OpenPNM#2305]
Hi, 

With the following code I am plotting a pore network successfully. Cool feature :) 
Is it possible to have a legend linking the color code to the pore size?

`fig, ax = plt.subplots(figsize=[8, 8])
ax.imshow(im_o.T, cmap=plt.cm.bone);
op.topotools.plot_coordinates(ax=fig,
                              network=pn,
                              size_by=pn["pore.inscribed_diameter"],
                              color_by=pn["pore.inscribed_diameter"],
                              markersize=2000)
op.topotools.plot_connections(network=pn, ax=fig)
ax.axis("off");
ax.legend(['Test'])`

**Comment by jgostick** [comment]
That is probably asking too much of this function which is already pushing the limits of matplotlib.  To get really fancy just use paraview.  Then you can do colorbar all day long if you like.

**Comment by jgostick** [comment]
Not saying it's impossible though.  I have actually had problems adding color bars to the ``subplots`` objects.  If you can figure it out, please report back here.

**Comment by thsmit** [comment]
Thank you Jeff for your quick reply.

I did something which works:

```python
# Origional example
import numpy as np
import porespy as ps
import openpnm as op
import matplotlib.pyplot as plt
ps.visualization.set_mpl_style()
np.random.seed(10)

# add color bar
import matplotlib as mpl
from mpl_toolkits.axes_grid1 import make_axes_locatable

# Origional example
fig, ax = plt.subplots(figsize=[8, 8])
ax.imshow(im_o.T, cmap=plt.cm.bone);
op.topotools.plot_coordinates(ax=fig,
                              network=pn,
                              size_by=pn["pore.inscribed_diameter"],
                              color_by=pn["pore.inscribed_diameter"],
                              cmap='jet',
                              markersize=2000)
op.topotools.plot_connections(network=pn, ax=fig)
ax.axis("off");

# add color bar
divider = make_axes_locatable(plt.gca())
ax_cb = divider.new_horizontal(size="5%", pad=0.5)    
cb1 = mpl.colorbar.ColorbarBase(ax_cb, cmap=mpl.cm.jet, orientation='vertical', norm=mpl.colors.Normalize(vmin=100, vmax=600))
plt.gcf().add_axes(ax_cb)
```

![network2](https://user-images.githubusercontent.com/52911749/150627036-088f54d2-a7e4-484f-9726-ac2905a23f59.png)

**Comment by jgostick** [comment]
Wow, thanks @thsmit!  The solution you came up with is short, but must've taken ages to figure out!  We will probably steal your code snippet and add it to our plot functions, if that's ok with you?  You can also try doing a PR to add it if you want to get involved?

**Comment by jgostick** [comment]
Hi @thsmit, I actually just tried your code and it works for 2D networks, but not for 3D, for which we use a different plot type.  We also have a ``plot_jupyter_notebook`` which generates a plotly figure.  It seems that it's pretty easy to add a colorbar to the plotly figure, so I think we'll support this approach instead.

**Comment by thsmit** [comment]
Hi @jgostick, it wasn't very difficult, which also surprised me. I would be happy to do a PR and get involved, but if there is a better solutions, that is also good for me, off-course.

**Comment by jgostick** [comment]
Let's see if the plotly option works. No need to invest your time yet.
