### ISSUE TITLE
Can't define physics

### ISSUE THREAD

**Issue by loaa4** [PMEAL/OpenPNM#2324]
I followed the example to run a single phase simulation,but when it comes to define the physics,problems occured:

```
import numpy as np
import openpnm as op
%config InlineBackend.figure_formats = ['svg']
import matplotlib.pyplot as plt
%matplotlib inline
np.random.seed(10)
ws = op.Workspace()
ws.settings["loglevel"] = 40
np.set_printoptions(precision=5)

shape = [1, 10, 10]
spacing = 1e-5
net = op.network.Cubic(shape=shape, spacing=spacing)

geom = op.geometry.GenericGeometry(network=net, pores=net.Ps, throats=net.Ts)

air = op.phases.Air(network=net)

phys_air = op.physics.Standard(network=net, phase=air, geometry=geom)
```
![43L%XAPR$GI1U6SHT1OYL52](https://user-images.githubusercontent.com/99061790/153532206-0dc0983d-a73f-44d4-b1e3-7cbbd4c2ecd7.png)

I have tried to reinstall conda and openpnm,but it's not working,
and now my openpnm version is 2.8.2,
really confused and have no idea how to solve this problem,
any suggestion would be helpful,
thanks a lot.

**Comment by jgostick** [comment]
It's becuase you've used GenericGeoemtry.  You nee to assign some geometry properties to the pores and thoats.  If you're using 2.8.2, then you can do ``geo = op.geometry.StickAndBall(...)``

**Comment by loaa4** [comment]
It worked,
thank you for your help.
