### ISSUE TITLE
pore_area models are needlessly slow

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2327]
We're using list comprehensions in these models, but could use unbuffered vector operations:

``` python

import numpy as np
import openpnm as op

net = op.network.Cubic(shape=[3, 3])

net['pore.diameter'] = 1
net['throat.diameter'] = np.random.rand(net.Nt)*0.5
net['throat.length'] = 1

net['throat.cross_sectional_area'] =  4/3*np.pi*net['throat.diameter']**2
net['throat.surface_area'] = np.pi*net['throat.diameter']*net['throat.length']
# Find surface are of sphere
temp = 4*np.pi*(0.5*net['pore.diameter'])**2
# Subtract throat openings
a = net['throat.cross_sectional_area']
np.subtract.at(temp, net.conns.flatten(), np.hstack((a, a)))
# Readd throat surface areeas
a = net['throat.surface_area']/2
np.add.at(temp, net.conns.flatten(), np.hstack((a, a)))

```

**Comment by Ni2M** [comment]
Note to self for the PR: np.repeat
@jgostick The current pore_surface_area functions in dev https://github.com/PMEAL/OpenPNM/blob/007c521a4cb93d45beb26cb878b9b1ee1762a4f8/openpnm/models/geometry/pore_surface_area/_funcs.py#L49 don't include addition of throats surface area. I was wondering to confirm that the new changes should only have the subtract part, right?
