### ISSUE TITLE
Should we not import Workspace and Project at root level

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2350]
Currently, `Workspace` and `Project` are imported at root level, so they can be accessed at `op.Workspace` and `op.Project`. I think we did this for convenience so we don't have to do `op.utils.Workspace`, etc. But, it clutters the top-level autocomplete, especially that they're capitalized, so they show up at the top of the list.

@jgostick opinions?

**Comment by jgostick** [comment]
The point was the make them more visible to users, so this is the price we have to pay.
