### ISSUE TITLE
Are reaction_order and z_rds in BV models the same?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2353]
https://github.com/PMEAL/OpenPNM/blob/e74f01925c35aca1d6a5ff9465c9b6ed5f97021d/openpnm/models/physics/source_terms/_funcs.py#L562-L570

https://github.com/PMEAL/OpenPNM/blob/e74f01925c35aca1d6a5ff9465c9b6ed5f97021d/openpnm/models/physics/source_terms/_funcs.py#L686-L694

**Comment by ma-sadeghi** [comment]
@Ni2M @jgostick

**Comment by jgostick** [comment]
This confusion is now resolved by the recent PR
