### ISSUE TITLE
Pass size factor models explicitly to Imported class

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2362]
Currently, the information about which size factor model to use is part of `ImportedSettings` class, which is fine, but it's very error-prune and "hacky". Basically, the default values `pore_shape="cone"`, and `throat_shape="cylinder"` need to get concatenated in a very special way to match the model name, then `getattr` is called, etc. This doesn't seem very robust, and it hides the fact that the size factor model is going to be applied. Why not explicitly pass those two models (of course keep `cones_and_cylinders` as the default choice)?

**Comment by jgostick** [comment]
Or what about removing this altogether and instructing people to add their own pore-scale geometry models after import.  

Also, this is a bit irrelevant now, as per the discussion in #2399

**Comment by ma-sadeghi** [comment]
Yes, that'd be more explicit, and I'm all for explicit!

We're removing geometry and physics objects, but they still need to add size factor models to the network, right?

**Comment by jgostick** [comment]
Yes, the user will still have to do ``pn.add_model_collections(op.models.collections.physics.standard)``.  

That does seem a bit verbose though doesn't it?

**Comment by ma-sadeghi** [comment]
Yes, a bit, but at least they know what they are getting. Btw, I think they also need to add a geometry collection as well since size factor models are under geometry. Actually, not a collection, they rather need to just add the size factor model.

On a relevant note, now that there's no geometry/physics object, do we still want to keep geometry/physics models? or move them into network/phase?
