### ISSUE TITLE
OpenPNM attempting to change project name

### ISSUE THREAD

**Issue by akin-aroge** [PMEAL/OpenPNM#2368]
_(Note, you don't have to fill out every section here. They're just here for guidance. That said, nicely detailed feature requests are more likely to get dev attention sooner)_

**Describe the bug**
Are there rules for naming project? I tried initializing a project with the string `proj_dry`, but it appears OpenPNM is attempting too change the name to include an integer value in place of 'dry'. Problem goes away when I replace dry with an integer value

**To Reproduce**
Steps to reproduce the behavior, ideally a code snippet that only reproduces the bug:
```python
# import relevant packages
import porespy as ps
import openpnm as op

# generate sample binary image
im = ps.generators.overlapping_spheres(shape=[50, 50, 50], radius=10, porosity=0.5, iter_max=0)

# initializw workspace
ws = op.Workspace()
ws.clear()

# initialize project
proj_dry = ws.new_project(name='proj_dry')

#extract network
net = ps.networks.snow(im=im, boundary_faces=['right'])
```

**Expected behavior**
assign project name as specified

**Screenshots**

**Additional context**

**Comment by jgostick** [comment]
Hmmm, what happens if you don't use ``proj`` in front, but someting like ``foo``?  My thought is that the code looks for ``proj`` as a sort of default.

**Comment by jgostick** [comment]
Hi @akin-aroge 
I think I'm going to close this issue since we are changing a lot of things in the on-going V3 marathon, and I expect this bug wont' be an issue any longer.  Thanks for letting us know though!
