### ISSUE TITLE
ModuleNotFoundError: No module named 'openpnm.phase'

### ISSUE THREAD

**Issue by HP199731** [PMEAL/OpenPNM#2371]

**Comment by ma-sadeghi** [comment]
This has changed in OpenPNM v3, which hasn't been officially released. Please install the `dev` branch until we publish an official release.

Uninstall your current installation first:

```bash
pip uninstall openpnm
```

and then install the `dev` version.

```bash
pip install git+https://github.com/PMEAL/OpenPNM.git@dev
```
