### ISSUE TITLE
How should ``interpolate_data`` work?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2388]
When called ``obj.interpolate_data('pore.temperature')`` would expect:

(a) It finds the 'throat.temperature' values, and interpolates them to return the 'pore.tempature' values, or...
(b) If looks up 'pore.temperature' and returns the 'throat.temperature' values?

In other words, is the arg telling the function what to return or what to interpolate?

**Comment by jgostick** [comment]
This is a "no-brainer' now.  I have been playing with various pore-scale models where interleaving is used, and it's 200% obvious that you should request the data that you "want" not what you "have".  There are several places in the code where it interprets the request, parses the args, etc, which all goes away if you just do go with the "want" approach.  This has been implemented in V3 and we'll just have to update the places that work based on the old way.

**Comment by ma-sadeghi** [comment]
> ... and we'll just have to update the places that work based on the old way.

@jgostick Have you already made this change on your branch? If not, maybe reopen this issue?

**Comment by jgostick** [comment]
Yes I have changed it and am addressing the issue where ever it crops up.
