### ISSUE TITLE
Fix Butler Volmer models

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2394]

**Comment by Ni2M** [comment]
Brief summary of the meeting:

- [x] Change the naming: beta (symmetry factor), n (electrons), nu(gama). Explain eq, with reference.
- [x] Add reference to Newman's textbook
- [x] Upload ppt

**Comment by Ni2M** [comment]
[Rigorous derivation of BV based on Newman's textbook](https://github.com/PMEAL/OpenPNM/files/8627195/BV.checkings.pptx)
