### ISSUE TITLE
How to handle labels on different objects?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2405]
At the moment, the labels tend to be concentrated on the ``network`` object, but when applying models to a ``phase`` we need the labels to be present on it.  The current workaround is to transfer the labels over, so ``phase['pore.left'] = net['pore.left']``.  This is a bit annoying, so solutions are needed.  I'll list some options that come to mind:

1.  Automatically lookup the label on network if not found on phase.  This could be caught in the ``phase.__getitem__`` subclassed method very easily.  Should this work the other way too, and lookup from ``phase`` if not found on ``network``?
2. Store all labels on the ``project`` instead of the objects themselves.  This is a bit crazy and probably too much of a change, probably also too much code...but it does have a certain appeal.

**Comment by jgostick** [comment]
Option 1 above works very well, as long as it's not too confusing. Basically, if we think of phases having the following relationship to networks, then the connection between them is more clear.

```mermaid
  graph TD;
      A[pn] --> air;
      A --> water;
      A --> oil;
```

Note also that adding the ability to look up missing data from the network means that ALL types of data can be looked up, like 'pore.diameter'.  Not sure if this is good or bad.

Another thing to think about: if a user added 'pore.label' to the phase, then phase['pore.label'] will return the label on phase, regardless of what's on the network.  We *could* prevent this, by blocking the use of 'pore.label' if already present on network, but I'd like to avoid overly complex rules behind the scenes, and lean instead towards "we're all grown-ups" which is the python mantra for 'do what you want and live with the consequences'.

**Comment by jgostick** [comment]
I'll just note here that the reverse cannot be supported, since ``pn['pore.temperature']`` would find values on ALL the phase objects.  I guess it could be supported but it doesn't seem very useful.

**Comment by ma-sadeghi** [comment]
> I'll just note here that the reverse cannot be supported, since pn['pore.temperature'] would find values on ALL the phase objects. I guess it could be supported but it doesn't seem very useful.

Agreed, not very helpful.

> Another thing to think about: if a user added 'pore.label' to the phase, then phase['pore.label'] will return the label on phase, regardless of what's on the network. We could prevent this, by blocking the use of 'pore.label' if already present on network, but I'd like to avoid overly complex rules behind the scenes, and lean instead towards "we're all grown-ups" which is the python mantra for 'do what you want and live with the consequences'.

Agreed, would add complexity, which we're trying to get rid of in the first place by refactoring `Base`.

> Automatically lookup the label on network if not found on phase. 

Sounds good to me.

@jgostick Quick question: let's say you define `pore.domain1` on network. What happens if you ask for `throat.domain1`? Would it try to "interpolate"?

**Comment by jgostick** [comment]
> Quick question: let's say you define pore.domain1 on network. What happens if you ask for throat.domain1? Would it try to "interpolate"?

Great question!  At the moment I am throwing an error if someone tries to interpolate a boolean, for that exact reason.  There is not really a good default behavior for this, so an errors seems like the only good approach.

**Comment by jgostick** [comment]
Option 1 has been implemented:  phase['pore.coords'] will return coords from pn.
