### ISSUE TITLE
Appending '@all' to models with domain='' may have been a mistake

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2406]
I am finding lots of 'gotchas' popping up where the model was added as ``net.add_model(propname='pore.blah', model=f, domain='')`` then it gets stored as ``pn.models['pore.blah@all']``, but I'm expecting it to be called ``pn.models=['pore.blah']``.  For instance, doing ``pn.regenerate_models('pore.blah')`` fails since there is no model with that name.  I also had to overload the ``__delitem__`` method on the ``ModelsDict`` to delete ALL models that end with @<something> if 'pore.blah' is given instead of 'pore.blah@all'.  These little things keep popping up, is a sign of a problem.

**Comment by jgostick** [comment]
Another problem it causes: It breaks the update method.  When models are added we append ``@all``, but this now requires that we overload the ``update`` method on the ModelsDict, so you can't "just add" models anymore.

**Comment by ma-sadeghi** [comment]
From previous dev meeting:

- Maybe add `domain="all"` as argument to `regenerate_models` to make it more explicit.

**Comment by jgostick** [comment]
I also think that maybe overloading the ``update`` method on the models dict might be ok too, so it adds the '@all'.  I think I'll at least try to follow this idea to its logical conclusion and see how it shakes out.

**Comment by jgostick** [comment]
I have overloaded a few methods on the ``ModelsDict`` and things are working ok, so we can commit to sticking with the @all thing.
