### ISSUE TITLE
Dragonfly by ORS x-ray imaging software --- OpenPNM plug-in  

### ISSUE THREAD

**Issue by MarkyMark-thefunkybunch** [PMEAL/OpenPNM#2416]
In the OpenPNM plug-in in the Dragonfly x-ray image analysis software, it is not possible to extract numeric pore & throat volume size distribution (or any other physical property measurement, volume is just of particular importance to me). When looking at the statistics of the PNM in Dragonfly, the only available histogram & CSV file data you can get is the frequency % of selected size distribution, not the actual numerical frequency of the pore volumes. 

A quick hypothetical example- knowing the actual number of pores and/or throat between 100-200 cubic microns in size so much more desirable to know than knowing that 7.4% of total pores are in the 100-200 cubic microns. 

I think you could take that frequency percentage & just multiply it by the overall number of pores to get the total number of pores/throats for each percentage, but it would just be simpler & efficient to give the actual numerical frequency of the different pore size classes. Plus, I am pretty sure the option to see the total number of pores & throats is available in Dragonfly. 

I hope to see something like this in Dragonfly + maybe other PNM features sometime sooner than later. 

If I am incorrect on anything I said please let me know and feel free to point me in the right direction as I have been struggling with this for a while now. My plan B is to download the python code & just learn that to do a PNM if the OpenPNM plug-in does give me good results back or if the results I want are unobtainable from using Dragonfly.

**Comment by ma-sadeghi** [comment]
We developed that plugin a few years ago. It's now completely out of date, and we no longer maintain it (actually, we never maintained it! it was a one-time release). I think you should proceed with your plan B as that gives you access to the latest `openpnm`/`porespy` plus you can do much more (the plugin as you mentioned is very very limited). We have tons of examples that you can use to learn how the software works.

**Comment by MarkyMark-thefunkybunch** [comment]
>

**Comment by MarkyMark-thefunkybunch** [comment]
Got it! Thanks so much for the reply. While I am disappointed that the plug-in does not work well & was a one time thing with Dragonfly, I appreciate the follow-up & recommendation for using porespy & openpnm for my work. 

I appreciate it once again!
