### ISSUE TITLE
Update Dragonfly plugin?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2419]
I know that we didn't promise tech support for our Dragonfly plugin, but maybe updating it so that it works with the latest `porespy`/`openpnm` might not be a bad idea, of course if it's not going to take more than 5 hours of our time...

**Comment by muntahi398** [comment]
Hello, on  the Dragonfly software, what is the unit of Permeability they calculate using OpenPNM? cm2 or mD? 
![image](https://user-images.githubusercontent.com/28182093/189626280-9179ac49-828c-4539-88c1-c147e472a9da.png)

**Comment by ma-sadeghi** [comment]
Hi @muntahi398, neither, it's m2. OpenPNM uses SI units.

**Comment by muntahi398** [comment]
Thank you very much for confirming.
