### ISSUE TITLE
trim_pores error message using openpnm dev version

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2434]
### Discussed in https://github.com/PMEAL/OpenPNM/discussions/2433

<div type='discussions-op-text'>

<sup>Originally posted by **minzhangut** May 16, 2022</sup>
I got an error saying:
`Exception: Your network is clustered. Run h = net.check_network_health() followed by op.topotools.trim(net, pores=h['trim_pores']) to make your network fully connected.
`

I found that there are "isolated_pores" and "disconnected_pores" instead of "trim_pores", so I used `op.topotools.trim(network=pn, pores=h['disconnected_pores'])` instead.

So I think the error message from openpnm should be updated.
</div>

**Comment by ma-sadeghi** [comment]
Fixed in #2444
