### ISSUE TITLE
`AttributeError: module 'openpnm' has no attribute 'Metrics'`

### ISSUE THREAD

**Issue by minzhangut** [PMEAL/OpenPNM#2435]
From the Module Reference, I can see 'Metrics' is there. But I got the above error message when I am using openpnm dev version.

**Comment by ma-sadeghi** [comment]
There might be something wrong with your installation. I can see `openpnm.metrics` in mine. Could you print `openpnm.__version__`?

**Comment by minzhangut** [comment]
The version I am using is "2.8.2.dev1118".

This is my piece of code:
```
inv = op.Metrics.porosimetry(network=pn, phase=water)
inv.set_inlets(pores=pn.pores(['xmax', 'xmin']))
inv.run()
```
I got this error message:
`AttributeError: module 'openpnm' has no attribute 'Metrics'`

But when I use "m" instead of "M", I got a different error message:
`AttributeError: module 'openpnm.metrics' has no attribute 'porosimetry'`

I always thought I can use either "Metrics" or "metrics".

**Comment by ma-sadeghi** [comment]
`metrics` (with lowercase M) is the correct module name. I don't know why we don't automatically import `Porosimetry`, but you can manually import it:

```python
from openpnm.metrics._porosimetry import Porosimetry
```

**Comment by minzhangut** [comment]
Got it. Thanks!
