### ISSUE TITLE
`_parse_prop` method fails for edge case (e.g. `pore.concentration.Na_mix_01`)

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#2437]
See [line 1081](https://github.com/PMEAL/OpenPNM/blob/9b209ae9a469018f6e49a3dd05124d7787a42e60/openpnm/core/_base.py#L1081)

For pore.concentration.Na_mix_01 it returns pore.Na_mix_01. The problem is how only the last propname is indexed. This works in most cases except when we have multiple dots. Should we not use the dot then?

**Comment by jgostick** [comment]
This behavior is changed n V3, but on the Base2 class.  The link above goes to the original Base class, which I have kept for now.

**Comment by jgostick** [comment]
Also, if you're using the dev branch, you should inherit from op.core.Domain, which is the Base2 class plus some mixins.

**Comment by mkaguer** [comment]
Ok my bad, I wasn't working on dev branch. Now that I am working on dev branch I see the error actually occurs on this [line](https://github.com/PMEAL/OpenPNM/blob/9b209ae9a469018f6e49a3dd05124d7787a42e60/openpnm/core/_mixins.py#L177)
