### ISSUE TITLE
Errors in examples

### ISSUE THREAD

**Issue by jtecklenburg** [PMEAL/OpenPNM#2452]
The examples show errors. See:
https://openpnm.org/examples/simulations/percolation/relative_permeability_metrics.html
https://openpnm.org/examples/reference/uncategorized/intro_to_openpnm_advanced.html
https://openpnm.org/examples/simulations/multiphysics/advection_diffusion.html
https://openpnm.org/examples/simulations/multiphysics/advection_diffusion.html#Performing-Stokes-flow
This list of links may not be complete.

examples:
![grafik](https://user-images.githubusercontent.com/106079084/169816232-9558e2f8-784a-4b21-bdb1-9b7220cac2f0.png)

![grafik](https://user-images.githubusercontent.com/106079084/169816597-9c34a709-b484-491c-a216-9fc799543217.png)

**Comment by ma-sadeghi** [comment]
We're releasing v3 soon, and all the examples will be updated eventually.
