### ISSUE TITLE
Domain syntax downside(s)

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2471]
I just thought of a down-side to the @domain syntax.  

* Let's say you have created a network, and added some models, eg ``'pore.diameter'``.  
* By default this model will have the ``'@all'`` suffix added to it's model name.  
* Now, let's say you add boundary pores, and you want to give them a different ``'pore.diameter'`` model.  
* The problem is that you already have a ``'pore.diameter'`` model assigned to ``'@all'`` pores, so how to proceed becomes a bit tricky.

At present the most direct solution would be:
* Create a new label, like ``'pore.internal'``, which is all pores *except* the new boundary pores
* Physically reach in and change the name of the existing ``'pore.diameter@all'`` model to ``'pore.diameter@internal'``.  This only requires changing the name of the dictionary key, which is pretty handy, but still requires plenty of 'know-how'.
* You could then add the ``'pore.diameter@boundary'`` model

One alternative solution that occurs to me is that instead of using the ``'@all'`` label by default, we could introduce a new generic label, like ``'domain_01'``.  This label would be added to all pores when a network is created, BUT would be automatically set to ``False`` for all subsequently added pores.  The user would need to give the new pores a name, like ``'domain_02'``, then add their model to that domain.

**Comment by ma-sadeghi** [comment]
Here's an alternative proposal: any label can override 'all'. So if two models share some pores/throats, the one that's more specific overrides the more generic one, which is 'all'.

**Comment by ma-sadeghi** [comment]
Regarding its implementation (although I haven't given it much thought): in 'regenerate_models', always apply 'all' models first, so that more specific models can overwrite previous values (if any).

**Comment by jgostick** [comment]
Hmm, that is interesting.  Run models in the order they were added, which I think happens anyway, then any models added after ``'@all'`` would clobber it.  This actually probably already happens by accident!

**Comment by jgostick** [comment]
So I just confirmed that this basically already works as @ma-sadeghi is proposing.  The following puts 1.0 everywhere since the ``'@all'`` label was added last:

```python
pn.add_model(propname='pore.test',
             model=op.models.misc.constant,
             value=2.0,
             domain='left')
pn.add_model(propname='pore.test',
             model=op.models.misc.constant,
             value=1,
             domain='all')
pn.regenerate_models()
```

While this block gives 1's and 2's:

```python
pn.add_model(propname='pore.test',
             model=op.models.misc.constant,
             value=1.0,
             domain='all')
pn.add_model(propname='pore.test',
             model=op.models.misc.constant,
             value=2,
             domain='left')
pn.regenerate_models()
```

So aside from *maybe* checking that ``'@all'`` are run first, nothing needs to change.  Iguess I was just getting over-worried about things.

**Comment by ma-sadeghi** [comment]
@jgostick Do you think it might be worth it to add a unit test for this? (in case regenerate_models gets modified in the future)
