### ISSUE TITLE
Documentation - installing pypardiso on windows

### ISSUE THREAD

**Issue by DougAJ4** [PMEAL/OpenPNM#2481]
I was just browsing this site and noticed that the installation documentation says that pypardiso is not available for Python 3.7+ on Windows.

I installed pypardiso with Python 3.10 on Windows about a week ago, with a standard pip install.  I installed the MKL package before pypardiso, but I don't know if that is required or not.

**Comment by ma-sadeghi** [comment]
Thanks for reporting it. Could you please post the link to the documentation where it says that?

**Comment by DougAJ4** [comment]
https://pypi.org/project/pypardiso/

"Installation
PyPardiso runs on Linux, Windows and MacOS. It can be installed with conda or pip. It is recommended to install PyPardiso using a virtual environment."

I didn't use a avirtual environment, but it installed for me with no problems.

**Comment by jgostick** [comment]
We've unpinned the Discussion item that mentioned this problem.
