### ISSUE TITLE
Use 'pore.source.<name>' to identify all sources?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2491]
At the moment we have ``alg.settings['sources'] = <list of keys>`` which we look at to find out if any sources have been defined and what they are.  We recently had a bit of a eureka with using ``'pore.bc'`` to indicate boundary conditions (which btw, allows infinite flexibility in the BC machinery!).  I am now thinking we could do the same with sources?  So, we write ``alg['pore.source.rxn_1']`` and ``alg['pore.source.rxn_2']``, meaning that ``alg['pore.source'].keys()`` would return ``['rxn_1', 'rxn_2']``.  At the moment we just write ``alg['pore.rxn_1']`` and ``alg['pore.rxn_2']``, so not really a huge change. Also note that these are ``bool``s so just contain ``True/False`` of locations where the sources should be applied. This should be a very simple change (the bc_value to bc.value was easy!)

**Comment by jgostick** [comment]
@ma-sadeghi, @Ni2M and @mkaguer, can you give this suggestion some thought?  If we think it's a good idea I'll roll it into my BC refresh PR.

**Comment by ma-sadeghi** [comment]
@jgostick My first impression is that it makes the code more organized. Previously, there was no straightforward way to distinguish between different labels and to see which ones are source terms (of course you could look into your alg.settings), but with this proposed change, it will be more obvious by just looking at the dict keys. So, I think it has some upsides.
