### ISSUE TITLE
An error is reported when this case is executed (relative_permeability_metrics.ipynb)

### ISSUE THREAD

**Issue by kviitly** [PMEAL/OpenPNM#2502]
### Discussed in https://github.com/PMEAL/OpenPNM/discussions/2499

<div type='discussions-op-text'>

<sup>Originally posted by **QRW-bot** July  4, 2022</sup>
hello，dear development team. Thanks to this open source project, it is convenient for me to learn pore network simulation.
While running the relative penetration simulation case (relative_permeability_metrics.ipynb) provided by the website, An error is reported, that is "'NoneType' object has no attribute 'keys'".
![image](https://user-images.githubusercontent.com/97141125/177121576-33a336c9-5282-46db-80e8-660189b20aa9.png)
This line of code seems to get a collection of 'flow_inlets', but it doesn't seem to have typed 'flow_inlets'. How to solve this error please</div>

**Comment by kviitly** [comment]
Got a same problem

**Comment by jgostick** [comment]
Can you tell me what version of openpnm you are using?  If you do ``op.__version__`` at the python command line what do you get?

**Comment by kviitly** [comment]
Yes, sure, i have '2.8.2' version
![image](https://user-images.githubusercontent.com/108404519/177713510-ef1387ad-054c-46df-9dea-fbc8fa337875.png)

**Comment by jgostick** [comment]
OK, thanks. Just wanted to make sure your problem wasn't from something old or still in development.

Looking at your error it seems that flow inlets have not been set.  Had they been set, then the call to ``settings['flow_inlets']`` would have found them.  So, are you running the example notebook exactly as it is on the site, or have you made some customization to it?

**Comment by jgostick** [comment]
In V3 we have removed all the pre-written metrics in favor of detailed examples with explanations.  Since V3 will be released soon, I am going to close this issue.
