### ISSUE TITLE
Maybe the algorithms should not return the solution object

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2513]
The solution object is already attached to the algorithm, so I think no need to return it as well. Plus, the `run` method doesn't imply returning anything, so nobody really expects it to return anything.

**Comment by jgostick** [comment]
I think I agree, we should not return anything, to stress the fact that info/data is attached to the object, or stored in the dict.  It would be confusing to have it available via multiple different approaches.

**Comment by ma-sadeghi** [comment]
Fixed in #2352
