### ISSUE TITLE
Gotchas when using gauge pressure

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2517]
When using gauge pressure, some models break down silently, for instance the diffusivity model for `Air`. Maybe we should advertise somewhere so users don't use gauge pressure at all.

**Comment by jgostick** [comment]
We should probably write an example about how units are handled (or not) in OpenPNM.  This could include (a) a warning to always use SI and absolute values, (b) why we don't use pint or unyt, (c) ???

**Comment by jgostick** [comment]
A bullet has been added to #2521 to remind us to write an example about units, so we can close this.
