### ISSUE TITLE
`flatdict` is not compatible with Python 3.10+

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2542]

**Comment by jgostick** [comment]
I think this can be removed, but will require a bit of work.  It is used in the IO classes.

**Comment by jgostick** [comment]
Strange though, since python is supposed to be backwards compatible, so if `flatdict` hasn't changed anything it should still work.  Better error message is needed.

**Comment by jgostick** [comment]
This seems to be a false positive, so closing

**Comment by ma-sadeghi** [comment]
It seems that Python 3.10 has removed `MutableMapping` from `collections` module (moved it to `collections.abc`), see this stackoverflow answer:

https://stackoverflow.com/a/71902541/3438239

So, I'm reopening it. It'd be great if we could avoid using `flatdict` altogether since it seems to not be actively maintained.
