### ISSUE TITLE
Extracted network mistaken for a directed network

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#2545]
An exception was raised in `find_connected_nodes` triggering an error that said, "This function is not implemented for directed networks".  Talking to @ma-sadeghi I learned that a directed network has at least one bidirectional throat.  When I check my network health, however, I have zero bidirectional throats. So I don't know why my network is triggering this warning. I am working on an extracted network. While I manipulated the 'pore.coords' I did not change 'throat.conns' at all. I can confirm as well that my throat.conns are conditioned well as i < j for any throat (i, j).

Click [here](https://github.com/PMEAL/OpenPNM/blob/51443ec18d43b239e20f221d782a09b6782d8908/openpnm/_skgraph/queries/_funcs.py#L135) to see where the exception was triggered.

**Comment by ma-sadeghi** [comment]
@mkaguer Could you please post a MWE (minimum working example) that reproduces the bug?

**Comment by jgostick** [comment]
This was not a bug in openpnm, but a bug in the network extractor. however, it reveals that we should have a better explanation of our 'convention' for what directed means.  I am going to add this to the list of examples we should make.
