### ISSUE TITLE
Re-add `throat.end_points` models

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2554]
We removed these since they are no longer needed for the conductance calculations, but they are still useful.  For instance, I'm trying to plot a pore-throat-pore image and it would help a lot if I had the endpoints model available.  It doesn't have to be added to the objects, just available in the library if needed.

**Comment by ma-sadeghi** [comment]
@jgostick We currently have conduit length models, but not exposed, we might be able to write a generic throat endpoint model (instead of adding one for each conduit type, i.e., spheres and cylinders, etc.), by accepting `throat.conduit_lengths` as argument... Just an idea.
