### ISSUE TITLE
`Voronoi` generates 3D network when passing 2D shape

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2562]
When passing `shape=[5, 5]`, `Voronoi` still generates a 3D network, need to explicitly pass `shape=[5, 5, 0]` to make it 2D.

**Comment by jgostick** [comment]
That's not a bug.  That should give you a cylinder.  You can 2D network use [5, 5, 1].

**Comment by ma-sadeghi** [comment]
@jgostick Maybe we should update the docstrings then? The cylindrical shape is not mentioned.

https://github.com/PMEAL/OpenPNM/blob/453225075bd881b4690eae33200cd8388d175c68/openpnm/network/_voronoi.py#L22-L31
