### ISSUE TITLE
Add (or readd) tests to various places

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2573]
- [x] models.viscosity.air_correlation
- [x] models.viscosity.gas_pure_st
- [ ] ~~models.viscosity.gas_pure_cls~~
- [x] add `#pragma: no cover` to critical props funcs
- [x] add `#pragma: no cover` to models.diffusivity.gas_mixture_fw
- [x] models.vapor_pressure.liquid_pure_lk
- [x] models.vapor_pressure.liquid_pure_antoine only test the extended one, so add check for case where extended data is not found
- [x] models.thermal_conductivity.liquid_mixture_DIPPR9I
- [x] models.thermal_conductivity.liquid_pure_sr
- [x] phase.Mixture is tested, but not very thoroughly
- [ ] ~core.Base2 --> obj['conduit.diameter'] behavior is not tested~
- [x] core.Base2.keys with modes like models and constants
- [x] core.Base3.get_conduit_data has an 'edge case' that is not being covered
- [x] core.mixins.ModelsDict.__str__ should have `#pragma: no cover`
- [x] In fact, let add `#pragma: no cover` to all print, repr and str funcs
- [x] core.mixins.ModelWrapper needs tests throughout
- [x] algorithms.drainage.pc_curve is not tested at all
- [x] algorithms.Transport._validate_data_health should be tested against a "bad" case so that all the logic get triggered
- [x] network.Network.get_incidence_matrix
- [x] network.DelaunayVoronoiDual has several added functions that are not being tested
- [x] network.Gabriel is not tested at all  (consider just deleting?)

**Comment by jgostick** [comment]
- [x] skgraph and topotools need VERY thorough tests

**Comment by jgostick** [comment]
The following modules are all below 90% coverage and represent nearly a hundred lines.

- [x] models.geometry.conduit_lengths
- [x] models.geometry.throat_length
- [x] models.geometry.throat_capillary_shape_factor
- [x] models.geometry.throat_endpoints

**Comment by ma-sadeghi** [comment]
Closed in #2574
