### ISSUE TITLE
Remove the py module

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2612]
This is causing our nightly builds to fail, no sign of what went wrong but while digging I see that the devs [discourage](https://github.com/pytest-dev/py) its use

**Comment by jgostick** [comment]
After more digging this looks to be coming from another package. We seem to have pep8 and pycodestyle packages being installed, as well as flake8.  We should just use flake8 since it's the only one being maintained.

**Comment by jgostick** [comment]
Flake8 worked like a charm...and caught about 1000 errors!

https://github.com/PMEAL/OpenPNM/actions/runs/3340839408/jobs/5531397000#step:9:33

**Comment by jgostick** [comment]
Nice thing about this (I think) is that it's run as part of the ubuntu-latest tests, so only that one fails if any formatting is wrong. So we can at least know that tests all pass, and it's only a pep8 error.

**Comment by ma-sadeghi** [comment]
@jgostick I just learned that the author of `pycodestyle` has published a new release, fixing the `py` import that originated from his package. However, I still think that `flake8` is more mature and we probably should switch anyway.
