### ISSUE TITLE
Endless debug loop by `StokesFlow`

### ISSUE THREAD

**Issue by JorgeESantos** [PMEAL/OpenPNM#2621]
Had a script running fairly clean for permeability calculation using the StokesFlow() algorithm. Now, the script raises an **endless Warning loop** saying "WARNING  throat.ad_dif_conductance was not run since  _models.py:480
                    the following property is missing:                         
                    'throat.diffusive_conductance'"

![image](https://user-images.githubusercontent.com/114251367/200612465-05389e3f-230e-49bd-a764-78d8f76aa515.png)

Why does it raise this now when, in the past, I was able to run it without the phase property of 'pore.diffusivity' and therefore the 'throat.diffusive_conductance' property? Furthermore, I cannot define diffusivity no matter how hard I try with the available models.

``` python
from functions import TPMS_engine, scatter_3Ddataset
import numpy as np
import openpnm as pnm

#Generating Binary image of a porous scaffold
#scaffold, voxel_lenght = Trigo_scaffolds(Geo='b', shape=[2,2,2], elem=27, meshdata=False, min_dimen=13e-3)
scaffold, voxel_lenght = TPMS_engine([2,2,2], elem=40, min_dimen=6.5e-3, iT=0.366, meshdata=False)
#Voxel_image(scaffold, 'oldlace', 'darkgray')

#region Network creations
from porespy.networks import snow2
M0 = np.logical_not(scaffold)
snow_net = snow2(M0, boundary_width=0, accuracy='high',
                 voxel_size=voxel_lenght)
Net = pnm.io.network_from_porespy(snow_net['network'])

#Network manipulation
#needed properties
Net['pore.diameter'] = Net['pore.equivalent_diameter']
Net['throat.diameter'] = Net['throat.equivalent_diameter']
Net.add_model(propname='throat.length',
              model=pnm.models.geometry.throat_length.spheres_and_cylinders)
Net.add_model(propname='throat.lens_volume',
             model=pnm.models.geometry.throat_volume.lens)
Net.add_model(propname='throat.total_volume',
              model=pnm.models.geometry.throat_volume.cylinder)
Net.add_model(propname='throat.volume',
             model=pnm.models.misc.difference,
             props=['throat.total_volume', 'throat.lens_volume'])
Net.add_model(propname='throat.hydraulic_size_factors',
                model=pnm.models.geometry.hydraulic_size_factors.spheres_and_cylinders)

#needed labels
pnm.topotools.find_surface_pores(Net)
border_tol = Net['pore.diameter']/2*Net['pore.surface']
border_tol = np.amax(border_tol[border_tol != 0.0])
#pores_left = Net['pore.coords'][:, 0] <= np.amin([i for i in Net['pore.coords'][:, 0]]) + voxel_lenght
#pores_right = Net['pore.coords'][:, 0] >= np.amax([i for i in Net['pore.coords'][:, 0]]) - voxel_lenght
pores_left = Net['pore.coords'][:, 0] <= border_tol
pores_right = Net['pore.coords'][:, 0] == np.amax([i for i in Net['pore.coords'][:, 0]])
Net.set_label(pores=pores_left, label='left')
Net.set_label(pores=pores_right, label='right')

#checking Network health
Net.add_model(propname='pore.cluster_number',
             model=pnm.models.network.cluster_number)
Net.add_model(propname='pore.cluster_size',
             model=pnm.models.network.cluster_size)
health = pnm.utils.check_network_health(Net)
print('Network processed')
#endregion

#region Phase and physics definition
water = pnm.phase.Water(network=Net, name='water')
water.add_model_collection(pnm.models.collections.geometry.spheres_and_cylinders)
water.add_model_collection(pnm.models.collections.physics.standard)
water['pore.temperature'] = 297
water['throat.temperature'] = 297 #20ºC = 293K
#density
water.add_model(propname='pore.density',
                model=pnm.models.phase.density.water_correlation)
#viscosity
water.add_model(propname='pore.viscosity',
                model=pnm.models.phase.viscosity.water_correlation)
#hydraulic conductance
water.add_model(propname='throat.hydraulic_conductance',
                model=pnm.models.physics.hydraulic_conductance.generic_hydraulic)
water.regenerate_models()
#endregion

#region Setting Flow
flow = pnm.algorithms.StokesFlow(network=Net, phase=water)
flow.set_rate_BC(pores=Net.pores('left'), rates=1/60*1e-6)
flow.set_value_BC(pores=Net.pores('right'), values=0)
flow.run()

#Permeability calculation
P_left = Net['pore.left']*flow['pore.pressure']
P_left = np.mean(P_left[P_left != 0.0])
#P_left = np.mean(P_left) #inapropriado?

Q_inlet = flow.rate(pores=Net.pores('left'), mode='group')[0]
L = pnm.topotools.get_domain_length(Net, inlets=Net.pores('left'), outlets=Net.pores('right'))
A = pnm.topotools.get_domain_area(Net, inlets=Net.pores('left'), outlets=Net.pores('right'))
#L = 6.5e-3
#A = L*L
u = water['pore.viscosity'][0]
#K = (Q * u * L) / (A * P_left)
K = (Q_inlet * u * L) / (A * P_left)

print('Flow simulation performed')
#endregion
```

**Comment by jgostick** [comment]
Hi @JorgeESantos, I have not seen any error like this before, so not exactly sure, but try removing this line: ``water.add_model_collection(pnm.models.collections.geometry.spheres_and_cylinders)``.  This adds geometrical models to a phase, but these are already on the network.  Having them twice can't be helpful.

**Comment by JorgeESantos** [comment]
> Hi @JorgeESantos, I have not seen any error like this before, so not exactly sure, but try removing this line: `water.add_model_collection(pnm.models.collections.geometry.spheres_and_cylinders)`. This adds geometrical models to a phase, but these are already on the network. Having them twice can't be helpful.

Hello Professor. Your suggestion did not work. However, I've figured that changing the physics model from `water.add_model_collection(pnm.models.collections.physics.standard)` to `water.add_model_collection(pnm.models.collections.physics.basic)` does solve the endless loop problem and allows the code to compile.

Thank you for your attention.

**Comment by Clifford-Wang** [comment]
![image](https://github.com/PMEAL/OpenPNM/assets/167417015/93d652ff-dd44-4896-a382-065fd0f50aeb)
I'm having the same issue, but I've found that I seem to be missing a definition of water['pore.diffusivity'], this warning disappears after adding, hope it works for you

**Comment by Clifford-Wang** [comment]
![image](https://github.com/PMEAL/OpenPNM/assets/167417015/93d652ff-dd44-4896-a382-065fd0f50aeb)
I'm having the same issue, but I've found that I seem to be missing a definition of water['pore.diffusivity'], this warning disappears after adding, hope it works for you
