### ISSUE TITLE
Error loading modules

### ISSUE THREAD

**Issue by jayaraj777** [PMEAL/OpenPNM#2671]
The current version I use for openpnm is 3.1.1. But modules like openpnm.geometry, openpnm.phases give a "no-module found" error.
![Screenshot from 2023-01-19 00-07-05](https://user-images.githubusercontent.com/123013599/213266004-b2bb5efd-0b8d-48c1-bc85-158b8a62670e.png)
![Screenshot from 2023-01-19 00-07-05](https://user-images.githubusercontent.com/123013599/213266021-2d653458-6385-4341-bedf-6bf716f54c74.png)

**Comment by jgostick** [comment]
You are using an old script with the new version.  I wrote a bit of a blog article on what changed and where [here](http://pmeal.com/posts/2022-10-10-notebook-post/)
