### ISSUE TITLE
Without  pn.pores('top') tag in Voronoi‘s generating network

### ISSUE THREAD

**Issue by LS-Maxwell** [PMEAL/OpenPNM#2728]
Hi, I moved from openpnm2 to openpnm3 and I'm having some problems with it now. The biggest puzzle is why there are no surface labels such as pn.pores('top') in the tags when Voronoi is used to generate network. I think surface labels are very convenient for my work because nerwork can be  generated in openpnm2.  So I suggest that openpnm3 can also add this small function.

**Comment by jgostick** [comment]
In openpnm v3 we wanted to "assume less", partly to reduce the amount of code we need to maintain so we stripped a lot of stuff out.  I agree that labels are handy though, and we do intend to add them.  I'll use this issue as a reminder.  

Note that we'll probably use 'xmin' and 'xmax' instead 'left' and 'right', which is more explicit.
