### ISSUE TITLE
Iterative solver preconditioners

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#275]
As discussed during the last telecon, here is a script showing (a) how to setup a simulation such that outside solvers can be called (i.e. how to access A and b) and (b) some strange business about how the convergence of CG seems to depend on the values in A:

```python

import OpenPNM
import scipy.sparse as sprs

X = 15
Y = 15
Z = 15
Lc = 1

pn = OpenPNM.Network.Cubic(shape=[X,Y,Z],spacing=Lc)
geom = OpenPNM.Geometry.Toray090(network=pn,pores=pn.Ps,throats=pn.Ts)
air = OpenPNM.Phases.Air(network=pn)
phys = OpenPNM.Physics.Standard(network=pn,phase=air,pores=pn.Ps,throats=pn.Ts)

alg = OpenPNM.Algorithms.FickianDiffusion(network=pn,phase=air)
alg.set_boundary_conditions(bctype='Dirichlet',bcvalue=0.5,pores=pn.pores('top'))
alg.set_boundary_conditions(bctype='Dirichlet',bcvalue=0.4,pores=pn.pores('bottom'))
alg.setup(conductance='throat.diffusive_conductance',quantity='pore.mole_fraction')

# First use Scipy's default
x = sprs.linalg.spsolve(A=alg.A,b=alg.b)
print(alg.rate(pores=pn.pores('bottom'),X_value=x))

# Then use CG
x = sprs.linalg.cg(A=alg.A,b=alg.b,tol=1e-15)[0]
print(alg.rate(pores=pn.pores('bottom'),X_value=x))
print('CG fails here since tol was too high')

# Now try this funny little trick
phys['throat.diffusive_conductance'] = phys['throat.diffusive_conductance']*1000
alg.setup(conductance='throat.diffusive_conductance',quantity='pore.mole_fraction')
x = sprs.linalg.cg(A=alg.A,b=alg.b,tol=1e-15)[0]
print(alg.rate(pores=pn.pores('bottom'),X_value=x))
print('CG solved worked this time using the same tolerance, just because conductances were 1000x bigger!')
```

**Comment by jgostick** [comment]
I tried using sp.spilu to get a 'partial approximation' of the inverse of A.  Everything seems to work ok, but when I passed the resulting SuperLU object to the CG solver it threw an error.  This might be a scipy bug because I'm pretty sure that is how things are meant to work.

**Comment by islah** [comment]
Just for an alternative:
Pysparse's iterative solvers are more handy since they're easier to do preconditioner. I do not remember why exactly it was long time ago. This is the case I did

from pysparse.precon import precon
from pysparse.itsolvers import krylov
M = precon.ssor(A.to_sss(), 1., 1)
info, n_iter, relres = krylov.pcg(A.to_sss(), b, x, tol, maxit, M)

But, pysparse's sparse matrix format is not compatible to scipy's.

**Comment by jgostick** [comment]
We decided to stick with Scipy and avoid dependencies on too many packages.  The way GenericLinearSolver is setup now, you can probably find a way to use PySparse.

**Comment by jgostick** [comment]
I think we're ok with the umfpack scikits performance for now.  We can reopen or restart this discussion later if needed.
