### ISSUE TITLE
np.bool used in _vtk.py is deprecated 

### ISSUE THREAD

**Issue by AnnaMareike** [PMEAL/OpenPNM#2757]
**Describe the bug**
I just noticed that running the `project_to_vtk() ` function of `openpnm/io/_vtk.py` will lead to an error message at 
```python
if array.dtype == np.bool:
``` 
as in numpy `np.bool` was deprecated in NumPy 1.20 and instead `np.bool_` or `bool` should be used (please see error message below).

**Error message**

> File "lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
>     raise AttributeError(__former_attrs__[attr])
> AttributeError: module 'numpy' has no attribute 'bool'.
> `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

**To Reproduce**
For me the following raises the Error (My NumPy version is 1.24):
```python
import openpnm

network = openpnm.network.Cubic(shape=[10, 10, 10], spacing=1e-4)
openpnm.io._vtk.project_to_vtk(network.project, filename="test")
```

**Expected behavior**
No error while calling function `project_to_vtk()` .

**Comment by jgostick** [comment]
Thank you.  I included a fix for this in my recent PR to fix the Delaunay/Voronoi bug (#2759)
