### ISSUE TITLE
spheres_and_cylinders does not calculate the hydraulic_size_factors

### ISSUE THREAD

**Issue by xiangWu-WW** [PMEAL/OpenPNM#2764]
Dear Professor:
I write a simple code to import the PNM extracte from Avizo, the net work can normally generate, but when i add geometry feature, it could not generage  throat.hydraulic_size_factors and throat.diffusive_size_factors. It resualt i could calculate its permability. 

import openpnm as op
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def RebuildPNM(file, size=1):
    # Pore ID	Volume	Area	EqRadius	LabelID	 X Coord	Y Coord	 Z Coord	Coordination Number
    pdata = np.array(pd.read_excel(file, sheet_name=0), dtype=np.float16)
    tdata = np.array(pd.read_excel(file, sheet_name=1))
    net = op.network.Network(conns=np.asarray(np.column_stack((tdata[:, 4],
                                                    tdata[:, 5])),dtype=np.int32),
                             coords=np.column_stack((pdata[:, 5],
                                                     pdata[:, 6],
                                                     pdata[:, 7])))
    net['pore.diameter'] = pdata[:, 3] * 2 * size
    net['throat.diameter'] = tdata[:, 2] * 2 * size
    return net

pn = RebuildPNM(file='0Vug.xlsx')
pn.add_model_collection(op.models.collections.geometry.spheres_and_cylinders)
pn.regenerate_models()
print(pn)

from simulation import cal_permeability
out,P = cal_permeability(net=pn,bound=2e-5)
print(out)
ax = op.visualization.plot_connections(pn)
ax = op.visualization.plot_coordinates(pn,ax=ax)
plt.show()
[0Vug.xlsx](https://github.com/PMEAL/OpenPNM/files/11705062/0Vug.xlsx)

Cal permability
def cal_permeability(net,bound=2e-5):
    #添加几何属性
    start_time = time.time()
    net.add_model_collection(op.models.collections.geometry.spheres_and_cylinders)
    net.regenerate_models()

    #定义流体及基本属性
    phase = op.phase.Phase(network=net)
    phase['pore.viscosity'] = 0.01
    phase.add_model_collection(op.models.collections.physics.basic)
    phase.regenerate_models()

    #获取各方向长度，设定出入口孔隙
    x, y, z = net['pore.coords'].T
    Lx = x.max() - x.min()
    Ly = y.max() - y.min()
    Lz = z.max() - z.min()
    labels = ['front', 'back', 'left', 'right', 'bottom', 'top']
    for label in labels:
        if 'pore.' + label not in net.keys():
            net['pore.' + label] = False
    net['pore.front'][x <= x.min() + bound] = True
    net['pore.back'][x >= x.max() - bound] = True
    net['pore.left'][y <= y.min() + bound] = True
    net['pore.right'][y >= y.max() - bound] = True
    net['pore.bottom'][z <= z.min() + bound] = True
    net['pore.top'][z >= z.max() - bound] = True

    flow_x , phase_x = cal_permeability_single_direction(net=net, phase=phase, direction='x')
    flow_y , phase_y = cal_permeability_single_direction(net=net, phase=phase, direction='y')
    flow_z , phase_z = cal_permeability_single_direction(net=net, phase=phase, direction='z')

    mu = 0.01
    delta_P = 3000
    Kx = float(flow_x * mu*Lx/(delta_P*Ly*Lz))/(0.97*10**-15)
    Ky = float(flow_y * mu*Ly/(delta_P*Lx*Lz))/(0.97*10**-15)
    Kz = float(flow_z * mu*Lz/(delta_P*Lx*Ly))/(0.97*10**-15)

    pnVolume= np.sum(net['pore.volume']) + np.sum(net['throat.volume'])
    porosity_micro =((pnVolume)/(Lx*Ly*Lz))*100
    K_ave = (Kx + Ky + Kz) / 3
    outdata = [porosity_micro, Kx, Ky, Kz, K_ave, time.time() - start_time]
    outdata = np.round(np.asarray(outdata), 2)
    return outdata,(phase_x,phase_y,phase_z)

def cal_permeability_single_direction(net,phase,direction = 'x'):

    if direction == 'x':
        inlet = net.pores(['front'])
        outlet = net.pores(['back'])
    elif direction =='y':
        inlet = net.pores(['left'])
        outlet = net.pores(['right'])
    elif direction == 'z':
        inlet = net.pores(['top'])
        outlet = net.pores(['bottom'])

    flow = op.algorithms.StokesFlow(network=net, phase=phase)
    flow.set_value_BC(pores=inlet, values=13000)
    flow.set_value_BC(pores=outlet, values=10000)
    flow.run()
    phase.update(flow.soln)
<img width="851" alt="微信图片_20230609181007" src="https://github.com/PMEAL/OpenPNM/assets/83948137/09e4fbc8-254c-4886-8bf3-712586e7db79">

    return flow.rate(pores=inlet, mode='group')[0],phase

**Comment by jgostick** [comment]
Hi @xiangWu-WW,
1. I apologize for my late response to this.  I missed the email and only noticed it now that I'm scanning through the open issues.
2. Your issue report is not good, it has way too much code for a dev to digest.  You need to provide a minimum example that demonstrates your problem in the simplest way.  This may require some time on your part to figure out how to reproduce it, but its only fair that you invest your time instead of asking the devs to.
3. I think your problem is coming from some bad values in your network, like nans or negative pore sizes or something, because spheres_and_cylinders works fine for me.  That said, we are thinking about making the conductance models more robust and do some extra error checking in them to avoid issues like this, but that will have to wait.
