### ISSUE TITLE
StokesFlow.run() show "A or b contains inf/nan values"

### ISSUE THREAD

**Issue by MJL-JLU** [PMEAL/OpenPNM#2778]
Dear professor
      I generated a batch of model data using avizo and porespy,  but I got this error when running the _flow_run_ function of the Predicting absolute permeability case, I tried several models, only one worked, how should I fix it.

**Comment by jgostick** [comment]
It often happens if your pores are too big and overlap.

**Comment by MJL-JLU** [comment]
> It often happens if your pores are too big and overlap.

Thank you very much for your reply, Professor, is there any way to solve this problem, can this only be determined by the characteristics of the model itself?

**Comment by jgostick** [comment]
start inspecting your pores sizes via graphs, look into the specific values to find the ones that are a probably.  It takes a bit of investigation. If you are using a generated network, then you can increase the spacing too.
