### ISSUE TITLE
Estimation of absolute permeability of multiscale pore network generated from porespy

### ISSUE THREAD

**Issue by anooppandey276** [PMEAL/OpenPNM#2784]
Respected sir,
I was trying to estimate the absolute permeability of a multiscale pore network using openpnm algorithm (stokes flow based). Pore network has been generated using porespy and have been aligned to openpnm. Currently I am facing error of clustering network shown below. 
I have tried to clip smaller clusters but still not getting desired outcomes. Can you please guide me regarding that
![Screenshot (57)](https://github.com/PMEAL/OpenPNM/assets/129926811/f7cf0471-b3a1-4c8d-916a-a4301603d9e3)

**Comment by jgostick** [comment]
Have you looked at [this tutorial](https://openpnm.org/examples/reference/networks/managing_clustered_networks.html)?

**Comment by morendong** [comment]
Following the tutorial, the problem of " clustering network" has been solved. But,  'throat.diffusive_size_factors', 'throat.hydraulic_size_factors', 'throat.hydraulic_conductance', and 'throat.electrical_conductivity'  were missing.    Can you please guide me on how to deal with it?
Thanks.
![image](https://github.com/PMEAL/OpenPNM/assets/141892470/a5b560af-b1f6-4821-954a-48195262ac71)
