### ISSUE TITLE
Newer Version of Numpy Result in Errors

### ISSUE THREAD

**Issue by shillcoat** [PMEAL/OpenPNM#2787]
Newer versions of numpy have gotten rid of the `bool` attribute, resulting in an error being thrown when trying to export a network to vtk format (there are likely other instances where this occurs, but this is where I've encountered it). This is the error:

```
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

An example of this is in the PoreSpy documentation: https://porespy.org/examples/networks/tutorials/snow_advanced.html

**Comment by ma-sadeghi** [comment]
Thanks for reporting it. This has been fixed on the dev branch, I'll issue a minor release today so you can get it from pip.

**Comment by ma-sadeghi** [comment]
Should be fixed now, just run `pip install -U openpnm`.
