### ISSUE TITLE
Network output to STL not working

### ISSUE THREAD

**Issue by LS-Maxwell** [PMEAL/OpenPNM#2797]
Dear Gostick and Sadeghi, 

I would like to inquire about how to export the generated 3D porous media from OpenPNM into an STL file format that can be recognized by COMSOL or other CFD software. I have attempted to use 'network_to_stl', but the 'netgen' within it fails to operate. Therefore, I am wondering if there are any examples available for exporting to an STL file.

**Comment by jgostick** [comment]
This has always been a bit fragile and netgen itself is quite difficult to install properly. We have actually recently proposed to remove these functions since they are more trouble than they're worth...sorry.
