### ISSUE TITLE
how to include deformation in pore network !!

### ISSUE THREAD

**Issue by kunal0kumar0sinha** [PMEAL/OpenPNM#2803]
_(Note, you don't have to fill out every section here. They're just here for guidance. That said, nicely detailed feature requests are more likely to get dev attention sooner)_

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jgostick** [comment]
OpenPNM doesn't have this feature, sorry.
