### ISSUE TITLE
spacing for BodyCenteredCubic network

### ISSUE THREAD

**Issue by PhGum2** [PMEAL/OpenPNM#2892]
Apparently it is required to set the square root of the desired value of the spacing for the BodyCenteredCubic network

Using 
pn = op.network.BodyCenteredCubic(shape=[20, 20, 20], spacing=np.sqrt(1e-4))
gives a network of size 20*1e-4 

the expected behavior should be
pn = op.network.BodyCenteredCubic(shape=[20, 20, 20], spacing=1e-4)
to get a network of size 20*1e-4, isn't it ?

miscellaneous issue 
Actually, the domain length obtained by 
L = op.topotools.get_domain_length(pn, inlets=pn.pores('left'), outlets=pn.pores('right'))
gives 0.0019000, not 0.002 as expected, why ?

**Comment by rongqingpin** [comment]
I had the same issue w/ version 3.4.0, but I think it's fixed with version 3.4.1

**Comment by jgostick** [comment]
Yes, we fixed this problem with this issue #2847, sorry for not responding, this one slipped through the cracks.

**Comment by PhGum2** [comment]
Hi,thank you for the information.  I installed 3.4.1 and it works.RegardsPEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Melanie ***@***.***> Date : 25/02/2024  22:13  (GMT+01:00) À : PMEAL/OpenPNM ***@***.***> Cc : PhGum2 ***@***.***>, Author ***@***.***> Objet : Re: [PMEAL/OpenPNM] spacing for BodyCenteredCubic network (Issue #2892) 
I had the same issue w/ version 3.4.0, but I think it's fixed with version 3.4.1
