### ISSUE TITLE
Log to a file

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#290]
Seems like a good idea to send debug messages to a file, as well as regular logger output to console.

**Comment by jgostick** [comment]
one can also use the stdout to change where the python logger output goes.

**Comment by MichaelHoeh** [comment]
the corresponding command for redirecting the console output to a file would be: 
import sys
sys.stdout = open('filename.txt', 'w')

**Comment by jgostick** [comment]
I looked into this for quite a while and found no way to log to a file AND to the console.  I will close this issue as 'not worth the trouble to address right now'
