### ISSUE TITLE
module 'openpnm.models.physics' has no attribute 'GenericPhysics'Concise description of the feature

### ISSUE THREAD

**Issue by Absinthejiu** [PMEAL/OpenPNM#2915]
_(Note, you don't have to fill out every section here. They're just here for guidance. That said, nicely detailed feature requests are more likely to get dev attention sooner)_

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jgostick** [comment]
You are using a V2 script/code with V3.
