### ISSUE TITLE
Massive overestimation of absolute permeability in extracted networks from Nano-CT Tiff stacks

### ISSUE THREAD

**Issue by andtoni** [PMEAL/OpenPNM#2924]
_(Note, you don't have to fill out every section here. They're just here for guidance. That said, nicely detailed feature requests are more likely to get dev attention sooner)_

**Describe the bug**
Hi all, I would sincerely appreciate some advice.

I start off with importing a 800^3 tiff stack, converting to 3d tiff, segmenting and finally binarising all within my python code.

I then run the snow algorithm, and convert the extracted network using io.network_from_porespy.

Interestingly, the new network lacks surface labels, so I used the topotools.label_faces to assign surface labels, however, if I leave the tol at 0, it only labels a single pore per surface. If I increase the tol to 0.1, this number increases dramatically. Not sure how to approach this step correctly.

I then am able to trim clusters and run the absolute permeability as instructed in the docs, however, my results cause many errors and output extremely high mD values which do not seem possible. I would sincerely appreciate any advice around this.

![Screenshot 2024-07-08 150132](https://github.com/PMEAL/OpenPNM/assets/174879741/39398be6-fa64-41ce-a316-9d36e14f9c31)

**Comment by jgostick** [comment]
Hi @andtoni, I am going to remove the bug label and transfer this over to the Discussion's section because I'm fairly sure this falls under the category of 'needing help' rather than 'bug'.
