### ISSUE TITLE
test_controller fails

### ISSUE THREAD

**Issue by islah** [PMEAL/OpenPNM#301]
I ran test_script.py with the current develop code and got this result:

============================= test session starts ==============================
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 9 items

test_script.py F........

=================================== FAILURES ===================================
_______________________________ test_controller ________________________________

    def test_controller():
        # The following tests check if the Controller's ghost, save, load and clear methods work
        ctrl = OpenPNM.Base.Controller()
        ctrl.clear()  # Clear controller to make sure it has not lingering objects
        ctrl.loglevel = 50
        pn = OpenPNM.Network.TestNet()
        geom = OpenPNM.Geometry.TestGeometry(network=pn,pores=pn.Ps,throats=pn.Ts)
        loc1 = geom.__repr__()
        loc2 = ctrl[geom.name].__repr__()
        assert loc1 == loc2  # Ensure both locations hold same object
        geom2 = ctrl.ghost_object(geom)  # Create a ghost object
        loc3 = geom2.__repr__()
        assert geom.__repr__() == loc1  # Ensure geom is still same object
        assert loc3 != loc1  # Ensure identities are not getting swapped
>       ctrl.save('test_net')  # Save current state

test_script.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../OpenPNM/Base/__Controller__.py:334: in save
    _pickle.dump(self,open(filename+'.pnm','wb'))
/usr/lib/python2.7/pickle.py:1370: in dump
    Pickler(file, protocol).dump(obj)
/usr/lib/python2.7/pickle.py:224: in dump
    self.save(obj)
/usr/lib/python2.7/pickle.py:331: in save
    self.save_reduce(obj=obj, *rv)
/usr/lib/python2.7/pickle.py:401: in save_reduce
    save(args)
/usr/lib/python2.7/pickle.py:286: in save
    f(self, obj) # Call unbound method with explicit self
/usr/lib/python2.7/pickle.py:562: in save_tuple
    save(element)
/usr/lib/python2.7/pickle.py:286: in save
    f(self, obj) # Call unbound method with explicit self
/usr/lib/python2.7/pickle.py:649: in save_dict
    self._batch_setitems(obj.iteritems())
/usr/lib/python2.7/pickle.py:663: in _batch_setitems
    save(v)
/usr/lib/python2.7/pickle.py:331: in save
    self.save_reduce(obj=obj, *rv)
/usr/lib/python2.7/pickle.py:419: in save_reduce
    save(state)
/usr/lib/python2.7/pickle.py:286: in save
    f(self, obj) # Call unbound method with explicit self
/usr/lib/python2.7/pickle.py:649: in save_dict
    self._batch_setitems(obj.iteritems())
/usr/lib/python2.7/pickle.py:663: in _batch_setitems
    save(v)
/usr/lib/python2.7/pickle.py:331: in save
    self.save_reduce(obj=obj, *rv)
/usr/lib/python2.7/pickle.py:419: in save_reduce
    save(state)
/usr/lib/python2.7/pickle.py:286: in save
    f(self, obj) # Call unbound method with explicit self
/usr/lib/python2.7/pickle.py:649: in save_dict
    self._batch_setitems(obj.iteritems())
/usr/lib/python2.7/pickle.py:663: in _batch_setitems
    save(v)
/usr/lib/python2.7/pickle.py:331: in save
    self.save_reduce(obj=obj, *rv)
/usr/lib/python2.7/pickle.py:405: in save_reduce
    self.memoize(obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pickle.Pickler instance at 0x7f5fcfc9f950>
obj = {'TestGeometry_CUmzB': <OpenPNM.Geometry.__TestGeometry__.TestGeometry object ...TestNet_MWlji': <OpenPNM.Network.__TestNet__.TestNet object at 0x7f5fcfc99618>}

    def memoize(self, obj):
        """Store an object in the memo."""
    
        # The Pickler memo is a dictionary mapping object ids to 2-tuples
        # that contain the Unpickler memo key and the object being memoized.
        # The memo key is written to the pickle and will become
        # the key in the Unpickler's memo.  The object is stored in the
        # Pickler memo so that transient objects are kept alive during
        # pickling.
    
        # The use of the Unpickler memo length as the memo key is just a
        # convention.  The only requirement is that the memo values be unique.
        # But there appears no advantage to any other scheme, and this
        # scheme allows the Unpickler memo to be implemented as a plain (but
        # growable) array, indexed by memo key.
        if self.fast:
            return
>       assert id(obj) not in self.memo
E       assert 140050734294552 not in {9532896: (475, <type 'object'>), 9560832: (2, <type 'dict'>), 51509856: (1, <class 'OpenPNM.Base.__Controller__.Controller'>), 51545184: (438, <class 'OpenPNM.Base.__ModelsDict__.ModelsDict'>), ...}
E        +  where 140050734294552 = id({'TestGeometry_CUmzB': <OpenPNM.Geometry.__TestGeometry__.TestGeometry object ...TestNet_MWlji': <OpenPNM.Network.__TestNet__.TestNet object at 0x7f5fcfc99618>})
E        +  and   {9532896: (475, <type 'object'>), 9560832: (2, <type 'dict'>), 51509856: (1, <class 'OpenPNM.Base.__Controller__.Controller'>), 51545184: (438, <class 'OpenPNM.Base.__ModelsDict__.ModelsDict'>), ...} = {9532896: (475, <type 'object'>), 9560832: (2, <type 'dict'>), 51509856: (1, <class 'OpenPNM.Base.__Controller__.Controller'>), 51545184: (438, <class 'OpenPNM.Base.__ModelsDict__.ModelsDict'>), ...}
E        +    where {9532896: (475, <type 'object'>), 9560832: (2, <type 'dict'>), 51509856: (1, <class 'OpenPNM.Base.__Controller__.Controller'>), 51545184: (438, <class 'OpenPNM.Base.__ModelsDict__.ModelsDict'>), ...} = <pickle.Pickler instance at 0x7f5fcfc9f950>.memo

/usr/lib/python2.7/pickle.py:244: AssertionError
====================== 1 failed, 8 passed in 3.20 seconds ======================

**Comment by jgostick** [comment]
My first thought was that these tests were run with Python 2.7, while I work in 3.4.  I don't see these failures, BUT I actually saw a different failure, that I've just spent an hour debugging.  The ghost_object method wasn't working quite right.  I will push my fixes asap.
