### ISSUE TITLE
Utilities - Vertexops Issues

### ISSUE THREAD

**Issue by Elsharqawy** [PMEAL/OpenPNM#313]
In OpenPNM-Utilities-vertexops I noticed the following:
 (1) The porosity function doesn’t include the throats volume which underestimate the porosity.
 (2) The vertex_dimension function uses the pore coordinate to calculate length, area, and volume while this is different from the description. Using pore coordinates underestimates the domain dimensions. 
 (3) The tortuosity function also doesn't work because it depends on the throat.centroid property which we don’t have any more.

**Comment by TomTranter** [comment]
I can only assume your using some of these utility functions on a geometry that isn't Voronoi.
1) I don't consider Voronoi throat volumes to contribute to porosity as pore volume overlaps them
2) It uses Voronoi vertices if they are present
3) Centroids are present with Voronoi
What purpose are you using vertexops for? I originally had most of the methods inside the Voronoi class but moved them into vertexops when saving and loading wasn't using the original geometry class for loaded networks. They could go back into Voronoi now to avoid confusion as most of them are very specific for that. It's also worth saying I've been improving Voronoi quite a bit recently and haven't merged my changes onto develop. There will be quite a bit of code to clean up / remove including many of the functions in vertexops but as it stands it should all work with the Voronoi geometry in develop

**Comment by Elsharqawy** [comment]
Some of these functions are very useful and could be used for cubic networks which I'm using. I wonder if we could add an exception for Voronoi in these functions and make it useful for other network types too?

**Comment by TomTranter** [comment]
Do you have some equivalent of a Voronoi vertex i.e. co-ordinates that bound your pores and throats that you are trying to manipulate? If you'd like to improve the functions and make them more generic then maybe create a branch and do some developing. I can help explain specific functions if needs be. You may also want to look at the DelaunayCubic network as Voronoi geometry will work with that
