### ISSUE TITLE
Generic Porosity Distribution Function

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#316]
At the moment I have a couple of probability distributions which seed regions of a Delaunay network with varying pore density. As I'm using Voronoi geometry this inversely determines the porosity distribution. I want to make this process a bit more user friendly by accepting some arguments such as a list of region fractions and relative porosities for each coordinate e.g. rx = [0.25,0.5,0.25], px = [1.0,0.75,1.0]. This would apply a porosity to a core region spanning half the domain in the x-direction equaling 3/4 that of the surface regions. Feasibly the same parameters could be used for cubic networks but the back-end would work differently and just scale the pore and throat sizes accordingly. It would have to be relative as the pore density is not the only parameter determining the porosity. Fibre diameter also sets it and for cubic it's the lattice spacing. 

So is is worth making a generic function to work with all network types or should I just try and improve Delaunay and can anyone forsee any problems?

**Comment by jgostick** [comment]
As discussed in the telecon today, I think you should either create a new Delaunay subclass, or adjust the existing one to accept a new argument that describes the spatial porosity distribution.

I think the argument 'could' be a 3D image of values varying between 0 and 1.  The generation scheme will then generate a point (3D coordinates), look into this map for the local value there, and keep or discard the point based on the value if finds, then onto a newly generated point.  This way the user can make their own distribution fields and they'll be easy to visualize  I can't think of any other general way.

**Comment by jgostick** [comment]
Any progress on this?

**Comment by TomTranter** [comment]
Yeah I've done it on my branch and will roll in with other delaunay changes, it's not generic enough for cubic though

Sent from my Sony Xperia™ smartphone


---- jgostick wrote ----


Any progress on this?

**Comment by jgostick** [comment]
This is worthy of a pore scale model, which scale the pore seeds in relation to their distance from given surfaces.  I had some sort of equation that did this in my Voronoi paper.  The arguments could be a bit tricky though, since there are so many variables, like distance, depth and direction of the profile.

**Comment by TomTranter** [comment]
This is addressed for Delaunay networks with prob argument. For cubic I agree that it should be linked to seeding. Could use the same input of a 3d probability

**Comment by jgostick** [comment]
For cubic you wouldn't need to send it to the Network generator though, it
could applied afterward via a pore.seed model.  Not sure how to specify the
distribution though...need to think about it.  I guess the 3d image is
probably the best way.

**Comment by jgostick** [comment]
This PR was merged
