### ISSUE TITLE
One Physics for each Geometry/Phase intersection

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#318]
As I make the figures for the manual, it would be much clearer if Physics were always only defined at the intersection between a Phase and a Geometry.  This is the way it used to be, but we removed that limitation to decrease the number of Physics objects required.  However, we now have ways to copy all physics models to new objects, so the burden is much lower now...and the added clarity might be worth it. 

This would be a fairly major API change in that it would break old code.  The initialization of Physics objects would be:

    phys1 = OpenPNM.Physics.GenericPhysics(network=pn,geomtery=geom1,phase=phase1)
    phys2 = OpenPNM.Physics.GenericPhysics(network=pn,geometry=geom2,phase=phase1)
    # and so on
    phys1.models = phys2.models.copy()  # would then copy all models from phys1 onto phys2

I suppose to avoid breaking the API we could leave the option of specifying specific pores/throats, but also accept Geometry objects as alternative arguments.  Then we could eventually prevent pores/throats as arguments in some future release.

**Comment by TomTranter** [comment]
Applying physics to subsets of pores in different geometries could be useful also which wouldn't be possible without creating more geometries. I think there are advantages and disadvantages to both approaches so I would be in favour of not breaking things

**Comment by jgostick** [comment]
PR Merged
