### ISSUE TITLE
Implement Code Linting

### ISSUE THREAD

**Issue by bspellio** [PMEAL/OpenPNM#334]
Implementing code linting allows us to automate the process of ensuring that all the code we merge is consistent stylistically. This encourages quality in the code base and makes it more approachable. I believe code linting is going to be coming to code climate soon, but until then we should have a substitute. My recommendation would be that we use the PEP8 style guide, for the most part it's the industry standard: https://www.python.org/dev/peps/pep-0008/

**Comment by jgostick** [comment]
The Spyder IDE that we all use supports the pylint plugin.  The only problem is that it gets very distracting when trying to code, because we get so many warnings.  :-D

**Comment by bspellio** [comment]
Absolutely, that's why automation can be great. 
* Write you code and be aware of the style to the best of your ability
* Open a PR
* Make all the needed style changes in a single commit :+1:
