### ISSUE TITLE
Tracking pore corners

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#335]
If we want to have oblong pores or any sort of aspect ratio we need to track the corners of the pore, not just the center and diameter.   The can already handle this information by storing an ndarray of objects, where each object is a list of coordinates.  The tricky part will be how to visualize this, so I'm guessing that the VTP writer needs to be improved.  Also, we'll need new physics models that account for shape of  pores and throats.  This 'little' change will end up being very BIG, which is why we've not done it yet.

**Comment by jgostick** [comment]
We should revive this.  Forgetting about visualization issues for now, this should be do-able.  I'm thinking the pore-scale model would work like:

> geom.add_model(propname = 'pore.shape',
>                              model=gm.pore_shape.sphere,
>                              diameter='pore.diameter'
>                              res=8)

where res is the number azimuthal and altitudinal angles to generate points at.  The user could then change res later and regen the points to get increased accuracy. This would generated a lot of points, but every pore would have the same number of points (azi * alt).

For cuboids:

> geom.add_model(propname = 'pore.shape',
>                              model=gm.pore_shape.cuboid,
>                              LWH='pore.dimensions')

where 'pore.dimensions' is an [x, y, z] array containing the L, W, H of each pore.  This would generate 8 points (one for each corner).

Calculating volumes would be easy, just find the convex hull around each pore's points.  

Calculating throat properties would become tricky though.

**Comment by TomTranter** [comment]
I know blender can do this type of thing so maybe I can look into how that works and if there are any common packages I can use rather than re-inventing the sphere :)

**Comment by jgostick** [comment]
Interoperability with blender output would be ideal too.

**Comment by jgostick** [comment]
This is less interesting now...we should focus on just have pores and throats with aspect ratios.  The only scenario where this seems useful is if we want ALL pores and throats to be treated the same (i.e. cubes, voronoi cells, extracted networks).  Then this approach would be the common denominator.  I'm not sure we'll be adopting this approach for a long time, so I think we should close this for now.
