### ISSUE TITLE
Refactor general_source_term.py

### ISSUE THREAD

**Issue by bspellio** [PMEAL/OpenPNM#347]
This file is incredibly repetitive and should be dried up so that the type checks for each of the arguments isn't rewritten in each method. The file could probably be at least 300 lines shorter.

**Comment by jgostick** [comment]
The only problem is that 'models' are meant to be stand-alone, rather than
relying on methods elsewhere in the code.  Perhaps you can mahmoud can
discuss a way to refactor it that mains the 'functions only, not classes'
philosophy of models.

**Comment by maghighi** [comment]
Exactly. We need them as functions not classes. I'll look into them again to see how many of the redundant sections I can remove.

**Comment by jgostick** [comment]
It 'might' be something that we can roll into the ModelWrapper 'run'
method.  I'll look at it tonight and see if I can get some ideas.

**Comment by maghighi** [comment]
I noticed that inside each method, 'Checks' for A1, A2, A3, ... are so similar to each other. So even if we don't add them to the ModelWrapper, it is still possible to shorten the code by summarizing similar parts inside each single method. I'll try to this tonight.

**Comment by bspellio** [comment]
> I noticed that inside each method, 'Checks' for A1, A2, A3, ... are so similar to each other.

This is primarily what I was referring too.

**Comment by bspellio** [comment]
#350 Addresses this, closing the issue.
