### ISSUE TITLE
Get to 85% test coverage

### ISSUE THREAD

**Issue by bspellio** [PMEAL/OpenPNM#362]
We should strive to really push our test coverage up now that #354 has been merged. I feel 85% is a good first goal to reach for before we release version 1.2.

**Comment by jgostick** [comment]
Absolutely...we should sit down together and see where the biggest gaps are.   Can you produce some sort of report, like this file, or class, or methods has XX% coverage?  Then we'll know where to get started.

**Comment by bspellio** [comment]
Why was this issue closed?
