### ISSUE TITLE
Building from Matlab file

### ISSUE THREAD

**Issue by Elsharqawy** [PMEAL/OpenPNM#366]
Some changes happen to the super function which made the MatFile in Network gives this error
File "C\OpenPNM\OpenPNM\Network\__MatFile__.py", line 90, in __init__
    super().__init__(**kwargs)
TypeError: super() takes at least 1 argument (0 given)

**Comment by Elsharqawy** [comment]
It seems that all codes that have super are not running. Is this the case with others too?

**Comment by RodericDay** [comment]
it's a python 2 vs python 3 error. py3 avoids redundancy by autofilling super args, but since youre running py2 its still expecting them.

**Comment by jgostick** [comment]
are you able to use Python 3, or is there are reason you're using Python
2.7 still?

**Comment by jgostick** [comment]
@Elsharqawy were you able to solve this problem using python 3.4?  I'll assume yes, and if not I'll reopen this.

**Comment by Elsharqawy** [comment]
Yes, I'm using Python 3 now and it works.
