### ISSUE TITLE
Load error for older files

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#375]
I have some simulations saved from a month or two ago and tried to load them but got an error from pickle because a class definition in ModelsDict has changed name. This isn't really a bug but something we should be aware of as a limitation of pickle. It basically means that OpenPNM is not backwards compatible for previously saved files. Could we try and minimize these types of changes - Moving and renaming classes. Using dill would result in the same problem if classes are renamed but might be an improvement on pickle if we move classes about and change the file structures.
http://stackoverflow.com/questions/2121874/python-pickling-after-changing-a-modules-directory

**Comment by jgostick** [comment]
Yikes, I didn't think about that when I renamed the ModelWrapper (it used
to be GenericModel).  I only thought about how if affected the current
code, which only references it in the back end, so I thought it's be an
invsible change.  We can re-add the GenericModel class as a 'legacy
support' thing.  Let's talk about it today.

**Comment by jgostick** [comment]
Try pasting this into the OpenPNM.Core.__ModelsDict__ file and let me know what happens:

class GenericModel(ModelWrapper):
    r"""
    This class is deprecated, and is replaced by ModelWrapper.  This is kept
    here to support legacy issues.
    """
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

**Comment by jgostick** [comment]
Ooop, the indentation was lost...I assume you can figure it out.

**Comment by TomTranter** [comment]
That works

**Comment by jgostick** [comment]
Awesome, I'll push that little fix, and be sure to stop messing with
things.  It never even occurred to me to think about saved files.  Our
testing framework should consider this somehow.

**Comment by jgostick** [comment]
PR has been made
