### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#398]
The TravisCI badge for the develop branch says we're failing, but when you click it and go to the Travis site we're all green.

Also, the coveralls badge is still not registering.  

@bspellio can you possibly get these sorted before you go, otherwise we'll never get it figured out.

**Comment by bspellio** [comment]
@jgostick for the TravisCI one, if we're not failing, it just means that GitHub has cached the badge and it'll update in a little while. I'll look into coveralls.

**Comment by jgostick** [comment]
The problem also occurs on the OpenPNM website though,even with a refresh.

**Comment by bspellio** [comment]
@jgostick If you use the badges in the README on master, it will work.
