### ISSUE TITLE
Drainage Curve in OP for contact angle less than 90

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#416]
I had a question from a user about the drainage curve when the contact angle is less than 90. I added some code in plot_drainage_curve() to try to always display the non-wetting phase saturation and pressure which works when using the Purcell equation for capillary pressure but not the Washburn equation. This was to try and incorporate imbibition but probably needs more thought,

**Comment by jgostick** [comment]
It's not really drainage if the contact angle is less than 90 is it?  The only way is the Purcell or some more complex model, but it is conceptually incorrect to use the washburn for drainage with theta < 90.

**Comment by TomTranter** [comment]
True but OP could be used for imbibition. I guess we should have two plotting functions or one that handles both with more generic name

**Comment by jgostick** [comment]
I think more generally, we want to start thinking about imbibition algorithms, or incorporating imbibition into IP and OP.  I will open new issue where we can start hashing out the requirements for the new algorithms.

**Comment by jgostick** [comment]
If contact angle is less than 90 (or more generally, if capillary entry pressure is negative), then it's not drainage, it's imbibition :-)  I"m going to close this issue, and we can open a new one called "proper imbition" or something.
