### ISSUE TITLE
 super().__init__(**kwargs) in _Cubic_.py 

### ISSUE THREAD

**Issue by zhangwise** [PMEAL/OpenPNM#426]
Previous version  ----> 1.3 version
super(Cubic, self).__init__(**kwargs)   ---->    super().__init__(**kwargs)

Error information: TypeError: super() takes at least 1 argument (0 given). 

And also for __GenericNetwork__.py

Thank you!

**Comment by zhangwise** [comment]
This problem was solved when the python system was switched from 2.7 to 3.4.

**Comment by jgostick** [comment]
We should probably make it more clear that we develop for python 3.4+
only....thanks for letting us know about the error though.
