### ISSUE TITLE
Geometry models for periodic throats?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#453]
I started making a PeriodicThroat geometry class, but wasn't quite sure what pore scale models to use.  We should discuss this briefly at the telecon then open a PR for it.

**Comment by jgostick** [comment]
I think for the sake of sanity this model should handle internal and periodic throats equally.  Requiring unique geometry's for each creates a big pain.  So the method should accept an argument called 'period_label'=None, but if a string is given it calculates the length of the so labelled throats differently.

**Comment by ma-sadeghi** [comment]
@jgostick Is this proposal still on the table?
