### ISSUE TITLE
Delete Toray120 class?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#455]
Not sure how it got in there to begin with.  The Toray090 class should also just be renamed the Toray class, but this would break things since it gets used quite a bit in the docs and examples.  The difference between 090 and 120 is just thickness, so that is a Network thing not a Geometry thing.

**Comment by TomTranter** [comment]
I created it when I was trying to match capillary pressure data.It had a different pore and throat size distribution. Don't mind if you delete it but clearly not all Toray is the same

**Comment by jgostick** [comment]
This has already been deleted, sorry for not consulting more.  There is not really a good reason to have a huge pile of pre-coded classes for these esoteric materials.  I think we decided to put recipes like this on the website, so if you want to create a Toray120 with the correct porosity profile, you should setup an rst file in the documentation.
