### ISSUE TITLE
Run the examples and tutorials as tests

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#464]
It seems that our examples and tutorials are often broken or out of date.  This can be very frustrating for people, so perhaps we would could have pytest run these too?  

I'm guessing this would be a pain, so a work around could be to copy them into the test/integration folder, remove all the text and just leave the code.

**Comment by jgostick** [comment]
I started a branch on this will make it a PR soon.  The bottom line is this:
* pytest can run code in rst files ONLY if it's a \>>> style line, 
* Code inside the .. code-block:: python sections is ignored, which is actually kinda useful for some things we don't want tested like printouts of objects or matplotlib graphs.  
* We must go through the rst and convert all to the \>>> format, but the docs need an overhaul anyway. 
* The problem with \>>> is that it's not cut-and-paste-able.  The \>>> are a pain.  Maybe there's a way to have sphinx add the ability to remove these like docutils does (ie. the object inspector).

(I might merge it with the 'improve_getting_started' PR since it's documentation related).

**Comment by TomTranter** [comment]
Maybe we could include a link to a full script at the bottom of each example document so people don't have to remove the >>> but can still read the code in line. Trouble is then I guess we're maintaining twice the code. Maybe notebooks are the way to go after all

**Comment by jgostick** [comment]
There is a way to add a button to remover the >>> in sphinx.  Many sites
have one (ie. astropy), we just need to figure out how to activate it in
our sphinx theme.
