### ISSUE TITLE
Change all examples to ipython notebooks?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#478]
I think Ipython notebooks are a stupid way to code, BUT...I think they may have value for our examples and tutorials.

- These are actually rendered on Github so users could see them when browsing our code. 
- They are also 'run' so errors would be noticed.
- They do look quite nice
- I'm not sure how to render them on the openpnm docs site.  probably a pain.

**Comment by TomTranter** [comment]
When I was learning python I came across this 12 steps to Navier Stokes guide written in ipython notebooks. http://lorenabarba.com/blog/cfd-python-12-steps-to-navier-stokes/ - I actually preferred watching the youtube videos that went with them and thought the notebook format was a bit silly and would rather just have a full script. However, I think lots of people do like them and they have some advantages. They also lend themselves well to the lesson format. I'd be happy to help re-write them

**Comment by jgostick** [comment]
Let's try to run examples with pytest instead.
