### ISSUE TITLE
New drainage algorithm and late pore filling bugs

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#486]
When using the new drainage algorithm a couple of things can break. Returning results before the get_drainage data method has been run results in an error as self._pore_filling hasn't been created. Both late pore filling models need to handle when Pc <= 0
When a late pore filling model is applied and a residual non-wetting phase is also applied the drainage data does not reflect the residual saturation. The late pore filling model recalculates it so drainage needs to override the saturation for the residual pores or the late pore filling model needs to leave them alone

**Comment by TomTranter** [comment]
Also I think return_results should return all the results as OP does not just the phase occupancy as these are useful for visualizations in paraview

**Comment by jgostick** [comment]
Do you want to try debugging/upgrading this?  I guess we should also add
new unit tests for these cases which you described.  The code was 99%
covered but that doesn't mean it correct :-(

**Comment by TomTranter** [comment]
Yeah, no problem. I started looking at it today as I want to start writing an imbibition algorithm and wanted a feel for how the new one worked. If we were being professional about testing we should always get a fresh pair of eyes on any new code to put it through it's paces. I think running things in the right order is not always obvious and was something highlighted with JM. Is the plan to remove OP in the future? Is it too difficult to write a general percolation algorithm from which drainage and imbibition could derive from as a lot of the logic and methods will be the same?

**Comment by jgostick** [comment]
The problem with our coding approach is that nobody has the time to review
others' code, and we're too impatient to wait before merging.  We should
definitely try to be better.  Anyway, I think we'll keep OP as it can do
bond and site percolation and could in principle do imbibition and drainage
I suppose.  Are you suggesting that we make a GenericOrdinaryPercolation
algorithm, then have Drainage and Imbibtion inherit from it?  I think that
sounds pretty good!

**Comment by TomTranter** [comment]
Yes I think a simple imbibition algorithm wouldn't be too different from the drainage algorithm so it makes sense to inherit from a common parent algorithm - less code to maintain and more streamlined functionality. _apply_percolation would be the only major difference with most of the setup methods being the same. Trapping and fractional filling might need to change a bit. Maybe even invasion_percolation could be included as a run method say as a transient method whereas ordinary percolation is steady state

**Comment by TomTranter** [comment]
With these specific issues I raised. It could be solved by moving the pore_filling model configuration and the pore and throat dictionary key assignment into setup instead of having them in get_drainage_data. This would reduce the flexibility a little but allow return_results and get_drainage_data to be run in any order. I don't know which is better? I guess this touches on a slightly deeper question which is do we need two methods that return data, one in the form of a dictionary which is more like results and one which updates phase information called return_results? My feeling is that the phases we pass into our algorithms should be updated automatically. This might require changing the algorithms a bit using the inner and outer loop functionality and introducing a timing concept if we were to couple them together but is more object orientated and I think better in the long run.

**Comment by jgostick** [comment]
I agree that the late pore filling info should go into setup, as well as
the pore_ and throat_prop assignments.

I'm not sure we should automatically update the phase.  This breaks the
idea of data encapsulation.  On the other hand, passing the phase in as an
argument does imply that it is being used in/by the algorithm.  I'll add a
discussion item to the next telecon agenda.

**Comment by maghighi** [comment]
We usually pass the phase in as an argument, because we not only need to access the pure data of that particular phase, but also need to know the connections between that phase and the other objects (sub-phases, physics, geometries, ...) to pull the data from them too. 

Generally speaking, I do not think we should update phase automatically. Maybe it makes sense for some of the algorithms, but generally I don't think so. I think it is OK to do this for one specific algorithm but not for the generic algorithm. In my simulations, most of the time I run several algorithms without even touching the phase (for example running several percolation regimes for one network). I guess the user should be able to update the data whenever and wherever it is necessary. Especially for the iterative simulations -when we need to run so many intermediate algorithms- automatic updating makes the coding extremely difficult.

**Comment by jgostick** [comment]
fixed with merging of PR #490
