### ISSUE TITLE
List of 2.0 Changes

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#491]
This issue is meant to collect a list of major/important changes we'd all like to see in version 2.0, meaning backwards incompatible.  This list should NOT contain features (i.e. algorithms and other things that could be added to 1.X, but only fundamental changes to the framework.

1.  The concept of Reactions: Stoichiometry, components, mixtures
2.  Rename Network to Topology, create a Network container that wraps each simulation
3.  Improve the way objects are linked/looked up (ie. net.phases() should return a dict instead of a list)

**Comment by jgostick** [comment]
4. Major rethink of the pore-scale model framework...it's too hard to explain!

**Comment by jgostick** [comment]
* add 'multigraph' (2+ throats connecting 2 pores) and 'digraph' (bi-directional throats) capability to the graph connectivity

**Comment by jgostick** [comment]
* move topological manipulation tools to OpenPNM.Topology.utilities (or tools).  They are currently buried under 'op.utilities.topology' or something.

**Comment by jgostick** [comment]
Rename all modules and submodules using the property capitalization, including chaning OpenPNM to openpnm.

**Comment by jgostick** [comment]
remove pore(throat)_diameter.sphere and .cuboid models (see issue #498)

**Comment by jgostick** [comment]
* Two changes to Pore Scale Models: 

(1) All functions should ONLY accept numerical values (arrays), which makes them MUCH easier to code.  (There are a few cases where this is not feasible, like when you need info from neighbor pores which requires a network object).  This change means no more passing in objects, only numbers so they are more straightforward code-wise.  This would make the documentation MUCH easier to write and understand (it's difficult to explain that 'pore.size' is a string to the location of the array containing actual pore data!). The length of the output would result automatically from the length of the input.  The returned value would be subject to the __setitem__ rules so scalars become vectors.  The models.add method would still take strings though!  This is how openpnm stores the arguments and allows for regenerating values (since it would recall the model with new values pulled from the specified dictionary key).

(2) The ```add.model``` command should accept dict key strings OR scalars.  There is no sense creating a bunch of extra arrays just to house a scalar value that we don't expect to change.  Arrays should NOT be allowed though, since implies spatially varying information that was calculated by some other model (hence might change upon regenerate). 

I actually think these changes could be done without breaking the code, but they would technically be backwards incompatible in the event that some users have written their own functions.

**Comment by jgostick** [comment]
Move some network methods to Network.Tools OR Network.models.  What and when should a network query be implemented as a model?

**Comment by jgostick** [comment]
Changing the way the object handles are stored on each object (or removing them completely).  At the moment there are hidden lists, and they are accessed using methods like ```geometries```.  These should be dicts, then objects can be accessed by name and also iterated over.  Also, it is insane the way ```network``` currently works.  It is different than all the other methods...duh.

**Comment by jgostick** [comment]
Remove the postprocessing sub module (discussed in #554 )

**Comment by jgostick** [comment]
Remove the MatFile network class, or at least not import it automatically ( #591 )

**Comment by stadelmanma** [comment]
2.0 might be the best place to implement the interface class ( #581 ) if you are still interested in that.  Adding it in as an after thought & backwards compatible could be rather messy. There are still some usability questions, mainly if we want the network to auto-generate interfaces based on existing phases or force the user to always define them manually.

**Comment by jgostick** [comment]
Github has just created a new Projects feature, which is exactly the place to put a discussion such as this thread/issue.  I'm closing this (and probably a few others) and moving the comments there.
