### ISSUE TITLE
WinPython installation link broken (documentation)

### ISSUE THREAD

**Issue by mohammadamin-sadeghi** [PMEAL/OpenPNM#500]
The hyperlink to WinPython installation is broken. So as the link to Spyder.
http://openpnm.org/docs/userguide/installation.html
@jgostick

**Comment by jgostick** [comment]
I nominate you to make the change!  We have a PR open called Improvements
to the 'getting_started_guide'...you down check-out that branch in
SourceTree, make the change, commit it, then push it.   :-D
