### ISSUE TITLE
Visualize Throats in Paraview

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#507]
This would be very useful to help ensure things are looking right, but at the moment my Paraview simulations only show lines between pores.  

I recall that @jhinebau once sent me a complex recipe for putting throat cylinders in paraview (using a series of paraview commands), but I wonder if there is something we can do to the output VTP files to include exactly what paraview needs to simply add oriented gliphs?  

GanttDue: 2018-10-25

**Comment by jgostick** [comment]
The example on the website already explains how to do this, but it is unreasonably complicated.  There MUST be a way to put more information into the file so that throat gliph information is present.

**Comment by jgostick** [comment]
I really want this!  The current process is insane!  We need a VTK expert to step up and help here.

**Comment by TomTranter** [comment]
I don't think there is a better way to do this with vtk and paraview. You could output separate sets of points data for pores and throats and then create separate glyphs but you can only scale by one factor so radius and length have to be set in two steps for the throats (which I haven't managed to figure out how to do properly - probably another set of convoluted filters). Or you could output polydata from OpenPNM leaving the user to control things like number of vertices in each glyph and making the output files much larger. Neither option is better than what we already have. With the GUI we could do all rendering in OpenPNM the way we want it. Paraview works much better with grids of data and images than with polygonal datasets imho

**Comment by jgostick** [comment]
I guess I'm thinking that the user should just be able to apply a tube filter to get tubes without the 5 step process paraview currently requires. We have throat end points, and throat diameter, so sure there is a shortcut to create the throats.  We don't have any vector data in our files, maybe this is the key? If we had vectors we could just put tubes on them?

**Comment by TomTranter** [comment]
I can use pyevtk to output vector data but the cylinder glyph still needs a
two step process. Not sure about tube

**Comment by jgostick** [comment]
Now that we have throat end points as a normal properties, perhaps we can revisit this and see if it'd doable?

**Comment by xu-kai-xu** [comment]
this is my problem, now i can export the python file to vtp format, by using this command 

import openpnm as op
pn = op.network.Cubic(shape=[10, 10, 10], spacing=0.0001)
geo = op.geometry.StickAndBall(network=pn, pores=pn.Ps, throats=pn.Ts)
Hg = op.phases.Mercury(network=pn)
phys = op.physics.Standard(network=pn, phase=Hg, geometry=geo)
mip = op.algorithms.Porosimetry(network=pn)
mip.setup(phase=Hg)
mip.set_inlets(pores=pn.pores(['left', 'right', 'top', 'bottom']))
mip.run()

# 生成vtp格式的文件的命令
op.io.VTK.save(pn, phases=phys, filename='first_examples', delim='|')

did i use the final line code rightly? and i can show pores or throats seperately, but can not show them in the same view window.  the first two is what i made.  
![p1](https://user-images.githubusercontent.com/44153643/49916257-147c9c00-fed5-11e8-86af-2a4c2ffc31cf.png)
![p2](https://user-images.githubusercontent.com/44153643/49916261-16def600-fed5-11e8-86bb-08116cc1e58b.png)

**Comment by jgostick** [comment]
One of the "quirks" of openpnm is that you need to return the results of an algorithm back to a phase object.  The idea is that you don't necessarily want your phase object to be updated with all kinds of data.  Anyway, what this means is that you need to do something like:

```
Hg['pore.invasion_pressure'] = mip['pore.invasion_pressure']
Hg['throat.invasion_pressure'] = mip['throat.invasion_pressure']
```

Then when you call the io class, use:

```
op.io.VTK.save(network=pn, phases=Hg, filename='first_examples')
```

**Comment by jgostick** [comment]
Regarding visualizing throats in paraview, there is an example for this because it is not at all easy.

https://github.com/PMEAL/OpenPNM-Examples/blob/master/IO_and_Visualization/view_vtp_in_paraview.md

**Comment by xu-kai-xu** [comment]
it seems nice, thanks. i did what the example told, and i find the trick is the filter, which is some kind of amazing to me.

**Comment by jgostick** [comment]
Hi @xu-kai-xu 
1.  I'm not sure why paraview is giving you an error...we use paraview everyday and it works fine.
2.  To get the syntax highlighting put the text inside single back ticks (`) or do multi-lines with triple back ticks (```)

**Comment by TomTranter** [comment]
Hi @xu-kai-xu 
Maybe you will find this useful
https://www.youtube.com/watch?v=g9yMuU5a5RA&feature=youtu.be
Code is in the comment

**Comment by TomTranter** [comment]
@xu-kai-xu @jgostick I think I know why you are getting this error with the data array may be too short. We have a few percolation algorithms but some assign -infinity to the invasion pressure for boundary pores. It appears that infinity and nan do not get read properly in paraview. I think we should address this issue by specifying a minimum inlet pressure. It is useful to be able to filter out the inlets which is why I think infinity or nan might have been used whereas a value match some of the genuine invasion pressures for other pores. The alternative is to catch infs and nans in the output and change them to some arbitrary very high or negative value

**Comment by xu-kai-xu** [comment]
@TomTranter @jgostick  thanks for the video and code, i will try figuring the problem, and it seems a lot to learn.

**Comment by TomTranter** [comment]
You just need to replace the bad values like phase[numpy.isinf(phase[property])]=9999

**Comment by xu-kai-xu** [comment]
@TomTranter  emm, bad news. i just copy your code in my spyder, but it gives me a syntaxerror.
the mysterious code is `print('Max Pressure', mip['throat.invasion_pressure'].max())﻿` , the last line, and the feedback is "
  File "D:\program_files_e\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-13-ca0e078b280f>", line 1, in <module>
    runfile('E:/xu/python_files/examples/tom\'s advice for openpnm.py', wdir='E:/xu/python_files/examples')

  File "D:\program_files_e\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "D:\program_files_e\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/xu/python_files/examples/tom's advice for openpnm.py", line 42
    print('Max Pressure', mip['throat.invasion_pressure'].max())﻿
                                                                ^
SyntaxError: invalid character in identifier", i have no idea  what happened.

**Comment by TomTranter** [comment]
So it works without that line? I would rename the file something without spaces and apostrophe to see if that helps

**Comment by xu-kai-xu** [comment]
> 
> 
> You just need to replace the bad values like phase[property][numpy.isinf(phase[property])]=9999

i think i know what you mean. when i read the openpnm.io.vtk.py files, i find that `def save(cls, network, phases=[], filename='', delim=' | ', fill_nans=None):` line, tht last Parameter is `fill_nans=None`, and the documentation about it is that 

> fill_nans : scalar
            The value to use to replace NaNs with.  The VTK file format does
            not work with NaNs, so they must be dealt with.  The default is
            `None` which means property arrays with NaNs are not written to the
            file.  Other useful options might be 0 or -1, but the user must
            be aware that these are not real values, only place holders.

then i change it to  `fill_nans=9999`,  just as you said,  then the output works.

**Comment by xu-kai-xu** [comment]
it should be `fill_nans=0`, the '9999' value receive that"scalar range is zero", and the '0' value works.

**Comment by xu-kai-xu** [comment]
@TomTranter @jgostick  Hi, these days I am studying and working with openpnm. I used the method Tom told me nearly one year ago. I want to create a simple network with only one same direction throats, like
![K0206I YFS__)7L066GJRY5](https://user-images.githubusercontent.com/44153643/71136960-7b980380-2241-11ea-96b8-8e4cdc62c0a7.png)

Then when I visualize it with ParaView, I found something confusing me.
Tom told me to extract the throats using three filters: cell data to point data, extract surface, tube, which looks like 
![image](https://user-images.githubusercontent.com/44153643/71137123-fd882c80-2241-11ea-9660-c7104f23c0f4.png)
when I use only two filters: extract surface, tube, the result looks like another way:
![image](https://user-images.githubusercontent.com/44153643/71137174-2f00f800-2242-11ea-93da-994d22a4bba5.png)
The latter is much closer to what I expected.

So  I just want to ask the function of the filter "cell data to point data". Which of the above two visualization is better and close to my expected. 

I attached the vtp file for your inspection.

Thanks for your help.
[water_alg.vtp.txt](https://github.com/PMEAL/OpenPNM/files/3981332/water_alg.vtp.txt)

**Comment by TomTranter** [comment]
I think it is the celldatatopointdata function doing some rounding errors you have very small throat diameter and maybe this is causing trouble. If you don't do this step you can't scale the throat glyphs. Instead of making the diameter tiny why not use the topotools trim function to actually remove the ones you don't want.

**Comment by xu-kai-xu** [comment]
@TomTranter , thanks for your advice. I repeat the unidirection model and use `openpnm.topotools,trim` method to process the non-z-direction throats. The result is very nice.
(Sorry for the laaaaaaate reply, and thank you again)
![image](https://user-images.githubusercontent.com/44153643/83348939-41d83680-a363-11ea-855b-1b3c3b16933a.png)

**Comment by xu-kai-xu** [comment]
hi, @TomTranter  and @jgostick, when I use paraview to visualize throats, I found that the applied filters (cell data to point data --> extract surface --> tube) suggested by Tom is with one little problem. The problem is that the radius of the throats are not visualized to be their real radius, which means the throat's visual result depends on the two pores this throat is connected to. 

e.g., when I created a unidirectional network, in which pores and throats shown as follow:

![image](https://user-images.githubusercontent.com/44153643/86530311-55d70100-beea-11ea-929f-6101c596c105.png)

this network only has two kinds of pore diameters: 2.5e-5 and 5e-5 m. And only the throats connected by two small pore diameter values are assigned with the value 2.5e-5, which means only one group throats are 2.5e-5(number of 100), and other 800 are 5e-5. The throats above are visualized by only using tube filter directly on "cubic-5.vtp" file. Then, I show the results by applying all three filters on cubic-5.vtp:

![image](https://user-images.githubusercontent.com/44153643/86530485-908d6900-beeb-11ea-9603-345821b34a77.png)

After applying "cell data to point data" and "extract surface" filters, the throats seem to be changed for visualization. The throat diameter changes too much than the half of size.

For now, I don't know how to visualize it properly. So I just show the throat diameter distribution by color. Do you know how to show them correctly?

**Comment by jgostick** [comment]
I think you're doing it correctly, but the throat scaling in paraview is not perfect.  It's only for visualization, so you manually adjust the the scale factor until it looks right.  If you want to do real investigation of pore and throat sizes you should use real data in python, not visualization.

**Comment by xu-kai-xu** [comment]
Thank you! So you mean, just focus the data processed by python. Paraview is just an assistant work. The real pore and throat relations are reflected in the results of openpnm. Do I understand right?

**Comment by jgostick** [comment]
In paraview you are just making pictures to help visualize, but the pictures are not 'quantitative'.  You basically have a bit of artistic license to make the picture look right.  If you want to be sure that throats are correct sizes, a picture is not the right way to do this...you should analyze the numerical arrays instead.  So, basically don't stress about getting throat scaling perfect, just approximate.  If you are confident in your throat sizes, via numerical analysis, then this is not a trick.

**Comment by xu-kai-xu** [comment]
@jgostick  Thank you!

**Comment by ma-sadeghi** [comment]
@xu-kai-xu I recently found a way to get throat scaling perfect. Here's what you need to do:

0. Create a new label in `OpenPNM` to store throat **radius** data via
```python
net["throat.radius"] = net["throat.diameter"] / 2
```

1. Apply `Shrink` filter and set `Shrink Factor` to 1
2. Apply `CellDatatoPointData` filter
3. Apply `ExtractSurface` filter
4. Apply `Tube` filter

Up to this step, pretty much the same as what you can find in our documentation (except for step 0), here's the extra steps:

5. In the `Tube` filter window, select `throat.radius` for your `Scalars`
6. [Optional] Set `Number of Sides` to 32 for better visualization
7. Set `Radius` parameter to 1.
8. Set `Vary Radius` parameter to `By Absolute Scalar`
9. Set `Radius Factor` to 1.
10. Apply!

Here's a screen shot of a network with spacing = 1 and throat diameter = 0.5.
![image](https://user-images.githubusercontent.com/14086031/86692013-60bb8f80-bfd7-11ea-94b3-1d880cabd22f.png)

**Comment by xu-kai-xu** [comment]
@ma-sadeghi, Thanks a lot! I tried it. The result is fascinating. 
In the following pictures, I change throats' diameters for a group of tubes crossing the tube direction. Very nice.
![image](https://user-images.githubusercontent.com/44153643/86693795-92674180-c03d-11ea-8800-d3a9467f378c.png)
