### ISSUE TITLE
transforms3d dependency should be added to the documentation!

### ISSUE THREAD

**Issue by mohammadamin-sadeghi** [PMEAL/OpenPNM#521]
I was doing a fresh install on my PC this afternoon, and noticed that transforms3d is not included in WinPython. However, according to the documentation: "The simplest way to get Python and all the necessary Python packages for scientific computing in Windows is to download the WinPython package", which I think is not the case. transforms3d should be installed separately using "pip install transforms3d". @jgostick

**Comment by mohammadamin-sadeghi** [comment]
I must add that this only happens when OpenPNM repository is cloned, rather than being installed by pip.

**Comment by mohammadamin-sadeghi** [comment]
I think we should explicitly mention in the documentation, that in case somebody wants to use OpenPNM as a developer, transforms3d must be separately installed.

**Comment by jgostick** [comment]
It's actually in the latest setup.py file, so if you install the package it gets install for you.  If you are running from a local repository, you shoud ```pip install -e 'path/to/source/code'```.  This will install the local code and all dependencies as if you are you installing from PyPI.
