### ISSUE TITLE
Add mask to find_nearby_pores and possibly other topological queries

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#524]
I'm coding a function to identify pores that overlap and I'm doing this by using the find_nearby_pores function and the pore radius. The problem is I'd like to exclude boundary pores from the search and the best and mos useful way to do this I think would be to add a mask or label functionality to the topological query

**Comment by jgostick** [comment]
Can you just send in a pre-masked list of pores?   We used to accepts labels into lots of different methods, but found it was more general to use the pores() method to filter, then pass the resulting list of pores.  Would this work?

**Comment by TomTranter** [comment]
I don’t think so as the search is done over the whole network so the list you send in could still pick up boundary pores. You could filter the output I suppose. This larger task is actually proving quite tricky… I was planning on merging pores that were overlapping but if I have lots of overlapping ones then it’s not a just simple cluster search. I could have two fairly large pores near to each other that both overlap some pores in between them but not each other and these would all end up merging together.

**Comment by TomTranter** [comment]
I don't think this is really necessary after all
