### ISSUE TITLE
About Random PNM with Delaunay Network and Voronoi Geometry

### ISSUE THREAD

**Issue by Rickku** [PMEAL/OpenPNM#531]
Hi all,

I am a newcomer of OpenPNM and try to get started with it using the examples. However, I cannot get the results as the example of PNM with Delaunay Network and Voronoi Geometry shows. The pore size distribution shows that large amounts of pores are in zero diameters and the throat length distribution shows that all the throat lengths are zero. I just copied the code and run it in the openpnm without any change. Can you help me with this?

Thank you!

**Comment by TomTranter** [comment]
Hi @Rickku,

Thanks for pointing this out. The distributions shown in the example don't correspond exactly to the network generated you are right. I think we must have reduced the number of pores and also placed the boundary pores into a separate geometry object. Also the throat length calculated for the Voronoi set as the fibre diameter. A property called throat.c2c which stands for centre to centre is also created which is what's being displayed. 

The following line should give you the expected distributions once boundary pores are assigned a different geometry.

OpenPNM.Postprocessing.Plots.distributions(geo, throat_length='throat.c2c') 

I've also attached the full script here (just rename the file extension .py) and we'll amend the example documentation.

Thanks,
Tom
[test_voronoi.txt](https://github.com/PMEAL/OpenPNM/files/158624/test_voronoi.txt)

**Comment by Rickku** [comment]
Hi @TomTranter 

I really appreciate for your help.

Thank you

Rick
