### ISSUE TITLE
Agenda for April 4th, 2016 Telecon

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#542]
1. Status of Docs
2. Plans for Network.tools.  PR #543 is ready to merge
3. Experimental features:  propose a ``Utilities.experimental`` or ``Utilities.sandbox`` to house ANY and ALL features, methods, functions, algorithms until they've proved useful enough to graduate.
4. Reaction class/scheme overview by @maghighi

**Comment by TomTranter** [comment]
Sorry I'm going to be 30 minutes or so late for this
