### ISSUE TITLE
Generate 3D porous media

### ISSUE THREAD

**Issue by Rickku** [PMEAL/OpenPNM#545]
Hi,

I want to generate a 3-D porous media where different pores are located.  The example code of OpenPNM has been tried but the results are different from what is shown on the web page.

Can I use the Delaunay Network and Voronoi Geometry to generate a 3-D porous media where the pore size distribution can be defined in code?

Thank you,

Rick

**Comment by jgostick** [comment]
Hi @Rickku I'm not quite sure what you're asking, but I think you want to generate a 3D network with pores randomly located? The Delaunay Network generator makes random pores and connects pores to their nearest neighbor using the [Delaunay triangulation logic](https://en.wikipedia.org/wiki/Delaunay_triangulation).  

The Voronoi Geometry class calculates pore and throat sizes by assuming the material is fibrous and thus Voronoi tessellation is a good approximation of the fibers so their positions basically define the pore geometry [See details here](http://jes.ecsdl.org/content/160/8/F731.abstract).  

If you you do NOT want a fibrous media, the we don't actually have a dedicated Geometry class to determine pore and throat sizes (we really should though...I'm going to open an issue about this right away).  Instead you simply assign pore and throat geometry models from the standard library of models.  

FYI, The reason that a specific Geometry class would be useful is to ensure that all pores are as large as possible without overlapping their neighbors, which is not necessarily trivial.  

Also, I'll add that each network generation is random, so if you're instance looks different than the one the website, that might be the reason.  

Finally, our documentation is under a complete renovation and will be done in a month or so.  One of the main changes has been to move the examples to a new repo called [OpenPNM-Examples](https://github.com/PMEAL/OpenPNM-Examples).  You can browse through the various files in the repo on the github website and they should be nicely rendered for you.  There is a Delaunay example.

Please let me know if I can help you further.

**Comment by Rickku** [comment]
Hi @jgostick 

Thank you so much!

Basically, I want to simulate the air diffusion in micro porous layer where there are many pores with various shapes and sizes. I am looking for a program that can help me with this simulation. Could you please tell me whether the OpenPNM can conduct the simulation or not?

Best,

Rick

**Comment by jgostick** [comment]
I assume you're referring to a fuel cell MPL?  Does it need to be a random
pore network?  Do you know what range of shapes and sizes you have?  How
much information do you have about your material?  Tomography images,
porosimetry, porosity, etc? What sort of info are you planning to get from
the simulation?  Do you have a hypothesis like "wider pore size
distribution should lead to lower diffusivity"?

**Comment by Rickku** [comment]
Hi @jgostick 

It is the MPL in the fuel cell and I have obtained the tomography images by SEM scanning. The approximate pore size distribution was known but the shapes of pores are random. I just want to know how the factors such as porosity, pore size or even pore shape can affect the air diffusion, especially the effective diffusivity in the MPL. I hope to get a relation between effective diffusivity in the MPL that is used in the fuel cell.

Thank you,

Rick

**Comment by jgostick** [comment]
Hi @Rickku , we know that our documentation is not great so we're doing a COMPLETE revamp.  The 'user guide' will consist of 3 tutorials, each at a different level.  You can view these tutorials now though, via the open pull request.  Here is the link:  

https://github.com/PMEAL/OpenPNM/tree/doc_refinements/docs/userguide/tutorials

Try doing tutorial 1 and 2.  This should give you a good idea of how to create a customized simulation.  These tutorials do a permeability simulation but it's pretty straightforward to change this to diffusion.

**Comment by Rickku** [comment]
Thank you @jgostick

**Comment by jgostick** [comment]
I will close this for now, since open issues bug me :-D  Please email me directly or move the conversation on to the gitter chat stream.
