### ISSUE TITLE
Remove Postprocessing?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#554]
It was discussed to move basic plot code to each relevant class, then move the rest of the plots (ie. porosity profile, etc) to OpenPNM-Examples.  

Surprizingly, some methods in Postprocesses are actually used (i.e. plot_distributions)

**Comment by TomTranter** [comment]
I agree

**Comment by jgostick** [comment]
I'm going to mention this issue in the ongoing compilation of backwards incompatible changes ( #491 )
