### ISSUE TITLE
Add pore.inv_satn to Drainage

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#557]
It would be handy if the Drainage algorithm had a list that contained the total network saturation when the pore was invaded.  This way you could find a mask of invaded pores using a boolean check on saturation, like we currently do on pressure:

```
Ps = mip['pore.inv_satn'] < 0.5
```

**Comment by TomTranter** [comment]
InvasionPercolation needs this too, unless we're replacing it? Where are you with AwesomeIP?
I don't mind doing this BTW

**Comment by jgostick** [comment]
This main issue with this, and I think the reason that I removed it in the first place, is that it's impossible to account for late pore filling in this boolean query.  I suppose the value we store in inv_satn could be the the saturation upon first penetration?  But this would require then calculating the actual filled volume at the chosen invasion state...very tricky.  Or, maybe if late pore filling is specified, then this option is not available?

**Comment by jgostick** [comment]
@MichaelHoeh has opened a PR on this ( #647 ).  The PR is currently failing, but this could be fixed up and added to the next version.
