### ISSUE TITLE
Create special network classes upon importing

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#570]
As I'm reviewing PR #568 by @stadelmanma I'm feeling like the 'Empty' network class that gets returned by default is a bit misleading. The class name gets used as the object name by default so seeing the word "Empty" makes it look there is a problem.  

This would be simple (but fun) fix:  Each import class should subclass the Empty class and give it an appropriate name.  The subclass could have literally ZERO attributes added, but it might also add a few things like storing the path to the file(s) that it was imported from, or perhaps other relevant info.  

This is a minor and admittedly superficial issue, so it's just a suggestion.

**Comment by stadelmanma** [comment]
Would it be better to base them off the GenericNetwork class instead of Empty? I'm not sure if there are fundamental differences between the two. Seeing "GenericNetwork" is also less misleading than "Empty". I kind of like the specific naming scheme though.

**Comment by jgostick** [comment]
Empty allows you to specify Np and Nt without actually having pore.coords
and throat.conns.  Generic doesn't allow that.  In any case I like the idea
of having properly named classes better too.

On Tue, May 10, 2016 at 4:47 PM, Matthew Stadelman <notifications@github.com

**Comment by jgostick** [comment]
As @maghighi and I discussed today, maybe we should revisit the idea of having something like ```op.Network.Networkx``` that calls ```op.Utilities.IO.NetworkX.load```.  Or perhaps create a subfolder of import classes such as ```op.Network.Import.NetworkX()```?

**Comment by stadelmanma** [comment]
I just stumbled across this, the types builtin library might give you an elegant way to implement this without a ton of boiler plate code. I've not used it much yet but it says supported in 3.3+

https://docs.python.org/3/library/types.html#dynamic-type-creation

**Comment by jgostick** [comment]
The process of import networks deserves a complete rethink.  I'm closing this and making more general issues about it with a V2.0 label.
