### ISSUE TITLE
Agenda for June 22, 2016 Telecon

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#597]
* Discuss & Merge some PRs ( #585 , #596 , #594 )
* What's up with OP Site Percolation ( #571 )

**Comment by TomTranter** [comment]
Hi,
I'm not able to join the meeting today. The problem with OP Site Percolation is a lack of tests covering the changed lines. I've been a bit busy to do this but will see to it next week in time for the telcon so we can discuss the changes
