### ISSUE TITLE
Agenda for July 6th 2016 Telecon

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#602]
* @ma-sadeghi  wil talk about multiscale porosity and reaction
* @maghighi will talk about stefan-maxwell in PNMs
* @TomTranter will talk about OP with site percolation
* @stadelmanma will talk about dynamic IP (maybe)

**Comment by TomTranter** [comment]
Hey guys, sorry I missed this telcon - been rushed off my feet trying to finish a paper. Now that the manual paper is on researchgate I got an email saying we could upload the full text. I'm happy to do this and add some pictures and an abstract etc to boost its visibility a bit

**Comment by TomTranter** [comment]
Ah I think we aren't allowed to upload the publishers version but the final pre-print. I don't have that

**Comment by jgostick** [comment]
I'll send it...but I believe the editor told me he would make it open
access for us.  I'll followup with him on that.
