### ISSUE TITLE
Agenda for July 27th Telecon

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#613]
1. @MichaelHoeh is in Montreal!  For the next two months  electrolyzer modeling will be on the agenda.
2. Chat about maximal ball extraction (if @TomTranter is present)
3. Go over issues and PRs

**Comment by TomTranter** [comment]
Sorry, can't make this week, or many others this month

**Comment by TomTranter** [comment]
Is there a meeting this week?
