### ISSUE TITLE
``plot_coordinates`` always returns a 3d plot even when passed a 2d network.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#623]
``plot_coordinates`` seems to always return a 3d plot even when passed a 2d network. It would be ideal for it to return a consistent plot based on the shape of the passed network.

**Comment by jgostick** [comment]
All networks in OpenPNM are 3D.  Even a single layer of pores still has a z-coordinate.  

Perhaps there is a way to tell MatPlotLib to view the graph in 2d, like fig.view(blah, blah)?

**Comment by ma-sadeghi** [comment]
I know, but still it gives the user a better experience if the method plots consistently.

**Comment by jgostick** [comment]
Try to find the command that controls the view angle or camera angle of the
3d axes, and we can either add it to the documentation of the method, find
a way to invoke it automatically if the input points are 2D.  I think it
should still be a 3d plot, but just viewed in 2d, no?  I think that's how
Matlab works.  If you grab any 2d scatter plot and drag it, you get a 3d
view.

**Comment by ma-sadeghi** [comment]
Why aren't we using `networkx` for plotting? It's fairly straightforward and customizable.

**Comment by jgostick** [comment]
1. It doesn't let you chose the locations of the pores/nodes.  It puts them
wherever they make the least messy graph.
2. It doesn't support 3d graphs, they all lie in a plan.  Same problem with
Gephi and other tools.

Besides, the matplotlib solution makes the most sense for us since we
already have it as a dependency, and it's the de facto python math plotting
package so people generally know how to use it.

**Comment by jgostick** [comment]
@ma-sadeghi , do you think your networkX graphs should be added to the code somehow?  Are they faster than the matplotlib approach?  Are they prettier?  Do they interleave with the existing plot tools, or will they be new methods?  Are they just meant for 2D?  Do they offer better rotation behavior in 3D?

**Comment by jgostick** [comment]
I"m going to close this is since it's really just about setting the view angle on the Matplotlib window.  The use can drag the graph to the view they like.  It's also possible to manipulate the matplotlib axes as needed.  Here is a receipe (I will put this into the documetation for the methods):

``` python
import OpenPNM as op
import matplotlib.pyplot as plt
net = op.Network.Cubic(shape=[5, 5, 1])
fig = op.Network.tools.plot_connections(network=net)
ax = fig.axes()[0]  # Get handle to the subaxis containing the plot
ax.elev = 90  # Set the camera elevation
ax.azim = 0  # Set the camera azimuth
ax.axis('off')  # Remove axis from image to reduce clutter
fig.canvas.draw()  # Update the figure to the new rotation
```
