### ISSUE TITLE
`largest_sphere` method produces `pore.diameter`s slightly greater than spacing!

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#627]
In the `largest_sphere` method, if you choose any `iters`>1, some of the pores will eventually have diameters slightly greater than spacing, leading to negative throat lengths (almost near zero ~ 1e-10). @jgostick

**Comment by jgostick** [comment]
I think there is a fudge factor int there, like 0.99, maybe we could reduce
it to 0.95.  It would take more iters, but might converge better?  Or we
could alter the code to naturally reduce pore sizes if negative throats are
found.

**Comment by jgostick** [comment]
Hi @ma-sadeghi , can you confirm that this problem is resolved if the fudge factor is set to 0.95 instead of 0.99 in the model?

**Comment by ma-sadeghi** [comment]
`fudge_factor` does play a role on fixing this issue, but is not really predictable. For instance when I set it to 0.9, it works fine for some networks while it leads to negative throat lengths for some others. The most robust condition is to leave the fudge_factor as is, and set `iters` to 1. This way, you always get positive throat lengths, while the pore diameters are close enough (95% percent) to their ideal potential maximum value.

**Comment by jgostick** [comment]
@ma-sadeghi Can you cook up a recipe that reproduces this problem?  Then we'll know how to to proceed. Like @maghighi said, it might be due to bug #638 .

**Comment by jgostick** [comment]
@ma-sadeghi Did we not figure out what was causing this problem?

**Comment by ma-sadeghi** [comment]
@jgostick I think it was related to the interlate_data issue, but for some reason I don't remember how. I'll try to reproduce it.

**Comment by jgostick** [comment]
we allow overlapping pores now, so let's let this issue go.
