### ISSUE TITLE
Extending network with properties on the network (i.e. as imported) breaks subsequent simulations

### ISSUE THREAD

**Issue by MichaelHoeh** [PMEAL/OpenPNM#630]
`OpenPNM.Network.tools.extend()` causes parameters that are defined on the network before extending the network (like pore diameters on imported networks) to be increased to the new size, but with the new entries filled with NANs. This causes subsequent steps to show warnings like "RuntimeWarning: invalid value encountered in less".

The problem is that if I do
 
```
pn = op.Network.Cubic(shape=[5,5,5],spacing=1,name='net')
pn['pore.diameter'] = 1
pn.add_boundaries()
```

I end up after adding boundaries with

```
pn['pore.diameter'] = array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
     			  ...  nan,
      			  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])
```

If I follow the typical routine of defining Network first, then Geometry, I get

```
pn = op.Network.Cubic(shape=[5,5,5],spacing=1,name='net')
pn.add_boundaries()
geom = op.Geometry.GenericGeometry(network=pn,pores=Ps,throats=Ts)
geom['pore.diameter'] = 1
pn['pore.diameter'] = array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
			...
      			 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
```

Here everything is fine, and I would like to have this behaviour automatically for imported networks also. 

When a network is imported (i.e. from the Statoil class), it usually carries network properties like the pore coordinates and usually also pore diameters. If this network is imported, boundary pores cannot automatically be appended, as there is no generic method currently implemented in OpenPNM, the implemented methods to add boundaries are for the Delaunay or Cubic class only, and specific to them. So adding boundaries has to be done manually, i.e. by creating a new network and then stitching this to the imported one. With stitching, the network size increases. 
`OpenPNM.Network.tools.extend()` handles the extension of the network. For parameters that are not in a hard coded list in the extend() method, the size of the array is increased to the new network size, but the remaining entries are filled with NANs. 

Not knowing about this behaviour can be very confusing, and it took me several hours to track this down. The NANs in cause warnings like "RuntimeWarning: invalid value encountered in less".

This is a general issue when importing networks that already hold properties, and which have to be extended in OpenPNM to get boundary pores. So there should be a generic approach to it.

Some ideas that I can think of right now:

- special `add_boundaries()` method for generic imported networks that already hold properties - this method could stitch a cubic network around the network, and could automatically take care of extending the properties that are already on the network - I guess the ideal version, but hard to implement for totally generic imported networks

- allow user to determine behaviour of `extend()` - i.e. change hard coded list, or use his own `extend()` method instead, or by inserting a flag in the `extend()` arguments (i.e. imported network with properties on the network yes/no), or pass a list of specific parameters that are already on the network and which should be increased to the new size, and the remaining entries filled with zeros.

- specify a procedure according to which the user should import networks, and leaving everything as is

I am willing to work on this, as soon as we decided on a way to approach it.

**Comment by jgostick** [comment]
There is actually another problem to consider: when importing networks the
Geometry values end up on the Network, not on Geometry objects.  Ideally,
things like pore.diameter should be put on a Geometry and removed from the
Network.  Then you could create new Geomtries every time you add new pores,
like boundary pores.  Then on the Boundary Geometry would have nans after
extending.

**Comment by MichaelHoeh** [comment]
Thanks for you thoughts Jeff. Yet this is highly confusing, especially for someone that just wants to use the IO.Statoil class and continue to run simulations. 
To my mind, what we should do is:
- either have IO.Statoil not write Geometry data to Network at all, and write it to a newly generated Geometry object instead
- or have a method that has to be run after the current IO.Statoil, that cleans up everything - installs boundary pores, save Geometry data to a new Geometry file - so that this method outputs a Network with boundary pores and a Geometry, that can then put into simulations without worrying about any other necessary steps anymore.
In my understanding, the methods are provided by OpenPNM should allow to just go ahead and run simulations, without having to mess with which entries are on which object, so therefore I think we should clean this up properly.

**Comment by stadelmanma** [comment]
A possible middle ground solution might be a generic method to transfer properties from a network to another OpenPNM object. The main use would be on imported networks, to cleanly move properties over to an appropriate object. So the user would first import their network and secondly call this function specifying what property keys to transfer over. After that you're in an easier situation to add new pores and throats as Jeff mentioned. 

This idea just popped into my head so I don't know how feasible it would be to implement. I imagine you'd just have to specify the 'type' of object i.e. passing in the `GenericGeometry` class and not an instance. So syntax would roughly look like `transfer_props(network, GenericGeometry, [list of prop keys])`, and returns generic_geom instance registered to the network passed in. 

Just food for thought, NaNs are relatively easy to find and change in sp arrays, once you know they are there. Zeros can easily masquerade as "real" data and bite you much later on down the road. I've ran into that multiple times when trying to debug code and why I now tend to avoid using 0 or -1 as a default value in favour of NaN or -2^63 in float or integer arrays respectively.

**Comment by MichaelHoeh** [comment]
@stadelmanma 
Having a transfer method sounds like a good idea to me! But I guess it would be not so easy to implement. 
And I definitely agree that having NaNs instead of zeros makes it easier to debug.

Also considering @jgostick's comment to having the Geometry have NaN as value on the Boundary, we have the following issue:
If we want to have NaNs on the network, we will get "RuntimeWarning: invalid value encountered in less" during computations, as this occurs when operations are attempted between arrays holding NaNs - and as often the full array is considered, also the NaN entries come into play. 

So the question for me is whether we want NaNs on the arrays - if yes, then the RuntimeWarnings should be adapted, as they should not appear under business-as-usual scenarios

**Comment by jgostick** [comment]
The idea is that you put NaNs in there SPECIFICALLY to get the RunTime warning.  That way you know that simulation is not complete yet.  The ```check_data_health``` method checks for NaNs and tells you where the problems are.  

When you add pores to a network you then have to specify properties for those pores.  Deleting pores is easy, but adding requires subsequent work.  This is all expected behavior.

As for a transfer method, I think it's a bit overkill, since moving data between dicts and deleting entries is just basic python.

The basic flow would be like this:

    geom = op.Geometry.GenericGeometry(network=net, pores=net.Ps, throats=net.Ts)
    for item in ['pore.volume', 'pore.diameter', 'throat.length']:
        geom[item] = net.pop(item)
    
Then you can add boundary pores to the network, and then create boundary pores, THEN create a Geometry object for the boundary pores.  This new Geometry object will then either need to have the correct size info assigned.  Basically, since you have not imported the boundary pores, you still have to assign porescale models for it.

**Comment by jgostick** [comment]
Also, as for importing Geoms and Networks, the i mport classes 'could' return tuples of objects like:
(net, geom) = op.Utilities.IO.Statoil.load(file).  BUT, I think that the 3 lines of code I gave in my previous comment are probably more straightforward.
