### ISSUE TITLE
Bug in OpenPNM.Network.tools.extend() - closely linked to #630

### ISSUE THREAD

**Issue by MichaelHoeh** [PMEAL/OpenPNM#631]
When a network is extended by new pores/throats, the arrays holding the properties of the original network should be extended in a meaningful manner, be it NaNs or 0 (cf. discussion in #630, as this bug is closely linked to that). 

If we do this in the way as it should be done, so extending the network first, and then defining a geometry on a subset of the network, the entries in the array not belonging to the subset hold very small values.

```
pn = op.Network.Cubic(shape=[5,5,5],spacing=1,name='net')
pn.add_boundaries()
Ps = pn.pores('boundary',mode='not')
Ts = pn.find_neighbor_throats(pores=Ps,mode='intersection',flatten=True)
geom = op.Geometry.GenericGeometry(network=pn,pores=Ps,throats=Ts)
geom['pore.diameter'] = 1.

pn['pore.diameter'] = 
array([  1.00000000e+000,   1.00000000e+000,   1.00000000e+000,
         1.00000000e+000,   1.00000000e+000,   1.00000000e+000,
         1.00000000e+000,   1.00000000e+000,   1.00000000e+000,
       
         2.96439388e-323,   3.45845952e-323,   3.95252517e-323,
         4.44659081e-323,   4.94065646e-323,   5.43472210e-323,
         5.92878775e-323,   6.42285340e-323,   6.91691904e-323,
         7.41098469e-323,   7.90505033e-323])
```

If it is done the other way around, so defining a network, then a geometry, and then adding boundaries, something else happens. In fact the values that appear on the array for the 'pore.diameter' are the 'pore.coords' values in this special case, which should not be. Either these entries should be filled by NaNs or by 0 or by -inf or something like that. 

```
pn = op.Network.Cubic(shape=[5,5,5],spacing=1,name='net')
Ps = pn.pores()
Ts = pn.find_neighbor_throats(pores=Ps,mode='intersection',flatten=True)
geom = op.Geometry.GenericGeometry(network=pn,pores=Ps,throats=Ts)
geom['pore.diameter'] = 1.
pn.add_boundaries()

pn['pore.diameter'] = 
array([  1.00000000e+000,   1.00000000e+000,   1.00000000e+000,
         1.00000000e+000,   1.00000000e+000,   1.00000000e+000,
         1.00000000e+000,   1.00000000e+000,   1.00000000e+000,
        
         3.50000000e+000,   4.50000000e+000,   3.64126381e-321,
         6.92859600e-310,   6.92859600e-310,   1.50000000e+000,
         5.00000000e-001,   4.50000000e+000,   1.50000000e+000,
         1.50000000e+000,   4.50000000e+000,   1.50000000e+000,
         2.50000000e+000,   4.50000000e+000,   1.50000000e+000,
         3.50000000e+000,   4.50000000e+000,   1.50000000e+000,
         4.50000000e+000,   4.50000000e+000])
```

This behaviour can be confusing, and should therefore be eliminated. I guess this is due to a misbehaving OpenPNM.Network.tools.extend().

**Comment by MichaelHoeh** [comment]
The behaviour isn't even reproducible, I just ran some code a couple of times, and these are the outputs:

```
net['pore.diameter'] = 
array([  2.35779600e-06,   4.00463800e-06,   4.94821800e-07, ...,
         5.86330024e-04,   2.95320000e-04,   2.04570879e-04])

array([  2.35779600e-006,   4.00463800e-006,   4.94821800e-007, ...,
         5.62266468e-319,   5.62271408e-319,   5.62276349e-319])

array([  2.35779600e-006,   4.00463800e-006,   4.94821800e-007, ...,
         2.02216128e-319,   2.18179389e-319,   2.02230950e-319])

array([  2.35779600e-06,   4.00463800e-06,   4.94821800e-07, ...,
                    nan,              nan,              nan])

array([  2.35779600e-06,   4.00463800e-06,   4.94821800e-07, ...,
         2.17609600e-06,   8.62722200e-07,   2.49784000e-06])
```

While the first line always matches (the original diameters), the values in the extended parts don't show a clear pattern. Something is going wrong here, this should not happen.

**Comment by MichaelHoeh** [comment]
Something similar appears in other cases as well, so this might not be ultimately due to the extend() method.

Consider the above example, where 'geom' lives on a subset of the pores of 'net' . So every time I change the entries on 'geom', only the relevant part of 'net' should be altered, and the other pores, that are not in the subset of 'geom', should be left unaltered. Yet they are altered as well, as can be seen here: 

```
geom["pore.diameter"] = geom["pore.radius"]*2
net["pore.diameter"] = 
array([  2.35779600e-006,   4.00463800e-006,   4.94821800e-007, ...,
         3.11389814e-319,   3.11394755e-319,   3.11399695e-319])

geom["pore.diameter"] = 1.
net["pore.diameter"] =
array([  1.00000000e+000,   1.00000000e+000,   1.00000000e+000, ...,
         4.94065646e-324,   4.94065646e-324,   4.94065646e-324])

geom["pore.diameter"] = geom["pore.radius"]*2
net["pore.diameter"] = 
array([  2.35779600e-006,   4.00463800e-006,   4.94821800e-007, ...,
         3.11389814e-319,   3.11394755e-319,   2.49127661e-318])
```

Maybe in the end it is all about how the values are broadcast?

**Comment by jgostick** [comment]
You might be having an "Object pointer" problem.  I'll have to look more closely, but when assigning an array to another array, you sometimes get a pointer to the original array.  Try using new_array = old_array.copy()?

**Comment by jgostick** [comment]
I think this is a bug in the 'interleave_data' method...will investigate

**Comment by jgostick** [comment]
The following illustrates that the error occurs when only one geom is defined, but the goes away when another geom is added:

``` python
import OpenPNM as op
net = op.Network.Cubic(shape=[10, 10, 10])
net.add_boundaries()

Ps = net.pores('boundary', mode='not')
geom = op.Geometry.GenericGeometry(network=net, pores=Ps)
geom['pore.diameter'] = 1.0

print(net['pore.diameter'])  # This is erronoeous and includes messed up numbers

Ps = net.pores('boundary')
boun = op.Geometry.GenericGeometry(network=net, pores=Ps)

print(net['pore.diameter'])  # This is correct and will include NaNs as it should
```

**Comment by jgostick** [comment]
This is captured in #638
