### ISSUE TITLE
Pre-existing entries on Network object can't be altered by accessing through Geometry object

### ISSUE THREAD

**Issue by MichaelHoeh** [PMEAL/OpenPNM#633]
This issue is somewhat related to the discussion in #631, but should not be related to the extend() method, so I created a new issue. 

Assume the following code, where a network is created, and then the 'pore.diameter' is defined on the network. After, a Geometry is defined on this network, and a value is assigned to the `geom['pore.diameter']`. In this specific case, the new value is only written to `geom['pore.diameter']`, but not to `pn['pore.diameter']`, so we end up with TWO arrays carrying different 'pore.diameter' information, one on Geometry, one on Network.
This does not appear if 'pore.diameter' is only set after introducing the Geometry object with `geom['pore.diameter']`. These entries are then automatically written to `pn['pore.diameter']`

```
pn = op.Network.Cubic(shape=[5,5,5],spacing=1,name='net')
pn['pore.diameter'] = 1
Ps = pn.pores()
geom = op.Geometry.GenericGeometry(network=pn,pores=Ps)
geom['pore.diameter'] = 5
print(5 in geom['pore.diameter'])    # returns True
print(5 in pn['pore.diameter'])     # returns False
```

What I describe here might also be feature rather than bug - in the sense that any property existing on the network before any other object is defined should be "protected" so that it can't be altered. But I don't think this is intended, and it might be confusing, again if networks are imported that already carry some entries, like mentioned in the previous issues #631 and #630.

**Comment by jgostick** [comment]
This is expected behavior for amalgamate_data.  A new issue has been opened up to prevent #637 this from happening.
