### ISSUE TITLE
Presence of boundary Geometry prevents keys from Geometry / Network object dict from being deleted

### ISSUE THREAD

**Issue by MichaelHoeh** [PMEAL/OpenPNM#634]
When there is a boundary Geometry object in place like below, a key cannot be deleted from the Network/Geometry object dict. Instead, an array filled with NaNs remains on the object. This is bad, as if a new value should be assigned to a key, it is written into this array of NaNs, which can mess things up. 

```
pn = op.Network.Cubic(shape=[5,5,5],spacing=1,name='net')
pn.add_boundaries()
Ps = pn.pores('boundary',mode='not')
geom = op.Geometry.GenericGeometry(network=pn,pores=Ps)
geom['pore.diameter'] = 1
del geom['pore.diameter']
print(geom['pore.diameter'])     # returns KeyError - as expected

Ps = pn.pores('boundary')
Ts = pn.find_neighbor_throats(pores=Ps,mode='not_intersection')
boun = op.Geometry.Boundary(network=pn,pores=Ps,throats=Ts)
geom['pore.diameter'] = 1
del geom['pore.diameter']
print(geom['pore.diameter'])	# returns array filled with nans
```

This only appears if there is a boundary Geometry defined. Using `del` versus `geom.pop()` makes no difference.

As a consequence right now, for imported images all geometry-related entries have to be stripped of the network object first, then Geometry objects instantiated, and then the previously stripped values written back to the network, but only via the Geometry objects, and not directly to the network object.

**Comment by jgostick** [comment]
This is expected behavior but possible insane?  The call to geom looks for pore.diameter, but finds nothing, so then looks in network, which also finds nothing, which then looks into ALL geometries, finds the 0's in boundary, creates an amalgamated array of 0's and Nan's, then returns the Nans' to the original query by geom.  Clearly insane.
