### ISSUE TITLE
Move op.Network.cubic.add_boundary_pores() to op.Network.GenericNetwork

### ISSUE THREAD

**Issue by MichaelHoeh** [PMEAL/OpenPNM#635]
The Cubic and Delaunay classes have their network-specific `add_boundaries()` methods, that extend boundary pores to the network without any further considerations required. However, `op.Network.cubic.add_boundary_pores()` requires the user to provide a list of pores to which boundary pores should be added and an offset by which the then cloned boundary pores should be placed away from the original pores. 
This makes this method in fact network-agnostic, as boundaries can be added to any specified pores, also on arbitrary networks. Therefore I propose to move this method to `op.Network.GenericNetowrk`, so that it can be used on any Network object that inherits from or is an instance of GenericNetwork

**Comment by jgostick** [comment]
We'll have lots of things to talk about at the telecon on Wednesday!

**Comment by jgostick** [comment]
I fully agree that it should be on ```GenericNetwork```, OR under ```Network.tools```.
