### ISSUE TITLE
Overlapping pores

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#644]
I think we should try to handle these more correctly.  Instead of throwing a warning we could actually calculate the pore-scale models accordingly.  If two pores overlap then we could calculate the volume of each partial sphere (or cube) by subtracting the overlapping volume.  The throat volume/length could be 0.  Basically, I think a few pore-scale models should be added to do this right.  

As I plan this out in my head it occurs to me that it would require explicit knowledge of the pore body shape, which is a bit of an open issue at the moment too ( #512 ).

**Comment by ma-sadeghi** [comment]
@jgostick We can assume spherical pore shape unless otherwise specified (through other pore-scale models for instance), right?

**Comment by jgostick** [comment]
This has been added along with the equivalent area models.
