### ISSUE TITLE
Agenda for September 28th, 2016 Telecon

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#645]
I won't be able to make the telecon on the 14th, as I'll be on a plane.  I think we should push it off to the 28th.  Here is an agenda:

1.  Paraview has ray tracing!  This is extra incentive to address #507 (so that adding throats in paraview is as simple as adding cylinder glyphs).
2.  Time to release 1.6?  There have been quite a lot of updates and additions to the code.
3.  Fix the examples repo?  The build is failing because it pulls from pip but but Python 3.3 is no longer supported.  Also it is running a few newer examples (which I merge by accident).  Also, the Statoil demo is misleading / mistaken because it doesn't deal with the addition of boundary pores correctly (similar to @MichaelHoeh 's recent troubles)
4.  What to do about importing pore size info onto networks?  This should be part of the 1.6 release.

**Comment by jgostick** [comment]
Wow, Paraview keeps getting [awesomer](https://blog.kitware.com/refreshingreloading-files-in-paraview/)

**Comment by MichaelHoeh** [comment]
I won't be able to make today's telecon, but I am happy for work on the whole Statoil importing complex - after I will have prepared a PR for the current method, incorporating all the details as discussed in previous issues, I can also update the example accordingly.
