### ISSUE TITLE
Export to NetworkX

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#650]
@ma-sadeghi : You have already got a networks plotting in NetworkX, so this must mean you are exporting the properties to a NetowrkX compatible format right?  This should be rolled into a the Utilities.IO.NetworkX class under the `save` method.  There is already a place holder there for it.

**Comment by ma-sadeghi** [comment]
@jgostick Yes, kind of. Hopefully, I'll look into it after the CSCHE.

**Comment by jgostick** [comment]
Hey @ma-sadeghi...can you look into this a bit more?  NetworkX is particularly important since they have a ton of graph algorithms that people might want to leverage.

**Comment by ma-sadeghi** [comment]
@jgostick Sure. Will let you know asap.

**Comment by jgostick** [comment]
You should close this issue before you forget how to use NetworkX

**Comment by jgostick** [comment]
This was added to V1.6, but instead of writing to yaml files, is just outputs a NetworkX object.  There is also an equivalent import that accepts a networkx object.
