### ISSUE TITLE
Create a new package: OpenPNM-materials

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#654]
We talked about this ages ago ( #217 ) but I'm thinking about it again.  It would be nice to have a module that contains a bunch of pre-specified materials, like Berea, Toray090, etc.  These would include the correct network construction AND the correct pore scale models.  The main thing really is the network spacing and connectivity.  Some things would have fixed size, such as the thickness of Toray090 and Toray120.

**Comment by jgostick** [comment]
We didn't really say no to the idea back then, but decided to shelve it.  Instead of making a new module, we could just add 'recipes' to the example repo?  That may be better than filling the package with more cruft I guess.

**Comment by jgostick** [comment]
If it were setup as examples, the md files could contain nice images of networks, comparisons to known data and values, etc.  It'd be much harder to to this in a module...but on the other hand a module would be more directly useful...but on the other hand, examples are easier for users to contribute...bah!

**Comment by stadelmanma** [comment]
From my perspective as primarily a user and less a developer I'd lean towards just examples. While code is always more fun to write; as you mentioned examples can include images, comparisons, logic and reasonings as to *why* something was done. That would be more useful in my mind than providing cookie-cutter classes, since it would educate the user while providing template code to get them up and running quickly.

**Comment by jgostick** [comment]
Yes, I think so too.  We should always try to lean away from adding code to
the package.  In V2 with might consider having NO specific classes at all.

On Sun, Oct 30, 2016 at 3:56 PM, Matthew Stadelman <notifications@github.com

**Comment by jgostick** [comment]
I guess I keep changing my mind on this, but at the moment I think this is a very good idea.

**Comment by jgostick** [comment]
I'm closing this once and for all.  If we want something like this it should be accomplished by adding extra classes to network like CubicBerea, VoronoiToray

**Comment by jgostick** [comment]
Hilariously, we are thinking this is a good idea again.  At the very least it should be discussed as a group.

**Comment by jgostick** [comment]
We are currently under agreement that this should be a new repo, and perhaps a new pip package.  It is hoped that users would be more likely to contribute.  The readme could be instructions for how to contribute.

**Comment by jgostick** [comment]
OK, I've created a bare repo and stuck Berea in there, but it's not really done yet...needs testing, code cov, etc.

**Comment by jgostick** [comment]
I'm closing this issue, so any further issues relating to the materials should take place on that repo.
