### ISSUE TITLE
Really fast IP w trapping

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#663]
This is something that we dabbled with last year (PR #421) but never really finished. This is a key algorithm that we need to implement at some point soon.

**Comment by TomTranter** [comment]
We could try implementing this algorithm which does it as a post process. http://dx.doi.org/10.1016/j.cageo.2016.02.003
I had a go a few months back but didn't get very far

**Comment by jgostick** [comment]
Funny, this is what we do for OP, but it never occurred to publish a paper
about it.  I seem to remember giving this some thought once and decided
that it would not work, but I can't remember why.

**Comment by TomTranter** [comment]
I have created a branch called Fast_IP_Trapping and implemented a version of the algorithm previously mentioned. It needs testing and documenting a bit. I'd like to attach a script you can use to see it in action but it needs to be a txt file. Bit annoying. Maybe we could put a part of the repo for useful scripts that aren't officially part of OpenPNM or have a dropbox folder 
[IP_trapping_test.txt](https://github.com/PMEAL/OpenPNM/files/870524/IP_trapping_test.txt)

**Comment by TomTranter** [comment]
That was a bit premature - don't test it yet I'm still de-bugging

**Comment by TomTranter** [comment]
OK I re-wrote it and also implemented an old slow version using the OP logic of making a new cluster image for every invasion step. For 200 square 2D network the fast algorithm takes about 100s and the slow 800s. Not bad. Attached is a picture of the final invasion image and an updated test script. Still need to make tests and do Pep8 but happy with the logic.
![200_square_with_trapping](https://cloud.githubusercontent.com/assets/7068741/24379527/6b6654b4-1315-11e7-8a30-9ae3e9a4cdba.png)


[IP_trapping_test.txt](https://github.com/PMEAL/OpenPNM/files/873921/IP_trapping_test.txt)

**Comment by jgostick** [comment]
How long is it without the trapping?  How much of the 200s is just the IP?

**Comment by TomTranter** [comment]
Almost all of it, it does about 500 pores per second

**Comment by TomTranter** [comment]
The good thing is it scales pretty linearly with Np, old method is way worse. It could probably be tweaked to run faster but it works pretty well

**Comment by TomTranter** [comment]
![image](https://cloud.githubusercontent.com/assets/7068741/24388318/e44d8820-1347-11e7-9008-6c65bb1be69f.png)

**Comment by TomTranter** [comment]
@jgostick how do we want trapped pores and throats to be represented on our objects? I think a label might be best although it's nice to be able to know the sequence that they become trapped at. Also, the invasion sequence won't display properly in paraview if it contains nans or infs so how to fill the standard invasion sequence, pressure, saturation arrays for trapped pores

**Comment by jgostick** [comment]
@TomTranter ... don't forget to do a PR on this code

**Comment by jgostick** [comment]
@TomTranter what is the status of this?  Did we merge it?

**Comment by TomTranter** [comment]
Yes, the trapping algorithm is in InvasionPercolation on master
