### ISSUE TITLE
Compressing network object for working with large networks with limited RAM

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#683]
The network object becomes extremely large for relatively large networks (> 1M pores) and needs lots of RAM. It would be nice to be able to compress a network so it won't take as much space. Jeff and I think this can be possible by refactoring numpy arrays to 16-bit floats from 64-bit floats.

**Comment by jgostick** [comment]
I'm going to close this because I think it's related to the fact that objects are not being garbage collected ( #692 ).  It will also be partially fixed by allowing the 'constant' key ( #717 )

**Comment by jgostick** [comment]
It is now possible using ``dump_data`` to push all data from all objects into an hdf5 file.  There is also ``load_data`` which pulls from the same file.  With some thinking, this could be tuned to actually leave the data on the disk, but just appear as if it's in memory.  I'm going to close this for now, and we can revisit if/when we actually need this feature.
