### ISSUE TITLE
Agenda for March 1st, 2017 Telecon

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#684]
1.  1.6 was released...hooray (added automatic deployment to PyPI)
2.  V1.7.... or .... V2.0?  If 1.7, let's tag features for the release.
3.  lambda's as pore scale models (#653)?  I almost never use them, but is this a good idea?
4. Void Visualization as a TIFF (#126):  Are we happy with this?
5. Export to NetworkX (#650): Any progress?  This should be a priority given the similarities with openpnm.
6.  Materials Module (#654): This keeps coming back to me as a good idea....am I crazy?
7. The pyAMG solver is awesome (#676): but it needs to be compiled by pip, so would break our code.  
8.  Brainstorm session: How to do pore-scale models better?  List the requirements, then see what's possible
9. Walk-ins?

**Comment by sw82arup** [comment]
Hi Jeff, I am a research from Technische Universität Darmstadt, Germany, Department of Applied Geosciences (Geothermal Energy).  I would like to participate in the Telecon, or is it for a confined group of Developers ?

Cheers,
Swarup

**Comment by jgostick** [comment]
Here is a link to today's meeting: https://bluejeans.com/744944898
