### ISSUE TITLE
Make Geometry and Physics optional

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#686]
This is a pretty large change, but let me explain:

1.  We decided to 'splinter' **geom** and **phys** objects in order to support heterogeneous networks (like @ma-sadeghi's hierarchical stuff, or @maghighi's GDL/CL stuff).  This was a good decision, but it complicates things, not doubt.  If you don't use multiple domains, then you must wonder WTF were we thinking.  

2.  This splintering is also in keeping with OOP, since each **geom** and **phys** look after their own data.  It really does make things much easier 'behind the scenes' *most of the time*.

3.  Splintering has a downside that it's hard to get all data for each region as a single array.  To remedy this we introduced the idea that you can do ```net['pore.diameter]``` to get all the 'pore.diameter' values stored on each **geom**.  

4. You can also do the opposite, and get **net** data using ```geom['pore.net_property']```.  

5.  You can **NOT** write data this way, only read it.  There are also some other limitations imposed on this, but I can't remember them now.  

So, it seems to me that OpenPNM could in principle work with out **geom** or **phys** if the user has no need for this.  We'd probably have to change a few initialization requirements, and a few other things to accommodate it, but it should be easy enough.

**Comment by ma-sadeghi** [comment]
Are you suggesting that geometrical properties such as pore/throat diameter should be stored in the network object as well? @jgostick

**Comment by jgostick** [comment]
Yes, that's the idea.  The **geom** and **phys** thing would be optional and meant for "power users" or for special cases.

**Comment by ma-sadeghi** [comment]
@jgostick I couldn't agree more :D This weird, yet useful, feature of ```openpnm``` was the most confusing for me when I used it for the very first times.

**Comment by jgostick** [comment]
It would be pretty sweet if you could assign the "Standard" physics models to a phase in one line somehow...have to think about it.

**Comment by jgostick** [comment]
This is now implemented in V2.  You can attach any models to any objects, so you can put the 'pore.diameter' model on the network, and skip the geometry completely if you wish.
