### ISSUE TITLE
Not able to run version 1.6

### ISSUE THREAD

**Issue by borahdj2010** [PMEAL/OpenPNM#688]
Hi,
This might be a trivial issue, but I am not able to solve it. I have done a clean install of the version 1.6 on Winpython 3.4.4.6. But I am not able to do anything thereafter. I keep getting the following error
" ImportError: No module named 'openPNM' "

I did not have any problems like this with the previous version. I have tried changing the path variable but that did not work. Could anyone please help?

Regards
Deep

**Comment by jgostick** [comment]
It's a capital "O", as in import OpenPNM.  This is a pain and is a mistake
we made early on...in version 2.0, it will just be all lower case.

________________________________________
Jeff Gostick, PhD, PEng
Associate Professor
University of Waterloo
Department of Chemical Engineering
Waterloo ON N2L 3G1
Tel: 519-888-4567 x38949
Web: pmeal.com

**Comment by borahdj2010** [comment]
Thanks a lot, I just found it a few seconds ago, by reading the __init__.py file.

**Comment by jgostick** [comment]
Hi @xu-kai-xu...if you recently install openpnm via pip (like within the last few months), then you'll have version 2+.  Try `import openpnm as op` in lower case and let me know what happens.  If you really want to stick with version 1, then you can do `pip install openpnm==1.7`, then `import OpenPNM as op`.

**Comment by xu-kai-xu** [comment]
Traceback (most recent call last):
  File "D:\program_files\python3.7\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "D:\program_files\python3.7\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "D:\program_files\python3.7\lib\site-packages\git\cmd.py", line 290, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import openpnm as op
  File "D:\program_files\python3.7\lib\site-packages\openpnm\__init__.py", line 56, in <module>
    from git import Repo
  File "D:\program_files\python3.7\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
　export GIT_PYTHON_REFRESH=quiet
　 
　and when I use python IDLE, the problems are
　
　>>> import openpnm as op
　Traceback (most recent call last):
　  File "<pyshell#0>", line 1, in <module>
　    import openpnm as op
　ModuleNotFoundError: No module named 'openpnm'
　>>> import OpenPNM
　import OpenPNM as op
　>>> from OpenPNM.utils import vertexops as vo
　Traceback (most recent call last):
　  File "<pyshell#2>", line 1, in <module>
　    from OpenPNM.utils import vertexops as vo
　ModuleNotFoundError: No module named 'OpenPNM.utils'
　>>> from openpnm.itils import vertexops as vo
　Traceback (most recent call last):
　  File "<pyshell#3>", line 1, in <module>
　    from openpnm.itils import vertexops as vo
　ModuleNotFoundError: No module named 'openpnm'
　>>>
　
　Thanks a lot for helping me.
　Best wishes
　

Sent from Mail for Windows 10

**Comment by xu-kai-xu** [comment]
After surf the internet to find ways to do what you say, I failure. I download anaconda, but do not know how to create a new environment,  I found a button named create, so I did it and create a new environment, but do not see the choice to change the type of the environment. Then I use spyder to run the code “import OpenPNM”,  it gives a warning that “ ‘OpenPNM’  imported but unused ”, and the console says “File "C:/Users/asus/Desktop/hhh.py", line 8, in <module>
    import OpenPNM

ModuleNotFoundError: No module named 'OpenPNM' ” .  terrible.  

Thank you again,

**Comment by ma-sadeghi** [comment]
@xu-kai-xu Did you try `import openpnm` instead of `import OpenPNM`?

**Comment by jgostick** [comment]
If your install is all messed up try this:

* uninstall anaconda
* reinstall a new anaconda
* open your windows menu, select the anaconda program group, and click on anaconda prompt
* in the command window that opens up, type `pip install openpnm`
* open a python prompt, just for quick test by typing `python` at the promt
* this should have dropped you into a python commandline (noted by >>>), so now try `import openpnm`
* this should have worked, so you can exit this python prompt with `exit()`.  

Now try opening spyder from the anaconda navigator, and you should be in business.  Let me know if any of these steps don't work.

**Comment by xu-kai-xu** [comment]
The red line in the anaconda prompt seems to tell me I failed to install one file, it appeared sometimes, and when I use “import openpnm”, it says no module named openpnm, when use ”import OpenPNM”, there is no reply, then when use apyder, it still says “openpnm(or OpenPNM) imported but no used”. Do I need to uninstall all of them and install again?,  
Thanks for all the help.
Have a nice day or night.

Sent from Mail for Windows 10

**Comment by xu-kai-xu** [comment]
Thanks, it did not work.  openpnm  is imported but unused, I don’t know why.

Sent from Mail for Windows 10

**Comment by jgostick** [comment]
Your error message has both `openpnm` and `OpenPNM`, which means somehow your are mixing up version.  `openpnm` is version 2, while `OpenPNM` is version 1.  If you get this sorted out, it will work.  Perhaps you know a python expert that can sit at your computer and get you sorted out?

**Comment by xu-kai-xu** [comment]
Emmm, the previous problem still exists. I am still looking for someon to help solve it. And I found that, whatever modules I imported, spyder just feed back that the module imported but unused. That confuse me terribly. Do you have some suggestions?

Sent from Mail for Windows 10

**Comment by jgostick** [comment]
It seems that you have both version 1.6 and 2 installed at the same time.  I think this is only possible if you have downloaded the source code and have it stored somewhere on your machine that Python finds it.  This can be confirmed by creating a `test_script.py` file, and storing it somewhere far away from the location of the downloaded source code (Perhaps C:\?).  Then when you open this `test_script.py` file in spyder and run it, it will *not* find the source code, only the properly installed pip version.  The contents of the `test_script.py` file should be something like:
```
import openpnm as op
net = op.network.Cubic(shape=[5, 5, 5])
```

**Comment by xu-kai-xu** [comment]
I tried, then find it seems to work. And then the console told me 
“TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'”. Does it have something to do with the 32 byte systems?

Sent from Mail for Windows 10

**Comment by jgostick** [comment]
Can you supply some more of the error surrounding the message?  That way I'll know where it's coming from.  Can also give me the printout of `pip list` on the windows command line so I can see what you have installed?

**Comment by xu-kai-xu** [comment]
These are the pip lists:
“””
---------------------------------- ---------
alabaster                          0.7.11
anaconda-client                    1.7.2
anaconda-navigator                 1.9.2
anaconda-project                   0.8.2
appdirs                            1.4.3
array-split                        0.5.2
asn1crypto                         0.24.0
astroid                            2.0.4
astropy                            3.0.4
atomicwrites                       1.2.1
attrs                              18.2.0
Automat                            0.7.0
Babel                              2.6.0
backcall                           0.1.0
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.6.3
bitarray                           0.8.3
bkcharts                           0.2
blaze                              0.11.3
bleach                             2.1.4
bokeh                              0.13.0
boto                               2.49.0
Bottleneck                         1.2.1
certifi                            2018.8.24
cffi                               1.11.5
chardet                            3.0.4
click                              6.7
cloudpickle                        0.5.5
clyent                             1.2.2
colorama                           0.3.9
comtypes                           1.1.7
conda                              4.5.11
conda-build                        3.15.1
constantly                         15.1.0
contextlib2                        0.5.5
cryptography                       2.3.1
cycler                             0.10.0
Cython                             0.28.5
cytoolz                            0.9.0.1
dask                               0.19.1
datashape                          0.5.4
decorator                          4.3.0
defusedxml                         0.5.0
distributed                        1.23.1
docutils                           0.14
entrypoints                        0.2.3
et-xmlfile                         1.0.1
fastcache                          1.0.2
filelock                           3.0.8
Flask                              1.0.2
Flask-Cors                         3.0.6
flatdict                           3.1.0
gevent                             1.3.6
gitdb2                             2.0.5
GitPython                          2.1.11
glob2                              0.6
greenlet                           0.4.15
h5py                               2.8.0
heapdict                           1.0.0
html5lib                           1.0.1
hyperlink                          18.0.0
idna                               2.7
imageio                            2.4.1
imagesize                          1.1.0
incremental                        17.5.0
ipykernel                          4.10.0
ipython                            6.5.0
ipython-genutils                   0.2.0
ipywidgets                         7.4.1
isort                              4.3.4
itsdangerous                       0.24
jdcal                              1.4
jedi                               0.12.1
Jinja2                             2.10
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.2.3
jupyter-console                    5.2.0
jupyter-core                       4.4.0
jupyterlab                         0.34.9
jupyterlab-launcher                0.13.1
keyring                            13.2.1
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
llvmlite                           0.24.0
locket                             0.2.0
lxml                               4.2.5
MarkupSafe                         1.0
matplotlib                         2.2.3
mccabe                             0.6.1
menuinst                           1.4.14
mistune                            0.8.3
mkl-fft                            1.0.4
mkl-random                         1.0.1
more-itertools                     4.3.0
mpmath                             1.0.0
msgpack                            0.5.6
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.4.0
nbformat                           4.4.0
networkx                           2.1
nltk                               3.3
nose                               1.3.7
notebook                           5.6.0
numba                              0.39.0
numexpr                            2.6.8
numpy                              1.15.1
numpydoc                           0.8.0
odo                                0.5.1
olefile                            0.46
openpnm                            2.0.3
openpyxl                           2.5.6
packaging                          17.1
pandas                             0.23.4
pandocfilters                      1.4.2
parso                              0.3.1
partd                              0.3.8
path.py                            11.1.0
pathlib2                           2.3.2
patsy                              0.5.0
pep8                               1.7.1
pickleshare                        0.7.4
Pillow                             5.2.0
pip                                18.1
pkginfo                            1.4.2
pluggy                             0.7.1
ply                                3.11
porespy                            0.3.9
prometheus-client                  0.3.1
prompt-toolkit                     1.0.15
psutil                             5.4.7
py                                 1.6.0
pyasn1                             0.4.4
pyasn1-modules                     0.2.2
pycodestyle                        2.4.0
pycosat                            0.6.3
pycparser                          2.18
pycrypto                           2.6.1
pycurl                             7.43.0.2
pyflakes                           2.0.0
Pygments                           2.2.0
PyHamcrest                         1.9.0
pylint                             2.1.1
pyodbc                             4.0.24
pyOpenSSL                          18.0.0
pyparsing                          2.2.0
PySocks                            1.6.8
pytest                             3.8.0
pytest-arraydiff                   0.2
pytest-astropy                     0.4.0
pytest-doctestplus                 0.1.3
pytest-openfiles                   0.3.0
pytest-remotedata                  0.3.0
python-dateutil                    2.7.3
pytz                               2018.5
PyWavelets                         1.0.0
pywin32                            223
pywinpty                           0.5.4
PyYAML                             3.13
pyzmq                              17.1.2
QtAwesome                          0.4.4
qtconsole                          4.4.1
QtPy                               1.5.0
requests                           2.19.1
rope                               0.11.0
ruamel-yaml                        0.15.46
scikit-image                       0.14.0
scikit-learn                       0.19.2
scipy                              1.1.0
seaborn                            0.9.0
Send2Trash                         1.5.0
service-identity                   17.0.0
setuptools                         40.2.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.11.0
smmap2                             2.0.5
snowballstemmer                    1.2.1
sortedcollections                  1.0.1
sortedcontainers                   2.0.5
Sphinx                             1.7.9
sphinxcontrib-websupport           1.1.0
spyder                             3.3.1
spyder-kernels                     0.2.6
SQLAlchemy                         1.2.11
statsmodels                        0.9.0
sympy                              1.1.1
tables                             3.4.4
tblib                              1.3.2
terminado                          0.8.1
testpath                           0.3.1
toolz                              0.9.0
tornado                            5.1
tqdm                               4.26.0
traitlets                          4.3.2
transforms3d                       0.3.1
Twisted                            18.7.0
unicodecsv                         0.14.1
urllib3                            1.23
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.14.1
wheel                              0.31.1
widgetsnbextension                 3.4.1
win-inet-pton                      1.0.1
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.10.11
xlrd                               1.1.0
XlsxWriter                         1.1.0
xlwings                            0.11.8
xlwt                               1.3.0
zict                               0.1.3
zope.interface                     4.5.0	“””
after I uninstall the 32byte and install the 64byte anaconda, the error disapper, so I can’t show more details of the error surrounding.

Sent from Mail for Windows 10

**Comment by jgostick** [comment]
ok, so you're saying that the problem is gone now that you've installed the 64 bit anaconda?  That's great news!  It's also helpful to know that users *must* use the 64 bit version.  We do cast some internal arrays to 64 bit to accommodate large arrays, but I don't think we say explicitly that users must install the 64 bit version.

**Comment by xu-kai-xu** [comment]
Althouth I have no idea how the problem is solved, it runs well now, and thanks for all your help.

Sent from Mail for Windows 10

**Comment by xu-kai-xu** [comment]
sir, i look through the tutorials, both on the website, and in the format of pdf, but didn't find a specific way to extract the pnm data to the vtk or net.vtp format. i only find something in the IO module.  may you provide some more details about how to transform the data to the paraview foramt?  thanks a lot.

**Comment by xu-kai-xu** [comment]
emm, i read the vtk.py files and find the way to extract vtp files, and use it to generate a primary models. that looks a little simple.,and it seems i can make some better ones

**Comment by jgostick** [comment]
@xu-kai-xu I'm not sure what your question is :-)  It seems you were having trouble export data to vtk, but now you figured it out, but you think the data is not exported properly?  Could you maybe open a *new* issue where you state your problem more clearly.  BTW, if you're problem concerns that fact that the vtk files don't export throat data fully (so putting cylinder glyphs in paraview is a pain), then you are correct and that is an open issue.  See #507
