### ISSUE TITLE
Trivial warnings when defining multiple geometries

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#690]
When defining two geometries, lots of warnings pop up saying pore diameter not found, etc, which is kind of annoying. In other words, right now there's no way to define multiple geometries without producing such warnings, which obviously should not be the case. I tend to like @maghighi 's idea that we should not throw any warnings whatsoever. Instead, there should be a method like check_geometry_health() that takes care of the warnings once the geometries are initialized.

**Comment by jgostick** [comment]
There is an alternative: redirect the logger messages to a file:

```

import sys
sys.stdout = open('file', 'w')

```


________________________________________
Jeff Gostick, PhD, PEng
Associate Professor
University of Waterloo
Department of Chemical Engineering
Waterloo ON N2L 3G1
Tel: 519-888-4567 x38949
Web: pmeal.com

**Comment by ma-sadeghi** [comment]
Yea, I know the workaround. But, the problem is defining multiple geometries is very common. This way, the user might get confused about what has caused the problem. In other words, you can't tell if you actually did forget to assign geometry. Am I making sense?

**Comment by jgostick** [comment]
It's actually kinda funny that you bring it up because @TomTranter and I were literally talking about logger messages today!  They need work for sure.  There are too many of them, so they're not helpful.

**Comment by jgostick** [comment]
I'm going to close this issue, and open a newer more general one about 'rethinking the logger messaging' for version 2.0
