### ISSUE TITLE
Standardizing Percolation Algorithms

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#691]
I think we need to revise our percolation algorithms for a couple of reasons.

- They are not standardized i.e the output you get from each one is different

- They don't re-use code very well i.e. methods such as trapping are repeated in each one and don't follow the same logic

- Some are not very fast

- Some are not easy to understand

The question arises, should we even support OrdinaryPercolation when basic IP is now very fast? Have they all been bench-tested for networks of different sizes?

I would like to see one percolation algorithm with a setup method that does everything and then a separate run method that helps you interact with the class. I would also like to be able to give the run method a stop condition and then be able to start it again. This would be handy for coupled simulations where perhaps the phase occupancy might be altered by multiple algorithms running together. 

This issue arises because I am developing a model and I was originally using OP - I had to switch to IP for reasons I won't go into, but getting them to produce the same results is proving to be a very arduous task. 

I think this should be a group discussion to flesh out what we all want from the 'perfect' percolation algorithm and discuss how to make it more modular. Personally, I don't think implementing a basic one and then sub-classing it for different purposes is the way to go, then on the other hand giving a class lots of conditional running options is also confusing.

I suggest the following options a percolation algorithm should have for setup:
percolation_type [bond, site, mixed/both]
inlet_condition [individual, cluster] # accepts different shaped arguments [P1, P2, P3] for individuals or [[P1,P2], [P3,P4,P5]] for clusters
trapping [True, False] # trapping can be applied as a post-process for Ordinary but is typically applied at every step for IP. A new trapping algorithm for IP can be run as a post process but may need to run every time the algorithm is stopped if generating a drainage curve.
percolation_rule [ordinary, invasion]

Then run would have the following stop conditions (and probably more arguments I haven't thought of):
stop_condition [None, Pc_max, Sat_max, Step_max, Flow_max, Time_max]

We need to think about what information people want out of the algorithms and how they will be most frequently used to design them better. For example, (for my current work) I mainly just need to generate a drainage curve and so capillary pressure is the control on saturation and if needed I can apply a flow rate and work out a time to saturation after running the algorithm. However, others might need to interact dynamically with the algorithm and therefore flow rate or time might be the most sensible control method. It needs to run under both regimes and shouldn't require setting up and running two totally different classes.

It should also be able to start from a partially saturated network where disconnected clusters can grow like inlets or remain trapped. Percolation should really be able to handle evaporation and condensation too and so I know some of you will already be dealing with these issues.

**Comment by jgostick** [comment]
Don't forget late pore filling, viscous effects, drainage vs imbibition, changing meniscii volumes, three-phase flow, etc, etc, etc! :-)  

I agree with everything you say above, but I'm not confident it could/should all be done in one algorithm.  I personally favor the idea of a single SUPER fast IP algorithm (done in C or Cython), then all other variations use it behind the scenes.  Definitely, these algorithms should be way more consistent.

**Comment by TomTranter** [comment]
To handle drainage and imbibition maybe it would be possible to run setup a number of times giving it run_mode names then run could accept that run_mode as an argument and run with appropriate settings... You could of-course define multiple algorithms to achieve the same result. The key would be working from a partially saturated state. Late pore filling should be more general and be part of a volume fraction model possibly including inflating menisci volumes along with a standard 'fully occupied when invaded' setting. If running percolation controlling flow rate this model should be checked and forced to run automatically.

**Comment by jgostick** [comment]
I've started a kanban board under the projects tab, called "Perfect Percolation" where we can break each desired function or feature into a 'card', then decide how to deal with each.

**Comment by TomTranter** [comment]
Cool

**Comment by jgostick** [comment]
We are considering pulling the 'graph theory' and related functions/algorithms out of OpenPNM and into a stand-alone package.  (See #771 and the refactor_network_queries branch).  It would also make sense for these percolation algorithm to be part of this effort.  

Also, I think that Drainage should inherit from OP, which should come from GenericPercolation.  The IPs (viscous, quasi-static, etc) would also inherit from GenericPercolation.  Not sure what methods it will have, but this would make the whole picture more clear.

**Comment by TomTranter** [comment]
[Percolation_algs.pptx](https://github.com/PMEAL/OpenPNM/files/1975115/Percolation_algs.pptx)

**Comment by TomTranter** [comment]
Following our conversation we have to decided to strip out cooperative pore filling and snap off from MixedPercolation and make a subclass of it for Drainage for V2. MixedPercolation will then be developed in future to provide truly dynamic functionality

**Comment by TomTranter** [comment]
Proposed methods in the powerpoint is still ongoing. We could re-instate the kanban
