### ISSUE TITLE
OpenPNM seems to keep reference of objects even after purging them!

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#692]
I use ```purge_object()``` method to delete unused objects. However, once I tracked my memory on Windows Task Manager, it turned out even after purging the object, OpenPNM doesn't free the allocated memory to those objects. I tried to manually free unreferenced objects, but it didn't work. I also tried to change their scope by wrapping the part of the code which instantiates those OpenPNM objects, in a function, but it also didn't work. Basically, what I do is I generate a cubic network first, and then in a for-loop, I clone the network and play around with the cloned version, and finally purge it. Having said that, I think OpenPNM somehow keeps reference even after purging objects.

**Comment by jgostick** [comment]
This is also a Python thing.  They do Garbage collection, which means truly purge any de-referenced objects.  I guess there is somehow still a reference to it somewhere in our code.  We do store objects on objects, so maybe it's lingering somehow.

**Comment by ma-sadeghi** [comment]
Exactly, that's why I believe we're keeping references to the objects somehow.

**Comment by jgostick** [comment]
The 'referencing' system will be overhauled in V2.0, so let's add this to the TODO list

**Comment by ma-sadeghi** [comment]
Can you elaborate?

**Comment by jgostick** [comment]
I believe that this will be fixed in version 2, so I'm going to close this
