### ISSUE TITLE
Coordinates of the new pore after merging pores

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#693]
Currently, the coordinates of the new pore after merging pores is calculated as the mean of the merged pores. This is OK as long as the merged pores are roughly the same size. However, when merging a bunch of small pores and a big pore, the coordinates of the new pore is skewed towards the small ones since they have more weight when averaging the coordinates. Here's what I mean:

![figure_1-1](https://cloud.githubusercontent.com/assets/14086031/24919901/30abf5aa-1eb3-11e7-82ab-7e2a31f11a57.png)

I think the new pore should be placed in the centroid of the convex hull of the merged pores.

**Comment by jgostick** [comment]
This could be solved by finding the coordinates of all the neighbors of the new pore, and taking the average of those (which is akin to find the centroid of the new region).  This would also be subject to skewing though if the new neighbors are much different in size.

**Comment by TomTranter** [comment]
Did this ever get addressed?

**Comment by ma-sadeghi** [comment]
This is now addressed in PR #1191.
