### ISSUE TITLE
Range of Application for OpenPNM ?

### ISSUE THREAD

**Issue by johnwebster** [PMEAL/OpenPNM#695]
Hi，recently, I intend to start the pore network modeling. My research focus on transport of porous media, and I have known about that OpenPNM is an excellent tool. But I am not sure that whether OpenPNM could handle 3D images and extract a porenetwork from that? If you can make it possible, could please tell me some details about the steps or ideas? Thank you.

**Comment by jgostick** [comment]
Hi @johnwebster, OpenPNM does NOT take tomography images and extract networks.  However, there are other tools out there that can do this (maximal ball by Blunt's group at Imperial College, the iMorph software from a French group, 3DMA rock from Stoneybrook, etc).  We have created import functions for all of these formats, so you can get the network into openpnm for doing simulations.  Hope that helps.

**Comment by johnwebster** [comment]
Dear @jgostick Many thanks for your suggestions and telling me about the mature algorithms or softwares. I would try to tackle the extraction problem and mimics the flow in porous media using OpenPNM.

**Comment by jgostick** [comment]
We are also working on our own extraction code which will be rolled in the PoreSpy soon, but it's not quite ready yet.  Your request is a very common one, so we're trying to provide a solution for people.
