### ISSUE TITLE
add some examples to “IO_and_Visualization”？

### ISSUE THREAD

**Issue by johnwebster** [PMEAL/OpenPNM#699]
Dear Dr.Gostick，
The examples about OpenPNM are extremely valuable, especially for me. Cos I am new in the field of pore networks. I found some demos of '.dat' format data from Imperial College and '.mat'data imported into OpenPNM, from which I have achieved a lot. And I also intend to import the results from 'Imorph software'. But，I have to say that is difficult for me. Could you make some tutorials about the process?   
Thank you.

**Comment by jgostick** [comment]
Ok, I'll start a PR on that repo and close this.  But it should basically work the same as the statiol...also there should be an example in the docstring, no?

**Comment by jgostick** [comment]
Here you go!  

https://github.com/PMEAL/OpenPNM-Examples/blob/master/IO_and_Visualization/iMorph_load.md
