### ISSUE TITLE
how to find boudary pores

### ISSUE THREAD

**Issue by johnwebster** [PMEAL/OpenPNM#702]
Hi, I intend to define inlets and outlets of X, Y, Z direction. There should be 6 clusters of pores as respective oulets and inlets. However, I have no idea about seeking the relevant pores. Do you have any  pertinent suggestions? Thanks

**Comment by jgostick** [comment]
There is a function under ```OpenPNM.Network.tools``` called find surface pores.  It's pretty well documented, but in it's basic for is will just find all pores on ALL surfaces...it will label them as 'pore.surface'.  You can then do a coordinate-based boolean logic to find all pores that are both labelled 'pore.surface' AND have an X (or Y or Z) coordinate below some value.  

Like this:
``` python
op.Network.tools.find_surface_pores(network=net)
Ps = net['pore.surface']
crds = net['pore.coords']
net['pore.left'] = Ps*(crds[:, 0] < 0.1*sp.amax(crds[:, 0]))
net['pore.front'] = Ps*(crds[:, 1] < 0.1*sp.amax(crds[:, 1]))
net['pore.bottom'] = Ps*(crds[:, 2] < 0.1*sp.amax(crds[:, 2]))
net['pore.right'] = Ps*(crds[:, 0] > 0.9*sp.amax(crds[:, 0]))
net['pore.back'] = Ps*(crds[:, 1] > 0.9*sp.amax(crds[:, 1]))
net['pore.top'] = Ps*(crds[:, 2] > 0.9*sp.amax(crds[:, 2]))

```

I am thinking that this ```find_surface_pores``` method could be improved to label all 6 surfaces for the user, equivalent to calling it 6 times with one marker sent each time:

``` python
(xmax, ymax, zmax) = sp.amax(net['pore.coords'], axis=0)
(xmin, ymin, zmin) = sp.amin(net['pore.coords'], axis=0)
xave = (xmin+xmax)/2
yave = (ymin+ymax)/2
zave = (zmin+zmax)/2
markers = [[xmax + xave, yave, zave],
                  [xmin - xave, yave, zave],
                  [xave, ymax + yave, zave],
                  [xave, ymin - yave, zave],
                  [xave, yave, zmax + zave],
                  [xave, yave, zmin - zave]]
labels = ['right', 'left', 'back', 'front', 'bottom', 'top']
for face in [0, 1, 2, 3, 4, 5]:
    op.Network.tools.find_surface_pores(network=net, markers=markers[face], label=labels[face])
```

**Comment by johnwebster** [comment]
@jgostick Thanks for your providing the codes, and I have gained the favourable result. Although I suppose that this approach would miss lose some "effective pores", it is effective and enough to tackle boundary issues. I mean there is no counductance between all boundary pores (e.g. inlets pores), Setting pore 2 and 4 as inlets is reasonable, in fact, we consider pore 1 to 4 as inlets pores.
![demofigure](https://user-images.githubusercontent.com/27412340/27363072-cc555670-5664-11e7-9e21-24929ec359c6.png)

**Comment by jgostick** [comment]
Remember, the 'find_surface pores' function will only find pores that are on the surface...but all 6 surfaces.  The boolean mask of the coordinates will then help to differentiate which pores are on which face.  This means, according to the diagram you show above, that 3 would not be included since it would not be labeled surface, even though it's left of the coordinate cut-off value.  

In case you're interested, the 'surface' pore are identified using Delaunay tessellation to a fictitious point drawn farther left.  Any points that can form a delaunay triangle with this fictitious point would be considered as on the surface, and 3 is shielded by the 1, 2 and 4.

**Comment by johnwebster** [comment]
Okay, strong function, your interpretation is quite valuable to me, best wishes.
