### ISSUE TITLE
Direct Visualization with VTK

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#703]
VTK is now supported in python 3 although no-one seems to have made a song and dance about it. You can find a wheel on Christoph Gohlke's website http://www.lfd.uci.edu/~gohlke/pythonlibs/
This means it is now possible to do direct visualization in your IDE without having to export a vtk file and open it in paraview. 

It does however, come with a significant overhead for the user and is fairly complex to code with but over the last few days I've managed to write a few functions to help vizualize Voronoi and Stick_ball networks with both surface rendering using primitive geometric objects such as cylinders and spheres and also volume rendering using numpy arrays making the images.

I think going forward it would be worth developing a visualization class to enable users to quickly see the output of their algorithms. We wouldn't want to re-invent paraview and code too much functionality. But it would be useful and could be used by a future GUI. Emphasis will have to be on speed too as even a 10 cubed network is quite laggy with surface rendering on my machine and I have a fairly good graphics card. Volume rendered images are much faster to work with (zoom, rotate etc.) once rendered but a bit more work goes into creating them. 

Below are some examples of a volume rendered Voronoi geometry and a surface rendered cubic
![image](https://user-images.githubusercontent.com/7068741/27450110-988639f0-5758-11e7-9591-cba4511290fe.png)
![image](https://user-images.githubusercontent.com/7068741/27450141-ab5f59bc-5758-11e7-8c43-6ee187ab1540.png)

**Comment by ma-sadeghi** [comment]
Nice work Tom. Do you mind sharing your script? Anyways, if we want to just stick to the bare minimum visualizations, then why bother using VTK and not using `matplotlib`'s 3d features, which are in exchange fairly easy to use?

**Comment by TomTranter** [comment]
Hi @ma-sadeghi  sorry I just saw this reply. I can send you the scripts via email although they may need a bit of explaining. There are some really good examples here https://lorensen.github.io/VTKExamples/site/
I think this is something we need to discuss with Nevan as he develops the GUI. There must be a better way to output VTK information for paraview and for the GUI it may be better to write our own little visualization package. It would be great to be able to interact with objects for stitching, trimming, labeling etc. Matplotlib isn't really suitable for producing publication quality images but you're right could be a useful start for interactive plotting
