### ISSUE TITLE
Fix links in the documentation to the examples repo

### ISSUE THREAD

**Issue by Dezhao-Huang** [PMEAL/OpenPNM#705]
Hi everyone,
I am Dezhao Huang. I am currently a PhD in mechanical engineering at University of Notre Dame.I am new to OpenPNM. I have already finished the first tutorial to get  the resulting pressure gradient across the network, but I don't know how to visualize it by using the paraview software.
I have tried to click the instruction link below, but it does not exist anymore.
<img width="721" alt="image" src="https://user-images.githubusercontent.com/23017857/27522765-1405dcca-5a5b-11e7-86ed-d36ebe81ac57.png">
I would be really appreciated if anyone can give me a clue!
Thanks!

**Comment by jgostick** [comment]
Correct link is:

https://github.com/PMEAL/OpenPNM-Examples/blob/master/IO_and_Visualization/view_vtp_in_paraview.md

**Comment by jgostick** [comment]
I stupidly changed the file names a few months ago to make them more obvious when browsing the examples repo, but totally forgot about these links.  I'll make this an issue and fix it soon.

**Comment by Dezhao-Huang** [comment]
Thanks a lot!
