### ISSUE TITLE
Tutorial 1

### ISSUE THREAD

**Issue by Saeid-Sli** [PMEAL/OpenPNM#712]
1-It can be very helpful for beginners to have a link to the copy of the code of the entire tutorial (e.g., in a text file or as a python script). 

2-In tutorial 1: the boundary conditions have been set on 'front' and 'back' faces of the network but during  rate calculation of the network, the rate was evaluated at 'top' boundary which results in Q=0. So I think that we should make a change the code:
Q = alg.rate(pores=pn.pores('front')) instead of Q = alg.rate(pores=pn.pores('top'))

3-In tutorial 3: after adding boundary nodes to the network and during defining Geometry objects, the internal throats should be send to the 'geom' object. In the current version of this tutorial, all throats of the network (pn.Ts) has been passed to the 'geom' which make some problems during multiphase flow modeling. My recommendation is:

Ps = pn.pores('boundary', mode='not')
**Ts = pn.throats('boundary', mode='not')**
geom = op.Geometry.Stick_and_Ball(network=pn, **pores=Ps**, **throats=Ts**)

**Ps = pn.pores('boundary')
Ts = pn.throats('boundary')**
boun = op.Geometry.GenericGeometry(network=pn, **pores=Ps, throats=Ts**, name='boundary')

4- Adding a simple manual: "how to visualize OpenPNM  with Paraview?" can be so helpful for beginners. As working with Glyph is so tricky in the first use of this software.

**Comment by jgostick** [comment]
these fixes have been added in PR #722, which will be merged soon
