### ISSUE TITLE
Non-directional flow

### ISSUE THREAD

**Issue by joosthvanderlinden** [PMEAL/OpenPNM#715]
The documentation states:    
> Throats are non-directional, meaning that flow in either direction is equal (note that this restriction might be worth relaxing in a future release)

In the `return_results` function of the `GenericLinearTransport` class, the absolute value is taken of the flow rate(`rate = sp.absolute(g * dx)`).

If I were to remove the absolute value here, would the resulting (signed) flow rate be indicative of the direction of flow? If so, what is the reason the absolute value is taken here? 

For example, while it may not be likely, it is possible for an outlet node to have outgoing flow to another node. If the direction of flow is not taken into account, this flow is counted towards the total outflow. Consequently, wouldn't the permeability be incorrect?

**Comment by jgostick** [comment]
Hi @joosthvanderlinden 
The non-directional thing refers to the fact that transport from pore a to b experiences the same resistance as from b to a.  We only store 1 'conductance' for each throat, so both directions experience the same resistance.  

However, as you correctly point out, the flow can still have a direction.  I think you are correct that this ``absolute`` should be removed.  I will consult with @maghighi who knows this section of the code very well.  

As for permeability calculations, there are two things to keep in mind.  1.  Inlet and outlet nodes ONLY have inlet flow or outlet flow, so direction does not matter.  2.  When the calculating permeability using the ``StokesFlow`` class and calling ``calc_effective_permeability`` it calculates the rates into and out of each pore using the values stored on the Algorithm class, not the results that have been returned to the Phase.  In other words, this potential bug probably doesn't impact the permeability calculations.

**Comment by joosthvanderlinden** [comment]
Your reply makes sense @jgostick. I see now that the permeability uses the `rate` method of `GenericLinearTransport ` (rather than the `rate` variable in `return_results`), which does take direction into account. 

It looks like the only place where the `rate` variable in `return_results` is used, is to set the throat rates for the phase: `self._phase['throat.rate'][throats] = rate[throats]`. I couldn't find anywhere that the phase's throat rates are called, so I guess this bug has no real implications. Probably good to fix anyway. Thanks for looking into this!

**Comment by maghighi** [comment]
The sign of the throat rate between the two connecting pores depends on the direction of the flow. If we remove the `absolute`, it only shows the direction of the flow between tpore1 and tpore2 (low index pore and high index pore) which may not be useful. Because the users should be aware of the indices of the two pores to know the actual direction of the flow. So, in general the users should calculate it themselves.
The main rate which correctly calculates the net pore rate is the `rate` function in the `GenericLinearTransport` class.  The `rate` in `return_results` does not provide us any relevant data and I suggest to remove it in the next versions of the code.

**Comment by jgostick** [comment]
To summarize, there is no meaningful definition of 'direction'  The flow always goes from high to low pressure, but left/right, up/down, etc are meaningless.  This is why the absolute value is kept.  Sorry that I didn't clue into this right away.
