### ISSUE TITLE
Origin in Cubic is mixed up

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#718]
When looking at 'front', the left is not left but right, etc.

**Comment by Saeid-Sli** [comment]
First of all, we should decide where the origin is located (e.g., top left corner with z positive downward) then fix this issue. Also the right hand rule should be consistent with the place of origin and main directions (i, j, k) definition!

**Comment by jgostick** [comment]
Interestingly, I am noticing that throat numbers are not what they used to be (see #763)...I wonder if numpy has changed their array ordering or something?

**Comment by magnaou** [comment]
Just for our records, I revised this with @jgostick and apparently there is nothing wrong. However, openpnm convention regarding the orientation of the axis (x, y, z) is different from the one used in Paraview. We decided to keep it as it is.
