### ISSUE TITLE
Isotherm sorption - drying simulation

### ISSUE THREAD

**Issue by saeid-babaei** [PMEAL/OpenPNM#719]
Dear all,

I am a PhD candidate and I am trying to use OpenPNM to simulate isotherm sorption curve (water content vs relative humidity) and basically drying process of a pore network. Since I am from a solid mechanics background my knowledge is limited in this field. Hence I would really appreciate if you can help me through this problem.

I think for drying process I need to define the air as invading phase and model the invasion using "InvasionPercolation" or  "OrdinaryPercolation". then I can calculate relative diffusivity and so on. For the first phase my code is as follows but the quantities for relative humidity in network is wrong.
###############################################
import OpenPNM
import numpy as np
import matplotlib.pyplot as plt
workspace = OpenPNM.Base.Workspace()
workspace.clear()
# Generating the Network, adding Geometry and creating Phases
pn = OpenPNM.Network.Cubic(shape=[30, 30, 30], spacing=4.0e-5, connectivity=6)
pn.add_boundaries()

Ps = pn.pores('boundary', mode='not')
Ts = pn.find_neighbor_throats(pores=Ps,mode='intersection',flatten=True)
geom = OpenPNM.Geometry.Toray090(network=pn, pores=Ps, throats=Ts)
Ps = pn.pores('boundary')
Ts = pn.find_neighbor_throats(pores=Ps,mode='not_intersection')
boun = OpenPNM.Geometry.Boundary(network=pn, pores=Ps, throats=Ts)

air = OpenPNM.Phases.Air(network=pn, name='air')
water = OpenPNM.Phases.Water(network=pn, name='water')

# Define the Pore-Scale Physics
phys_air = OpenPNM.Physics.Standard(network=pn, phase=air, pores=pn.Ps,
                                    throats=pn.Ts)

phys_water = OpenPNM.Physics.Standard(network=pn, phase=water, pores=pn.Ps,
                                      throats=pn.Ts)
air['pore.surface_tension'] = water['pore.surface_tension']
mod=OpenPNM.Physics.models.capillary_pressure.washburn
phys_air.add_model('throat.capillary_pressure', model=mod)
# Set up and run the Ordinary Percolation Algorithm

bounds = [['front', 'back'], ['left', 'right'], ['top', 'bottom']]
OP_1 = OpenPNM.Algorithms.OrdinaryPercolation(network=pn,
                                              invading_phase=air,
                                              defending_phase=water)
inlets = pn.pores('bottom_boundary')
outlets= pn.pores('top_boundary')
step = 2
used_inlets = [inlets[x] for x in range(0, len(inlets), step)]
OP_1.run(inlets=used_inlets)
OP_1.return_results()

pt1=OP_1.plot_drainage_curve()
pt2=OP_1.plot_primary_drainage_curve()
cap=pt1['capillary_pressure']

totalvolume=pt1['total_volume']
C2C=4.0e-5
porosity=(totalvolume)/((30*C2C)**3)

dry=pt1['defending_phase_saturation']
dry=np.array(dry)
Relativehumidity =np.exp(-((cap*0.18)/(1*8.31*273.15)))

########################################

I would really appreciate it if you can help me with this problem and inform me what kind of algorithm is the right choice for this process.

Many thanks for your time and consideration
Kind regards,
Saeid

**Comment by jgostick** [comment]
Hi @saeid-babaei 
In your issue title you mention isotherms and sorption.  I'll firstly say that OpenPNM does not have a sorption algorithm...yet.  We would be very happy to help you develop one and welcome you to contribute it back into the code i/when you want.

As for your code snippet above, this is probably not quite what you're looking for.  The way you've got, is the pressure based invasion of air into a water filled, hydrophilic media.  There is not humidity gradients here.  If you were interested in humidity, you should invade some air to get a stable water configuration, then do a FickianDiffusion algorithm to model the movement of water vapor out of the system...as in, set the pores neighboring all water clusters to 100% RH (i.e. 0.5 mole fraction of water, or what ever the vapor pressure dictates), then set the top boundary to 0RH (or what ever your simulation requires), using Dirichlet conditions.  This would then give you a humidity gradient.  

I'll point you to [this example](https://github.com/PMEAL/OpenPNM-Examples/blob/master/Simulations/relative_diffusivity.md) which might be helpful.

**Comment by saeid-babaei** [comment]
Dear @jgostick 
Many thanks for your prompt feedback and help. I would like to develop the sorption algorithm and I would be grateful if you could help me during the development. Unfortunately I'm not an expert in Python but I will give it a try and keep you posted.
