### ISSUE TITLE
Tutorial 3 issues

### ISSUE THREAD

**Issue by wrighematthey** [PMEAL/OpenPNM#721]
Tutorial 3 as written does not work at present.  The main issue appears to be with the boundary pores. Following the code as written brings up errors when creating the internal geometry - possibly due to using all throats including boundary ones or that the boundary pore diameter is not defined at this point.  Even when the geometries can be created without errors, the phys_air_internal object is not created properly.  This leads to the drainage algorithm failing.

There is also an error with the mason model defined in the tutorial.  The model has Pc = -4*sigma*sp.cos(f*sp.deg2rad(theta))/Dt which generates negative values.  Looking at the paper, the minus sign is not present and removing this corrects the problem.

**Comment by jgostick** [comment]
You're probably the first person to ever make it to tutorial 3!  We are aware of the problems, and have an open PR ( #722 ) to fix it, which will occur within the next week or so.  Thanks!
