### ISSUE TITLE
Add a Vug generation class

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#725]
It would be helpful to have a network generation class that produces multiscale, hierarchical network objects.  This is in progress, but needs to be converted to a pull request.

**Comment by ma-sadeghi** [comment]
@jgostick What's the status of this issue? Is @Saeid-Sli working on it?

**Comment by Saeid-Sli** [comment]
@ma-sadeghi,  I translated the vug generation code into the 2nd version of OpenPNM and the code is with @jgostick right now.

**Comment by ma-sadeghi** [comment]
Thanks for the update @Saeid-Sli.
