### ISSUE TITLE
Correction in Tutorial 2

### ISSUE THREAD

**Issue by borahdj2010** [PMEAL/OpenPNM#732]
In the scipy.stats.norm definition it is mentioned that the loc keyword specifies the mean and the scale keyword specifies the standard deviation (same description given in the openPNM module). But in the OpenPNN tutorial in the link: 
http://openpnm.readthedocs.io/en/master/userguide/tutorials/intermediate_usage.html

under the heading  "Add pore size distribution model to each geometry" it is mentioned as below: 

“The remaining arguments are those required by the chosen model. In the above cases, these are the parameters that define the statistical distribution. Note that the mean pore size for geom1 will be 20 um (set by scale) while for geom2 it will be 50 um, thus creating the smaller surface pores as intended. The pore-scale models are well documented regarding what arguments are required and their meaning; as usual these can be viewed with Object Inspector in Spyder.”

I think this needs some modification.

**Comment by jgostick** [comment]
The scipy stats module changed, and we didn't update our docs.  Good catch.  I will change this along with your other issue on a PR today.
