### ISSUE TITLE
Unable to add geometry to network on Matfile

### ISSUE THREAD

**Issue by rupakbanerjee** [PMEAL/OpenPNM#738]
When I try to add geometry to a network created using a Matfile import, it does not allow me to add geometry to it. 

>>>pn = OpenPNM.Network.Matfile('Test.mat', xtra_pore_data='type', xtra_throat_data='type', name='my_import')
>>>Ps = pn.pores()
>>>Ts = pn.throats()
>>>geo = OpenPNM.Geometry.Genericgeometry(network=pn, pores=Ps, throats=Ts)

I get an error which says:

Exception: Provided locations are in use, instantiation cancelled_

I don't get this error when I create the network using OpenPNM.Network.Cubic

How can I get around this? I need to add geometry so that I can calculate throat lengths and then calculate permeability.

**Comment by jgostick** [comment]
I believe the Matfile class actually pulls all the data out into it's own Geometry...after you do the first line, what do you get when you do pn.geometries()?  It's probably not an empty list, which means a geometry has already been created for you.  If you want to access it directly you can do geo = pn.geometries[0] (assuming there is only one).

**Comment by rupakbanerjee** [comment]
pn.geometries() gets me the following:

>>>pn.geometries()
Output: GenericGeometry_yR0H0']

And when i try to access it directly, it gives me the following:

>>>geo = pn.geometries[0]
Output: 
Traceback (most recent call last):

  File "<ipython-input-4-91c691ddf64b>", line 1, in <module>
    geo=pn.geometries[0]

KeyError: 0

I can open the pn to see the following structure:
![image](https://user-images.githubusercontent.com/22400308/32176176-359c6c98-bd87-11e7-8c37-cf74b72ffb42.png)

I know that it is the correctly formatted mat file as I checked the .mat file in Matlab before importing. 

I really appreciate the help. Thank you

**Comment by jgostick** [comment]
My bad...you have to do ```geo = pn.geometries()[0]```

**Comment by rupakbanerjee** [comment]
That does work. But it gives me a string of size 1 and value 'GenericGeometry_yR0H0'. I still can't add models to this geometry (such as throat_length'). When I try to add model:

>>>geo.add_model('throat_length',model=OpenPNM.Geometry.models.throat_length.straight)

I get the following error:
AttributeError: 'str' object has no attribute 'add_model'

**Comment by jgostick** [comment]
arg, I"m sorry, my openpnm is apparently a bit rust...also what version of openpnm are you using?  
Try this: ```geo = pn._geometries[0]```?

**Comment by rupakbanerjee** [comment]
Wow @jgostick. Thank you. Even when it is rusty, you got it working for me. I have everything working the way I wanted. 

I am using Python 3.6 with OpenPNM 1.6.2. I took your advice and moved to the new platform when I started working on this new project.

**Comment by jgostick** [comment]
The way that objects are stored on other objects is a confusion pain in the but that we will try to remedy in version 2, which will be out sooner or later.  Glad it's working, happy coding!
