### ISSUE TITLE
Question about boundaries for a network imported using Statoil function

### ISSUE THREAD

**Issue by Mandzhi** [PMEAL/OpenPNM#739]
Hello,

I would like to ask about boundaries in non-cubic network. I imported network of Berea sandstone and wanted to perform a calculation of relative permeabilities (for air and water system). But when I started to set boundary conditions, an error appeared (raise KeyError(prop)
KeyError: 'pore.top'). Perhaps, it happens because there are no labels (top, bottom, left, right) for non-cubic networks. My question is - How to implement this particular case and is there any other option to set boundaries except manual choice of pores and assign labels to them?
Another question - what is 'inlets' and 'outlets' for pores? When I used them instead of top ann bottom, I  got the following warning: warn("Matrix is exactly singular", MatrixRankWarning)
MatrixRankWarning: Matrix is exactly singular and k_rel appeared as 'nan'.

P.S. I can attach my code upon request. Many thanks in advance!

**Comment by jgostick** [comment]
You are correct that there are not any 'top' labels.  You can add labels using either ``find_surface_pores`` or ``label_faces``, both are found in OpenPNM.Network.tools.  

Inlets and outlets for the invasion algorithms indicate where the invading fluid enters (inlets) and defending phase leaves (outlets).  You need to specify these using the set_inlets and set_outlets methods.

**Comment by Mandzhi** [comment]
Hello,
I tried suggested methods of adding labels, but don't think that I did it right. I couldn't find 'label_faces' in Network.tools (maybe I have an old version of OpenPNM - 1.6.1). 
And when I applied 'find_surface_pores', first, I decided to do it as follows:
bc_pores = op.Network.tools.find_surface_pores(network=pn, label='left')
bc_pores = pn['pore.left']
bc_pores = op.Network.tools.find_surface_pores(network=pn, label='right')
bcc_pores = pn['pore.right']
and 
water_flow.set_boundary_conditions(pores=pn.pores('left'), bcvalue=200000, bctype='Dirichlet')
water_flow.set_boundary_conditions(pores=pn.pores('right'), bcvalue=100000, bctype='Dirichlet')
water_flow.run()
Q_partial = water_flow.rate(pores=pn.pores('right'))
water_flow.run()
Q_full = water_flow.rate(pores=pn.pores('right'))
K_rel = Q_partial/Q_full
print(K_rel)
but I got an error: Exception: Because of the existing BCs, the method cannot apply new BC with the merge mode to the specified pore/throat.
And when I printed both lists, I realised that both right and left pores'lists are similar.
Then I labeled them as 'boundary' pores, however, I am still struggled in distinguishing them as 'left', 'right', etc.

**Comment by jgostick** [comment]
Yes, I think the ``label_faces`` was added in 1.6.2.  If you browse the code tab on github you can see the function, but I paste it below so you can see the gist:

``` python
def label_faces(network):
    r"""
    Finds pores on the surface of the network and labels them according to
    whether they are on the *top*, *bottom*, etc.  This function assumes the
    network is cubic in shape (i.e. with six flat sides)
    Parameters
    ----------
    network : OpenPNM Network object
        The network to apply the labels
    """
    find_surface_pores(network)
    Ps = network['pore.surface']
    crds = network['pore.coords']
    network['pore.top'] = (crds[:, 2] > 0.9*_sp.amax(crds[:, 2])) * Ps
    network['pore.bottom'] = (crds[:, 2] < 0.1*_sp.amax(crds[:, 2])) * Ps
    network['pore.right'] = (crds[:, 1] > 0.9*_sp.amax(crds[:, 1])) * Ps
    network['pore.left'] = (crds[:, 1] < 0.1*_sp.amax(crds[:, 1])) * Ps
    network['pore.back'] = (crds[:, 0] > 0.9*_sp.amax(crds[:, 0])) * Ps
    network['pore.front'] = (crds[:, 0] < 0.1*_sp.amax(crds[:, 0])) * Ps
```

**Comment by jgostick** [comment]
You can see that is just uses ``find_surface_pores`` then applies some logic to the pore locations to label the 6 faces.

**Comment by Mandzhi** [comment]
Thank you. It works!
