### ISSUE TITLE
Pore-scale model for calculating conductance for the solid phase in cubic networks

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#740]
Right now, we only have pore-scale models for calculating the conductance for the void. It would be nice to have them in the solid phase as well. This is useful since we can simulate both phases (ex. heat transfer in the solid + mass transfer in the void) using a single network.

**Comment by ma-sadeghi** [comment]
We decided not to model conduction in solid phase as it turned out to be insignificant (in the flow battery project).

**Comment by jgostick** [comment]
We have several new network classes that allow one to model the solid phase with a dual network, so let's close this...although we should open a new issue about adding solid phase models that work well with the dual networks.
