### ISSUE TITLE
Allow negative throat length to account for overestimated conductance of overlapping pores

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#743]

**Comment by ma-sadeghi** [comment]
@jgostick What do you think?

**Comment by jgostick** [comment]
I'll need a bit more explanation on the what and why

**Comment by ma-sadeghi** [comment]
Sorry for the confusion. Let's say we want to create a cubic network to represent SGL, which is highly porous and at the same time has a wide pore size distribution (see below, note that the x-axis is radius)
![image](https://user-images.githubusercontent.com/14086031/33077522-0a115d68-ce9e-11e7-9e63-0f5e2c2419fc.png)
Clearly, a spacing of 40 microns will lead to lots of (?) overlapping pores and yet porosity would not even exceed 50%. To match porosity, we need to increase spacing, which creates more overlapping pores. The problem with overlapping pores is that the calculated conductance between them is not realistic.

**Comment by jgostick** [comment]
Hi porosity materials in a cubic network is a pain for sure.   You have to use cubic pores and throats to get sufficient porosity, but even then the psd is not wide enough...but it's better.  You basically can't have overlapping pores.  I  was thinking that you could let pores overlap, if you then removed the region of overlap from each pore and set the throat to essentially 0 length.

**Comment by ma-sadeghi** [comment]
So do you think we should embed this in Cubic class by default?

**Comment by jgostick** [comment]
I would be a pore-scale model.  I think there is an issue already about this: #644
