### ISSUE TITLE
Improve reduce_coordination model to prevent connectivity errors

### ISSUE THREAD

**Issue by borahdj2010** [PMEAL/OpenPNM#746]
I was trying with different coordination numbers on cubic networks. Line 83-86 of the code in pore_topology.py say that     
Notes
    -----
    Pores with only 1 throat will be ignored in all calculations since these
    are generally boundary pores.

However, I am getting isolated pores after I trim the pores using 
        pn.add_model(propname='throat.trim', model=mod, z=8, mode='random')
        pn.trim(throats=pn['throat.to_drop'])

Moreover, when I run a transport simulation finally I end up with nan values for permeability. It would be beneficial if there was a check in place to raise an error before start of the simulation.

Please let me know if I am missing something here. Right now I put on a loop to check for isolated pores and delete them until the count reaches 0.

**Comment by jgostick** [comment]
This function is known to do this if the too many throats are removed. It is not very smart...but just yesterday we were having a conversation that might be relevant here.  If this function first finds the minimum spanning tree of the network, and treats these throats as 'untouchable', then the network will always remain connected.  With this approach it would be possible to get down to a coordination of 2.  I will cook this up and post some code here.

**Comment by jgostick** [comment]
OK, below is some code that you can put into your script to get a desired coordination without wrecking the network:

``` python
import scipy as sp
from scipy.sparse import csgraph as csg
import OpenPNM as op
import matplotlib.pyplot as plt

# Create network
pn = op.Network.Cubic(shape=[30, 30, 30], connectivity=6)

# Find minimum spanning tree using random weights
am = pn.create_adjacency_matrix(sym=False, data=sp.rand(pn.Nt))
mst = csg.minimum_spanning_tree(am, overwrite=True)
mst = mst.tocoo()

# Label throats on spanning tree to avoid deleting them
Ts = pn.find_connecting_throat(mst.row, mst.col)
Ts = sp.hstack(Ts)
pn['throat.mst'] = False
pn['throat.mst'][Ts] = True

# Trim throats not on the spanning tree to acheive desired coordination
z = 3.5
Ts = sp.random.permutation(pn.throats('mst', mode='not'))
Ts = Ts[:int(pn.Nt - pn.Np*(z/2))]
pn.trim(throats=Ts)

# Analyze resulting distribution of coordination numbers and check health
print(sp.mean(pn.num_neighbors(pores=pn.Ps)))
plt.hist(pn.num_neighbors(pores=pn.Ps), bins=10)
print(pn.check_network_health())

```

**Comment by jgostick** [comment]
We probably won't put this change into openpnm right away.  We are working on Version 2, and want to stop adding features to Version 1.

**Comment by borahdj2010** [comment]
Thank you very much.

**Comment by jgostick** [comment]
I'm going to assume it worked for you.  I'll keep this issue open so we don't forget to update the code with this improvement.  If you have any problems with it please come back here and let me know so we can keep improving it.

**Comment by jgostick** [comment]
OK, this has been added in V2 as a model under network.models.topology
