### ISSUE TITLE
Question about capillary pressure digital experiments (and relperms)

### ISSUE THREAD

**Issue by Mandzhi** [PMEAL/OpenPNM#750]
Hello,
First of all, happy holidays! I have a question about implementation of capillary pressure 'experiments' in OpenPNM (in particular, drainage). I am trying to reproduce several lab Pc experiments for sand packs and Berea / Bentheimer sandstone. In general it looks not so bad (the image is attached) although some mismatch occurs, but I have a problem with Sc (connate water saturation), since in a case of simulated Pc-curve it starts from 0 and finishes at 1. My question is - how to change the range for Sw and take Sc values into account for each particular case?
I also tried to calculate relative permeabilities as it was described at Section 3.5.3 Calculate Relative Permeability of Each Phase in OpenPNM user guide, but I got an error: warn("Matrix is exactly singular", MatrixRankWarning), and I don't know why it could happen.
Thank you!
![figure_pc_drainage_curves](https://user-images.githubusercontent.com/28112614/34653170-5ef2af46-f3f9-11e7-87d0-8a6f210e1c5c.jpeg)

**Comment by jgostick** [comment]
Hi @Mandzhi 
Your fit to the PC data is pretty good.  In order to get the Sw to start at 0.8 you can use the ``set_residual`` method of the drainage function to set 20% of the pores to be initially air filled.  Which pores you set to filled is a question though.  :-)  There is also the option to include trapping in this algorithm, so that not all the water phase escapes.  To do this you need to specify outlet locations using ``set_outlets`` but also enable trapping in the ``setup`` step (``trapping=True``).

**Comment by jgostick** [comment]
I'll add that at the moment we don't have an imbibition algorithm that is general enough (only applied to fibers).  Ideally you'd want to run this first to get the trapped air configuration, which is presumably the cause of the 20% initial air in your data above.  We are working on a more general imbibition algorithm, but are also in the process of releasing OpenPNM V2, so not sure which will come first.  If you want to code up your own imbibition algorithm, I'd be glad to guide through it.

**Comment by Mandzhi** [comment]
Thank you @jgostick 
I think, I'll try a set_residual approach. I didn't start yet, but I want to get a list of pores (their indexes and pore size); then to sort them and choose the smallest ones that were initially air filled. And insert them as an array to set_residual params [kind of semi-manual method]. Also, in the network that I use (from Imperial College London) there are 241 isolated pores. I think if I will find their volumes and the total volume of all pores, it can be possible to find total and open porosity. Maybe after this, I can code an imbibition algorithm.
