### ISSUE TITLE
Rename Neumann BC to rate

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#776]
Mehrezh pointed out that the Neumann conditions is defining the gradient, while our Neumann is prescribing the flux (i.e. conductivity * gradient).

**Comment by ma-sadeghi** [comment]
I think it makes more sense to prescribe flux. Maybe we should only change the keyword from Neumann to flux. This is how it works in most commercial CFD packages I know about.

**Comment by jgostick** [comment]
We'll stick with Neumann, because all other options are not general to all physics.

**Comment by jgostick** [comment]
we'll go with rate, and perhaps support neumann just for olde times sake

**Comment by jgostick** [comment]
After some flip-flopping, it's probably better to keep neumann, to be more in-line with the dirichlet
