### ISSUE TITLE
Use sympy to do taylor series expansion for source terms

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#781]

**Comment by jgostick** [comment]
Tom is using this for a capillary pressure model, so it will be a dependency, so we should figure out how to do Taylor series expansions with it.

**Comment by TomTranter** [comment]
@jgostick I've started a new branch for this code 'sympy_source_terms'. So far I've updated the old ones and made the equivalent sympy versions. If you look at the code you'll see they follow the same basic pattern and the method of linearization is the same for all of them to match the old methods. However, I'm not totally convinced this will work when we start plugging values in. See pg. 49 of the Patankar [book](https://www.researchgate.net/profile/Luisiana_Cundin/post/Can_someone_help_me_prove_the_approximate_coefficient_of_numerical_diffusion/attachment/59d63e6779197b807799b078/AS:423813709078528@1478056470430/download/Patankar+Numerical+Heat+Transfer+and+Fluid+Flow+-.pdf). It seems that the S2 term always needs to be negative to prevent divergence

**Comment by TomTranter** [comment]
[source_term_lin_test.txt](https://github.com/PMEAL/OpenPNM/files/1877368/source_term_lin_test.txt)
This script checks that the methods return the same results

**Comment by TomTranter** [comment]
@jgostick I've pushed another change to this branch which implements a general_symbolic source term method. This takes the equation and an OrderedDict which maps the symbols in the equation to the data on the object to evaluate in the function. I think this is close to what you want and it would also be possible to rewrite all the existing source terms to use this function as a base. We should discuss how we want to call it and limitations at the next meeting
