### ISSUE TITLE
What to do for models that want to return more than one property?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#793]
@TomTranter has a situation where a model calculates 5 things.  He *could* break the mode up into 5 different models, then calculate each separately, but this would introduce redundant computations.  How should we handle this?

**Comment by TomTranter** [comment]
The pandas data frame and numpy.recarray are both options. Recarrays are difficult to make on their own. I ended up making a dataframe from a dict then using the .to_records() function

**Comment by jgostick** [comment]
Did the resulting array work like a normal numpy array?  Did setitem complain?

**Comment by TomTranter** [comment]
It worked but got changed back to a normal ndarray I think. Would require
some tweaking

**Comment by jgostick** [comment]
This should be handled by a 'record array', which is a multi-column array, that can be accessed by label:

```pn['throat.capillary_data']['critical_radius']```

We just need to make sure openpnm doesn't mess it up upon saving, loading and interleaving

**Comment by jgostick** [comment]
Alternavely, instead of storing a recarray, the '__setitem__' method could detect it, then split the columns up like:
``pn['pore.capillary_data_critical_radius']``

This would help with interleaving A LOT

**Comment by jgostick** [comment]
It might even be simpler to just return a nested dict
