### ISSUE TITLE
`__getitem__` throws an error when the passed `sources` is not a list

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#796]
I wanted to use `_interleave_data` to pass some data from physics to phase, but it seems that `__getitem__` doesn't like it when the passed `sources` argument is not a list.

**Comment by jgostick** [comment]
Is this a version 1 error?

**Comment by ma-sadeghi** [comment]
I don't remember, but maybe.

**Comment by jgostick** [comment]
If the sources is not a list, just a single item, then you don't need to use interleave data, no?

**Comment by ma-sadeghi** [comment]
@jgostick I do in Knudsen pore-scale model, where `mixed_diffusivity` is stored in `physics`, but `bulk_diffusion` model needs them to be on `phase`.

**Comment by jgostick** [comment]
the automatically interleaving of data should just work...if you ask phase for a key it doesn't have, it searches on each physics...if it finds it there it interleaves an array for you..
