### ISSUE TITLE
`diffusive_conductance` model assumes that the throats are cylindrical.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#798]
I just realized that the `diffusive_conductance` model assumes that the throats are cylindrical. This is strange since the method accepts the optional argument `throat_area='throat.area'`.

**Comment by jgostick** [comment]
We definitely intended the model to be agnostic to the shape, hence the area argument. Are we really calculating area in there explicitly as a circle?

**Comment by ma-sadeghi** [comment]
Yep, here's a piece of code:
```
# Get the properties of every throat
tdia = network[throat_diameter]
tarea = _sp.pi*(tdia/2)**2

**Comment by jgostick** [comment]
This is  must fix for V2

**Comment by jgostick** [comment]
This is fixed in the big dispersion PR ( #849 )

**Comment by ma-sadeghi** [comment]
@jgostick Are you sure? It still assumes spherical cross-section. See line 43 of `diffusive_conductance.py` in the dispersion PR.

**Comment by ma-sadeghi** [comment]
I just pushed a fix to this.
