### ISSUE TITLE
scipy's allclose method might not be suitable for assertions in our tests.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#800]
`scipy`'s `allclose` method accepts two arguments, absolute error `atol` and relative error `rtol`. Currently, we're using the default values, which are 1e-8 and 1e-5, respectively. This gives huge error when the values are close to zero such conductances, diffusivities, etc.

`scipy` has another method under its unit_testing module called `assert_approx_equal`. The advantage is that this method accepts the number of significant errors as one of its arguments, which is exactly what we want. Just a caveat,  for some reason, `scipy`'s documentation advises that we use `allclose`! In that case, we should pass custom `atol` and `rtol` values depending on what variables we're comparing, which is not worth it IMO. What do you think?

**Comment by jgostick** [comment]
If it works, go for it.  This is way simpler.

**Comment by jgostick** [comment]
see [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_approx_equal.html)

**Comment by ma-sadeghi** [comment]
I just realized that we're still using numpy/scipy's `allclose` method for comparing desired and actual values in our tests. I reopened this issue as a reminder that we still need to fix this.

**Comment by ma-sadeghi** [comment]
Not to mention, currently those tests that are using `allclose` are literally not testing the code. Check this out:

```
from numpy import allclose
np.allclose(1e-10, 2e-10)
>>> True
```
