### ISSUE TITLE
Allow passing of dicts to setitem

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#802]
This is based on the discussion in #793.  

It would be ideal if the __setitem__ method detected when passed dictionaries and split them up into separate arrays, such as:

``` python
d = {}
d['pore.blah'] = 1
d['pore.yawn'] = 2
# Then assign it:
pn['pore.new_prop'] = d
# Which will create two new arrays:
pn['pore.new_prop_blah'] 
pn['pore.new_prop_yawn']

```

**Comment by jgostick** [comment]
OK, this is done and pushed.  One limitation: The dictionary must contain only pore or throat arrays, but not both.   The 'pore' or 'throat' part is decided by the dictionary key your assigning to, so all arrays in the received dict must agree.  This makes sense if you're using this in a pore-scale mode where you set the propname to 'pore.something'.  All data produced by said model should by pore-length arrays.

Example:
``` python
pn = op.network.GenericNetwork(Np=10, Nt=10)
d = {'array1': 1, 'array2': pn.Ps}
pn['pore.testing] = d
print(pn)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
openpnm.network.GenericNetwork:         net_1
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#     Properties                                    Valid Values
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
1     pore.testing_array1                           10 / 10   
2     pore.testing_array2                           10 / 10   
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#     Labels                                        Assigned Locations
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
1     pore.all                                      10        
2     throat.all                                    10        
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by ma-sadeghi** [comment]
@jgostick So we still can't use it for models such as Knudsen diffusivity where both pores and throats are assigned values.

**Comment by jgostick** [comment]
We'll have to discuss tomorrow, I'll add it to the agenda.
