### ISSUE TITLE
Consider using Cantera for Phases?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#806]
They've now [officially annointed by NumFocus](https://www.numfocus.org/blog/cantera-joins-numfocus-sponsored-projects/?utm_source=NumFOCUS+Master+List&utm_campaign=02e6d236c9-EMAIL_CAMPAIGN_2018_02_19&utm_medium=email&utm_term=0_d97ca30fde-02e6d236c9-505209225&mc_cid=02e6d236c9&mc_eid=77788db7ba), so I guess we can rely on the package to be maintained.

Might be useful to use this in the background, or somehow use it to make some calculations.

**Comment by jgostick** [comment]
@ma-sadeghi would you mind spending an afternoon with the package to see how we can use it?  It has a Python wrapper, but I believe needs to be installed from a separate binary.

**Comment by ma-sadeghi** [comment]
@jgostick Sure! I'll brief you guys during the next week's telecon.

**Comment by ma-sadeghi** [comment]
I briefly looked at the package and here's what I understood:

0. The backend is written mostly in `C/C++`, so it's pretty fast. It has nice wrappers for `Python`, `R`, and `Matlab`.
1. Installation is straightforward. You can install it using `conda`. The only downside is that it forces you to downgrade `numpy` to `1.13`. The latest is `1.14`, so not a big deal I guess.
2. It has plenty of nice features, but most of them are irrelevant to what we do in `openpnm`. For instance, it can solve a mixed reactor with hundreds of coupled reactions very quickly. You can even have a series of mixed reactors (which is similar to different pores in a pore network model), and it's still relatively fast. But, I think what we want is mostly thermophysical and transport properties of pure compounds and mixtures, which Cantera provides a nice interface for that too.
3. Basically, Cantera works with `phase` and `interface` objects. `phase` could be a pure fluid or a mixture of different species. You can attach relevant information such as homogeneous and heterogeneous reactions to both objects (homogeneous reactions would ideally attach to `phase` and heterogeneous once would attach to `interface`).
4. It has plenty of built-in materials available, but you can write your own custom materials as `cti` or `ctml` formats. `ctml` is basically `XML` and `cti` is their own format that has lots of abstractions and is easier to work with. Here's a sample `cti` script for adding a new reaction:
```
reaction( "O + HCCO <=> H + 2 CO", [1.00000E+14, 0, 0])
```
This is the equivalent `ctml`:
```
<reaction id="0028" reversible="yes">
  <equation>O + HCCO [=] H + 2 CO</equation>
  <rateCoeff>
    <Arrhenius>
      <A units="cm3/mol/s"> 1.000000E+14</A>
      <b>0</b>
      <E units="cal/mol">0.000000</E>
    </Arrhenius>
  </rateCoeff>
  <reactants>HCCO:1 O:1</reactants>
  <products>H:1 CO:2</products>
</reaction>
```
5. Here's an actual script that we could use in `openpnm`.
```
>>> import cantera as ct
```
Create a new phase and call it `air`.
```
>>> air = ct.Solution('air.xml')
>>> air()
  air:

       temperature             300  K
          pressure          101325  Pa
           density         1.17681  kg/m^3
  mean mol. weight         28.9697  amu

                          1 kg            1 kmol
                       -----------      ------------
          enthalpy            1894        5.487e+04     J
   internal energy          -84208       -2.439e+06     J
           entropy            6866        1.989e+05     J/K
    Gibbs function     -2.0579e+06       -5.962e+07     J
 heat capacity c_p          1003.1        2.906e+04     J/K
 heat capacity c_v          716.05        2.074e+04     J/K

                           X                 Y          Chem. Pot. / RT
                     -------------     ------------     ------------
                O2           0.21         0.231957         -26.2344
                N2           0.78         0.754253         -23.2816
                AR           0.01        0.0137896         -23.2152
     [   +5 minor]              0                0
```
Look at the species inside `air`.
```
>>> air.species()
[<Species O>,
 <Species O2>,
 <Species N>,
 <Species NO>,
 <Species NO2>,
 <Species N2O>,
 <Species N2>,
 <Species AR>]
```
Defining methane as a new specie. 
```
ch4 = ct.Species('CH4', 'C:1, H:4')
ch4.thermo = ct.ConstantCp(300, 1000, 101325,
                           (300, -7.453347e7, 1.865912e5, 3.576053e4))
tran = ct.GasTransportData()
tran.set_customary_units('nonlinear', 3.75, 141.40, 0.0, 2.60, 13.00)
ch4.transport = tran
```
Adding methane to the phase `air`.
```
>>> air.add_species(ch4)
>>> air.species()
[<Species O>,
 <Species O2>,
 <Species N>,
 <Species NO>,
 <Species NO2>,
 <Species N2O>,
 <Species N2>,
 <Species AR>,
 <Species CH4>]
```
Get binary diffusion coefficients vector.
```
>>> air.mix_diff_coeffs
array([  3.25335392e-05,   2.02637226e-05,   2.91851207e-05,
         2.04994129e-05,   1.73415530e-05,   1.55681482e-05,
         2.32485196e-05,   1.98256672e-05,   2.24190689e-05])
```
Change the mole fraction of methane and get the updated (on the fly) diffusivities.
```
>>> temp = air.X
>>> temp[-1] = 0.5 # setting x_ch4 to 0.5
>>> air.X = temp
>>> air.mix_diff_coeffs
array([  2.79449505e-05,   1.73897011e-05,   2.50377319e-05,
         1.78882423e-05,   1.52103321e-05,   1.36386140e-05,
         1.58879590e-05,   1.73627822e-05,   2.24190689e-05])
```
And lots of other stuff about thermophysical and transport properties...

**Comment by jgostick** [comment]
Can this be vectorized, like can we get all 9 diffusion coefficients at 1000 temperatures without a loop?

**Comment by jgostick** [comment]
It would also be interesting to see a pore-scale model that uses this.  Could you create a model that calculates the diffusion coefficient of oxygen in air for all pores, with the possibility that they are all at different temperatures?

**Comment by ma-sadeghi** [comment]
Sure. I’ll cook something up and let you know in the next telecon.

**Comment by jgostick** [comment]
Hi @ma-sadeghi , Can you create a PR that has your example pore-scale model in it?  I want to capture the idea before we forget.  We won't necessarily merge it, but we can play around with it.

**Comment by ma-sadeghi** [comment]
@jgostick Done.

**Comment by jgostick** [comment]
The only issue with this is that cantera is not installed by default with anaconda (yet)...so maybe do the import inside the function, and do a try / except if it's not there?

**Comment by ma-sadeghi** [comment]
Sure. It's now fixed.

**Comment by jgostick** [comment]
@ma-sadeghi did you even find out if it's possible to generate only a sub-set of cantera properties?

**Comment by jgostick** [comment]
Here is an example script from PR #996:

``` python

import openpnm as op
import cantera as ct
from openpnm.utils.misc import tic, toc
ws = op.core.Workspace()

net = op.network.Cubic(shape=[10, 10, 10], spacing=1e-6, name='test_net')
proj = net.project
geom = op.geometry.GenericGeometry(network=net, pores=net.Ps, throats=net.Ts)

air = op.phases.Air(network=net)
phys_air = op.physics.GenericPhysics(network=net, phase=air, geometry=geom)

cantera = op.models.phase.thermal_conductivity.cantera

print('Calculating thermal conductivity with Cantera')
tic()
air.add_model(propname='pore.thermal_conductivity',
              model=cantera,
              cantera_phase_obj=ct.Solution('air.xml'))
air.regenerate_models(propnames='pore.thermal_conductivity')
toc()


print('Calculating thermal conductivity directly')
tic()
water_conductivity = op.models.phase.thermal_conductivity.water
air.add_model(propname='pore.thermal_conductivity', model=water_conductivity)
air.regenerate_models(propnames='pore.thermal_conductivity')
toc()

```

**Comment by jgostick** [comment]
And here is the example model:

``` python

def cantera(target, cantera_phase_obj, temperature='pore.temperature',
            pressure='pore.pressure'):
    r"""
    Uses Cantera module to calculate thermal conductivity.
    Parameters
    ----------
    target : OpenPNM Object
        The object for which these values are being calculated.  This
        controls the length of the calculated array, and also provides
        access to other necessary thermofluid properties.
    cantera_phase_obj : Cantera Solution instance
        The object which contains the model to calculate thermal conductivity
    temperature : string
        The dictionary key containing the temperature values (K)
    pressure : string
        The dictionary key containing the pressure values (Pa)
    """
    try:
        import cantera as ct
    except ModuleNotFoundError:
        raise Exception('Cantera is not installed. Visit https://www.canter' +
                        'a.org/docs/sphinx/html/install.html for more info.')

    T = target[temperature]
    p = target[pressure]
    states = ct.SolutionArray(phase=cantera_phase_obj, shape=T.size)
    states.TP = T, p
    return states.thermal_conductivity

```

**Comment by jgostick** [comment]
We have decided to implement this functionality with ``chemicals`` instead of canterra, so I'm closing this.
