### ISSUE TITLE
Should mass transfer algorithms solve for concentration rather than mole fraction?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#808]
Following @magnaou question about why we have molar density in diffusive conductance terms, I think it's worth discussing whether this the best way.

**Comment by jgostick** [comment]
This might be a good idea, since you can only take concentration out of the differential if its constant, which it may not be.

**Comment by jgostick** [comment]
They actually don't explicity solve for anything...the user makes it mode fraction by (a) including molar concentration in the conductance, and (b) call the quantity mode_fraction.  You could easily use a different conductivity (just Dab*e/t) and set quantity to 'concentration', and you're done.

**Comment by ma-sadeghi** [comment]
@jgostick So do you think we should change the way we define conductance?

**Comment by magnaou** [comment]
In line 61 (https://github.com/PMEAL/OpenPNM/blob/dev-V2-alpha1/openpnm/models/physics/diffusive_conductance.py), we have:
gp1 = ct*DABt*parea[Ps[:, 0]] / plen1
where ct, the molar_density[mol/l] is by default read from the phase object.
So, unless the user specifies a priori phase['pore.molar_density']=1, the solver will be solving for mol fraction.

**Comment by magnaou** [comment]
@jgostick is the ['pore.molar_density'] in [mol/l]? If yes, should we convert it to SI units?

**Comment by jgostick** [comment]
so apparently this is a good idea after all

**Comment by jgostick** [comment]
I've added this change to my 'fix_open_issues' branch and it breaks 6 tests all related to the diffusive conductance obviously.  @magnaou would you be able to fix these tests?  Thanks

**Comment by magnaou** [comment]
Yes @jgostick I will do
