### ISSUE TITLE
check_network_helath returns empty list

### ISSUE THREAD

**Issue by borahdj2010** [PMEAL/OpenPNM#809]
I was working with the statoil class to import some networks from CT-images. I used the check_network_health function and found that for duplicate throats it returned like this:

h['duplicate_throats'] = [[1, 2], [45, 66], [], [23, 66]]

which need to be removed before I can take out the first element of each pair.

**Comment by jgostick** [comment]
Not sure why it would give an empty list, but you can easily pop it out of the list:
a = [i for i in h['duplicate_throats'] if i]

I won't close this issue yet, to remind us to fix this in the first place

**Comment by jgostick** [comment]
I can't seem to reproduce this, so I will close for now.
