### ISSUE TITLE
other admin methods, purge, copy, etc?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#811]
What about just saving the network?  Or purging other objects?  These are not implimented in V2 yet

**Comment by jgostick** [comment]
Hey @TomTranter @ma-sadeghi 
Can you give me your 2 cents worth on what other methods the Project class should have?  

The Project is a list, so has the usual methods, such as append and extend, which I've subclassed to ensure only OpenPNM objects can be added. 

 I've also added a few extras:
``purge_object``: Remove object from project, but also removes it's labels from all associated objects
``geometries``, ``phases``, ``physics``, ``algorithms``: returns a list of said objects
``find_phase``, ``find_geometry``: given a physics, returns it's associated object
``find_physics``: given a phase and/or a geometry, returns a list of physics
``grid``: returns The Grid

The Workspace has lots of other admin type things, like:
``save_workspace``, ``save_project``, ``load_workspace``, ``load_project``, ``copy_project``, ``close_project``, ``new_project``, ``import_data``, ``export_data``

**Comment by jgostick** [comment]
Just added:
``save_object`` and ``load_object`` to ``Project``, which lets you save an individual object

**Comment by TomTranter** [comment]
I don't know, I quite like the fact that it's just a list

**Comment by jgostick** [comment]
These were all added
