### ISSUE TITLE
Use `settings` to customize models in Geomety and Physics?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#813]
Instead of having hard-coded classes, like StickAndBall and Standard physics, what about having a CustomizablePhysics that accepts a bunch of settings in init that control which models are added?

**Comment by ma-sadeghi** [comment]
I like the idea. A nontrivial use case would be passing the shape of pores/throats as settings.

**Comment by jgostick** [comment]
This this is a lot of overhead and complexity for a small benefit.  It's almost just as easy to add new models by hand.
