### ISSUE TITLE
The definition of porosity in Utilities.vertexops is misleading

### ISSUE THREAD

**Issue by borahdj2010** [PMEAL/OpenPNM#814]
The function for porosity is defined as (Line 259-271):

def porosity(network):
    r"""
    Return the porosity of the domain - sum of the pore volumes divided by domain
    volume
    """
    domain_vol = vertex_dimension(network, network.pores(), parm='volume')
    try:
        pore_vol = np.sum(network['pore.volume'])
    except KeyError:
        logger.error('Geometries must be assigned first')
        pore_vol = 0
    porosity = np.around(pore_vol/domain_vol, 3)
    return porosity

Here it only considers the pore volume and not the throat volume. Before I was explicitly calculating porosity for my simulations, so had not troubles. But I started working with some extracted networks and used this function to quickly calculate the porosity of the samples to check fro consistency. However, the values were widely off the actual values. While checking the code for the function I have found that it only considers the pore volume in calculation of porosity. It is kind of misleading in my opinion.

**Comment by jgostick** [comment]
@TomTranter Can we remove some  or all of this vertex ops stuff?

**Comment by TomTranter** [comment]
Some of it is still important in v2 so should go into the materials class - we can discuss next Tuesday

**Comment by jgostick** [comment]
vertex ops has finally been deleted!  This misleading function will haunt us no more....however, we are left with the fact that openpnm actually has NO way to calculating porosity automatically, which stems from the fact that we don't know the true outer dimensions of the domain (only the bounding box around the outer pores, which lies inside the actual domain)....but this is another issue.
