### ISSUE TITLE
Create proper Boundary class, and enforce it

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#839]
To solve the area/length calc problem, we should make a boundary class that does it, along with all the other stuff the boundary class should do.

**Comment by ma-sadeghi** [comment]
Is this with respect to the so-called 'boundary' pores or those with boundary conditions?

**Comment by jgostick** [comment]
Maybe: 
* enforce that it MUST have throats?
* Nt must equal Np?
* must always be generated last?
