### ISSUE TITLE
`phases` attached to `Project` object is a method whereas expected to be a dictionary.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#843]
The `rate` method of `GenericTransport` expects `project.phases` to be a dictionary, whereas `project.phases` is a method.

```
phase = self.project.phases[self.settings['phase']]
```

Which one was it meant to be?

**Comment by jgostick** [comment]
This is fixed in PR #838 (reworking algs).  It should be a method....we decided that unless you plan to allowing writing to an attribute, then just making it a method.
