### ISSUE TITLE
Has `not_intersection` been replaced by `exclusive_or`?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#844]
If so, `rate` method attached to `GenericTransport` should be modified accordingly, right now it throws an error for 'unsupported logic'.

**Comment by jgostick** [comment]
Yes, exclusive_or is the correct term.....should we support both but make 'not_intersection' hidden?

**Comment by ma-sadeghi** [comment]
I guess it would complicate things in the long run. Let's stick with `exclusive_or`.
