### ISSUE TITLE
How to install OpenPNM?

### ISSUE THREAD

**Issue by PNMZR** [PMEAL/OpenPNM#846]
I have downloaded the soft called Anaconda. When I type the code 'pip install openpnm' in spyder of Anaconda, it didn't work. So can you give me a more detail instruction about how to install OpenPNM in Anaconda. Thanks

**Comment by ma-sadeghi** [comment]
1. Open terminal (if you're on linux/mac), or command prompt (if you're on windows).
2. Type `pip install OpenPNM`.
3. You should be good to go!
Enjoy!

**Comment by jgostick** [comment]
Only a minor point: openpnm should be all lower case when doing pip install.  The key is to enter this at the system terminal, not they python terminal.
