### ISSUE TITLE
Phyics initialization accept a list of geometries?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#847]
Instead of forcing users to create a physics for each geometry, maybe we could allow the passing of a list of
geometries?  Then the init would apply the physics to all the pores and/or throats associated with those geometries.  

On the other hand, This would break the bottom-up object associate look-ups

**Comment by TomTranter** [comment]
Most people don't know what they're doing

**Comment by jgostick** [comment]
but there are actually 3 options:
1. Use add_locations
2. Copy models between GenericPhysics
3. Add models to the phase

This would just add yet another option (confusion) and its just to save a few key strokes in a run script.  

I agree the idea is OK (after all, I originally suggested it), but I'm not sure it is worth adding yet another feature or trick.  We can discuss at the next telecon.
