### ISSUE TITLE
Update Percolation algs to V2

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#850]
* OP and IP have not been ported over to V2
* Drainage does not comply with V2 yet (needs to use settings instead of hidden attributes, results instead of return results, etc).  
* There is also a host of improvements that @TomTranter proposed in #691 .

**Comment by TomTranter** [comment]
Having just discussed removing it I'm of the mind that we should keep the GenericPercolation Class, simply to enforce consistency on the naming of data variables. Inlets and outlets could also be consistent across the more basic subclasses and set_residual is probably generic enough too
