### ISSUE TITLE
Dirichlet to value and Neumann to rate?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#862]
The ambiguity of the neumann boundary condition is causing problems...apparently OpenFOAM calls them fixed_value and fixed_rate.  Should we just go with value and rate?

**Comment by ma-sadeghi** [comment]
I like changing Neumann to rate but Dirichlet is expressive enough.

**Comment by jgostick** [comment]
I propose changing both so that they *match*...consistency is good right?

@TomTranter and @magnaou , can you weigh in on this one?

**Comment by magnaou** [comment]
@jgostick following our yesterday's discussion, I agree.

**Comment by TomTranter** [comment]
i like value and flux

**Comment by TomTranter** [comment]
rates can be volumetric

**Comment by ma-sadeghi** [comment]
@TomTranter But flux is supposed to be per unit area, might be confusing.

**Comment by TomTranter** [comment]
Isn't that what we want? That's the BC in any 3d fluid mechanics simulation

**Comment by ma-sadeghi** [comment]
Currently, Neumann applies rate (flux * area).

**Comment by TomTranter** [comment]
This is frustrating, we need units!!!!

**Comment by TomTranter** [comment]
We should go with the situation most like an experiment. You control the value, or you control the flow rate. X/m^2.s

**Comment by TomTranter** [comment]
Anyway - my point was that rate is a little ambiguous. Whatever Neumann is - if we're doing Neumann then we should call it Neumann. If we want to be like other fluid solvers we should accept a flux as a BC and change the calculations slightly if that's not what we actually use.

**Comment by ma-sadeghi** [comment]
I totally agree. The only concern is that if you want to apply rate/flux to a single pore, definition of the area could get tricky. This does not happen often as we can't apply flux/rate to a single pore in reality. But a really good use case is when dealing with dual networks. Let's say you're generating heat in the gas phase and due to high thermal conductivity of the solid, you assume that all of the generated heat transfers to the solid network. In that case, we might need to apply rate directly, rather than flux.

**Comment by TomTranter** [comment]
Isn't that more like a source term

**Comment by ma-sadeghi** [comment]
Yep, could be. But then every rate BC could be treated as a constant source term and vice versa (I guess).

**Comment by jgostick** [comment]
:-D  We are definitely in the wrong by using 'neumann'.  Flux would be nice, but the area is a pain to figure out, so we should go with rate.  As for changing Dirichlet, we are technically fine here, but I just want the terms to 'match' because I'm ridiculous.  Besides, it's what openfoam uses, so I propose changing dirichlet to value.

**Comment by jgostick** [comment]
we could arguably add 'flux' at some future date if we ever figure out what that means.  Flux might be a good term to use for the old 'nemann_group', were you assign a cumulative rate to a group of pores.

**Comment by TomTranter** [comment]
domain flux for the effective props

**Comment by TomTranter** [comment]
Something feels wrong about boundary pores altogether... It might make more sense to just have boundary throats that are all connected to one big pore (the super pore or Neumann group) and then define the total rate leaving the super pore. The super pore would span the domain face.

**Comment by TomTranter** [comment]
Is that essentially how it worked before except we had a bunch of boundary pores in between?

**Comment by TomTranter** [comment]
It kinda fits more with the flux convention as the important property of the throat is the cross-sectional area

**Comment by jgostick** [comment]
Trying to fix this presented a stupidly annoying problem: we use 'pore.dirichlet' to indicate the locations where dirichlet conditions are applied, and 'pore.dirichlet_value' to indicate the value at those locations.  If we change the name to 'value', then we now have 'pore.value' and 'pore.value_value'.  

A fix would be to only have on array called 'pore.value', which is initialized to nans.  Then the locations where bcs are set is found using ~sp.isnan.  Same would go for `pore.rate`.  Actually, to be super clear, I would say that these arrays should be called 'pore.bc_value' and 'pore.bc_rate'.

**Comment by TomTranter** [comment]
If our boundaries were individual geometry objects would that help. Like
bound_l = op.geometry.boundary(net, (P1,2,3), name=left, value=1.0,
rate=None)
They could then contain planar checks and other methods. Might want to
break out rules of not having overlapping geometries or give them a class
of their own.

**Comment by jgostick** [comment]
very interesting!  We also have an issue open about making better use of boundary objects (#839), so this might be an interesting approach.

**Comment by jgostick** [comment]
This is now done in a PR I will push shortly

**Comment by xu-kai-xu** [comment]
I think the boundary condition setting now is nice.  The name of  `value` and `rate` is vivid and explicit. And the name of `Dirichlet` and `Neumann` seems too mathematical. 

Then, I have another question about the boundary condition. In some numerical simulations, like LBM, **periodic boundary condition**, **elastic boundary condition**, and so on. These boundary conditions may deal with the materials, as I understand. I am curious about which boundary condition is used in PNM, e.g., if I set inlet and outlet pressures for a network. What do OpenPNM do with the fluid flowing out of the network? Just ignore it, or put it back to the inlet pores.

Or, my question is wrong. OpenPNM do not have this kind of boundary conditions.

**Comment by jgostick** [comment]
I don't know about elastic bcs, but periodic would indeed be nice. This requires more than just a BC though, it's requires topological changes to the network, by adding 'stitch' throats.  In fact, our oldest open issues on github pertains to how to deal with 'periodic' throats.
