### ISSUE TITLE
IO tools do not overwrite existing files.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#864]
Currently, IO tools do not overwrite existing files without throwing any warning. I think they should overwrite. Either way, they should be a warning thrown either if a file is overwritten or not being saved because of existing files.

**Comment by jgostick** [comment]
So what are you saying?  You want to prevent overwriting of existing files?  I think that can be done by changing the mode of the write function.

**Comment by ma-sadeghi** [comment]
No, I think overwrite should be the default mode and a small warning.

**Comment by ma-sadeghi** [comment]
It seems that it's gotten fixed
