### ISSUE TITLE
rename reactiveTransport 'tolerance' to 'r_tolerance'

### ISSUE THREAD

**Issue by magnaou** [PMEAL/OpenPNM#868]
I think we should rename reactiveTransport 'tolerance' to 'r_tolerance' as we also have 't_tolerance' in the TransientTransport.

**Comment by jgostick** [comment]
i think you've done this now, right?

**Comment by magnaou** [comment]
I did it only in the TransientReactiveTransport. The ReactiveTransport still has "tolerance" in the settings dict. Do you want to change it as well?
