### ISSUE TITLE
`bulk_diffusion` uses the interpolated throat diffusivity for pores as well.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#877]
I just pushed a fix (at least I assume it's a fix 😀) to the dev branch without making a PR. Just wanted to check with you guys if you approve of the idea.

Right now, `bulk_diffusion` uses the interpolated diffusivity for calculating `gp1`, `gp2`, and `gpt` (pore/throat conductances in a conduit). This approach might be reasonable in the absence of Knudsen effect. Even in the absence of Knudsen effect, this approach could potentially fail (introduce error) for cases where the gradient of properties could be high such as in multiscale networks at the interface between small and big pores. So, I think it's proper to use the corresponding diffusivity when calculating conductances within a conduit (1/2 pore + throat + 1/2 pore).

Also I added `throat_diffusivity` as argument to `bulk_diffusion` method (and inevitably changed the name of `diffusivity` to `pore_diffusivity`). This change is to allow directly passing throat diffusivity instead of interpolating it (ex. Knudsen effect).

What do you think?

**Comment by ma-sadeghi** [comment]
@TomTranter What do you think Tom?

**Comment by TomTranter** [comment]
I haven't read the code but it seems like a good idea if we're adopting the method of changing bulk diffusivity for capturing Knudsen effects. There may also be local temperature fluctuations that influence Dbulk. I suppose that the function should use a throat value if it exists and iterpolate if it doesn't

**Comment by jgostick** [comment]
this is dealt with in #898.  Basically, the rule should be that all models that calculate BOTH pore and throat properties, should accept the option to specify BOTH (pore_viscosity, throat_viscosity), but if one or the other is not found, then it is interpololated from the other.  Obviously at least one of them needs to be there.  I'm going to implement this in all of our physics modes, since they are the only ones that might needs BOTH.

**Comment by ma-sadeghi** [comment]
@jgostick There's still one issue left. We're using interpolated throat properties for pores. As an example, take a look at lines 50 and 55 in `hagen_poiseuille` on the latest DEV branch.

**Comment by jgostick** [comment]
No, I fixed this in #898, and it will be merged soon.

**Comment by ma-sadeghi** [comment]
Yup, confirmed. My bad.
