### ISSUE TITLE
models regen_mode problems when deferred or constant

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#880]
import openpnm as op
from openpnm.models.misc import random as rm
net = op.network.Cubic(shape=[2,2,2], spacing=1)
net['pore.blah']=1.0
net.add_model(propname='pore.blah', model=rm, element='pore',
              regen_mode='constant')
print(net['pore.blah'])
net['pore.blah']=1.0
net.add_model(propname='pore.blah', model=rm, element='pore',
              regen_mode='deferred')
print(net['pore.blah'])
net['pore.blah']=1.0
net.add_model(propname='pore.blah', model=rm, element='pore',
              regen_mode='normal')
print(net['pore.blah'])

**Comment by TomTranter** [comment]
If property exists it doesn't get recalculated in modes other than normal, even if model has changed. Is this the expected behavior? Seems a bit unexpected

**Comment by jgostick** [comment]
I think this is all fixed now by the dependency_tree PR (#888)
