### ISSUE TITLE
_run_reactive method improvement

### ISSUE THREAD

**Issue by magnaou** [PMEAL/OpenPNM#881]
In "_run_reactive" method, the "if" condition to assess the convergence with respect to the given tolerance leads to a "maximum recursion depth exceeded" error when having a slow convergence. I think we should fix it.

**Comment by jgostick** [comment]
The maximum recursion depth is around 1000, so this it pretty high.  Is the problem with the way tolerance is checked?  Have you updated it from my original, which was very crude?

**Comment by magnaou** [comment]
I updated it from your original. It is causing problems at the beginning of certain simulation cases when the tolerance is small (10^-6). If this tolerance is relaxed, the simulation runs well.

**Comment by jgostick** [comment]
@magnaou if this is fixed, can you close this issue?

**Comment by magnaou** [comment]
Fixed. There was a problem updating physics leading to slow convergence.
