### ISSUE TITLE
move conduit lengths out of utils

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#883]
This function looks like a pore network model, that should be in models/geometry, or maybe should be on VoronoiFiber?

**Comment by TomTranter** [comment]
It's used by the conductance models and uses centroids if they are there and coords if not so not specific to voronoi but was developed so that centroids would be used from voronoi (other geoms could have them though). It's a method used by more than one conductance model so I put it in utils originally. I don't think it really would work as a pore scale model as it's not data the user is really interested in - more like a helper function for the resistors in series calc. Why do you want to move it?

**Comment by jgostick** [comment]
It seems out of place.  It really feels like a pore scale model to me...shoudn't you calculate conduit lengths, store them on the object, then use those values in subsequent models?  I know it's actually more of a hassle this way, but I'm thinking in terms of philosophical consistency.

**Comment by TomTranter** [comment]
I suppose you could but if it's only used in the conductance model why not just leave it as a little helper function. Seems like more work and potentially more confusing data for the user to deal with

**Comment by TomTranter** [comment]
If it's bothering you philosophically then sure go ahead and change it

**Comment by TomTranter** [comment]
As this came up in the meeting today again I had a look at the code. diffusive and hydraulic conductance models have the ability to use it but the default is not to and electrical and thermal don't at all. There is an option 'calc_pore_len' that controls whether to use it or not and so I'm not even sure the latest Voronoi papers would be using it. But it exists for a reason which is that for polygonal pores the centroid is not necessarily the pore coordinate. Perhaps we could actually remove it and bear this in mind if polygonal pores ever get implemented properly

**Comment by TomTranter** [comment]
Whatever we decide we should standardize the conductance models treatment of length in the conduit calcs

**Comment by jgostick** [comment]
This is a very interesting problem.  This model should probably be the ONLY say pore and throat lengths are calculated inside any conductance model.  Instead of ``pore_length`` and ``throat_length``, the models all just take ``conduit_lengths``, and this should be a Nt x 3 array of [LP1, LT, LP2].  In the case of a cubic or normal network, these can be found easily from just radius of each pore and the spacing.  In more complicated geometries (ie extracted networks, voronoi) you'd need to calculate it a bit more carefully.

Here is a compromise: keep ``pore_len`` and ``throat_len`` as arguments, but IF ``conduit_lengths`` is specified, then is uses that instead.  That way we can make ``conduit_lengths`` a geometry model, then work on generalizing it.

**Comment by jgostick** [comment]
I am working on a pore-scale geometry model that will take the place of this.  It will require a bit of re-jiggering of the voronoi code, so I'm leaving the current function in place.  We can look at my new model for a while and figure out how to make it work for everyone.

**Comment by jgostick** [comment]
This is related to PR #912 and issue #923 , which both aim to calculate the throat length more rigorously as a throat property model.  I'm going to close this and move the discussion
