### ISSUE TITLE
Toray090 with OpenPNM

### ISSUE THREAD

**Issue by angelswat** [PMEAL/OpenPNM#887]
Hi @jgostick and @TomTranter,

I want to generate a network like Toray090 carbon paper, which is a fibrous media. However, I read some issues where Prof. Gostick indicates that lonely Voronoi do it. 
Even when I created a media, I first create a Delaunay network, then a Toray090 geometry, but it being a fibrous media don't have a function to see a fibre slice (voronoi network has it). So, I don't understand it!
Also, I can't view the fibres created, because the characteristic of Toray090 is that. 

I have those problems, and I don't know how to do it, maybe I am wrong!

Or what is the use of Toray 090? How to use it? Can I mix Voronoi with Toray090?

Please help me, 

Thanks, Angel.

**Comment by jgostick** [comment]
Hi @angelswat 
Your confusion is justified.  We are actively working on V2 which will alleviate problems like the one you are having, but that won't be ready for a few more weeks yet.  

The problem is this:
1.  Toray Geometry is meant to be associated with a cubic geometry, as per my 2007 paper in JPS. 
2.  The Voronoi network is both a network AND a geometry in one go (Note that in V2 we are adding a new module called 'materials' that will house classes which return these sort of 'complete' networks).  This Voronoi network is similar to my 2013 paper in JES, as well as the recent works by @TomTranter in Fuel Cells and TiPM.  

Depending on what you want, those are your two options.  For now, Id suggest creating a Cubic with a size of [40, 40, 10] and then adding the Toray090 geometry to it.  This will get you started.

**Comment by TomTranter** [comment]
You can do it but the good thing about using the Voronoi geometry is the spatial correlation between pore locations and sizes. Follow this example https://github.com/PMEAL/OpenPNM-Examples/blob/master/Topology/generate_voronoi_network.md. Taking a random network and then adding a Toray geometry will probably give you reasonable results but will have no spatial correlation as the sizes are picked at random from the distributions defined in the Toray geometry

**Comment by angelswat** [comment]
Thanks @TomTranter,

Exactly, I see that Toray090 geometry is even incomplete, instead, Voronoi has a lot of good functions. I believe can do it with Voronoi.
Being that you mentioned that example, I replicate it, and also I would like to do the part of Blender, however, the library is incomplete. What you recommend me to see the fibres, another library similar to Blender?

Another dude I have, throat diameter and fibre radius are not same ? That is to say, Fibres integrate the polygon where inside is the pore? And from it leave throat to connect another pore? If this is the case, what is the right fibre radius that I have to set?
(For example, I want to make a cubic media of length 280 um.)

I am writing a paper about it and I want to do it very well!

I hope your help, thanks.

**Comment by angelswat** [comment]
I will try to do with tiff files. I see some of the configurations that you mentioned. Then, the throat length is variable, therefore, I don't have to set fibre radius, because there's not a fixed throat length. Another thing I saw, for default, there're sizes in fibre radius and voxel length. Why? Is there a important reason?
I say it because if two pores are apart over the fibre radius, what happen? Is not this a problem? 

Thanks.

**Comment by TomTranter** [comment]
My 2016 paper has the statistical distribution parameters that were fit to my voronoi generate networks if you did want to put that into a pore scale model. The drawback with the Voronoi is that the image takes up a lot of memory and some time to generate one of a large size - Above 1 mm x 1 mm x 250 microns will take more than 30 mins and something like 2-3Gb of RAM

**Comment by angelswat** [comment]
Thanks so much @jgostick and @TomTranter.
Good luck with OpenPNM!

**Comment by angelswat** [comment]
Hi,

Sorry but I have a question (excuse me if I can´t understand it).

The fibres generated by Voronoi represents the solid material in the reality? Then, the empty space is represented by a kind of polyhedra in 3D. This is I can see in this image:
https://user-images.githubusercontent.com/32890792/39497757-57d041ea-4d6a-11e8-960a-4561fec14c4d.png

However, where is represented the pores and throats, that also in reality represents empty space? 

Thanks.

**Comment by jgostick** [comment]
The fibers are generated as the Voronoi graph, which has two benefits:  1. it's complement is the delaunay graph, which is the *pore network*.  2. it is nice to visualize the solid structure graphically as voronoi edges.  The picture you link to is the solid structure, and the delaunay graph exists in the pore space.

**Comment by TomTranter** [comment]
Yes just to elaborate a little more. The picture you link to is the solid (made in blender which I would not advise using) and currently we don't support visualizing the exact shapes of the pores and throats in openpnm itself. The last picture in the voronoi example on github shows a ball type representation of the pores with an equivalent diameter which was made in paraview. You can get a better image of the pore space by saving the voronoi._hull_image which is a 3d image of the entire domain with pores labelled by their pore index. This can be saved as a tiffstack and viewed in paraview and you can use thresholds so look at individual pores. There are some images in my thesis like this http://etheses.whiterose.ac.uk/16086/  on pg.133 which were actually generated doing morphological image opening to visualize water (which is maybe a topic for another day). The _hull_image is used in conjunction with the _fiber_image to get the pore properties such as inscribed diameter and volume. One thing to note with OpenPNM is that trimming pores from the network updates the index of the pores but does not update the indices in the image so I think this original index is saved as data on the geometry. This makes neighbor look-ups tricky if you're trying to visualize clusters of pores. Maybe something to consider developing in future but for now we have enough on our plates ;-)

**Comment by TomTranter** [comment]
@jgostick I think I'll update the example for version 2 and increase the explanations to address these questions - which have been helpful for us to know about. Thanks @angelswat

**Comment by angelswat** [comment]
Thanks so much @TomTranter and @jgostick. Your help has been awesome. Good luck!
