### ISSUE TITLE
convert printed messages in the transport algs to logger.info

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#899]
Making the progress of the transport algs a logger message means that they can be turned off if not needed by setting the loglevel on the workspace.

**Comment by jgostick** [comment]
@magnaou ... can you take care of this?  You can find examples of using the logger in the Base class.  Basically, you just import it at the top of the file, then use something like:
``` 
logger.info('put message here')
```
Then people can set loglevel to 30 to not see these message if the desire.

**Comment by magnaou** [comment]
@jgostick  yes, sure.

**Comment by jgostick** [comment]
Can pull the branch I created in PR #929, and fix there in there?

**Comment by magnaou** [comment]
I pushed the changes (+ others) to "more_issue_fixing_mhrz".
2 points to discuss:
1) by default ws.loglevel=30. So, the info in algs won't appear. In my opinion, we should make appear by default to allow the user to follow the progress of the computation (especially when it's transient or in the presence of non-linear S term).
2) setting ws.loglevel=20, prints what's expected but the formatting is not perfect...

**Comment by magnaou** [comment]
Example, when setting ws.loglevel=20:

2018-06-29 15:06:34,065 | INFO     | openpnm.algorithms.ReactiveTransport._run_reactive | Tolerance not met: 729.0
2018-06-29 15:06:34,070 | INFO     | openpnm.algorithms.ReactiveTransport._run_reactive | Solution converged: 0.0
2018-06-29 15:06:34,080 | INFO     | openpnm.algorithms.ReactiveTransport._run_reactive | Tolerance not met: 49.0478596908
2018-06-29 15:06:34,087 | INFO     | openpnm.algorithms.ReactiveTransport._run_reactive | Tolerance not met: 0.229598850146
2018-06-29 15:06:34,095 | INFO     | openpnm.algorithms.ReactiveTransport._run_reactive | Solution converged: 5.29378162761e-06
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Running ReactiveTransport
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Running ReactiveTransport

**Comment by magnaou** [comment]
The same example running the old way with prints:

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Running ReactiveTransport
Tolerance not met: 729.0
Solution converged: 0.0
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Running ReactiveTransport
Tolerance not met: 49.0478596908
Tolerance not met: 0.229598850146
Solution converged: 5.29378162761e-06

**Comment by ma-sadeghi** [comment]
This is addressed in PR #941
