### ISSUE TITLE
Rate method returns negative value for both inlets and outlets.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#903]
`StokesFlow.rate` returns a negative value for both inlets and outlets. I know we discussed the new sign convention earlier but regardless of that, my understanding is that the inlet rate should be opposite sign of the outlet rate.
![image](https://user-images.githubusercontent.com/14086031/40575204-9a80d052-60ae-11e8-8f10-13b8d6ab2a8e.png)

**Comment by jgostick** [comment]
I just fixed this and I'll make a PR with this plus other issue fixes soon.
