### ISSUE TITLE
Possible bug in set_source: positive reaction rate constant is treated as negative and vice versa!

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#906]
When you add a source term with a positive rate constant, `set_source` treats it as a sink and vice versa. I looked into the code and here's how it works right now:

Reaction = S1 * X + S2
1. Add S1 to the diagonal of `A`
2. Add -S2 to `b`

This makes sense only if the sign of the diagonal of the `A` matrix is negative, but since we build `A` with positive diagonal, the order has to be reversed:

1. Add -S1 to the diagonal of `A`
2. Add S2 to `b`

OR, we could build `A` with negative diagonal.

**Comment by jgostick** [comment]
The problem with fixing this is that the broyden iteration seems to really prefer positive values for S1, so we might have to switch the signs behind the scenes....and that could lead to unforseable problems to say the least!

**Comment by ma-sadeghi** [comment]
This is now addressed in PR #941

**Comment by ma-sadeghi** [comment]
Just for the record, as of now, negative source means consumption.
