### ISSUE TITLE
Finally a NumFocus-supported package for unit manipulations in Python!

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#909]
The yt-project team (part of NumFocus) have recently released `unyt` [package](https://github.com/yt-project/unyt) for manipulating units in Python. The package fully supports `numpy` arrays, and might be worth considering in `OpenPNM`. They've also submitted a [paper](https://github.com/yt-project/unyt/blob/master/paper/paper.md) to JOSS discussing the performance overhead of their package.

**Comment by jgostick** [comment]
I've got a PR (#914) going that shows this in action.

**Comment by jgostick** [comment]
I'm going to close this issue, since there is a PR already open on the matter where further discussion should occur.
