### ISSUE TITLE
Improved conductance calculation using proper pore area

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#913]
@ma-sadeghi and @Zohaib-Atiq have both been working on calculating the hydraulic and diffusive conductance of pore bodies, and have independently derived some equations that do a better job than present (flawed) approach.  These should be added as soon as possible and released in V2.1, which I think should appear within a month of 2.0.  (2.1 will include many of the 'extra' features we've been shelving).

**Comment by jgostick** [comment]
We talked about this extensively during todays' telecon (#922)

* We realized that there should be a model in the 'throat.area' folder that calculates the effective area of the pore-throat-pore conduit, called 'throat.effective_area' or 'throat.effective_conduit_area'.
* This model should take 'pore_shape' and 'throat_shape' as arguments, which can be pyramid, sphere, cube, circle, or square (the last 2 for 2D), and cylinder, cuboid, or rectangle (for 2d).
* The result of this model can be sent to a physics conductance model as 'throat_area', and the user would specify 'throat_length' still.  Also, 'pore_area' and 'pore_size' would no longer be needed so could be removed from the model.

**Comment by ma-sadeghi** [comment]
This is addressed in PR #935
