### ISSUE TITLE
Better 3d plotting of (small) networks

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#916]
https://veusz.github.io/3d/

**Comment by ma-sadeghi** [comment]
How's it different than matplotlib?

**Comment by jgostick** [comment]
making 3d plots in matplotlib is a bit of a pain, and seems like an afterthought added onto the code.  These guys have made it the marquee feature of their V3 release, so I'm hopeful it might be better.

**Comment by jgostick** [comment]
Their examples are downloadable as 'vsz' files, which is a mystery and pain in the butt...I think we're good with matplotlib.
