### ISSUE TITLE
Add throat.endpoints as a property

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#923]
If we had explicit coordinates for each end of a given throat, many geometry calculations would be much easier.  

It would really help the calculation of conduit conductance, since the actual throat length would be known, as would the true length of the pore in each direction (instead of using radius)

A rough outline of this is provided in PR #912 

Problems:
1.  The exact point where a throat ends is not so simple.  If the pore is a sphere, then there is a 'lens' that is created by the intersection of the pore and throat.  If the pore is a cube this does not happen.  
2.  Also, what if the throat is not cylindrical, but a cuboid?
3.  How should this information be represented?  pore.coords are Np x 3, so throat.endpoints should be Nt x 3 x 2?  (where the x 2 indicates an Nt x 3 array for each end?).

**Comment by jgostick** [comment]
At today's telecon we had a long discussion about this. To summarize:
1.  The actual end points depend on the pore shape...so maybe a basic model that finds the point on the perimeter of a sphere is a good start, and this could used in subsequent models where the shape is known/given/assumed.
2  It also ties in nicely with the discussion of better conductance models, which would use these end points to get pore lengths.

**Comment by xu-kai-xu** [comment]
@jgostick  I look into the source files about the `throat.endpoint` and `pore.diameter`. And I found that when using `conduit_length`, the summation of  `throat.conduit_length.pore1`, `throat.conduit_length.pore2` and `throat.conduit.throat` is 1 (i set the network spacing with 1). 
But the `throat,conduit_length.pore1` is always smaller than the corresponding `pore.diameter`/2. Maybe just like you said above. "The exact point where a throat ends is not so simple." And the relative difference is nearly 10% of the `pore.diameter`. Is that true about my understanding? 
Thanks.

**Comment by magnaou** [comment]
@xu-kai-xu as you said, the `throat.conduit_length.pore1` is always smaller than the corresponding `pore.diameter/2` (see attached figure).
![conduit](https://user-images.githubusercontent.com/34344677/71909333-d2f10b80-313d-11ea-8e1f-7569684f016c.png)

**Comment by xu-kai-xu** [comment]
Thank you!

**Comment by xu-kai-xu** [comment]
@magnaou, hi, I am preparing a journal manuscript. And I reproduce the figure you show in the last comment, as follows:

> 
> 
> @xu-kai-xu as you said, the `throat.conduit_length.pore1` is always smaller than the corresponding `pore.diameter/2` (see attached figure).
> ![conduit](https://user-images.githubusercontent.com/34344677/71909333-d2f10b80-313d-11ea-8e1f-7569684f016c.png)

![图片](https://user-images.githubusercontent.com/44153643/132968741-ffb8c11f-7ed2-42a5-a84a-6009281ae557.png)

I just wondering did you use it in another published papers or not. If yes, I will need to ask for a copy right permission. If not, I make a footnote at the bottom of the page. Do you think it is ok with my re-procuce and the statement of its original source? Thanks. 

![图片](https://user-images.githubusercontent.com/44153643/132969172-e377cb16-3740-47c8-83a0-ddb1e8f0a61a.png)

**Comment by jgostick** [comment]
You are allowed to recreate your own version of a figure without permission.  You just can not cut&paste the actual figure from the paper.
