### ISSUE TITLE
3d data for extracting  pore-network parameters

### ISSUE THREAD

**Issue by Jiali0622** [PMEAL/OpenPNM#925]
I generated some random 3-D porou structures,0 for solid and 1 for pore.

I want to extract pore-network parameters by porespy.network_extrction.extract_pore_network

It always failed,and Indexerror is “too many indices for array” and don't konw how to slove it.

Please find my datas in the attachment. I upload some structures datas

**Comment by jgostick** [comment]
Hi @Jiali0622 ... there seems to be no attachment.  Perhaps you could paste your script into the comment box?  

Also, are you following the [tutorial](https://github.com/PMEAL/porespy-examples/blob/master/network_extraction/snow_advanced.md)?

**Comment by Jiali0622** [comment]
Thanks。
May I can think the code may suitable for high porosity?
I randomly selected some 0/1 datas for testing the code ,perhaps they are not suitable.
Later I will try to ues a real structure data .

**Comment by Jiali0622** [comment]
Thanks。
May I can think the code may suitable for high porosity?
I randomly selected some 0/1 datas for testing the code ,perhaps they are not suitable.
Later I will try to ues a real structure data .  @jgostick

**Comment by jgostick** [comment]
The porosity is not really the issue, but rather it's the resolution of the image.  The smallest pore should be about 5+ voxels across at least.  If you're just testing, the refer to the porespy-exapmles repo which shows how to generate some fake images.
