### ISSUE TITLE
CubicTemplate is super slow because it requires pore/throat ids

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#930]
CubicTemplate takes ages to run on a fairly large network say 200 cubed, and the only reason I think is that it relies on pore/throat ids be present. We decided to not generate pore/throat id's when creating a network, and only generate them when asked for. But, in the case of CubicTemplate, they are required.

**Comment by ma-sadeghi** [comment]
Actually, the main problem is `trim` since that is the method that relies on pore/throat id's. But at any rate, trimming relatively large networks takes minutes (probably hours), and we should probably do something about it.

**Comment by jgostick** [comment]
After some checking, it seems that the slow part of generating ids is actually the uuid function, which focuses on cryptographically secure and unique hashes.  We don't need this at all, just unique values.  I will open an issue specifically about changing this.

**Comment by jgostick** [comment]
The problem is that `trim` generates the ids, which haven't yet been generated.  It will still work the same, but will generate unique ints instead of fancy uuids.

**Comment by jgostick** [comment]
How slow is slow?  I have now got the ids being generated as ints, and a 100**2 sphere took about 45 seconds.
