### ISSUE TITLE
Add I/O support for JSON Graph Format

### ISSUE THREAD

**Issue by neumannrf** [PMEAL/OpenPNM#934]
The [JSON Graph Format](http://jsongraphformat.info/) (JGF) specifies how to write a graph structure as a JSON file. It provides a [JSON Schema](https://github.com/jsongraph/json-graph-specification) to facilitate validation.

This extension of the I/O classes entails the creation of a `JSONGraphFormat.py` file in the `openpnm/io/` directory containing the `JSONGraphFormat` class and its `.save()` and `.load()`. methods.

The work will be developed at https://github.com/neumannrf/OpenPNM, in a branch based on `dev-V2-alpha1`, and later merged into `https://github.com/PMEAL/OpenPNM#master` via a Pull Request (after `v2` has been released).

**Comment by neumannrf** [comment]
Hi @jgostick! I already got the green lights and forked your repo into mine. I still cannot start working on it right right now, but at least I was able to set up the infrastructure.

**Comment by neumannrf** [comment]
@jgostick Remember I told you that in our simulation model we assume zero-volume pores? 
What will happen inside OpenPNM if I set `network['pore.diameter'] = sp.zeros(node_squared_radius)` and `(network['pore.volume'], network['pore.area'])` accordingly to zero?

Should I, for the sake of compatibility and interoperability, assign a non-zero diameter / area / volume to each pore so that the simulation algorithms contained in OpenPNM can work with that network?

**Comment by jgostick** [comment]
You can set them to 0 with no issue at all.  All of the other models will use the 0 values accordingly.  We use 0 volumes for boundary pores already.

**Comment by neumannrf** [comment]
Hey @jgostick , I am ready to create the PR!

I made it so it is mergeable to `dev` instead of `master` because I assume you wouldn't want to do an official release _just for this feature_. 

I am issuing the PR now, just to get it out of my to-do list (and into yours 😜) but I realise you're in the middle of a conference, so take your time!

Let's take this conversation to the PR...

**Comment by jgostick** [comment]
I'm going to close this issue since all future discussion should occur on the open PR
