### ISSUE TITLE
Remove transient stokes flow

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#942]
StokesFlow should not be done transiently since we model mass balances, not momentum balances.  The mass in a imcompressible fluid should respond instantly to changes, but the transient code does not behave this way.

**Comment by ma-sadeghi** [comment]
I removed `TransientStokesFlow` and `TransientStokesFlowTest` in the PR #935 so the tests would pass (I updated all transport algorithm tests to not use any embedded `Geometry`, `Physics`, and `Phase`)

**Comment by ma-sadeghi** [comment]
This is addressed in PR #935
