### ISSUE TITLE
Straight throat length model does not work with multiple geometries

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#946]
The throat length model depends on the pore diameter. If there are two geometries with the first containing throats that connect to a pore belonging to the second geometry then the diameter data will not be there to lookup and the throat length and subsequent models that use it gets nans. This is quite a basic flaw.
A few suggestions: 
- Change dependency tree to run models across geometries i.e. geo1.pore_diameter then geo2.pore_diameter then geo1.throat_length etc... This would involve catching interleaves somehow.
- Enforce throats that connect geometries to belong to a special geometry (interior or interface) and make a bespoke set of models. The order you generate the geometries in then becomes a factor and may not suit every single model
- Quick and dirty fix would be to look at all the models that have nans and then re-run them in the hope that missing data is now there after all geometry objects have models run

**Comment by jgostick** [comment]
Oy, this has been vexing us for ages.  The Project would be a natural place to put a ``regenerate_models`` that could look across objects.  There is also the `check_data_health` method, that among other things, looks for nans, so the regenerate_models function could use that to know how things worked out. Like, after running `regenerate_models`, call `check_data_health` and if any arrays are bad, THEN look into other objects of the same type (Geometry or Physics) and call `regenerate_models` on them.

**Comment by TomTranter** [comment]
Now you mention putting a function on the project maybe that's where interleave_data should also go? And perhaps interleave could return a flag that models could use to automatically put them into a list of ones to re-run if data was not found

**Comment by TomTranter** [comment]
I feel like the better way to do it would be to get a cross-object dependency though.. again involving more work on interleave probably

**Comment by jgostick** [comment]
I think the first option above is nice, but I'm actually a but stumped on how to do it...

Here is my first guess: For every throat you can get some ID for geometry on each end of it, and if they don't match, then you've got yourself a 'spanner' throat (i.e. spans between two geoms).  You could then deal with just those throats and pores somehow.

**Comment by jgostick** [comment]
To summarize our discussion from last week, we should add a class called "Border" (or something better?...Joints?) that supports the idea of an interface class (ie. only throats) but not force users to use it.  

The init could take only geoms as args, and find the correpsonding throats for the user:
``bdr = op.geometry.Border(network=pn, geometries=[geom1, geom2, geom3])``

**Comment by TomTranter** [comment]
This problem stems from not generating things in the right order but also from putting throats on the outer edge of internal geometries. We could make a more strict Boundary class method but requires more thought I think we should bump this issue for now

**Comment by jgostick** [comment]
Interesting!!  The function could actually check to make sure that target is an instance of GenericNetwork.

**Comment by jgostick** [comment]
This is something that we just have to live with.  Also, it seems like this has been fixed....at least many cases seem to work fine now.
