### ISSUE TITLE
Should users be allowed to add any model to any object?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#953]
I was fixing an error in `quick_start.rst` where a `physics` model was accidentally added to `phase` which caused `target.find_geometry` method to fail since it only operates on `physics` whereas `phase` was passed in as `target`.

**Comment by jgostick** [comment]
Basically the model should fail if added to the wrong object type.  Like if target is meant to be a network or geom, but it's attached to a phase, then the dict looks will raise key errors.  So it will fail 'naturally' instead of us enforcing it.
