### ISSUE TITLE
Maybe we need to change the way throat and pore volumes are calculated?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#955]
I think the throat and pore volume/surface area should account for the actual length of throats stored in `conduit_lengths.throat`.

**Comment by ma-sadeghi** [comment]
Also, `'pore.volume` is now being overestimated because of the all extra volumes from the intersection of adjacent throats.

**Comment by jgostick** [comment]
This brings up the issue of throat end points again (#912).  If you had throat end points you could easily find the volume of the lens at each pore-throat intersection.

**Comment by jgostick** [comment]
What about adding a model under throat_volume called `lens` that calculates the volume of the lens on each of the throat.  This means that the user is in charge of dealing with the shape of the pores and throats.  If the pore is a cube, then there is not lens.  If the throat is a cylinder there is one model, and if the throat is a cuboid the lens would be different.  Could either pass a keyword like throat shape, or have different models for each case (spherical_lens and cubic_lens)?

**Comment by jgostick** [comment]
@ma-sadeghi has worked up some rough solution to this, but is worried that it is not robust, so I think we'll shelve for V2.1

**Comment by jgostick** [comment]
I have already added these two pore-scale models to geometry.  

https://github.com/PMEAL/OpenPNM/blob/80a77dc8786e07e67ec1ce5ce71e737b8f3c68c0/openpnm/models/geometry/throat_volume.py#L135
