### ISSUE TITLE
Interpretation of Toray090 3D media. 

### ISSUE THREAD

**Issue by angelswat** [PMEAL/OpenPNM#963]
Hi, 

I have a question with respect to toray 3d media generated. When I generated a file.vtp and  I see a lot of interconected lines, are those throats or fibres?

I say it because, when I apply a pressure analysis, I obtain a pressure gradient (throats), but when also I apply a voltage/temperature analysis (fibres), I obtain a gradient. But inside the logic this can´t be possible, because the lines can´t be fibres and throats at the same time. 

I need really to know what are those, fibres or throats. (I attach a photo for reference)

![image](https://user-images.githubusercontent.com/32890792/42456966-c7dad820-835b-11e8-8ab3-bc9cd48fc7b5.png)

Please, I need help, thanks.

**Comment by ma-sadeghi** [comment]
I think by default, the lines represent throats. When you apply temperature/voltage gradient, you're applying it to the void like when you apply pressure gradient. If you want to be able to simulate both void and solid (fibers), then I think you need to use one of our `DualNetwork`s. @TomTranter knows more.

**Comment by TomTranter** [comment]
Hi @angelswat, these are throats and @ma-sadeghi is correct. Dual networks are a new thing we are working on to simulate heat conduction in the solid and void. Keep an eye on our openpnm and examples repo in the next few weeks for updates

**Comment by jgostick** [comment]
Fluid in pores can have a temperature gradient too!  And it can also have a voltage gradient if it is an electrolyte or mercury :-)

**Comment by angelswat** [comment]
You´re telling me when I do transport phenomena analysis in a toray090 that has in essence fibres (solid material), I am really doing an analysis in void??? Or only is in void the representation when I see the gradient in 3d media??? Please, explain me this.

**Comment by jgostick** [comment]
To reiterate what @ma-sadeghi says, you are after all running a *pore* network model.  The idea using a *network* to also represent the solid is relatively new, since more pore network models universally focus on the void phase.
