### ISSUE TITLE
Give algs a reset method

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#965]
Setting up a simple linear transport algorithm then running in a loop whilst changing conductance requires rebuilding A and b matrices or making a new alg object and re-applying all the B.C's and sources. Simply running the run method (as in V1) will return results and the effective properties appear to change giving the impression that the algorithm has changed but the rate is the same and the effective properties are using the new conductance values. This is confusing. A reset method that is implemented in GenericAlgorithm and modified by each subclass will allow for resetting the matrices. Also it should be decided whether to keep B.C's and source terms which I would be in favor of - otherwise it's about as much typing to just make a whole new alg.

**Comment by jgostick** [comment]
How about each alg accepts boolean flags for what to reset:

`algs.reset(bcs=False, results=True, complete=False)`

This way the docstring could have detailed info about what options are available and what each means?

**Comment by jgostick** [comment]
We are not entirely sure how the reset should work, but generally agree it's a good idea. A blank method will be added to the GenericAlgorithm class with a NotImplementedError, awaiting devs to define their own reset behavior.

**Comment by jgostick** [comment]
Done and merged
