### ISSUE TITLE
Do we always need a geometry

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#966]
Some of the old examples didn't make a geometry and either didn't make use of geom type models or simply put info on the network directly. Do we still want to support this or enforce that there should always be at least one geom. Some models go looking for geometries and don't find them. We need to handle these situations a bit better.

**Comment by jgostick** [comment]
This was one of the features that everyone as asking for...the ability to put geometry models on networks, and physics models on phase, and forgoing the need for physics and geometry at all if there was not subdomains.  So, we don't want to enforce a Geometry.

**Comment by jgostick** [comment]
RE the discussion in #964, Physics models shouldn't be asking Geometry models for info...they should be asking the Network for it via interleave data.

**Comment by jgostick** [comment]
Since we're talking about this in #964 I'm going to close this
