### ISSUE TITLE
Add new method to do plane-average calculations

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#972]
This could be useful especially in Cubic networks. However, it's basically calling `mean` with the preferred axis, maybe a bit more. Might be worth thinking about.

**Comment by jgostick** [comment]
The problem with these sort of functions is that there is no end to what you can add, and they never quite make everyone happy.  We had a few of them in V1 for plotting porosity profiles, or showing histograms.  The other problem is that they are very hard to generalize.  I'd say just let users write up their own code for these little things.

**Comment by ma-sadeghi** [comment]
Agreed. Were just jotting down ideas as issues in case one turns out useful 😉
