### ISSUE TITLE
Paraview won't open exported VTK when multiple geometries have different properties

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#973]
Try adding `StickAndBall` and `Boundary` geometries to a network and export to `VTK`. Paraview complains about `nans`.

**Comment by jgostick** [comment]
Hmmm, the interleave data puts nans in places where there is data on one but not the other geom.  I guess the VTK writer should put 0's in there?  I think paraview might not like infs either.

**Comment by ma-sadeghi** [comment]
I think so, putting zeros should work fine.

**Comment by jgostick** [comment]
maybe the save method should take an extra argument like `fill_nans` and the user can specify what to put?  The default would be None, which means don't write that data to the file.  Then the user would have to manually put 0 or -1 or whatever, so they know what's happening.  I have a PR going and will add this.

**Comment by jgostick** [comment]
This is fixed in #988
