### ISSUE TITLE
set_source overrides Dirichlet boundary conditions

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#982]
When adding a source term to pores with `Dirichlet` boundary condition, it overrides it.

**Comment by ma-sadeghi** [comment]
@jgostick @magnaou

**Comment by ma-sadeghi** [comment]
I made a PR to fix this. See PR #983

**Comment by magnaou** [comment]
It depends on the order you set source terms or Dirichlet BCs?

**Comment by jgostick** [comment]
PR #983 now blocks any attempt to write BC to pores with a source term and vice versa.  Just waiting on merhrez to confirm if anything is needed in the transient algs of if they inherit their set BC and set source functions entirely.

**Comment by magnaou** [comment]
@jgostick I take car of updating the Transient alg according to your changes on PR #983.
